Repository kubesphere/website, pull requests merged in 2020-10, with the labels that each got.

#345 fix mistaken style
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
Labels: approved, dco-signoff: yes, size/S

#293 add event query, alert and notification docs
  content/en/docs/cluster-administration/alerting/_index.md
  content/en/docs/cluster-administration/alerting/alerting-message.md
  content/en/docs/cluster-administration/alerting/alerting-policy.md
  content/en/docs/cluster-administration/cluster-settings/_index.md
  content/en/docs/cluster-administration/cluster-settings/mail-server.md
  content/en/docs/project-user-guide/alerting/_index.md
  content/en/docs/project-user-guide/alerting/alerting-message.md
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  content/en/docs/toolbox/events-query.md
  static/images/docs/alerting/alerting_message_node_level_comment.png
  static/images/docs/alerting/alerting_message_node_level_detail.png
  static/images/docs/alerting/alerting_message_node_level_guide.png
  static/images/docs/alerting/alerting_message_node_level_list.png
  static/images/docs/alerting/alerting_message_node_level_notification.png
  static/images/docs/alerting/alerting_message_node_level_policy.png
  static/images/docs/alerting/alerting_message_workload_level_comment.png
  static/images/docs/alerting/alerting_message_workload_level_detail.png
  static/images/docs/alerting/alerting_message_workload_level_list.png
  static/images/docs/alerting/alerting_message_workload_level_notification.png
  static/images/docs/alerting/alerting_message_workload_level_policy.png
  static/images/docs/alerting/alerting_policy_node_level_alerting_rule.png
  static/images/docs/alerting/alerting_policy_node_level_basic_info.png
  static/images/docs/alerting/alerting_policy_node_level_create.png
  static/images/docs/alerting/alerting_policy_node_level_guide.png
  static/images/docs/alerting/alerting_policy_node_level_monitoring_target.png
  static/images/docs/alerting/alerting_policy_node_level_notification_rule.png
  static/images/docs/alerting/alerting_policy_workload_level_alerting_rule.png
  static/images/docs/alerting/alerting_policy_workload_level_basic_info.png
  static/images/docs/alerting/alerting_policy_workload_level_create.png
  static/images/docs/alerting/alerting_policy_workload_level_monitoring_target.png
  static/images/docs/alerting/alerting_policy_workload_level_notification_rule.png
  static/images/docs/alerting/mail_server_config.png
  static/images/docs/alerting/mail_server_guide.png
  static/images/docs/events/events_query_detail.png
  static/images/docs/events/events_query_guide.png
  static/images/docs/events/events_query_home.png
  static/images/docs/events/events_query_list.png
Labels: dco-signoff: yes, lgtm, size/L

#347 Update kubesphere-3.0.0-ga-announcement.md
  content/en/news/kubesphere-3.0.0-ga-announcement.md
Labels: dco-signoff: no, size/XS

#349 Fix comma splice in VMware vSphere installation
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: dco-signoff: yes, size/XS

#306 Add guide for Alertmanager and Notification Manager
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/_index.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
  static/images/docs/cluster-administration/cluster-settings/cluster-wide-alerting-and-notification/alertmanager@kubesphere.png
  static/images/docs/cluster-administration/cluster-settings/cluster-wide-alerting-and-notification/notification-manager.png
Labels: dco-signoff: yes, lgtm, size/L

#313 add auditing operating user guider
  content/en/docs/toolbox/_index.md
  content/en/docs/toolbox/auditing-operating.md
  static/images/docs/toolbox/auditing-log-detail.png
  static/images/docs/toolbox/auditing-log-filter.png
  static/images/docs/toolbox/auditing-operating.png
  static/images/docs/toolbox/toolbox.png
  static/images/docs/toolbox/user-changed.png
Labels: dco-signoff: yes, size/L

#355 Update api doc file and folder name
  content/en/docs/api-reference/_index.md
  content/en/docs/api-reference/api-docs.md
  content/en/docs/api-reference/api-glossary.md
Labels: dco-signoff: yes, size/XS

#351 update mailchimp
  config/upstream-zh/config.toml
Labels: dco-signoff: yes, size/XS

#356 Update doc style guide
  KubeSphere Documentation Style Guide.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#299 feat: Add statefulset user guide
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/project-user-guide/workloads/healthCheck.png
  static/images/docs/project-user-guide/workloads/statefulsets.png
  static/images/docs/project-user-guide/workloads/statefulsets_detail.png
  static/images/docs/project-user-guide/workloads/statefulsets_detail_operation_btn.png
  static/images/docs/project-user-guide/workloads/statefulsets_detail_pod.png
  static/images/docs/project-user-guide/workloads/statefulsets_detail_state.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_1.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2_container_1.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2_container_2.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2_container_3.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2_container_btn.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_2_container_finish.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_3.png
  static/images/docs/project-user-guide/workloads/statefulsets_form_4.png
  static/images/docs/project-user-guide/workloads/statefulsets_list.png
Labels: dco-signoff: yes, lgtm, size/L

#348 Update alerting policy, message and event query wording
  content/en/docs/cluster-administration/alerting/alerting-message.md
  content/en/docs/cluster-administration/alerting/alerting-policy.md
  content/en/docs/cluster-administration/cluster-settings/mail-server.md
  content/en/docs/project-user-guide/alerting/alerting-message.md
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  content/en/docs/toolbox/events-query.md
  static/images/docs/alerting/alerting-policy-node-level-detail-page.png
Labels: dco-signoff: yes, lgtm, size/L

#357 Update previous page UI
  i18n/en.yaml
  i18n/zh.yaml
  layouts/docs/single.html
Labels: dco-signoff: yes, lgtm

#341 Update cluster resource and application resource monitoring wording
  content/en/docs/cluster-administration/application-resources-monitoring.md
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/cluster-status-monitoring/component-monitoring.jpg
Labels: dco-signoff: yes, size/L

#340 add: Add deployment and daemonset user guide
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  static/images/docs/project-user-guide/workloads/daemonsets.png
  static/images/docs/project-user-guide/workloads/daemonsets_detail.png
  static/images/docs/project-user-guide/workloads/daemonsets_detail_operation_btn.png
  static/images/docs/project-user-guide/workloads/daemonsets_detail_pod.png
  static/images/docs/project-user-guide/workloads/daemonsets_detail_state.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_1.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2_container_1.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2_container_2.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2_container_3.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2_container_btn.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_2_container_finish.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_3.png.png
  static/images/docs/project-user-guide/workloads/daemonsets_form_4.png
  static/images/docs/project-user-guide/workloads/daemonsets_list.png
  static/images/docs/project-user-guide/workloads/deployments.png
  static/images/docs/project-user-guide/workloads/deployments_detail.png
  static/images/docs/project-user-guide/workloads/deployments_detail_operation_btn.png
  static/images/docs/project-user-guide/workloads/deployments_detail_pod.png
  static/images/docs/project-user-guide/workloads/deployments_detail_state.png
  static/images/docs/project-user-guide/workloads/deployments_form_1.png
  static/images/docs/project-user-guide/workloads/deployments_form_2.png
  static/images/docs/project-user-guide/workloads/deployments_form_2_container_1.png
  static/images/docs/project-user-guide/workloads/deployments_form_2_container_2.png
  static/images/docs/project-user-guide/workloads/deployments_form_2_container_3.png
  static/images/docs/project-user-guide/workloads/deployments_form_2_container_btn.png
  static/images/docs/project-user-guide/workloads/deployments_form_2_container_finish.png
  static/images/docs/project-user-guide/workloads/deployments_form_3.png
  static/images/docs/project-user-guide/workloads/deployments_form_4.png
  static/images/docs/project-user-guide/workloads/deployments_list.png
Labels: dco-signoff: yes, lgtm, size/XL

#361 Add cluster admin index and relocate alerting guide in this chapter
  content/en/docs/cluster-administration/_index.md
  content/en/docs/cluster-administration/alerting/_index.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/en/docs/cluster-administration/platform-settings/_index.md
  content/en/docs/cluster-administration/platform-settings/role-member-management.md
Labels: dco-signoff: yes, size/M

#325 add Chinese document for introduction glossary page
  content/zh/docs/introduction/glossary.md
Labels: dco-signoff: yes, size/M

#288 Add bare metal installation guide
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: size/L

#278 feat: Add service user guide
  content/en/docs/project-user-guide/application-workloads/services.md
  static/images/docs/project-user-guide/workloads/create_service_type.png
  static/images/docs/project-user-guide/workloads/services_detail.png
  static/images/docs/project-user-guide/workloads/services_lists.png
  static/images/docs/project-user-guide/workloads/services_lists_finish.png
  static/images/docs/project-user-guide/workloads/stateless_form.png
  static/images/docs/project-user-guide/workloads/stateless_form_1.png
  static/images/docs/project-user-guide/workloads/stateless_form_2.png
  static/images/docs/project-user-guide/workloads/stateless_form_3.png
  static/images/docs/project-user-guide/workloads/stateless_form_4.png
  static/images/docs/project-user-guide/workloads/stateless_form_internetAccess.png
Labels: dco-signoff: yes, lgtm, size/L

#363 Add Chinese document of quick start index page
  content/zh/docs/quick-start/_index.md
Labels: dco-signoff: yes, lgtm, size/M

#344 Add "Shutting Down and Restart Cluster Gracefully.md" for cluster-administrator, add asciicast demo for "all-in-one-on-linux.md" and "minimal-kubesphere-on-k8s.md".
  content/en/docs/cluster-administration/Shuting Down and Restart Cluster cracefully.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
Labels: dco-signoff: yes, size/M

#366 Update service guide wording
  content/en/docs/project-user-guide/application-workloads/services.md
  static/images/docs/project-user-guide/workloads/services_lists.jpg
  static/images/docs/project-user-guide/workloads/services_lists.png
  static/images/docs/project-user-guide/workloads/services_lists_finish.jpg
  static/images/docs/project-user-guide/workloads/services_lists_finish.png
  static/images/docs/project-user-guide/workloads/stateless_form.jpg
  static/images/docs/project-user-guide/workloads/stateless_form.png
  static/images/docs/project-user-guide/workloads/stateless_form_1.jpg
  static/images/docs/project-user-guide/workloads/stateless_form_1.png
  static/images/docs/project-user-guide/workloads/stateless_form_2.jpg
  static/images/docs/project-user-guide/workloads/stateless_form_2.png
  static/images/docs/project-user-guide/workloads/stateless_form_3.jpg
  static/images/docs/project-user-guide/workloads/stateless_form_3.png
  static/images/docs/project-user-guide/workloads/stateless_form_4.jpg
  static/images/docs/project-user-guide/workloads/stateless_form_4.png
Labels: dco-signoff: yes, lgtm, size/L

#372 Update telemetry guide
  content/en/docs/faq/telemetry.md
  static/images/docs/faq/telemetry-in-kubesphere/edit-crd.jpg
  static/images/docs/faq/telemetry-in-kubesphere/edit-ks-installer.jpg
  static/images/docs/faq/telemetry-in-kubesphere/enable-telemetry.jpg
Labels: dco-signoff: yes, size/M

#369 Aqara case study typo fix
  content/en/case/aqara.md
Labels: dco-signoff: yes, size/XS

#370 Add project user guide index page
  content/en/docs/project-user-guide/_index.md
Labels: dco-signoff: yes

#371 Update wording and format of shutting down and restarting a cluster
  content/en/docs/cluster-administration/Shuting Down and Restart Cluster cracefully.md
Labels: dco-signoff: yes, lgtm, size/M

#374 Update telemetry guide
  content/en/docs/faq/telemetry.md
  content/zh/docs/faq/telemetry.md
Labels: dco-signoff: yes, size/L

#320 feat: Add cronjob user guide
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  static/images/docs/cronjob-actions.png
  static/images/docs/cronjob-create-basic-info.png
  static/images/docs/cronjob-detail-records.png
  static/images/docs/cronjob-list-new.png
  static/images/docs/cronjob-list.jpg
Labels: dco-signoff: yes, size/M

#338 Update job creation wording and images
  content/en/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/job-actions.png
  static/images/docs/job-create-add-container-image.png
  static/images/docs/job-create-add-container-params.png
  static/images/docs/job-create-job-settings.png
  static/images/docs/job-create.png
  static/images/docs/job-detail-pods.png
  static/images/docs/job-detail-records.jpg
  static/images/docs/job-list.png
  static/images/docs/project-user-guide/application-workloads/jobs/add-container-image-job.png
  static/images/docs/project-user-guide/application-workloads/jobs/container-log-check.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/container-log.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/create-job.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/execution-record.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/job-container-settings.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-basic-info.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-job-settings.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-list-new.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-operation.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/start-command-job.jpg
Labels: dco-signoff: yes, size/L

#354 Refactor auditing and update wording
  content/en/docs/toolbox/auditing-operating.md
  content/en/docs/toolbox/auditing/_index.md
  content/en/docs/toolbox/auditing/auditing-query.md
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/en/docs/toolbox/auditing/auditing-rule.md
  static/images/docs/toolbox/alerting-archiving-rule.jpg
  static/images/docs/toolbox/auditing-crd.jpg
  static/images/docs/toolbox/auditing-operating-ui.jpg
Labels: dco-signoff: yes, size/XL

#381 Fix Deploy button image link
  content/en/docs/installing-on-linux/public-cloud/install-ks-on-azure-vms.md
Labels: dco-signoff: yes, kind/bug, size/XS

#383 Update style guide
  KubeSphere Documentation Style Guide.md
Labels: dco-signoff: yes

#377 Spring cloud on kubeshpere
  content/zh/blogs/spring-cloud-on-kubeshpere.md
  static/images/blogs/spring-cloud-on-kubesphere/0.springcloud.png
  static/images/blogs/spring-cloud-on-kubesphere/1.Credentials.PNG
  static/images/blogs/spring-cloud-on-kubesphere/10.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/11.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/12.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/13.run.PNG
  static/images/blogs/spring-cloud-on-kubesphere/14.deploy.PNG
  static/images/blogs/spring-cloud-on-kubesphere/15.deploy.PNG
  static/images/blogs/spring-cloud-on-kubesphere/16.deploy.PNG
  static/images/blogs/spring-cloud-on-kubesphere/17.service.PNG
  static/images/blogs/spring-cloud-on-kubesphere/18.service.PNG
  static/images/blogs/spring-cloud-on-kubesphere/19.service.PNG
  static/images/blogs/spring-cloud-on-kubesphere/2.createpipline.PNG
  static/images/blogs/spring-cloud-on-kubesphere/20.service.PNG
  static/images/blogs/spring-cloud-on-kubesphere/21.ingress.PNG
  static/images/blogs/spring-cloud-on-kubesphere/3.pipeline.PNG
  static/images/blogs/spring-cloud-on-kubesphere/4.pipeline.PNG
  static/images/blogs/spring-cloud-on-kubesphere/5.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/6.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/7.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/8.design.PNG
  static/images/blogs/spring-cloud-on-kubesphere/9.design.PNG
Labels: dco-signoff: yes, size/L

#321 feat: Add ingress user guide
  content/en/docs/project-user-guide/application-workloads/ingress.md
  static/images/docs/route-create-annotations.png
  static/images/docs/route-detail-resource.png
  static/images/docs/route-detail.png
  static/images/docs/route-set-rule-auto.png
  static/images/docs/route-set-rule-domain.png
  static/images/docs/set-gateway.png
Labels: dco-signoff: yes, size/L

#388 Update readme
  README.md
Labels: dco-signoff: yes

#385 doc(all-in-one-linux): fix a password typo
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: dco-signoff: yes, lgtm, size/XS

#394 Add TiDB En blog
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
Labels: dco-signoff: yes, size/L

#396 remove outdated cmd for storage installation
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: dco-signoff: yes, size/M

#400 add gitlab docs
  content/en/docs/application-store/built-in-apps/gitlab-app.md
  content/en/docs/application-store/external-apps/_index.md
  content/en/docs/application-store/external-apps/gitlab-app.md
  static/images/docs/appstore/gitlab/add-ks-repo.png
  static/images/docs/appstore/gitlab/add-repo.png
  static/images/docs/appstore/gitlab/deploy-app.png
  static/images/docs/appstore/gitlab/deploy-gitlab-conf.png
  static/images/docs/appstore/gitlab/deploy-gitlab-done.png
  static/images/docs/appstore/gitlab/deploy-gitlab-info.png
  static/images/docs/appstore/gitlab/deploy-gitlab.png
  static/images/docs/appstore/gitlab/gitlab-password.png
  static/images/docs/appstore/gitlab/kubectl.png
  static/images/docs/appstore/gitlab/nginx-port.png
  static/images/docs/appstore/gitlab/signin-gitlab.png
Labels: dco-signoff: yes, do-not-merge/hold, size/L

#393 add app-store docs(rabbitmq,tomcat)
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  static/images/docs/rabbitmq-app/rabbitMQ04.jpg
  static/images/docs/rabbitmq-app/rabbitmq01.jpg
  static/images/docs/rabbitmq-app/rabbitmq02.jpg
  static/images/docs/rabbitmq-app/rabbitmq021.jpg
  static/images/docs/rabbitmq-app/rabbitmq03.jpg
  static/images/docs/rabbitmq-app/rabbitmq05.jpg
  static/images/docs/rabbitmq-app/rabbitmq06.jpg
  static/images/docs/rabbitmq-app/rabbitmq07.jpg
  static/images/docs/rabbitmq-app/rabbitmq08.jpg
  static/images/docs/rabbitmq-app/rabbitmq09.png
  static/images/docs/rabbitmq-app/rabbitmq10.png
  static/images/docs/tomcat-app/tomcat-app01.jpg
  static/images/docs/tomcat-app/tomcat-app02.jpg
  static/images/docs/tomcat-app/tomcat-app03.jpg
  static/images/docs/tomcat-app/tomcat-app04.jpg
  static/images/docs/tomcat-app/tomcat-app05.jpg
  static/images/docs/tomcat-app/tomcat-app06.jpg
  static/images/docs/tomcat-app/tomcat-app07.jpg
  static/images/docs/tomcat-app/tomcat-app08.jpg
  static/images/docs/tomcat-app/tomcat-app09.jpg
  static/images/docs/tomcat-app/tomcat-app10.jpg
  static/images/docs/tomcat-app/tomcat-app11.jpg
  static/images/docs/tomcat-app/tomcat-app12.jpg
  static/images/docs/tomcat-app/tomcat-app13.jpg
  static/images/docs/tomcat-app/tomcat-app14.jpg
Labels: dco-signoff: yes, size/L

#382 Update cronjob wording
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/cronjob-actions.png
  static/images/docs/cronjob-create-basic-info.png
  static/images/docs/cronjob-detail-records.png
  static/images/docs/cronjob-list-new.png
  static/images/docs/cronjob-list.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/container-log-1.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/container-log-2.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-action.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-create-basic-info.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-list-new.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-list.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/execution-record.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/finish-image.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/input-busybox.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-detail-page.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-list.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/start-command.jpg
Labels: dco-signoff: yes, lgtm, size/L

#368 Update node management wording and images
  content/en/docs/cluster-administration/nodes.md
  static/images/docs/cluster-administration/assign_pods_to_nodes.png
  static/images/docs/cluster-administration/label_node.png
  static/images/docs/cluster-administration/node-management/add-taints.jpg
  static/images/docs/cluster-administration/node-management/assign_pods_to_node.jpg
  static/images/docs/cluster-administration/node-management/clusters-management-select.jpg
  static/images/docs/cluster-administration/node-management/drop-down-list-node.jpg
  static/images/docs/cluster-administration/node-management/label_node.jpg
  static/images/docs/cluster-administration/node-management/node_detail.png
  static/images/docs/cluster-administration/node-management/node_status.png
  static/images/docs/cluster-administration/node-management/select-a-cluster.jpg
Labels: dco-signoff: yes, size/M

#273 Adding Network Isolation Related Documents
  content/en/docs/project-administration/project-network-isolation.md
  content/en/docs/workspaces-administration/workspace-network-isolation.md
  static/images/docs/project-administration/network-isolation-off.png
  static/images/docs/project-administration/network-isolation-on.png
  static/images/docs/workspace-administration/network-isolation.png
Labels: dco-signoff: yes, size/L

#405 change weight
  content/en/docs/application-store/_index.md
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/project-administration/_index.md
Labels: dco-signoff: yes, size/XS

#380 add app-store docs
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署Nginx.md
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署Redis.md
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署mongoDB.md
  static/images/app-store/image-20201021143316670.png
  static/images/app-store/image-20201021143546762.png
  static/images/app-store/image-20201022112823164.png
  static/images/app-store/image-20201022113156240.png
  static/images/app-store/image-20201022113349510.png
  static/images/app-store/image-20201022113353449.png
  static/images/app-store/image-20201022120204884.png
  static/images/app-store/image-20201022120448986.png
  static/images/app-store/image-20201022120632898.png
  static/images/app-store/image-20201022120644789.png
  static/images/app-store/image-20201022134207395.png
  static/images/app-store/image-20201022134258742.png
  static/images/app-store/image-20201022135630726.png
  static/images/app-store/image-20201026100924696.png
  static/images/app-store/image-20201026100957077.png
  static/images/app-store/image-20201026101026317.png
  static/images/app-store/image-20201026101100959.png
  static/images/app-store/image-20201026101148434.png
  static/images/app-store/image-20201026101224796.png
  static/images/app-store/image-20201026101525181.png
  static/images/app-store/image-20201026101911123.png
  static/images/app-store/image-20201026101940403.png
  static/images/app-store/image-20201026102012448.png
  static/images/app-store/image-20201026102039163.png
  static/images/app-store/image-20201026102122480.png
  static/images/app-store/image-20201026102256634.png
  static/images/app-store/image-20201026102601704.png
  static/images/app-store/image-20201026102823482.png
  static/images/app-store/image-20201026110147496.png
  static/images/app-store/image-20201026110323363.png
Labels: dco-signoff: yes, size/L

#415 Change "Cluster Operations" to "Add/Delete Nodes" since the latter is…
  content/en/docs/installing-on-linux/cluster-operation/_index.md
Labels: approved, dco-signoff: yes, size/XS

#409 Update CI node setting, credential management, and email server config in devops user guide
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/en/docs/devops-user-guide/how-to-use/set-ci-node.md
  static/images/devops/set-jenkins-email-3.png
  static/images/docs/devops-user-guide/credential-management/create-credential-page.jpg
  static/images/docs/devops-user-guide/credential-management/create-credential-step1.jpg
  static/images/docs/devops-user-guide/credential-management/credential-detail-page.jpg
  static/images/docs/devops-user-guide/credential-management/credentials-list.jpg
  static/images/docs/devops-user-guide/credential-management/dockerhub-credentials.jpg
  static/images/docs/devops-user-guide/credential-management/edit-credentials.jpg
  static/images/docs/devops-user-guide/jenkins-email/set-jenkins-email-3.jpg
  static/images/docs/devops-user-guide/jenkins-email/workloads-list.jpg
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/clusters-management.jpg
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/set-node-1.png
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/set-node-2.png
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/set-node-3.png
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/set-node-4.png
  static/images/docs/devops-user-guide/set-ci-node-for-dependency-cache/set-node-5.png
Labels: dco-signoff: yes, lgtm, size/L

#422 Update allinone on Linux: refine doc and change the default download …
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, size/S

#424 Translate Minimal KubeSphere on Kubernetes task
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  static/images/docs/quickstart/kubesphere-components-zh.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#427 zh-Installing on Kubernetes Index Page
  content/zh/docs/installing-on-kubernetes/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#420 add logging & monitoring faq
  content/en/docs/pluggable-components/faq/_index.md
  content/en/docs/pluggable-components/faq/logging.md
  content/en/docs/pluggable-components/faq/monitoring.md
  content/en/docs/pluggable-components/logging.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#410 docs：add demo to multioverview.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#414 update manifests url
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-huawei-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/installing-on-kubernetes/introduction/overview.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/service-mesh.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/zh/docs/installing-on-kubernetes/introduction/overview.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/service-mesh.md
  content/zh/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
Labels: approved, dco-signoff: no, lgtm, size/L

#323 add Chinese document for introduction architecture page
  content/zh/docs/introduction/architecture.md
Labels: approved, dco-signoff: yes, lgtm, size/M
