Repository kubesphere/website, pull requests merged in 2020-12, with the labels that each got.

#688 Add cigo cloud partnership news
  content/en/news/_index.md
  content/en/news/kubesphere-cigo-partnership.md
Labels: dco-signoff: yes, size/M

#695 Add system resource editing faq
  content/en/docs/faq/edit-resources-in-system-workspace.md
Labels: dco-signoff: yes, size/M

#690 Minor wording fix
  content/en/docs/application-store/app-lifecycle-management.md
Labels: dco-signoff: yes, size/XS

#646 Update create pipeline using graphical editing panels
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/devops/checkout-scm-sonarqube.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/access-service.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/add-artifact-stage.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/add-nested-step-2.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/add-nested-step.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/add-parameter.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/advanced-settings.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/artifact-info.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/basic-info.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/build-and-push-image.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/code-analysis-stage.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/complete.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/container.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/create-pipeline.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/credential-list.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/develop-to-dev.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/docker-credential.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/dockerhub-image.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/download-artifact.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/edit-panel.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/edit-pipeline.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/enter-repo-url.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/first-stage-set.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/graphical-panel.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/input-message.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/inspect-logs.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/kubernetesDeploy.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/login-docker-command.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/maven-container.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/maven-set.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/nested-step-maven.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/nested-step.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/pipeline-done.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/pipeline-list.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/pipeline-successful.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/push-snapshot-to-docker.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/run-pipeline.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/service-exposed.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/shell-command.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/shell.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonar-ready.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonar-token.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonar.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonarqube-credentials.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonarqube-result-detail.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/sonarqube-shell-new.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/timeout-nested-step.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/timeout.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/unit-test-set.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/unit-test.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/view-deployment.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/waitforqualitygate.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#693 Translate create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/Pipeline-Overview.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/access-endpoint.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/activity-failure.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/advanced-setting.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/branch-settings.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/commit-changes.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/create-pipeline-2.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/create-pipeline.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/credential-list.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/devops-prod.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/docker-hub-result.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/fork-github-repo.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/generate-github-token-1.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/generate-github-token-2.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/github-result.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/inspect-pipeline-log-1.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/inspect-pipeline-log-2.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/jenkins-edit-1.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/jenkins-edit-2.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/jenkinsfile-online.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/pipeline-deployments.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/pipeline-detail.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/pipeline-list.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/pipeline-proceed.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/project-list.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/remove-behavioral-strategy.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/sample-app-result-check.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/select-repo.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/sonar-token.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/sonarqube-result-detail-1.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/sonarqube-result-detail.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/create-a-pipeline-using-a-jenkinsfile-zh/tag-name.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#694 Update Jenkins settings guide
  content/en/docs/devops-user-guide/how-to-use/jenkins-setting.md
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/app-config.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/cluster-management.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/configuration-as-code.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-configmap.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-jenkins.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/jenkins-dashboard.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/manage-jenkins.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/more-list.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#698 App Store-Index Page Translated into Chinese
  content/zh/docs/application-store/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#697 translation updated
  content/zh/docs/introduction/what-is-kubesphere.md
Labels: dco-signoff: yes, do-not-merge/hold, size/M

#680 Rewrite volumes and refactor storage part in Deployments, StatefulSet…
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/en/docs/project-user-guide/storage/volumes.md
  static/images/docs/project-user-guide/volume-management/volumes/basic-volume-info.jpg
  static/images/docs/project-user-guide/volume-management/volumes/create-volume.jpg
  static/images/docs/project-user-guide/volume-management/volumes/delete-volume.jpg
  static/images/docs/project-user-guide/volume-management/volumes/local-pending.jpg
  static/images/docs/project-user-guide/volume-management/volumes/select-storage-class.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-creation-method.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-detail-page.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-finish-creation.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-finished.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-monitoring.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-page.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-status.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volumebindingmode.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#645 feature: add the blog about remote macOS to run pipelines
  content/zh/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp.md
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/add-mac-to-jenkins.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/frpc-osx-allow.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/frpc-warnning-2.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/frpc-warnning.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-add-credential-1.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-add-node-1.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-add-node-2.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-node-config.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-node-list.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-node-run.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-result-view.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/jenkins-run-result.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/ks-2.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/ks-3.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/ks-4.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/osx-firewall.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/osx-ssh.png
  static/images/blogs/add-remote-macos-physical-machine-to-run-pipelines-using-frp/osx.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#696 Add B2I and S2I guide and add steps for creating common use Secrets
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/set-ci-node.md
  content/en/docs/project-user-guide/configuration/secrets.md
  content/en/docs/project-user-guide/image-builder/_index.md
  content/en/docs/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/project-user-guide/configurations/secrets/docker-hub-secret.jpg
  static/images/docs/project-user-guide/configurations/secrets/github-secret.jpg
  static/images/docs/project-user-guide/configurations/secrets/secret-create.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/access-service.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/advanced-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/buidling-settings-2.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/build-binary.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/build-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building-status.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/container-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/create-service.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/deployment.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image-pushed.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/exposed-port.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-builder.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-success.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-log.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-logs.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job-created.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/service-build.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/service.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/successful.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/upload-artifact.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-log.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-process.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-settings.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/building.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/copy-repo-code.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-finish.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-service.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/deployment.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/docker-image.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/fork-repository.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/health-checker.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/job.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/select-lang-type.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-detail.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-settings.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/success-result.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#685 Add TiDB deployment en second blog
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#701 improvement: add helm3 installation to sonarqube
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#702 Update index number of release notes, introduction, quickstarts and i…
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/installing-on-linux/cluster-operation/_index.md
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
  content/en/docs/installing-on-linux/faq/_index.md
  content/en/docs/installing-on-linux/faq/configure-booster.md
  content/en/docs/installing-on-linux/introduction/_index.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/introduction/port-firewall.md
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
  content/en/docs/installing-on-linux/introduction/vars.md
  content/en/docs/installing-on-linux/on-premises/_index.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/_index.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/installing-on-linux/uninstall-kubesphere-and-Kubernetes.md
  content/en/docs/introduction/_index.md
  content/en/docs/introduction/advantages.md
  content/en/docs/introduction/architecture.md
  content/en/docs/introduction/features.md
  content/en/docs/introduction/glossary.md
  content/en/docs/introduction/scenarios.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/en/docs/quick-start/_index.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/quick-start/wordpress-deployment.md
  content/en/docs/release/_index.md
  content/en/docs/release/release-v200.md
  content/en/docs/release/release-v201.md
  content/en/docs/release/release-v202.md
  content/en/docs/release/release-v210.md
  content/en/docs/release/release-v211.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#703 Update index number of installing on k8s, multicluster, pluggable com…
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-kubernetes/faq/_index.md
  content/en/docs/installing-on-kubernetes/faq/faq1.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/_index.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/installing-on-kubernetes/introduction/_index.md
  content/en/docs/installing-on-kubernetes/introduction/overview.md
  content/en/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/_index.md
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
  content/en/docs/multicluster-management/_index.md
  content/en/docs/multicluster-management/enable-multicluster/_index.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/multicluster-management/enable-multicluster/retrieve-kubeconfig.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/_index.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/en/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/en/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
  content/en/docs/multicluster-management/introduction/_index.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/multicluster-management/introduction/overview.md
  content/en/docs/multicluster-management/unbind-cluster.md
  content/en/docs/pluggable-components/_index.md
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/faq/_index.md
  content/en/docs/pluggable-components/faq/logging.md
  content/en/docs/pluggable-components/faq/monitoring.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/network-policy.md
  content/en/docs/pluggable-components/overview.md
  content/en/docs/pluggable-components/service-mesh.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-ks-installer.md
  content/en/docs/upgrade/_index.md
  content/en/docs/upgrade/overview.md
  content/en/docs/upgrade/upgrade-faq.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/en/docs/upgrade/what-changed.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#704 Add 4 ZHCN video demos
  content/zh/docs/installing-on-kubernetes/introduction/overview.md
  content/zh/docs/installing-on-linux/introduction/ha-configuration.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#699 Update installation links
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/installing-on-linux/introduction/ha-configuration.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#708 Change access control, project admin, app store, toolbox, faq and refe…
  content/en/docs/access-control-and-account-management/_index.md
  content/en/docs/access-control-and-account-management/configuring-authentication.md
  content/en/docs/api-reference/_index.md
  content/en/docs/api-reference/api-changes/_index.md
  content/en/docs/api-reference/api-changes/logging.md
  content/en/docs/api-reference/api-changes/monitoring.md
  content/en/docs/api-reference/api-docs.md
  content/en/docs/api-reference/glossary.md
  content/en/docs/application-store/_index.md
  content/en/docs/application-store/app-developer-guide/_index.md
  content/en/docs/application-store/app-developer-guide/helm-developer-guide.md
  content/en/docs/application-store/app-developer-guide/helm-specification.md
  content/en/docs/application-store/app-lifecycle-management.md
  content/en/docs/application-store/built-in-apps/_index.md
  content/en/docs/application-store/external-apps/_index.md
  content/en/docs/faq/_index.md
  content/en/docs/faq/byop.md
  content/en/docs/faq/console-faq.md
  content/en/docs/faq/edit-resources-in-system-workspace.md
  content/en/docs/faq/telemetry.md
  content/en/docs/project-administration/_index.md
  content/en/docs/project-administration/project-and-multicluster-project.md
  content/en/docs/project-administration/project-gateway.md
  content/en/docs/project-administration/project-network-isolation.md
  content/en/docs/project-administration/project-quota.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/toolbox/_index.md
  content/en/docs/toolbox/auditing/_index.md
  content/en/docs/toolbox/auditing/auditing-query.md
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/en/docs/toolbox/auditing/auditing-rule.md
  content/en/docs/toolbox/events-query.md
  content/en/docs/toolbox/history.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#707 Workspace Overview translated
  content/zh/docs/workspace-administration/what-is-workspace.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/created-workspace.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/delete-workspace.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/provide-workspace-info.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-basic-info.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-list.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-overview.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#289 Add access control and account management user guide
  content/zh/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  static/images/docs/access-control-and-account-management/multi-tenancy-architecture.png
  static/images/docs/access-control-and-account-management/networkpolicy.png
  static/images/docs/access-control-and-account-management/rbac.png
  static/images/docs/access-control-and-account-management/request-chain.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#711 Update devops index page
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#713 Update devops cn index
  content/zh/docs/devops-user-guide/_index.md
Labels: approved, dco-signoff: yes, size/M

#716 Role and Member Management translated.
  content/zh/docs/workspace-administration/role-and-member-management.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-invite-user.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-create-step1.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-create-step2.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-detail.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-edit.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-user-edit.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#717 Add gateway guide
  content/en/docs/project-administration/project-gateway.md
  static/images/docs/project-administration/project-gateway/access-method.png
  static/images/docs/project-administration/project-gateway/lb.png
  static/images/docs/project-administration/project-gateway/nodeport.jpg
  static/images/docs/project-administration/project-gateway/set-project-gateway.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#723 Add project gateway en source file for cn
  content/zh/docs/project-administration/project-gateway.md
Labels: dco-signoff: yes, size/M

#722 Use US spelling of dialog instead of UK spelling of dialogue
  content/en/docs/application-store/app-lifecycle-management.md
  content/en/docs/application-store/built-in-apps/mongodb-app.md
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/en/docs/devops-user-guide/how-to-use/set-ci-node.md
  content/en/docs/project-user-guide/application-workloads/services.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  content/en/docs/workspace-administration/upload-helm-based-application.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#721 change some expressions
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/en/docs/workspace-administration/role-and-member-management.md
  content/en/docs/workspace-administration/upload-helm-based-application.md
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#718 Upload Helm-based Applications translated.
  content/zh/docs/workspace-administration/upload-helm-based-application.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/confirm-upload.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/draft-app.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-app-template.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-helm.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-icon.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/version-page.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#719 Translate role-and-member-management.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  static/images/docs/devops-admin-zh/devops_invite_member.png
  static/images/docs/devops-admin-zh/devops_list_member.png
  static/images/docs/devops-admin-zh/devops_role_list.png
  static/images/docs/devops-admin-zh/devops_role_step1.png
  static/images/docs/devops-admin-zh/devops_role_step2.png
  static/images/docs/devops-admin-zh/devops_user_edit.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#720 Add en multi-tanancy and update its zhcn version
  content/en/docs/access-control-and-account-management/configuring-authentication.md
  content/en/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/zh/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  static/images/docs/access-control-and-account-management/multi-tanancy-in-kubesphere/multi-tenancy-architecture.png
  static/images/docs/access-control-and-account-management/multi-tanancy-in-kubesphere/rbac.png
  static/images/docs/access-control-and-account-management/multi-tanancy-in-kubesphere/request-chain.jpg
  static/images/docs/zh-cn/access-control-and-account-management/multi-tanancy-in-kubesphere/multi-tenancy-architecture.png
  static/images/docs/zh-cn/access-control-and-account-management/multi-tanancy-in-kubesphere/rbac.png
  static/images/docs/zh-cn/access-control-and-account-management/multi-tanancy-in-kubesphere/request-chain.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#724 add meet up
  assets/scss/index.scss
  layouts/index.html
  static/images/home/close.svg
  static/images/home/group-16.svg
  static/images/home/group-18.svg
  static/images/home/group-19.svg
  static/images/home/group-20.svg
  static/images/home/二维码.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#725 Add some desc for the address field in config-sample
  content/en/docs/installing-on-linux/introduction/multioverview.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#726 migrate glossary to the reference part
  content/en/docs/api-reference/glossary.md
  content/en/docs/introduction/_index.md
  content/en/docs/introduction/glossary.md
  content/zh/docs/api-reference/glossary.md
  content/zh/docs/introduction/_index.md
  content/zh/docs/introduction/glossary.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#727 Update multinode installation note
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#729 Update format and expression, and delete demo in English all-in-one
  content/en/docs/quick-start/all-in-one-on-linux.md
  static/images/docs/quickstart/all-in-one-installation/Installation-complete.png
  static/images/docs/quickstart/all-in-one-installation/environment-check.png
  static/images/docs/quickstart/all-in-one-installation/kubesphere-components.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#728 Import Helm Repository translated.
  content/zh/docs/workspace-administration/app-repository/import-helm-repository.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-info-dialogue.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo-list.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/validate-link.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#730 Minor expression update
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  static/images/docs/quickstart/minimal-installation-on-k8s/kubesphere-components.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#731 Update uninstalling file wording
  content/en/docs/installing-on-linux/uninstall-kubesphere-and-Kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#735 snipping updated in Workspace Overview
  content/zh/docs/workspace-administration/app-repository/_index.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/delete-workspace.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-basic-info.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-list.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-overview.PNG
Labels: approved, dco-signoff: yes, lgtm, size/XS

#737 Update monitoring faq wording
  content/en/docs/pluggable-components/faq/monitoring.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#733 Update logging faq wording
  content/en/docs/pluggable-components/_index.md
  content/en/docs/pluggable-components/faq/logging.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#734 Use strict grammar for titles in DevOps guides and relocate images
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_invite_member.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_list.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_step1.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_step2.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_user_edit.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#738 Add blog for Dockershim Deprecation
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/blogs/dockershim-out-of-kubernetes.md
Labels: dco-signoff: yes, size/L

#743 update header's announcement
  layouts/partials/header.html
Labels: approved, dco-signoff: yes, size/XS

#746 fix header height
  layouts/_default/baseof.html
  layouts/docs/single.html
  layouts/partials/content.html
Labels: dco-signoff: yes, size/XS

#739 Translate jenkins-setting.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-setting.md
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/app-config.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/cluster-management.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/configuration-as-code.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/edit-configmap.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/edit-jenkins.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/jenkins-dashboard.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/manage-jenkins.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/jenkins-system-settings-zh/more-list.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#745 add blog: dockershim-out-of-kubernetes.md
  content/zh/blogs/dockershim-out-of-kubernetes.md
  content/zh/blogs/kubesphere-values.md
  static/images/blogs/dockershim-out-of-kubernetes/containerd.png
  static/images/blogs/dockershim-out-of-kubernetes/cri-o.png
  static/images/blogs/dockershim-out-of-kubernetes/isula.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#747 Project User Guide-Index-ZH updated.
  content/zh/docs/project-user-guide/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#750 Translate harbor.md
  content/zh/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/devops-zh/create-pipline-2.png
  static/images/devops-zh/create-pipline-3.png
  static/images/devops-zh/edit-Jenkinsfile.png
  static/images/devops-zh/harbor-login.png
  static/images/devops-zh/harbor-new-project.png
  static/images/devops-zh/harbor-project-ok.png
  static/images/devops-zh/harbor-robot-account-ok.png
  static/images/devops-zh/harbor-robot-account-save.png
  static/images/devops-zh/harbor-robot-account.png
  static/images/devops-zh/ks-console-create-credential.png
  static/images/devops-zh/ks-console-create-pipline.png
  static/images/devops-zh/ks-console-credential-ok.png
  static/images/devops-zh/run-pipline.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#753 Add cn video demo for air-gapped installation and upgrade
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: yes, size/S

#755 update format and images in alerting, auditing, networkpolicy and ser…
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/network-policy.md
  content/en/docs/pluggable-components/service-mesh.md
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/alerting.png
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-auditing-logs/auditing.png
  static/images/docs/enable-pluggable-components/kubesphere-auditing-logs/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-auditing-logs/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-service-mesh/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-service-mesh/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-service-mesh/istio.png
  static/images/docs/enable-pluggable-components/network-policies/clusters-management.png
  static/images/docs/enable-pluggable-components/network-policies/edit-yaml.png
  static/images/docs/enable-pluggable-components/network-policies/networkpolicy.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#751 KubeSphere App Store - translation and snipping updated
  content/zh/docs/pluggable-components/app-store.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/app-store.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/edit-yaml.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/openpitrix.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#757 docs: fix the describes of network environments, add a new demo.
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#752 fix some typos
  content/en/docs/project-user-guide/_index.md
  layouts/partials/header.html
Labels: approved, dco-signoff: yes, lgtm, size/XS

#756 Update booster format and images
  content/en/docs/installing-on-linux/faq/configure-booster.md
  static/images/docs/installing-on-linux/faq/configure-booster/booster-url.png
  static/images/docs/installing-on-linux/faq/configure-booster/container-registry.png
  static/images/docs/installing-on-linux/faq/configure-booster/image-booster.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#754 Update format and image location in App store, devops, logging and ev…
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  static/images/docs/enable-pluggable-components/kubesphere-app-store/app-store.png
  static/images/docs/enable-pluggable-components/kubesphere-app-store/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-app-store/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-app-store/openpitrix.png
  static/images/docs/enable-pluggable-components/kubesphere-devops-system/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-devops-system/devops.png
  static/images/docs/enable-pluggable-components/kubesphere-devops-system/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-events/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-events/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-events/events.png
  static/images/docs/enable-pluggable-components/kubesphere-logging-system/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-logging-system/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-logging-system/logging.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#761 Update TiDB second blog
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
Labels: dco-signoff: yes, size/S

#758 Update download link desc
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/installing-on-linux/introduction/ha-configuration.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#759 Minor word update in pluggable component index
  content/en/docs/pluggable-components/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#762 Add multitenancy video
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#763 Application Lifecycle Managament translated.
  content/zh/docs/application-store/app-lifecycle-management.md
  static/images/docs/zh-cn/app-store/application-lifecycle-management/account-ready.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/activate-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/activate-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-active.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-category.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-draft.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-in-category-list-expected.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-review-name.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-store.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-templates-page.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-to-be-reviewed.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/app-to-be-upgraded.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/confirm-category.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/create-review-role.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/create-role.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/create-roles.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/deploy-redis.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/deployed-instance-success.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/deploying-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/deployment-place.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/edit-app-information.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/edit-app-template.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/new-version-redis.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/redis-new-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/redis.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/remove-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/reviewing.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/see-new-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/set-app-type.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/set-category-for-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/submit-for-review.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/submitted-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/suspend-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/suspend-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/test-deployment.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upgrade-an-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upgrade-finish.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upload-app.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upload-icon.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upload-new-redis-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/upload-template.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/uploaded-new-version.PNG
  static/images/docs/zh-cn/app-store/application-lifecycle-management/version-upgraded.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#766 KubeSphere Logging System translation updated.
  content/zh/docs/pluggable-components/logging.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-logging-system/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-logging-system/edit-yaml.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-logging-system/logging.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#765 KubeSphere DevOps System translation updated.
  content/zh/docs/pluggable-components/devops.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-devops-system/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-devops-system/devops.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-devops-system/edit-yaml.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#768 Minor title fix
  content/en/docs/application-store/app-lifecycle-management.md
  content/zh/docs/application-store/app-lifecycle-management.md
Labels: dco-signoff: yes

#767 Fix some wording in alertmanager and notification manager guide
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager-in-kubesphere/alertmanager@kubesphere.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager/notification-manager.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#771 Minor word change in workspace network isolation
  content/en/docs/workspace-administration/workspace-network-isolation.md
  static/images/docs/workspace-administration/workspace-network-isolation/workspace-isolation.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#776 hide meet up
  layouts/index.html
Labels: dco-signoff: yes, size/XS

#774 High Availability Configurations translated.
  content/zh/docs/installing-on-linux/introduction/ha-configuration.md
  static/images/docs/zh-cn/installing-on-linux/introduction/ha-configurations/ha-architecture.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#773 Temp
  content/en/docs/faq/edit-resources-in-system-workspace.md
  content/zh/docs/faq/edit-resources-in-system-workspace.md
  content/zh/docs/installing-on-linux/faq/configure-booster.md
  static/images/docs/zh-cn/installing-on-linux/faq/configure-booster/booster-url.PNG
  static/images/docs/zh-cn/installing-on-linux/faq/configure-booster/container-registry.PNG
  static/images/docs/zh-cn/installing-on-linux/faq/configure-booster/image-booster.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#777 Update how to setup HTTP basic auth in app repo
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#779 add forgot password faq
  content/en/docs/faq/forgot-password.md
  static/images/docs/faq/forgot-password/modify-password.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#778 Air Gapped Installation translated.
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  static/images/docs/zh-cn/installing-on-linux/introduction/air-gapped-installation/kubesphere-login.PNG
  static/images/docs/zh-cn/installing-on-linux/introduction/air-gapped-installation/self-signed-cert.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#782 Refactor doc faq section
  content/en/docs/faq/access-control/_index.md
  content/en/docs/faq/access-control/forgot-password.md
  content/en/docs/faq/console/_index.md
  content/en/docs/faq/console/console-web-browser.md
  content/en/docs/faq/console/edit-resources-in-system-workspace.md
  content/en/docs/faq/forgot-password.md
  content/en/docs/faq/installation/_index.md
  content/en/docs/faq/installation/configure-booster.md
  content/en/docs/faq/installation/telemetry.md
  content/en/docs/faq/observability/_index.md
  content/en/docs/faq/observability/byop.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/faq/observability/monitoring.md
  content/en/docs/faq/upgrade/_index.md
  content/en/docs/faq/upgrade/upgrade-faq.md
  content/en/docs/installing-on-kubernetes/faq/_index.md
  content/en/docs/installing-on-kubernetes/faq/faq1.md
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/installing-on-linux/faq/_index.md
  content/en/docs/pluggable-components/_index.md
  content/en/docs/pluggable-components/faq/_index.md
  content/en/docs/upgrade/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#781 Translated faq/telemetry.md.
  content/zh/docs/faq/telemetry.md
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/edit-crd.jpg
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/edit-ks-installer.jpg
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/enable-telemetry.jpg
Labels: dco-signoff: yes, lgtm, size/M

#786 cluster administration title fix
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
Labels: dco-signoff: yes, size/M

#791 fix title in app templates and app store
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
Labels: dco-signoff: yes

#792 Add language change faq
  content/en/docs/faq/console/change-console-language.md
  static/images/docs/faq/kubesphere-web-console/change-console-language/basic-info-page.jpg
  static/images/docs/faq/kubesphere-web-console/change-console-language/user-settings.jpg
Labels: dco-signoff: yes, size/S

#785 Translated project-administration/project-and-multicluster-project.md.
  content/zh/docs/project-administration/project-and-multicluster-project.md
  static/images/docs/zh-cn/project-admin/basic-info-multicluster.jpg
  static/images/docs/zh-cn/project-admin/basic-info-page.jpg
  static/images/docs/zh-cn/project-admin/create-multicluster-project-page.jpg
  static/images/docs/zh-cn/project-admin/create-multicluster-project.jpg
  static/images/docs/zh-cn/project-admin/create-project-page.jpg
  static/images/docs/zh-cn/project-admin/create-project.jpg
  static/images/docs/zh-cn/project-admin/multicluster-project-list.jpg
  static/images/docs/zh-cn/project-admin/project-list.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#783 App Template translated.
  content/zh/docs/project-user-guide/application/app-template.md
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/app-store.PNG
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/private-app-repository.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#780 Update http basic auth in ZH and EN
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  content/zh/docs/workspace-administration/app-repository/import-helm-repository.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#789 Air-gapped installation under Installing on Kubernetes translated.
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/_index.md
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  static/images/docs/zh-cn/installing-on-kubernetes/installing-on-on-premises-kubernetes/air-gapped-installation/kubesphere-login.PNG
  static/images/docs/zh-cn/installing-on-kubernetes/installing-on-on-premises-kubernetes/air-gapped-installation/self-signed-cert.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#796 Refactor ZH FAQ
  content/zh/docs/faq/access-control/_index.md
  content/zh/docs/faq/access-control/forgot-password.md
  content/zh/docs/faq/console/_index.md
  content/zh/docs/faq/console/change-console-language.md
  content/zh/docs/faq/console/console-web-browser.md
  content/zh/docs/faq/console/edit-resources-in-system-workspace.md
  content/zh/docs/faq/installation/_index.md
  content/zh/docs/faq/installation/configure-booster.md
  content/zh/docs/faq/installation/telemetry.md
  content/zh/docs/faq/observability/_index.md
  content/zh/docs/faq/observability/byop.md
  content/zh/docs/faq/observability/logging.md
  content/zh/docs/faq/observability/monitoring.md
  content/zh/docs/faq/upgrade/_index.md
  content/zh/docs/faq/upgrade/upgrade-faq.md
  content/zh/docs/installing-on-kubernetes/faq/_index.md
  content/zh/docs/installing-on-kubernetes/faq/faq1.md
  content/zh/docs/installing-on-linux/_index.md
  content/zh/docs/installing-on-linux/faq/_index.md
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/pluggable-components/faq/_index.md
  content/zh/docs/upgrade/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#793 Add FAQ index page
  content/en/docs/faq/_index.md
  content/en/docs/faq/access-control/forgot-password.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#794 Translated project-administration\role-and-member-management.md.
  content/zh/docs/project-administration/role-and-member-management.md
  static/images/docs/zh-cn/project-admin/project_invite_member_step2.png
  static/images/docs/zh-cn/project-admin/project_role_create_step1.png
  static/images/docs/zh-cn/project-admin/project_role_create_step2.png
  static/images/docs/zh-cn/project-admin/project_role_detail.png
  static/images/docs/zh-cn/project-admin/project_role_list.png
  static/images/docs/zh-cn/project-admin/project_user_edit.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#797 Update wording and format in Bring Your Own Prometheus
  content/en/docs/faq/observability/byop.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#798 Minor wording change in faq
  content/en/docs/faq/console/console-web-browser.md
  content/en/docs/faq/installation/telemetry.md
  content/en/docs/faq/upgrade/qingcloud-csi-upgrade.md
  static/images/docs/faq/kubesphere-web-console/supported-browsers/console-browser.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#795 Add some installation notes
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#800 multi-node installation guide minor word fix
  content/en/docs/installing-on-linux/introduction/multioverview.md
  static/images/docs/installing-on-linux/introduction/multi-node-installation/login.png
Labels: dco-signoff: yes, size/S

#802 Update en source files for cn files in faq
  content/en/docs/faq/upgrade/qingcloud-csi-upgrade.md
  content/zh/docs/faq/console/console-web-browser.md
  content/zh/docs/faq/observability/byop.md
  content/zh/docs/faq/upgrade/qingcloud-csi-upgrade.md
Labels: dco-signoff: yes, size/L

#764 Update cluster visibility wording
  content/en/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/cluster-visibility-settings-1.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/cluster-visibility-settings-2.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/create-project.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/create-workspace.jpg
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/select-a-cluster.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#801 update api reference
  content/en/docs/api-reference/api-docs.md
  static/images/docs/api-reference/ks-apiserver.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#804 Update toolbox format and title
  content/en/docs/toolbox/auditing/auditing-query.md
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/en/docs/toolbox/auditing/auditing-rule.md
  content/en/docs/toolbox/events-query.md
  content/en/docs/toolbox/history.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
  content/zh/docs/toolbox/auditing/auditing-query.md
  content/zh/docs/toolbox/auditing/auditing-receive-customize.md
  content/zh/docs/toolbox/auditing/auditing-rule.md
  content/zh/docs/toolbox/events-query.md
  content/zh/docs/toolbox/history.md
  content/zh/docs/toolbox/log-query.md
  content/zh/docs/toolbox/web-kubectl.md
  static/images/docs/toolbox/history.png
  static/images/docs/toolbox/history/recent-history.jpg
  static/images/docs/toolbox/history/toolbox.jpg
  static/images/docs/toolbox/toolbox.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#803 Translated deploy-app-from-appstore.md
  content/zh/docs/project-user-guide/application/deploy-app-from-appstore.md
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/app-store.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nodeport.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#799 Add helm specification guide
  content/en/docs/application-store/app-developer-guide/helm-specification.md
  content/zh/docs/application-store/app-developer-guide/helm-specification.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#807 update header
  layouts/partials/header.html
Labels: approved, dco-signoff: yes, size/XS

#806 ZH doc updated.
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/ha-configuration.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  static/images/docs/zh-cn/installing-on-linux/introduction/multi-node-installation/login.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#808 Translated deploy-app-from-template.md.
  content/zh/docs/project-user-guide/application/deploy-app-from-template.md
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/add-app-repo.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/app-config.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/click-eye-icon.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/confirm-info.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/create-new-app.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/deploy-grafana.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/edit-access.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/exposed-port.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/grafana-UI.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/grafana-secret.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/grafana-services.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/home-page.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/input-repo-info.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/nodeport.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/private-app-template.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/repository-list.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/search-grafana.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/secret-page.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-templates/select-app-templates.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#813 Polish multi-cluster management intro
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/multicluster-management/introduction/overview.md
  static/images/docs/multicluster-management/introduction/kubesphere-federation/centrol-control-plane.png
  static/images/docs/multicluster-management/introduction/kubesphere-federation/kubesphere-federation.png
  static/images/docs/multicluster-management/introduction/overview/multi-cluster-overview.jpg
Labels: approved, dco-signoff: yes, lgtm, size/S

#819 Update bare metal guide format
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
Labels: dco-signoff: yes, size/L

#814 Translated rabbitmq-app.md.
  content/zh/docs/application-store/built-in-apps/rabbitmq-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitMQ04.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitMQ11.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitma-dashboard-detail.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq-dashboard.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq01.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq02.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq021.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq03.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq05.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq06.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq07.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq08.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/rabbitmq-app/rabbitmq09.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#812 Translated project-gateway.md.
  content/zh/docs/project-administration/project-gateway.md
  static/images/docs/zh-cn/project-administration/project-gateway/access-method.png
  static/images/docs/zh-cn/project-administration/project-gateway/lb.png
  static/images/docs/zh-cn/project-administration/project-gateway/nodeport.jpg
  static/images/docs/zh-cn/project-administration/project-gateway/set-project-gateway.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#822 Reviewed vars.md-zh.
  content/zh/docs/installing-on-linux/introduction/vars.md
Labels: dco-signoff: yes, lgtm, size/XS

#820 Reviewed port-firewall.md.
  content/zh/docs/installing-on-linux/introduction/port-firewall.md
Labels: dco-signoff: yes, lgtm, size/S

#821 add authentication configuration doc
  content/en/docs/access-control-and-account-management/configuring-authentication.md
  content/en/docs/faq/access-control/session-timeout.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#818 Patrick-LuoYu Translated postgresql-app.md.
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  content/zh/docs/application-store/built-in-apps/postgresql-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/access-postgresql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/click-app-store.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/container-terminal.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/deploy-postgresql-2.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/deploy-postgresql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/edit-internet-access.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/nodeport.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/port-number.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/postgresql-in-app-store.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/postgresql-output.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/postgresql-ready.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/postgresql-app/set-config.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#824 Update some images in cluster visibility
  content/en/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/assign-workspace.jpg
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/cluster-visibility-settings-1.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/cluster-visibility-settings-2.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/workspace-list.jpg
Labels: dco-signoff: yes, size/XS

#823 Translate statefulsets.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/project-user-guide-zh/workloads-zh/statefulset-request-limit.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_detail.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_detail_operation_btn.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_detail_pod.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_detail_state.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_1.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_2.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_2_container_1.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_2_container_btn.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_3.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_form_4.png
  static/images/docs/project-user-guide-zh/workloads-zh/statefulsets_list.png
  static/images/docs/project-user-guide-zh/workloads-zh/update-strategy.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#811 Deployments translated.
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/zh/docs/project-user-guide/application-workloads/_index.md
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/add-container-image.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/advanced-settings.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployment-detail-page.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployment-listed.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployment-name.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/input-image-name.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/more-actions.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/mount-volumes.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/pod-details.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/replica-number.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/resource-setting.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/resource-status.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#826 fix image in toolbox index
  content/en/docs/toolbox/_index.md
  content/zh/docs/toolbox/_index.md
  static/images/docs/toolbox/index/toolbox.jpg
Labels: dco-signoff: yes, size/S

#832 Fix some links
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-tencent-tke.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/zh/docs/pluggable-components/alerting-notification.md
  content/zh/docs/pluggable-components/network-policy.md
  content/zh/docs/pluggable-components/service-mesh.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#830 Translate daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/daemonsets.md
  static/images/docs/project-user-guide-zh/workloads-zh/daemonset-request-limit.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_detail.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_detail_operation_btn.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_detail_pod.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_detail_state.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_form_1.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_form_2_container_1.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_form_2_container_btn.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_form_3.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_form_4.png
  static/images/docs/project-user-guide-zh/workloads-zh/daemonsets_list.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#827 Translated install-kubesphere-on-bare-metal-zh.
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#833 Multicluster Introduction Section Updated.
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
  static/images/docs/zh-cn/multicluster-management/introduction/kubesphere-federation/central-control-plane.png
  static/images/docs/zh-cn/multicluster-management/introduction/kubesphere-federation/kubesphere-federation.png
  static/images/docs/zh-cn/multicluster-management/introduction/overview/multi-cluster-overview.png
Labels: approved, dco-signoff: yes, lgtm, size/S

#809 Update installing on QingCloud instance guide
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/3-master.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/active-listener.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/active.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/apply-change.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/bind-eip.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/cluster-node.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/create-lb.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/ha-architecture.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/listener.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/listener2.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/qingcloud-lb.png
  static/images/docs/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/six-instances.png
Labels: approved, dco-signoff: no, lgtm, size/L

#834 Translated tomcat-app-zh.
  content/zh/docs/application-store/built-in-apps/tomcat-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/access-tomcat-browser.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/click-deploy.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/click-next.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/click-tomcat-service.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/deploy-tomcat.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/edit-internet-access.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/exposed-port.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/find-tomcat.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/nodeport.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/tomcat-app01.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/tomcat-running.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/tomcat-teminal-icon.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/tomcat-app/view-project.jpg
Labels: dco-signoff: yes, size/M

#842 minor space fix
  content/zh/docs/application-store/built-in-apps/postgresql-app.md
  content/zh/docs/application-store/built-in-apps/tomcat-app.md
Labels: dco-signoff: yes, size/XS

#838 Translated mysql-app-zh.
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/zh/docs/application-store/built-in-apps/mysql-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/access-mysql-success.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/click-deploy.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/deploy-mysql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/edit-internet-access.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/find-mysql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/go-to-app-store.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/log-in-mysql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/login.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/mysql-port-number.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/mysql-running.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/mysql-service.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/mysql-teminal.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/mysql-workload.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/nodeport-mysql.jpg
  static/images/docs/zh-cn/appstore/built-in-apps/mysql-app/uncomment-password.jpg
Labels: dco-signoff: yes, size/M

#839 KubeSphere Alerting and Notification ZH updated.
  content/zh/docs/pluggable-components/alerting-notification.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/alerting.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/edit-yaml.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#828 Container Image Settings translated.
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/add-container-explain.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/container-health-check.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/envi-var.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/exec-command-check.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/http-request-check.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/image-pull-policy.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/pod-replicas.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/resource-request-limit.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/security-context.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/start-command.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/tcp-port-check.PNG
Labels: approved, dco-signoff: yes, lgtm, size/L

#836 KubeSphere Events ZH updated.
  content/zh/docs/pluggable-components/events.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-events/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-events/edit-yaml.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-events/events.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#841 KubeSphere Auditing Logs ZH updated.
  content/zh/docs/pluggable-components/auditing-logs.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-auditing-logs/auditing.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-auditing-logs/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-auditing-logs/edit-yaml.PNG
Labels: approved, dco-signoff: yes, lgtm, size/M

#844 Network Policies ZH updated.
  content/zh/docs/pluggable-components/network-policy.md
  static/images/docs/zh-cn/enable-pluggable-components/network-policies/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/network-policies/edit-yaml.PNG
  static/images/docs/zh-cn/enable-pluggable-components/network-policies/network-policy.PNG
Labels: dco-signoff: yes, lgtm, size/L

#843 KubeShpere Service Mesh ZH updated.
  content/zh/docs/pluggable-components/service-mesh.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-service-mesh/Istio.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-service-mesh/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-service-mesh/edit-yaml.PNG
Labels: dco-signoff: yes, lgtm, size/L

#846 Add a cn source file
  content/zh/docs/access-control-and-account-management/configuring-authentication.md
Labels: dco-signoff: yes

#847 Fix some links
  content/en/blogs/value-of-kubesphere.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/introduction/architecture.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
Labels: dco-signoff: yes, size/S

#848 Revert capitalization format
  content/en/docs/faq/installation/configure-booster.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
Labels: dco-signoff: yes, size/S

#849 Update some subtitles
  content/en/docs/application-store/built-in-apps/etcd-app.md
  content/en/docs/application-store/built-in-apps/memcached-app.md
  content/en/docs/application-store/built-in-apps/minio-app.md
  content/en/docs/application-store/built-in-apps/mongodb-app.md
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/en/docs/application-store/built-in-apps/nginx-app.md
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  content/en/docs/application-store/built-in-apps/redis-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
Labels: dco-signoff: yes, size/M

#851 Translate doc homepage titles
  content/zh/docs/api-reference/_index.md
  content/zh/docs/cluster-administration/cluster-settings/_index.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/_index.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/devops-user-guide/examples/_index.md
  content/zh/docs/devops-user-guide/how-to-integrate/_index.md
  content/zh/docs/devops-user-guide/how-to-use/_index.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/_index.md
  content/zh/docs/faq/_index.md
  content/zh/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
  content/zh/docs/project-administration/_index.md
  content/zh/docs/project-user-guide/alerting/_index.md
  content/zh/docs/project-user-guide/application/_index.md
  content/zh/docs/project-user-guide/configuration/_index.md
  content/zh/docs/project-user-guide/custom-application-monitoring/_index.md
  content/zh/docs/project-user-guide/grayscale-release/_index.md
  content/zh/docs/project-user-guide/storage/_index.md
  content/zh/docs/toolbox/_index.md
  content/zh/docs/toolbox/auditing/_index.md
  content/zh/docs/toolbox/events-query.md
  content/zh/docs/toolbox/history.md
  content/zh/docs/toolbox/log-query.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/upgrade/what-changed.md
  content/zh/docs/workspace-administration/_index.md
  content/zh/docs/workspace-administration/workspace-network-isolation.md
Labels: dco-signoff: yes, size/M

#850 Add content in import-aws-eks.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: dco-signoff: yes, size/S

#852 Fix workspace role name desc
  content/en/docs/quick-start/create-workspace-and-project.md
  content/en/docs/workspace-administration/role-and-member-management.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/workspace-administration/role-and-member-management.md
Labels: dco-signoff: yes, size/S

#853 Fix image format
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
Labels: dco-signoff: yes
