Repository kubesphere/website, pull requests merged in 2020-11, with the labels that each got.

#429 Update link in Telemetry guide
  content/en/docs/faq/telemetry.md
  content/zh/docs/faq/telemetry.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#430 GitHub network status message change
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/public-cloud/install-ks-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/kubesphere-on-qingcloud-instance.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/public-cloud/install-ks-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/kubesphere-on-qingcloud-instance.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: yes, size/L

#428 reformat quick start: install minimal ks on existing K8s
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
Labels: dco-signoff: yes, size/S

#319 add Chinese document for introduction features page
  content/zh/docs/introduction/features.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#431 Update install minimal ks on existing K8s: Merge commands into one bl…
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
Labels: dco-signoff: yes, size/XS

#423 Update SonarQube setting and Jenkins agent intro guide
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/choose-jenkins-agent.md
  static/images/devops/sonarqube-config-1.png
  static/images/devops/sonarqube-config-2.png
  static/images/devops/sonarqube-config.png
  static/images/devops/sonarqube-token-1.png
  static/images/devops/sonarqube-view.png
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/access-sonarqube-console.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/add-sonarqube.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/configure-system.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/generate-a-token.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/jenkins-login-page.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/jenkins-projet-key.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/log-in-page.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/manage-jenkins.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-config-1.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-config-2.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-config-3.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-create-project.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-example.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-install.png
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-jenkins-settings.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-view-result.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-webhook-1.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-webhook-3.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/token-created.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/webhook-page-info.jpg
  static/images/docs/devops-user-guide/jenkins-agent/jenkins-agent.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#434 add installing-on-linux_index_zh
  content/zh/docs/installing-on-linux/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#436 allinone installation - make more clean
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
Labels: approved, dco-signoff: yes, size/S

#412 add etcd docs
  content/en/docs/application-store/built-in-apps/etcd-app.md
  static/images/docs/appstore/etcd/access-etcd-data.png
  static/images/docs/appstore/etcd/access-etcd-pod.png
  static/images/docs/appstore/etcd/access-etcd-terminal.png
  static/images/docs/appstore/etcd/access-etcd-workload.png
  static/images/docs/appstore/etcd/deploy-app.png
  static/images/docs/appstore/etcd/deploy-etcd-conf.png
  static/images/docs/appstore/etcd/deploy-etcd-done.png
  static/images/docs/appstore/etcd/deploy-etcd-info.png
  static/images/docs/appstore/etcd/deploy-etcd.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#435 add api change doc
  content/en/docs/api-reference/api-changes/_index.md
  content/en/docs/api-reference/api-changes/logging.md
  content/en/docs/api-reference/api-changes/monitoring.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#425 Update _index.md
  content/zh/docs/upgrade/_index.md
Labels: dco-signoff: no, size/S

#441 Sync en to zh
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
Labels: approved, lgtm, size/M

#443 Update ZH-CN upgrade index
  content/zh/docs/upgrade/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#442 update doc item
  layouts/partials/section.html
Labels: approved, dco-signoff: yes, lgtm

#444 Add devops guide index
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/devops-user-guide/how-to-integrate/_index.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#426 Update upgrade-overview.md
  content/zh/docs/upgrade/upgrade-overview.md
Labels: dco-signoff: no, size/S

#419 add app store doc(mysql) and Modify some descriptions of rabbitmq,tomcat
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  static/images/docs/mysql-app/mysql01.png
  static/images/docs/mysql-app/mysql02.png
  static/images/docs/mysql-app/mysql03.png
  static/images/docs/mysql-app/mysql04.png
  static/images/docs/mysql-app/mysql05.png
  static/images/docs/mysql-app/mysql06.png
  static/images/docs/mysql-app/mysql07.png
  static/images/docs/mysql-app/mysql08.png
  static/images/docs/mysql-app/mysql09.png
  static/images/docs/mysql-app/mysql10.png
  static/images/docs/mysql-app/mysql11.png
  static/images/docs/mysql-app/mysql12.png
  static/images/docs/mysql-app/mysql13.png
  static/images/docs/mysql-app/mysql14.png
  static/images/docs/mysql-app/mysql15.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#437 Add calendar page
  assets/scss/contribution.scss
  content/en/contribution/_index.md
  content/zh/contribution/_index.md
  layouts/contribution/list.html
Labels: approved, dco-signoff: yes, lgtm, size/M

#438 Change Wordpress to WordPress
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/quick-start/wordpress-deployment.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#447 update monitoring api change doc
  content/en/docs/api-reference/api-changes/monitoring.md
Labels: dco-signoff: yes, size/S

#448 Update ZH-CN linux installation index
  content/zh/docs/installing-on-linux/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#446 Update the index of installing ks on linux
  content/en/docs/installing-on-linux/_index.md
Labels: dco-signoff: yes, lgtm, size/XS

#449 refine installing ks on existing K8s
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-huawei-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/installing-on-kubernetes/introduction/overview.md
Labels: approved, dco-signoff: no, size/M

#287 add service-mesh docs
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/en/docs/project-user-guide/grayscale-release/traffic-mirroring.md
  static/images/service-mesh/blue-green-0.png
  static/images/service-mesh/blue-green-1.jpg
  static/images/service-mesh/blue-green-2.jpg
  static/images/service-mesh/blue-green-3.jpg
  static/images/service-mesh/blue-green-4.jpg
  static/images/service-mesh/blue-green-5.jpg
  static/images/service-mesh/blue-green-6.jpg
  static/images/service-mesh/blue-green-7.jpg
  static/images/service-mesh/canary-release-0.png
  static/images/service-mesh/canary-release-1.jpg
  static/images/service-mesh/canary-release-2.jpg
  static/images/service-mesh/canary-release-3.jpg
  static/images/service-mesh/canary-release-4.jpg
  static/images/service-mesh/canary-release-5.jpg
  static/images/service-mesh/canary-release-6.jpg
  static/images/service-mesh/canary-release-7.jpg
  static/images/service-mesh/istio-1.jpg
  static/images/service-mesh/traffic-mirroing-4.jpg
  static/images/service-mesh/traffic-mirroring-1.jpg
  static/images/service-mesh/traffic-mirroring-2.jpg
  static/images/service-mesh/traffic-mirroring-3.jpg
  static/images/service-mesh/traffic-mirroring-4.jpg
  static/images/service-mesh/traffic-mirroring-5.jpg
  static/images/service-mesh/traffic-mirroring-6.jpg
  static/images/service-mesh/traffic-mirroring-7.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#303 storageclass & volume docs
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/en/docs/cluster-administration/storageclass.md
  content/en/docs/project-user-guide/storage/volume-snapshots.md
  content/en/docs/project-user-guide/storage/volumes.md
  static/images/storage/apply-snapshot.png
  static/images/storage/attach-volume.png
  static/images/storage/create-snapshot.png
  static/images/storage/create-storage-class-basic-info.png
  static/images/storage/create-storage-class-settings.png
  static/images/storage/create-storage-class-storage-system-custom.png
  static/images/storage/create-storage-class-storage-system.png
  static/images/storage/create-volume.png
  static/images/storage/snapshot-list.png
  static/images/storage/storage-system.png
  static/images/storage/volume-features.png
  static/images/storage/volume-monitoring.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#451 Fix format issue: storage class
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
Labels: dco-signoff: yes

#452 Update installing ks on aks and eks
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#454 Update PV wording
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/clusters-management-select.jpg
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/create-storage-class-basic-info.png
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/create-storage-class-settings.png
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/create-storage-class-storage-system.png
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/custom-storage-class.jpg
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/storage-class.jpg
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/storage-system.png
  static/images/docs/cluster-administration/persistent-volume-and-storage-class/storage-volume-qingcloud.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#453 Update installing ks on cloud hosted K8s
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-huawei-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#445 add google analytics
  config/upstream/config.toml
  layouts/forum/list.html
  layouts/partials/head.html
  layouts/reason/list.html
  layouts/trends/list.html
Labels: approved, dco-signoff: yes, lgtm, size/M

#364 add api page
  content/en/api/crd.md
  content/en/api/kubesphere.md
  content/en/reason/_index.md
  content/zh/api/crd.md
  content/zh/api/kubesphere.md
  content/zh/reason/_index.md
  layouts/api/single.html
  static/images/ApiDocs.svg
  static/json/crd.json
  static/json/kubesphere.json
Labels: approved, dco-signoff: yes, size/XXL

#407 Add Memcached and PostgreSQL app doc
  content/en/docs/application-store/built-in-apps/memcached-app.md
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  static/images/docs/appstore/memcached/choose_memcached_from_app_store.png
  static/images/docs/appstore/memcached/connect_memcached.png
  static/images/docs/appstore/memcached/deploy_memcached.png
  static/images/docs/appstore/memcached/deploy_memcached_confirm.png
  static/images/docs/appstore/memcached/memcached_active.png
  static/images/docs/appstore/memcached/view_memcached_workload.png
  static/images/docs/appstore/postgresql/choose_postgresql_from_app_store.png
  static/images/docs/appstore/postgresql/connect_postgresql.png
  static/images/docs/appstore/postgresql/deploy_postgresql.png
  static/images/docs/appstore/postgresql/deploy_postgresql_confirm.png
  static/images/docs/appstore/postgresql/expose_postgresql_service.png
  static/images/docs/appstore/postgresql/get_postgresql_secret.png
  static/images/docs/appstore/postgresql/postgresql_active.png
  static/images/docs/appstore/postgresql/view_postgresql_service.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#458 翻译邮件服务器文档
  content/zh/docs/cluster-administration/cluster-settings/_index.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/_index.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-es-as-receiver.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-fluentd-as-receiver.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-kafka-as-receiver.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/cluster-administration/cluster-settings/mail-server.md
  static/images/docs/alerting/mail_server_config-zh.png
  static/images/docs/alerting/mail_server_guide-zh.png
Labels: dco-signoff: yes, size/XL

#457 Upate multi-cluster installation
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
Labels: approved, dco-signoff: yes, size/L

#456 Update blue-green deployment and canary release wording and images
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-0.png
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-1.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-2.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-3.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-4.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-5.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-6.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-7.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-job-list.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/version2-deployment.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/cabary-release-3.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-0.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-4.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-5.gif
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-6.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-job.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/create-canary-release.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/deployment-list-1.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/job-offline.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/set-task-name.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/take-over-traffic.jpg
  static/images/service-mesh/blue-green-1.jpg
  static/images/service-mesh/blue-green-2.jpg
  static/images/service-mesh/blue-green-3.jpg
  static/images/service-mesh/blue-green-4.jpg
  static/images/service-mesh/blue-green-5.jpg
  static/images/service-mesh/canary-release-1.jpg
  static/images/service-mesh/canary-release-2.jpg
  static/images/service-mesh/canary-release-3.jpg
  static/images/service-mesh/canary-release-4.jpg
  static/images/service-mesh/canary-release-5.jpg
  static/images/service-mesh/canary-release-7.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#403 Add OAuth2 provider user guide
  content/zh/docs/access-control-and-account-management/_index.md
  content/zh/docs/access-control-and-account-management/oauth2.md
  static/images/docs/access-control-and-account-management/github1.png
  static/images/docs/access-control-and-account-management/github2.png
  static/images/docs/access-control-and-account-management/github3.png
  static/images/docs/access-control-and-account-management/github4.png
  static/images/docs/access-control-and-account-management/oauth2.svg
Labels: approved, dco-signoff: yes, lgtm, size/L

#459 update copy code img
  assets/scss/common.scss
  static/images/docs/copy.png
Labels: dco-signoff: yes, size/XS

#460 Update enable app store
  content/en/docs/pluggable-components/app-store.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#461 Update traffic mirroring guide
  content/en/docs/project-user-guide/grayscale-release/traffic-mirroring.md
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/new-deployment.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/remove-traffic-mirroring.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroing-task.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-1.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-2.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-3.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-4.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-5.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-6.jpg
  static/images/service-mesh/traffic-mirroring-1.jpg
  static/images/service-mesh/traffic-mirroring-2.jpg
  static/images/service-mesh/traffic-mirroring-3.jpg
  static/images/service-mesh/traffic-mirroring-4.jpg
  static/images/service-mesh/traffic-mirroring-5.jpg
Labels: dco-signoff: yes, size/M

#421 Feature: docs for "How to compile and deploy a Go project" and "How to deloy applications cross multiple clusters"
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  static/images/devops/create-dockerhub-id.png
  static/images/devops/create-kubeconfig.png
  static/images/devops/devops-go-ok.png
  static/images/devops/dockerhub-create-token.png
  static/images/devops/dockerhub-settings.png
  static/images/devops/dockerhub-token-copy.png
  static/images/devops/dockerhub-token-ok.png
  static/images/devops/multi-cluster-ok.png
Labels: dco-signoff: yes, size/L

#463 Minor format change
  content/en/docs/devops-user-guide/_index.md
Labels: approved, dco-signoff: yes, lgtm

#439 Update jenkinsfile building pipeline wording and images
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/devops/20200107230822.png
  static/images/devops/20200107232100.png
  static/images/devops/20200108134653.png
  static/images/devops/jenkins-edit-1.png
  static/images/devops/jenkins-edit-2.png
  static/images/devops/service-view.png
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/activity-failure.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/advanced-setting.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/branch-settings.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/commit-changes.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/create-pipeline.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/credential-list.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/fork-github-repo.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/generate-github-token-1.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/generate-github-token-2.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/inspect-pipeline-log-1.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/inspect-pipeline-log-2.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/jenkins-edit-1.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/jenkins-edit-2.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/jenkinsfile-online.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/pipeline-detail.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/pipeline-list.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/pipeline-proceed.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/project-list.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/remove-behavioral-strategy.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/select-repo.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/sonar-token.jpg
  static/images/docs/devops-user-guide/create-a-pipeline-using-a-jenkinsfile/tag-name.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/access-endpoint.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/devops-prod.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/docker-hub-result.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/github-result.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/pipeline-deployments.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sample-app-result-check.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-result-detail-1.jpg.jpg
  static/images/docs/devops-user-guide/integrate-sonarqube-into-pipeline/sonarqube-result-detail.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#464 zh-project-user-guide-index-page
  content/zh/docs/project-user-guide/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#465 Update go project wording
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/copied-jenkins.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-dockerhub-id.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-kubeconfig.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/credential-docker-create.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/docker-image-1.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/docker-image-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/dockerhub-create-token.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/dockerhub-settings.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/dockerhub-token-copy.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/dockerhub-token-ok.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/edit-jenkinsfile.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/pipeline-running.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/run-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/set-pipeline-name.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/view-deployments.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#466 doc(pluggable-components): initial zh translation
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/pluggable-components/alerting-notification.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/faq/_index.md
  content/zh/docs/pluggable-components/faq/logging.md
  content/zh/docs/pluggable-components/faq/monitoring.md
  content/zh/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/network-policy.md
  content/zh/docs/pluggable-components/overview.md
  content/zh/docs/pluggable-components/service-mesh.md
Labels: approved, dco-signoff: yes, lgtm

#467 Update optional components enabling guide - app store, devops
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/devops.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#470 add google tag manager
  config/upstream/config.toml
  layouts/_default/baseof.html
  layouts/docs/single.html
  layouts/partials/content.html
  layouts/partials/head.html
Labels: dco-signoff: yes, size/M

#401 refine TiDB on KubeSphere
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/docs/cluster-administration/platform-settings/customize-basic-information.md
  content/en/docs/cluster-administration/shuting-down-and-restart-cluster-cracefully.md
  content/zh/blogs/tidb-on-kbesphere-using-qke.md
Labels: approved, dco-signoff: yes, size/L

#471 update google analytics script
  layouts/partials/head.html
Labels: dco-signoff: yes

#473 修复图片链接cluster-status-monitoring.md
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/platform.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#462 zh-cn localization of index page of multi-cluster management
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/multicluster-management/introduction/_index.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#468 Update install optional components - events, auditing
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/service-mesh.md
Labels: approved, dco-signoff: yes, size/XL

#474 Revert "修复图片链接cluster-status-monitoring.md"
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/platform.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#475 Update FAQ from Enable Pluggable Components
  content/en/docs/pluggable-components/faq/logging.md
  content/en/docs/pluggable-components/faq/monitoring.md
  content/en/docs/pluggable-components/network-policy.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#476 Chinese translation of page：quick-start/enable-pluggable-components
  content/zh/docs/quick-start/enable-pluggable-components.md
  static/images/docs/quickstart/clusters-management-zh.png
  static/images/docs/quickstart/crds-zh.png
  static/images/docs/quickstart/edit-ks-installer-zh.png
  static/images/docs/quickstart/enable-components-zh.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#477 Update Upgrade
  content/en/docs/upgrade/upgrade-overview.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#479 Chinese translation of page：quick-start/wordpress-deployment
  content/zh/docs/quick-start/wordpress-deployment.md
  static/images/docs/quickstart/WordPress-1.png
  static/images/docs/quickstart/access-method.png
  static/images/docs/quickstart/add-mysql-backend-component.png
  static/images/docs/quickstart/add-service.png
  static/images/docs/quickstart/add-wordPress-frontend-component.png
  static/images/docs/quickstart/advanced-setting.png
  static/images/docs/quickstart/advanced-settings-wordpress.png
  static/images/docs/quickstart/basic-info.png
  static/images/docs/quickstart/choose-existing-volume.png
  static/images/docs/quickstart/choose-existing.png
  static/images/docs/quickstart/container-image-mysql.png
  static/images/docs/quickstart/container-image-wordpress.png
  static/images/docs/quickstart/container-image.png
  static/images/docs/quickstart/create-secret.png
  static/images/docs/quickstart/create-volume.png
  static/images/docs/quickstart/create.png
  static/images/docs/quickstart/edit-internet-access.png
  static/images/docs/quickstart/environment-var.png
  static/images/docs/quickstart/environment-varss.png
  static/images/docs/quickstart/ingress.png
  static/images/docs/quickstart/key-value.png
  static/images/docs/quickstart/mysql-done.png
  static/images/docs/quickstart/mysql-name.png
  static/images/docs/quickstart/nodeport-number.png
  static/images/docs/quickstart/two-components-done.png
  static/images/docs/quickstart/volume-settings.png
  static/images/docs/quickstart/volume-template-wordpress.png
  static/images/docs/quickstart/volume-template.png
  static/images/docs/quickstart/wordpress-deployment.png
  static/images/docs/quickstart/wordpress-secrets.png
  static/images/docs/quickstart/wordpress-statefulset.png
  static/images/docs/quickstart/wordpress.png
Labels: approved, dco-signoff: yes, lgtm

#480 Update cluster management - index, storage
  content/en/contribution/_index.md
  content/en/docs/cluster-administration/_index.md
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/contribution/_index.md
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#483 fix:share url
  layouts/partials/content.html
Labels: dco-signoff: yes, size/XS

#418 feature: add a maven project example
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  static/images/devops/edit-jenkinsfile.png
  static/images/devops/maven-project-jenkins.png
  static/images/devops/run-maven-pipeline.png
  static/images/devops/view-credential-list.png
  static/images/devops/view-edit-jenkinsfile.png
  static/images/devops/view-namespace.png
  static/images/devops/view-result-maven-pipeline.png
  static/images/devops/view-result-maven-workload-svc.png
  static/images/devops/view-result-maven-workload.png
Labels: dco-signoff: yes, size/L

#484 Update cluster adminstation
  content/en/docs/cluster-administration/application-resources-monitoring.md
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  content/en/docs/cluster-administration/nodes.md
Labels: dco-signoff: yes, lgtm, size/M

#286 Add multicluster blog
  content/en/blogs/multi-cluster-deployment.md
  content/zh/case/vng.md
Labels: size/L

#487 Update cluster wide alerting and notification
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#490 add all-in-one on linux zh docs
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#489 format log connections and mail server
  content/en/docs/cluster-administration/cluster-settings/log-collections/add-es-as-receiver.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/add-fluentd-as-receiver.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/add-kafka-as-receiver.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/cluster-administration/cluster-settings/mail-server.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#493 note cn update
  i18n/zh.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#494 Update tomcat guide
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  static/images/docs/appstore/built-in-apps/tomcat-app/access-tomcat-browser.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/click-deploy.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/click-next.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/click-tomcat-service.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/deploy-tomcat.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/edit-internet-access.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/exposed-port.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/find-tomcat.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/nodeport.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/tomcat-app01.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/tomcat-running.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/tomcat-teminal-icon.jpg
  static/images/docs/appstore/built-in-apps/tomcat-app/view-project.jpg
  static/images/docs/tomcat-app/tomcat-app01.jpg
  static/images/docs/tomcat-app/tomcat-app02.jpg
  static/images/docs/tomcat-app/tomcat-app03.jpg
  static/images/docs/tomcat-app/tomcat-app04.jpg
  static/images/docs/tomcat-app/tomcat-app05.jpg
  static/images/docs/tomcat-app/tomcat-app06.jpg
  static/images/docs/tomcat-app/tomcat-app07.jpg
  static/images/docs/tomcat-app/tomcat-app08.jpg
  static/images/docs/tomcat-app/tomcat-app09.jpg
  static/images/docs/tomcat-app/tomcat-app11.jpg
  static/images/docs/tomcat-app/tomcat-app12.jpg
  static/images/docs/tomcat-app/tomcat-app13.jpg
  static/images/docs/tomcat-app/tomcat-app14.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#492 Update rabbitmq guide
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitMQ04.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitMQ11.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitma-dashboard-detail.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq-dashboard.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq01.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq02.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq021.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq03.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq05.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq06.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq07.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq08.jpg
  static/images/docs/appstore/built-in-apps/rabbitmq-app/rabbitmq09.jpg
  static/images/docs/rabbitmq-app/rabbitMQ04.jpg
  static/images/docs/rabbitmq-app/rabbitmq01.jpg
  static/images/docs/rabbitmq-app/rabbitmq02.jpg
  static/images/docs/rabbitmq-app/rabbitmq021.jpg
  static/images/docs/rabbitmq-app/rabbitmq03.jpg
  static/images/docs/rabbitmq-app/rabbitmq05.jpg
  static/images/docs/rabbitmq-app/rabbitmq06.jpg
  static/images/docs/rabbitmq-app/rabbitmq07.jpg
  static/images/docs/rabbitmq-app/rabbitmq08.jpg
  static/images/docs/rabbitmq-app/rabbitmq09.png
  static/images/docs/rabbitmq-app/rabbitmq10.png
Labels: approved, lgtm

#491 Update Chinese doc of installing allinone on linux
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: approved, dco-signoff: yes, size/M

#498 Update import helm repo doc.
  content/en/docs/workspaces-administration/import-helm-repository.md
  static/images/application-templates/20201109150224.png
Labels: approved, dco-signoff: yes, lgtm, size/XS

#472 Update multicluster app deployment using jenkinsfile
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/copied-jenkins.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-dockerhub-id.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-kubeconfig.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/credential-docker-create.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/docker-image-1.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/docker-image-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/dockerhub-create-token.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/dockerhub-settings.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/dockerhub-token-copy.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/dockerhub-token-ok.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/edit-jenkinsfile.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/multi-cluster-ok.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/pipeline-running.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/run-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/set-pipeline-name.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/view-deployments.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#398 Update QingCloud Storage setting installation explanation
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
  content/zh/docs/installing-on-linux/introduction/storage-configuration.md
  static/images/docs/installing-on-linux/introduction/persistent-storage-configuration/access-key.jpg
  static/images/docs/installing-on-linux/introduction/persistent-storage-configuration/storage-zone.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#499 Fix typo
  content/en/docs/access-control-and-account-management/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#501 Updates for toolbox
  content/en/docs/toolbox/_index.md
  content/en/docs/toolbox/auditing/_index.md
  content/en/docs/toolbox/events-query.md
  content/en/docs/toolbox/history.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
  static/images/docs/toolbox/history.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#495 Update workspace administration
  content/en/docs/workspace-administration/_index.md
  content/en/docs/workspace-administration/import-helm-repository.md
  content/en/docs/workspace-administration/role-and-member-management.md
  content/en/docs/workspace-administration/upload-helm-based-application.md
  content/en/docs/workspace-administration/what-is-workspace.md
  content/en/docs/workspace-administration/workspace-network-isolation.md
  content/en/docs/workspaces-administration/_index.md
  content/en/docs/workspaces-administration/upload-helm-based-application.md
  content/zh/docs/access-control-and-account-management/oauth2.md
  content/zh/docs/introduction/features.md
  content/zh/docs/workspace-administration/_index.md
  content/zh/docs/workspace-administration/import-helm-repository.md
  content/zh/docs/workspace-administration/role-and-member-management.md
  content/zh/docs/workspace-administration/upload-helm-based-application.md
  content/zh/docs/workspace-administration/what-is-workspace.md
  content/zh/docs/workspace-administration/workspace-network-isolation.md
  content/zh/docs/workspaces-administration/_index.md
  content/zh/docs/workspaces-administration/release-v210.md
  content/zh/docs/workspaces-administration/release-v211.md
  content/zh/docs/workspaces-administration/release-v300.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#503 fix file name typo and add some en source files to zh folder
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/_index.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
  content/zh/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#478 Translate cluster-status-monitoring.md
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/apiserver-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/cluster-nodes.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/cluster-resources-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/cluster-status-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/clusters-management.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/component-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/cpu-load-average.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/cpu-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/disk-throughput.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/disk-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/etcd-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/inode-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/iops.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/memory-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/netework-bandwidth.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/node-usage-ranking.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/physical-resources-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/pod-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/running-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/scheduler-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/service-components-status.png
Labels: dco-signoff: yes, size/L

#502 Update tidb blog
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
Labels: dco-signoff: yes, size/L

#486 Correct typos
  content/zh/docs/multicluster-management/enable-multicluster/_index.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/retrieve-kubeconfig.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
Labels: dco-signoff: yes, size/L

#500 Update mysql
  content/en/docs/application-store/built-in-apps/mysql-app.md
  static/images/docs/appstore/built-in-apps/mysql-app/access-mysql-success.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/click-deploy.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/deploy-mysql.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/edit-internet-access.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/find-mysql.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/go-to-app-store.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/log-in-mysql.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/login.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/mysql-port-number.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/mysql-running.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/mysql-service.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/mysql-teminal.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/mysql-workload.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/nodeport-mysql.jpg
  static/images/docs/appstore/built-in-apps/mysql-app/uncomment-password.jpg
  static/images/docs/mysql-app/mysql01.png
  static/images/docs/mysql-app/mysql02.png
  static/images/docs/mysql-app/mysql03.png
  static/images/docs/mysql-app/mysql04.png
  static/images/docs/mysql-app/mysql05.png
  static/images/docs/mysql-app/mysql06.png
  static/images/docs/mysql-app/mysql07.png
  static/images/docs/mysql-app/mysql08.png
  static/images/docs/mysql-app/mysql09.png
  static/images/docs/mysql-app/mysql10.png
  static/images/docs/mysql-app/mysql11.png
  static/images/docs/mysql-app/mysql12.png
  static/images/docs/mysql-app/mysql13.png
  static/images/docs/mysql-app/mysql14.png
  static/images/docs/mysql-app/mysql15.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#504 format toolbox --> log query, events query
  content/en/docs/toolbox/events-query.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#488 supplement air-gagged installation
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  static/images/docs/air-gapped/docker-registry.png
  static/images/docs/air-gapped/load-image.png
  static/images/docs/air-gapped/validate-registry.png
Labels: dco-signoff: yes, size/L

#507 add growingio
  layouts/partials/head.html
  layouts/partials/searchInput.html
Labels: dco-signoff: yes, size/S

#510 Update air-gapped installation on linux
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  static/images/docs/installing-on-linux/introduction/air-gapped-installation/self-signed-cert.jpg
Labels: dco-signoff: yes, size/XL

#508 Update glossary
  content/en/docs/api-reference/api-glossary.md
  content/en/docs/api-reference/glossary.md
  content/zh/docs/api-reference/_index.md
  content/zh/docs/api-reference/api-changes/_index.md
  content/zh/docs/api-reference/api-changes/logging.md
  content/zh/docs/api-reference/api-changes/monitoring.md
  content/zh/docs/api-reference/api-docs.md
  content/zh/docs/api-reference/glossary.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#506 Update etcd guide
  content/en/docs/application-store/built-in-apps/etcd-app.md
  static/images/docs/appstore/built-in-apps/etcd-app/deploy-etcd.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/deployment-location.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/etcd-app-store.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/etcd-command.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/etcd-running.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/etcd-statefulset.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/etcd-teminal.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/project-overview.jpg
  static/images/docs/appstore/built-in-apps/etcd-app/specify-volume.jpg
  static/images/docs/appstore/etcd/access-etcd-data.png
  static/images/docs/appstore/etcd/access-etcd-pod.png
  static/images/docs/appstore/etcd/access-etcd-terminal.png
  static/images/docs/appstore/etcd/access-etcd-workload.png
  static/images/docs/appstore/etcd/deploy-app.png
  static/images/docs/appstore/etcd/deploy-etcd-conf.png
  static/images/docs/appstore/etcd/deploy-etcd-done.png
  static/images/docs/appstore/etcd/deploy-etcd-info.png
  static/images/docs/appstore/etcd/deploy-etcd.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#511 clean up reference
  content/en/docs/api-reference/_index.md
  content/en/docs/reference/_index.md
  content/en/docs/reference/api-changes/_index.md
  content/en/docs/reference/api-changes/logging.md
  content/en/docs/reference/api-changes/monitoring.md
  content/en/docs/reference/api-docs.md
  content/en/docs/reference/glossary.md
  content/zh/docs/api-reference/_index.md
  content/zh/docs/reference/_index.md
  content/zh/docs/reference/api-changes/_index.md
  content/zh/docs/reference/api-changes/logging.md
  content/zh/docs/reference/api-changes/monitoring.md
  content/zh/docs/reference/api-docs.md
  content/zh/docs/reference/glossary.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#516 Update telemetry
  content/en/docs/faq/telemetry.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#481 Update application lifecycle management
  content/en/docs/application-store/app-lifecycle-management.md
  static/images/application-templates/app-templates-draft.png
  static/images/application-templates/deploy-emqx.png
  static/images/application-templates/edit-template.png
  static/images/application-templates/upload-icons.png
  static/images/application-templates/upload-templates.png
  static/images/docs/appstore/application-lifecycle-management/account-ready.jpg
  static/images/docs/appstore/application-lifecycle-management/activate-app.jpg
  static/images/docs/appstore/application-lifecycle-management/activate-version.jpg
  static/images/docs/appstore/application-lifecycle-management/app-active.jpg
  static/images/docs/appstore/application-lifecycle-management/app-category-1.jpg
  static/images/docs/appstore/application-lifecycle-management/app-category.jpg
  static/images/docs/appstore/application-lifecycle-management/app-deploy.jpg
  static/images/docs/appstore/application-lifecycle-management/app-draft.jpg
  static/images/docs/appstore/application-lifecycle-management/app-in-category-list-expected.jpg
  static/images/docs/appstore/application-lifecycle-management/app-processing.jpg
  static/images/docs/appstore/application-lifecycle-management/app-review-name.jpg
  static/images/docs/appstore/application-lifecycle-management/app-store.png
  static/images/docs/appstore/application-lifecycle-management/app-templates-page.jpg
  static/images/docs/appstore/application-lifecycle-management/app-to-be-reviewed.jpg
  static/images/docs/appstore/application-lifecycle-management/app-to-be-upgraded.jpg
  static/images/docs/appstore/application-lifecycle-management/assign-category.jpg
  static/images/docs/appstore/application-lifecycle-management/confirm-category.jpg
  static/images/docs/appstore/application-lifecycle-management/create-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/create-review-role.jpg
  static/images/docs/appstore/application-lifecycle-management/create-role.jpg
  static/images/docs/appstore/application-lifecycle-management/create-roles.png
  static/images/docs/appstore/application-lifecycle-management/deploy-redis.jpg
  static/images/docs/appstore/application-lifecycle-management/deployed-instance-success.jpg
  static/images/docs/appstore/application-lifecycle-management/deploying-app.jpg
  static/images/docs/appstore/application-lifecycle-management/deployment-place.jpg
  static/images/docs/appstore/application-lifecycle-management/edit-app-information.jpg
  static/images/docs/appstore/application-lifecycle-management/edit-app-template.jpg
  static/images/docs/appstore/application-lifecycle-management/edit-template.png
  static/images/docs/appstore/application-lifecycle-management/new-version-draft.jpg
  static/images/docs/appstore/application-lifecycle-management/new-version-redis.jpg
  static/images/docs/appstore/application-lifecycle-management/redis-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/redis.jpg
  static/images/docs/appstore/application-lifecycle-management/release-to-store.jpg
  static/images/docs/appstore/application-lifecycle-management/remove-app.jpg
  static/images/docs/appstore/application-lifecycle-management/reviewing.jpg
  static/images/docs/appstore/application-lifecycle-management/see-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/set-app-type.jpg
  static/images/docs/appstore/application-lifecycle-management/set-category-for-app.jpg
  static/images/docs/appstore/application-lifecycle-management/submit-for-review.jpg
  static/images/docs/appstore/application-lifecycle-management/submitted-app.jpg
  static/images/docs/appstore/application-lifecycle-management/suspend-app.jpg
  static/images/docs/appstore/application-lifecycle-management/suspend-version.jpg
  static/images/docs/appstore/application-lifecycle-management/template-list-one-app.jpg
  static/images/docs/appstore/application-lifecycle-management/test-deployment.jpg
  static/images/docs/appstore/application-lifecycle-management/test-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/upgrade-an-app.jpg
  static/images/docs/appstore/application-lifecycle-management/upgrade-finish.jpg
  static/images/docs/appstore/application-lifecycle-management/upload-app.jpg
  static/images/docs/appstore/application-lifecycle-management/upload-icon.jpg
  static/images/docs/appstore/application-lifecycle-management/upload-new-redis-version.jpg
  static/images/docs/appstore/application-lifecycle-management/upload-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/upload-template.jpg
  static/images/docs/appstore/application-lifecycle-management/uploaded-new-version.jpg
  static/images/docs/appstore/application-lifecycle-management/version-upgraded.jpg
Labels: dco-signoff: yes, size/L

#514 Update api doc
  content/en/docs/reference/api-changes/logging.md
  content/en/docs/reference/api-changes/monitoring.md
  content/en/docs/reference/api-docs.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#518 add aws quickstart and qke links
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: approved, dco-signoff: yes, size/S

#513 add import eks using direct method
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  static/images/docs/eks-kubeconfig.png
  static/images/docs/eks-overview.png
Labels: approved, dco-signoff: yes, size/L

#519 1. Update _index in project user guide
  content/en/docs/project-user-guide/_index.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  content/en/docs/project-user-guide/application-workloads/ingress.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/project-user-guide/application-workloads/s2i-template.md
  content/en/docs/project-user-guide/application-workloads/services.md
  content/en/docs/project-user-guide/application/compose-app.md
  content/en/docs/project-user-guide/configuration/secrets.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/_index.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/en/docs/project-user-guide/custom-application-monitoring/introduction.md
  content/zh/docs/project-user-guide/_index.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#517 Add app store index
  content/en/docs/application-store/_index.md
Labels: dco-signoff: yes, size/M

#521 add sync to gitee
  .github/workflows/build.yml
Labels: approved, dco-signoff: yes, size/S

#515 Translation installing on linux chapter, from en version to zh
  content/zh/docs/installing-on-linux/_index.md
  content/zh/docs/installing-on-linux/cluster-operation/_index.md
  content/zh/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/installing-on-linux/cluster-operation/remove-nodes.md
  content/zh/docs/installing-on-linux/faq/_index.md
  content/zh/docs/installing-on-linux/introduction/_index.md
  content/zh/docs/installing-on-linux/introduction/intro.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/port-firewall.md
  content/zh/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/on-premises/_index.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/public-cloud/_index.md
  content/zh/docs/installing-on-linux/public-cloud/install-ks-on-azure-vms.md
  content/zh/docs/installing-on-linux/uninstalling/_index.md
  content/zh/docs/installing-on-linux/uninstalling/uninstalling-kubesphere-and-Kubernetes.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#512 Add air-gapped installation guide on K8s
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
Labels: dco-signoff: yes, size/L

#522 Update Memcached guide
  content/en/docs/application-store/built-in-apps/memcached-app.md
  static/images/docs/appstore/built-in-apps/memcached-app/deploying-memcached.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/deployment-confirm.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/edit-config.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/in-app-store.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/memcached-app-store.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/memcached-port-pod.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/memcached-running.jpg
  static/images/docs/appstore/built-in-apps/memcached-app/memcached-service.jpg
  static/images/docs/appstore/memcached/choose_memcached_from_app_store.png
  static/images/docs/appstore/memcached/connect_memcached.png
  static/images/docs/appstore/memcached/deploy_memcached.png
  static/images/docs/appstore/memcached/deploy_memcached_confirm.png
  static/images/docs/appstore/memcached/memcached_active.png
  static/images/docs/appstore/memcached/view_memcached_workload.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#524 Update deployment, statefulset, daemonset in project user guide
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
Labels: approved, dco-signoff: yes, size/L

#526 Update service, job, cronjob in project user guide
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/project-user-guide/application-workloads/services.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#525 Update minio
  content/en/docs/application-store/built-in-apps/minio-app.md
  static/images/docs/appstore/built-in-apps/minio-app/config-file.jpg
  static/images/docs/appstore/built-in-apps/minio-app/deloy-minio-2.jpg
  static/images/docs/appstore/built-in-apps/minio-app/deploy-minio.jpg
  static/images/docs/appstore/built-in-apps/minio-app/edit-internet-access.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-app.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-browser-interface.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-browser.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-deploy.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-detail.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-in-app-store.jpg
  static/images/docs/appstore/built-in-apps/minio-app/minio-in-list.jpg
  static/images/docs/appstore/built-in-apps/minio-app/nodeport.jpg
  static/images/docs/appstore/built-in-apps/minio-app/port-exposed.jpg
  static/images/docs/appstore/built-in-apps/minio-app/template-list.jpg
  static/images/docs/appstore/minio/choose_minio_from_app_store.png
  static/images/docs/appstore/minio/deploy_minio.png
  static/images/docs/appstore/minio/deploy_minio_confirm.png
  static/images/docs/appstore/minio/expose_minio_service.png
  static/images/docs/appstore/minio/get_minio_access_key.png
  static/images/docs/appstore/minio/login_minio_console.png
  static/images/docs/appstore/minio/minio_active.png
  static/images/docs/appstore/minio/view_minio_service.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#527 Add "Workload" for deployment, statefulset, daemonset in project user…
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#411 Feature: add how-to-integrate-harbor-with-devpos docs
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/devops/create-pipline-2.png
  static/images/devops/create-pipline-3.png
  static/images/devops/edit-jenkins-file.png
  static/images/devops/harbor-login.png
  static/images/devops/harbor-new-project.png
  static/images/devops/harbor-project-ok.png
  static/images/devops/harbor-robot-account-ok.png
  static/images/devops/harbor-robot-account-save.png
  static/images/devops/harbor-robot-account.png
  static/images/devops/ks-console-create-credential.png
  static/images/devops/ks-console-create-pipline.png
  static/images/devops/ks-console-credential-ok.png
  static/images/devops/run-pipline.png
Labels: dco-signoff: yes, lgtm, size/L

#529 Update configmap under project user guide
  content/en/docs/project-user-guide/configuration/_index.md
  content/en/docs/project-user-guide/configuration/configmaps.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#379 add deploy harbor doc
  content/en/docs/application-store/built-in-apps/harbor-app.md
  static/images/docs/appstore/harbor/active_of_harbor.png
  static/images/docs/appstore/harbor/choose_app_from_store.png
  static/images/docs/appstore/harbor/config_of_harbor_deploy.png
  static/images/docs/appstore/harbor/deploy_set_of_harbor.png
  static/images/docs/appstore/harbor/overview_of_harbor_login.png
Labels: dco-signoff: yes, lgtm, size/M

#523 Clean and update apllication in project user guide
  content/en/docs/project-user-guide/application/_index.md
  content/en/docs/project-user-guide/application/application-repo.md
  content/en/docs/project-user-guide/application/compose-app.md
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/en/docs/project-user-guide/application/deploy-app-from-repo.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#533 Add mongodb deployment guide
  content/en/docs/application-store/_index.md
  content/en/docs/application-store/built-in-apps/mongodb-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  static/images/docs/appstore/built-in-apps/mongodb-app/app-store.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/confirm-deployment.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/deploy-mongodb.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/mongodb-in-app-store.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/mongodb-running.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/mongodb-service-terminal.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/mongodb-service.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/mongodb-terminal.jpg
  static/images/docs/appstore/built-in-apps/mongodb-app/set-app-configuration.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#532 Update PostgreSQL guide
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  static/images/docs/appstore/built-in-apps/postgresql-app/access-postgresql.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/click-app-store.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/container-terminal.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/deploy-postgresql-2.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/deploy-postgresql.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/edit-internet-access.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/nodeport.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/port-number.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/postgresql-in-app-store.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/postgresql-output.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/postgresql-ready.jpg
  static/images/docs/appstore/built-in-apps/postgresql-app/set-config.jpg
  static/images/docs/appstore/postgresql/choose_postgresql_from_app_store.png
  static/images/docs/appstore/postgresql/connect_postgresql.png
  static/images/docs/appstore/postgresql/deploy_postgresql.png
  static/images/docs/appstore/postgresql/deploy_postgresql_confirm.png
  static/images/docs/appstore/postgresql/expose_postgresql_service.png
  static/images/docs/appstore/postgresql/get_postgresql_secret.png
  static/images/docs/appstore/postgresql/postgresql_active.png
  static/images/docs/appstore/postgresql/view_postgresql_service.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#534 add redis deployment guide
  content/en/docs/application-store/built-in-apps/redis-app.md
  static/images/docs/appstore/built-in-apps/redis-app/access-redis.jpg
  static/images/docs/appstore/built-in-apps/redis-app/app-store.jpg
  static/images/docs/appstore/built-in-apps/redis-app/configure-redis.jpg
  static/images/docs/appstore/built-in-apps/redis-app/confirm-deployment.jpg
  static/images/docs/appstore/built-in-apps/redis-app/deploy-redis.jpg
  static/images/docs/appstore/built-in-apps/redis-app/redis-in-app-store.jpg
  static/images/docs/appstore/built-in-apps/redis-app/redis-running.jpg
  static/images/docs/appstore/built-in-apps/redis-app/redis-terminal.jpg
  static/images/docs/appstore/built-in-apps/redis-app/use-redis.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#535 Update secret in project user guide
  content/en/docs/project-user-guide/configuration/secrets.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#536 Add nginx deployment guide
  content/en/docs/application-store/_index.md
  content/en/docs/application-store/built-in-apps/nginx-app.md
  static/images/docs/appstore/built-in-apps/nginx-app/access-nginx.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/app-store.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/confirm-deployment.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/deploy-nginx.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/edit-config-nginx.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/edit-internet-access.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/exposed-port.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/manifest-file.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/nginx-in-app-store.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/nginx-running.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/nginx-service.jpg
  static/images/docs/appstore/built-in-apps/nginx-app/nodeport.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#530 fix search
  layouts/partials/searchInput.html
Labels: approved, dco-signoff: yes, lgtm, size/S

#538 other part of multicluster-management
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/_index.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
  content/zh/docs/multicluster-management/remove-cluster/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#539 Update tidb author name
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#542 Update and refactor app repository in workspace administration
  content/en/docs/workspace-administration/app-repository/_index.md
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  content/en/docs/workspace-administration/app-repository/upload-app-to-public-repository.md
  content/en/docs/workspace-administration/import-helm-repository.md
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-info-dialogue.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo-list.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/validate-link.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#543 Update workspace role and member management format and image path
  content/en/docs/workspace-administration/role-and-member-management.md
  static/images/docs/workspace-administration/role-and-member-management/workspace_invite_user.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_create_step1.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_create_step2.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_detail.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_edit.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_user_edit.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#540 overview
  content/zh/docs/installing-on-kubernetes/introduction/overview.md
  static/images/docs/zh-cn/installing-on-kubernetes/introduction/login.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#545 Add workspace overview
  content/en/docs/workspace-administration/what-is-workspace.md
  content/en/docs/workspace-administration/workspace-overview.md
  static/images/docs/workspace-administration/workspace-overview/created-workspace.jpg
  static/images/docs/workspace-administration/workspace-overview/delete-workspace.jpg
  static/images/docs/workspace-administration/workspace-overview/provide-workspace-info.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-basic-info.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-list.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-overview.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#544 Translate application-resources-monitoring.md Signed-off-by: kaige <154599029@qq.com>
  content/zh/docs/cluster-administration/application-resources-monitoring.md
  static/images/docs/cluster-administration/application-resources-monitoring-zh/application-resources-monitoring.png
  static/images/docs/cluster-administration/application-resources-monitoring-zh/cluster-resources-monitoring.png
  static/images/docs/cluster-administration/application-resources-monitoring-zh/time-range.png
  static/images/docs/cluster-administration/application-resources-monitoring-zh/usage-ranking.png
  static/images/docs/cluster-administration/cluster-status-monitoring-zh/platform.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#546 Update deploying app from templates and app store
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#547 Update workspace chapter name and index
  content/en/docs/workspace-administration/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#548 update introduction of custom monitoring in project user guide
  content/en/docs/project-user-guide/custom-application-monitoring/introduction.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#541 FIX: Update some describe of air-gapped installation.
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
Labels: dco-signoff: yes, lgtm, size/S

#549 Update Monitor MySQL
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#537 Update upload helm-based app guide
  content/en/docs/workspace-administration/upload-helm-based-application.md
  static/images/application-templates/app-detail-test-deploy.png
  static/images/application-templates/app-list.png
  static/images/application-templates/create-app.png
  static/images/application-templates/upload-app1.png
  static/images/application-templates/upload-app2.png
  static/images/application-templates/upload-app3.png
  static/images/application-templates/upload-app4.png
  static/images/docs/workspace-administration/upload-helm-based-application/confirm-upload.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/draft-app.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-app-template.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-helm.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-icon.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/version-page.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#551 Update sample web application for custom monitoring
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#552 Update authentication configuration
  content/en/docs/access-control-and-account-management/configuring-authentication.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#555 Rewrite app templates
  content/en/docs/project-user-guide/application/_index.md
  content/en/docs/project-user-guide/application/app-template.md
  content/en/docs/project-user-guide/application/application-repo.md
  static/images/application-templates/app-template-en.png
  static/images/docs/project-user-guide/applications/app-templates/app-store.jpg
  static/images/docs/project-user-guide/applications/app-templates/private-app-repository.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#557 Translate nodes.md
  content/zh/docs/cluster-administration/nodes.md
  static/images/docs/cluster-administration/node-management-zh/add-taints.png
  static/images/docs/cluster-administration/node-management-zh/assign_pods_to_node.png
  static/images/docs/cluster-administration/node-management-zh/clusters-management-select.png
  static/images/docs/cluster-administration/node-management-zh/drop-down-list-node.png
  static/images/docs/cluster-administration/node-management-zh/label_node.png
  static/images/docs/cluster-administration/node-management-zh/node_detail.png
  static/images/docs/cluster-administration/node-management-zh/node_status.png
  static/images/docs/cluster-administration/node-management-zh/select-a-cluster.png
  static/images/docs/cluster-administration/node-management-zh/taint-management.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#556 Update Chinese multi-node installation
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#558 Update deploy apps from app templates
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/add-app-repo.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/app-config.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/click-eye-icon.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/confirm-info.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/create-new-app.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/deploy-grafana.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/edit-access.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/exposed-port.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/grafana-UI.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/grafana-secret.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/grafana-services.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/home-page.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/input-repo-info.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/nodeport.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/private-app-template.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/repository-list.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/search-grafana.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/secret-page.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-templates/select-app-templates.jpg
Labels: approved, dco-signoff: yes, lgtm, size/L

#559 Translate cluster-administration/_index.md
  content/zh/docs/cluster-administration/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#553 Add guide to switch Prometheus
  content/en/docs/faq/byop.md
  content/en/docs/faq/console-faq.md
  content/en/docs/faq/telemetry.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#310 Translation ‘ QuickStart : Create Workspace, Project, Account and Role’ chapter, from en version to zh-cn
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#561 Add project amdin _index
  content/en/docs/project-administration/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#560 Update Chinese cluster administration _index
  content/zh/docs/cluster-administration/_index.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#563 Update deploy apps from app store
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/app-store.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nodeport.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#568 Translate alerting-message.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  static/images/docs/alerting-zh/alerting_message_node_level_comment.png
  static/images/docs/alerting-zh/alerting_message_node_level_detail.png
  static/images/docs/alerting-zh/alerting_message_node_level_guide.png
  static/images/docs/alerting-zh/alerting_message_node_level_list.png
  static/images/docs/alerting-zh/alerting_message_node_level_notification.png
  static/images/docs/alerting-zh/alerting_message_node_level_policy.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#569 Update project and multi-cluster project in project admin
  content/en/docs/project-administration/project-and-multicluster-project.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#571 Add grayscale release overview
  content/en/docs/project-user-guide/grayscale-release/overview.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#570 adjust project admin chapters order
  content/en/docs/project-administration/_index.md
  content/en/docs/project-administration/project-and-multicluster-project.md
  content/en/docs/project-administration/project-network-isolation.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#573 Update role and member management in project admin
  content/en/docs/project-administration/role-and-member-management.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#575 Update grayscale release guide format and prerequisites
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/en/docs/project-user-guide/grayscale-release/traffic-mirroring.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#576 Update how to deploy gitlab
  content/en/docs/application-store/external-apps/gitlab-app.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#572 fix zhcn link
  content/zh/_index.md
  i18n/zh.yaml
Labels: dco-signoff: yes, size/S

#581 Minor syntax fix
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/network-policy.md
  content/en/docs/pluggable-components/service-mesh.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#578 translate aks
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks.md
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-all-resources.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-choices-bash.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-cluster.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-create-command.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-dashboard.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-aks/aks-launch-icon.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#577 Translate alerting-policy.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/alerting-zh/alerting-policy-node-level-detail-page.png
  static/images/docs/alerting-zh/alerting_policy_node_level_alerting_rule.png
  static/images/docs/alerting-zh/alerting_policy_node_level_basic_info.png
  static/images/docs/alerting-zh/alerting_policy_node_level_create.png
  static/images/docs/alerting-zh/alerting_policy_node_level_guide.png
  static/images/docs/alerting-zh/alerting_policy_node_level_monitoring_target.png
  static/images/docs/alerting-zh/alerting_policy_node_level_notification_rule.png
Labels: approved, dco-signoff: yes, lgtm, size/M

#579 fix some zh-cn website links
  content/zh/_index.md
  content/zh/api/crd.md
  content/zh/api/kubesphere.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  content/zh/reference/_index.md
  content/zh/reference/api-changes/_index.md
  content/zh/reference/api-changes/logging.md
  content/zh/reference/api-changes/monitoring.md
  content/zh/reference/api-docs.md
  content/zh/reference/glossary.md
  data/zh/footer.yaml
  i18n/zh.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#583 Translate shut-down-and-restart-cluster-gracefully.md
  content/zh/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
Labels: approved, dco-signoff: yes, lgtm, size/M
