Repository kubesphere/website, pull requests merged in 2020-09, with the labels that each got.

#290 Added Chinese document for introduction index page
  content/zh/docs/introduction/_index.md
Labels: lgtm, size/M

#294 Update ZH-CN index link in Introduction
  content/zh/docs/introduction/_index.md
Labels: size/S

#297 Update EN source file in some ZH-CN folders
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/retrieve-kubeconfig.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
  content/zh/docs/pluggable-components/alerting-notification.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/network-policy.md
  content/zh/docs/pluggable-components/service-mesh.md
  content/zh/docs/quick-start/_index.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/quick-start/wordpress-deployment.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: size/XL

#298 Fix(install-ks-on-vm): fix some error in doc.
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: approved, size/M

#295 add Chinese document for introduction what-is-kubesphere page
  content/zh/docs/introduction/what-is-kubesphere.md
Labels: dco-signoff: no, lgtm, size/M

#305 minor word change in introduction
  content/en/docs/introduction/what-is-kubesphere.md
Labels: dco-signoff: yes, size/XS

#307 Add an example ZHCN loc file and parent image folder for Simplified C…
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/cloud-shell-oke.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/创建集群.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/启动Cloud-shell.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/完成创建集群.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/快速创建.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/概览页面.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/访问集群.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/集群创建完成.jpg
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke/集群基本信息.jpg
Labels: dco-signoff: yes, size/M

#308 KubeSphere introduction format and minor wording change
  content/zh/docs/introduction/what-is-kubesphere.md
Labels: dco-signoff: yes, size/S

#296 update docs css style
  assets/scss/common.scss
  assets/scss/content.scss
  assets/scss/doc.scss
  assets/scss/docs.scss
  assets/scss/markdown.scss
  assets/scss/partner.scss
  config/_default/config.toml
  content/en/support/_index.md
  content/zh/support/_index.md
  layouts/_default/_markup/render-link.html
  layouts/_default/search.html
  layouts/_default/support.html
  layouts/docs/list.html
  layouts/docs/single.html
  layouts/partials/content.html
  layouts/partials/firstPageInSection.html
  layouts/partials/header.html
  layouts/partials/share.html
  static/images/docs/reddit.svg
  static/images/header/star.svg
  static/js/aside.js
  static/js/markdown-tab.js
Labels: dco-signoff: yes, size/L

#315 fix anchor in docs
  static/js/aside.js
Labels: dco-signoff: yes, size/S

#309 add brand icons
  content/en/docs/installing-on-kubernetes/_index.md
  static/images/docs/brand-icons/aks.jpg
  static/images/docs/brand-icons/digital-ocean.jpg
  static/images/docs/brand-icons/gke.jpg
  static/images/docs/brand-icons/huawei.svg
  static/images/docs/brand-icons/oracle.jpg
Labels: dco-signoff: yes, size/M

#316 update: add hash for js file
  assets/js/aside.js
  assets/js/markdown-tab.js
  layouts/docs/single.html
  layouts/partials/content.html
Labels: dco-signoff: yes, size/S

#269 role and member management
  content/en/docs/devops-user-guide/devops-administration/role-and-member-management.md
  content/en/docs/project-administration/project-members.md
  content/en/docs/project-administration/project-roles.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/workspaces-administration/release-v210.md
  content/en/docs/workspaces-administration/role-and-member-management.md
  static/images/docs/devops-admin/devops_invite_member.png
  static/images/docs/devops-admin/devops_role_list.png
  static/images/docs/devops-admin/devops_role_step1.png
  static/images/docs/devops-admin/devops_role_step2.png
  static/images/docs/devops-admin/devops_user_edit.png
  static/images/docs/project-admin/project_invite_member_step1.png
  static/images/docs/project-admin/project_invite_member_step2.png
  static/images/docs/project-admin/project_role_create_step1.png
  static/images/docs/project-admin/project_role_create_step2.png
  static/images/docs/project-admin/project_role_detail.png
  static/images/docs/project-admin/project_role_list.png
  static/images/docs/project-admin/project_user_edit.png
  static/images/docs/ws-admin/workspace_invite_user.png
  static/images/docs/ws-admin/workspace_role_create_step1.png
  static/images/docs/ws-admin/workspace_role_create_step2.png
  static/images/docs/ws-admin/workspace_role_detail.png
  static/images/docs/ws-admin/workspace_role_edit.png
  static/images/docs/ws-admin/workspace_user_edit.png
Labels: dco-signoff: yes, size/L

#317 fix scrollbar style
  assets/scss/doc.scss
  layouts/_default/_markup/render-link.html
  layouts/partials/header.html
Labels: dco-signoff: yes, size/S

#302 Api documentation
  content/en/docs/api-documentation/_index.md
  content/en/docs/api-documentation/api-glossary.md
  content/en/docs/api-documentation/kubesphere-api.md
  content/en/docs/cluster-administration/nodes.md
  static/images/docs/cluster-administration/assign_pods_to_nodes.png
  static/images/docs/cluster-administration/label_node.png
  static/images/docs/cluster-administration/node_detail.png
  static/images/docs/cluster-administration/node_status.png
Labels: approved, dco-signoff: yes, size/L

#326 Update readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#327 Update/delete doc footer
  assets/js/aside.js
  assets/scss/common.scss
  assets/scss/content.scss
  assets/scss/doc.scss
  content/zh/docs/_index.md
  layouts/docs/single.html
Labels: dco-signoff: yes, size/XL

#328 Change Api doc weight
  content/en/docs/api-documentation/_index.md
Labels: dco-signoff: yes, size/XS

#331 Update style guide for preparation notice
  KubeSphere Documentation Style Guide.md
Labels: dco-signoff: yes, size/XS

#330 update docs footer
  assets/js/aside.js
  assets/scss/doc.scss
  assets/scss/videos.scss
  layouts/docs/single.html
Labels: dco-signoff: yes, size/L

#285 Add log query and web kubectl docs
  content/en/docs/toolbox/_index.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
  static/images/docs/log-query/log-query-drill-container.png
  static/images/docs/log-query/log-query-drill.png
  static/images/docs/log-query/log-query-guide.png
  static/images/docs/log-query/log-query-inspect-other-pods.png
  static/images/docs/log-query/log-query-interface.png
  static/images/docs/log-query/log-query-log-detail.png
  static/images/docs/log-query/log-query-log-search.png
  static/images/docs/log-query/log-query-time-range.png
  static/images/docs/web-kubectl/web-kubectl-cluster-select.png
  static/images/docs/web-kubectl/web-kubectl-enter.png
  static/images/docs/web-kubectl/web-kubectl-example.png
Labels: dco-signoff: yes, size/L

#260 Update huawei cce installation wording
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-huawei-cce.md
Labels: size/M

#312 Update some links
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/installing-on-linux/introduction/intro.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: dco-signoff: yes, size/M

#322 Update role and member management wording and add notes
  content/en/docs/devops-user-guide/devops-administration/role-and-member-management.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/workspaces-administration/role-and-member-management.md
Labels: dco-signoff: yes, lgtm, size/L

#332 refine upgrade cmds
  content/en/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: yes, size/XS

#324 Delete components that are not included in the architecture page
  content/en/docs/introduction/architecture.md
Labels: dco-signoff: yes, lgtm, size/XS

#275 add application resources and cluster status monitoring user guider
  content/en/docs/cluster-administration/application-resources-monitoring.md
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/application-resources-monitoring/application-resources-monitoring.png
  static/images/docs/cluster-administration/application-resources-monitoring/cluster-resources-monitoring.png
  static/images/docs/cluster-administration/application-resources-monitoring/time-range.png
  static/images/docs/cluster-administration/application-resources-monitoring/usage-ranking.png
  static/images/docs/cluster-administration/cluster-status-monitoring/apiserver-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cluster-management.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cluster-nodes.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cluster-resources-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cluster-status-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/clusters-management.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cpu-load-average.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cpu-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/disk-throughput.png
  static/images/docs/cluster-administration/cluster-status-monitoring/disk-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring/edit-yaml.png
  static/images/docs/cluster-administration/cluster-status-monitoring/etcd-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/inode-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/iops.png
  static/images/docs/cluster-administration/cluster-status-monitoring/memory-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/netework-bandwidth.png
  static/images/docs/cluster-administration/cluster-status-monitoring/node-usage-ranking.png
  static/images/docs/cluster-administration/cluster-status-monitoring/physical-resources-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/platform.png
  static/images/docs/cluster-administration/cluster-status-monitoring/pod-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring/running-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring/scheduler-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/service-components-status.png
Labels: dco-signoff: yes, lgtm, size/L

#276 feat: Add jobs user guide
  content/en/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/job-actions.png
  static/images/docs/job-container-settings.png
  static/images/docs/job-create-add-container-image.png
  static/images/docs/job-create-add-container-params.png
  static/images/docs/job-create-basic-info.png
  static/images/docs/job-create-job-settings.png
  static/images/docs/job-create.png
  static/images/docs/job-detail-pods.png
  static/images/docs/job-detail-records.jpg
  static/images/docs/job-list-new.png
  static/images/docs/job-list.png
Labels: dco-signoff: yes, size/L

#318 refactor addon config for storage
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
Labels: dco-signoff: yes, lgtm, size/L

#336 Fix/fix docs table style
  assets/scss/markdown.scss
Labels: dco-signoff: yes, size/XS

#337 update html layout
  layouts/docs/single.html
  layouts/index.html
Labels: dco-signoff: yes, size/M

#335 Update storage config wording
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
Labels: dco-signoff: yes, lgtm, size/M

#333 Update log query and kubectl doc wording
  content/en/docs/toolbox/_index.md
  content/en/docs/toolbox/log-query.md
  content/en/docs/toolbox/web-kubectl.md
Labels: dco-signoff: yes, size/M

#339 update: support html in markdown
  config/_default/config.toml
Labels: dco-signoff: yes, size/XS

#342 feature: add pipeline across clusters
  content/zh/blogs/create-pipeline-across-multi-clusters.md
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-deploy-gondor.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-deploy-project.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-deploy-rohan.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-deploy-shire.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-pipeline-apply.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-pipeline-display.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-pipeline-log.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-pipeline.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-project.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-devops-sonarqube-display.png
  static/images/blogs/create-pipeline-across-multi-clusters/create-ws.png
  static/images/blogs/create-pipeline-across-multi-clusters/credential-list.png
  static/images/blogs/create-pipeline-across-multi-clusters/multicluster-devops.svg
  static/images/blogs/create-pipeline-across-multi-clusters/use-case-for-multicluster.svg
Labels: dco-signoff: yes, size/L

#311 add telemetry and faq, fix broken links
  content/en/devops/_index.md
  content/en/docs/faq/_index.md
  content/en/docs/faq/console-faq.md
  content/en/docs/faq/telemetry.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/observability/_index.md
  content/en/service-mesh/_index.md
  content/zh/blogs/kubesphere-3.0.0-ga-announcement.md
  content/zh/devops/_index.md
  content/zh/docs/faq/_index.md
  content/zh/docs/faq/console-faq.md
  content/zh/docs/faq/telemetry.md
  content/zh/observability/_index.md
  content/zh/service-mesh/_index.md
  static/images/docs/faq/console-browser.png
Labels: approved, dco-signoff: yes, size/L
