Repository kubesphere/website, pull requests merged in 2021-12, with the labels that each got.

#2160 update the footer
  data/zh/footer.yaml
Labels: approved, lgtm, size/XS

#2163 update the page of live
  content/zh/live/_index.md
  content/zh/live/webhook1202-live.md
Labels: approved, lgtm, size/M

#2147 update the page of news
  content/zh/news/_index.md
Labels: approved, lgtm, size/L

#2158 add new blog of ebpf
  content/zh/blogs/ebpf-working-with-embedded-systems.md
Labels: approved, lgtm, size/L

#2159 add new blog of ebpf-tracing-user-processes
  content/zh/blogs/ebpf-tracing-user-processes.md
Labels: approved, lgtm, size/L

#2166 Update title of blog how-to-use-kubesphere-project-gateways-and-routes
  content/en/blogs/how-to-use-kubesphere-project-gateways-and-routes.md
  content/zh/blogs/how-to-use-kubesphere-project-gateways-and-routes.md
Labels: approved, lgtm, size/XS

#2165 Update GitLab Multi-branch Pipeline Docs
  content/en/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
Labels: approved, area/devops, lgtm, size/S

#2162 fix: modify documents which missing the container configuration
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/en/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
Labels: approved, area/devops, lgtm, size/L

#2145 fix: add kubectl command in the part of 'Uninstall KubeSphere Logging'
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2168 Fix Commands in 3.1.x Docs
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2150 fix: Update meetup slider card style
  assets/scss/content.scss
  assets/scss/live.scss
  layouts/live/list.html
Labels: approved, lgtm, size/L

#2169 Update Commands for Uninstalling DevOps from 3.2.0
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/shell.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/unit-test-set.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/shell_set.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/unit_test_set.png
Labels: approved, lgtm, size/L

#2173 Add Commands for Uninstalling DevOps from 3.2.0
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, area/devops, lgtm, size/S

#2152 Update cm devops-config instead of cc with sonarqube integration
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
Labels: approved, area/devops, lgtm, size/XS, tide/merge-method-squash

#2172 Update 3.2.0 Jenkins System Settings Docs
  content/en/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-setting.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-shared-library.md
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-setting.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-shared-library.md
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/edit-jenkins.png
Labels: approved, area/devops, lgtm, size/M

#2164 Add EN Blog: Integrate KubeSphere with Okta Authentication
  content/en/blogs/integrate-okta.md
  static/images/blogs/en/okta/oidc.png
  static/images/blogs/en/okta/step-4.png
  static/images/blogs/en/okta/step2.png
  static/images/blogs/en/okta/step3-1.png
  static/images/blogs/en/okta/step3-2.png
  static/images/blogs/en/okta/step3-3.png
  static/images/blogs/en/okta/step3-4.png
Labels: approved, lgtm, size/L

#2178 Update Commands for Uninstalling Auditing
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2179 Update Command for Uninstalling Logging
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/S

#2180 Sync Commands Updates to 3.1.x Docs
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/S

#2177 update the footer of form
  data/zh/footer.yaml
Labels: approved, lgtm, size/XS

#2183 update the page of live
  content/zh/live/_index.md
  content/zh/live/kubekey1209-live.md
  content/zh/live/webhook1202-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2161 Minor changes to OpenELB
  content/en/blogs/Kubernetes-multicluster-KubeSphere.md
  content/zh/blogs/Kubernetes-multicluster-KubeSphere.md
  content/zh/blogs/openelb-joins-cncf-sandbox-project.md
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/00-federation-control-plane.png
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/01-cluster-management.png
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/02-add-cluster.png
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/create-stateless-service-png.png
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/multi-tenant-support.png
  static/images/blogs/en/Kubernetes-multicluster-KubeSphere/view-status.png
Labels: approved, lgtm, size/L

#2124 Add a kubekey internal loadbalancer usage doc in zh docs
  .hugo_build.lock
  content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  static/images/docs/zh-cn/installing-on-linux/introduction/internal-ha-configuration/internalLoadBalancer.png
Labels: approved, lgtm, size/L

#2185 KubeCon China 2021
  content/en/news/_index.md
  content/en/news/kubecon-china-2021.md
  static/images/news/aws-quick-start/kubecon-china-2021/AWS-Interview.png
  static/images/news/aws-quick-start/kubecon-china-2021/Huo-Binjie.png
  static/images/news/aws-quick-start/kubecon-china-2021/Lai-Zhengyi.png
  static/images/news/aws-quick-start/kubecon-china-2021/Lei-Wanjun.png
  static/images/news/aws-quick-start/kubecon-china-2021/Wan-Hongming.png
  static/images/news/aws-quick-start/kubecon-china-2021/banner.png
  static/images/news/aws-quick-start/kubecon-china-2021/openebs-office-hours.png
Labels: approved, lgtm, size/M

#2186 pic fixed - KubeCon China 2021
  content/en/news/kubecon-china-2021.md
  static/images/news/kubecon-china-2021/aws-interview.png
  static/images/news/kubecon-china-2021/banner.png
  static/images/news/kubecon-china-2021/huo-binjie.png
  static/images/news/kubecon-china-2021/lai-zhengyi.png
  static/images/news/kubecon-china-2021/lei-wanjun.png
  static/images/news/kubecon-china-2021/openebs-office-hours.png
  static/images/news/kubecon-china-2021/wan-hongming.png
Labels: approved, lgtm, size/S

#2139 Update API change
  content/en/docs/reference/api-docs.md
  content/en/docs/release/release-v320.md
  content/zh/docs/reference/api-docs.md
  content/zh/docs/release/release-v320.md
Labels: approved, lgtm, size/S

#2188 add apache-log4j2-vulnerability-solution.md
  content/zh/blogs/apache-log4j2-vulnerability-solution.md
  content/zh/blogs/aws-kubernetes.md
  static/images/blogs/log4j/log4j.jpeg
Labels: approved, lgtm, size/M

#2187 Update Graphical Pipeline Docs
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/kubernetesDeploy.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/pipeline-done.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/kubernetesDeploy_set.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/pipeline_done.png
Labels: approved, lgtm, size/M

#2190 update the page of live
  content/zh/live/_index.md
  content/zh/live/ceph1216-live.md
  content/zh/live/kubekey1209-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2181 Fix Incorrect Content in 3.2.0 ZH Doc
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2182 Fix Incorrect Content in 3.1.x ZH Doc
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2191 Remove Stale Docs and Update KubeSphere Federation Docs
  content/en/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/en/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
Labels: approved, lgtm, size/M

#2192 Remove Stale Docs in 3.1.x Documentation and Update Relevant Docs
  content/en/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/en/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/_index.md
  content/zh/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
Labels: lgtm, size/M

#2197 update the header of website
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2193 Openelb joins cncf
  content/en/blogs/openelb-joins-cncf-sandbox-project.md
Labels: approved, lgtm, size/M

#2198 fix: Display problem
  assets/scss/learn.scss
  content/zh/learn/_index.md
Labels: approved, lgtm, size/S

#2199 fix: Teacher cards
  assets/scss/learn.scss
  layouts/learn/list.html
Labels: approved, lgtm, size/XS

#2200 Add KubeSphere 3.2.1 release note.
  content/en/docs/release/release-v321.md
  content/zh/docs/release/release-v321.md
Labels: approved, lgtm, size/M

#2201 Update Documentation Link from v3.2.0 to v3.2.x
  config/_default/config.toml
Labels: approved, lgtm

#2203 update the page of live
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2204 Fix minor issues in Chinese 3.2.1 release notes.
  content/zh/docs/release/release-v321.md
Labels: approved, lgtm, size/XS

#2210 Minor Updates
  content/en/_index.md
  content/zh/_index.md
Labels: approved, lgtm, size/XS

#2207 update the page of live
  content/zh/live/_index.md
  content/zh/live/ceph1216-live.md
  content/zh/live/faas1223-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2213 Minor Updates in LDAP Docs
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
Labels: approved, lgtm, size/S, tide/merge-method-squash

#2208 apache-log4j2-vulnerability-solution
  content/en/blogs/apache-log4j2-vulnerability-solution.md
Labels: approved, lgtm, size/M

#2217 fix: Support sort lesson by weight
  content/zh/learn/level_1/_index.md
  content/zh/learn/level_2/_index.md
  layouts/learn/list.html
Labels: approved, lgtm, size/XS

#2218 fix: Support table item by weight
  layouts/learn/list.html
Labels: approved, lgtm, size/XS

#2205 Add release note items of ks-devops
  content/en/docs/release/release-v321.md
Labels: approved, area/devops, lgtm, size/XS

#2228 level 9 : kubernetes cloud native observability
  content/zh/learn/level_2/_index.md
  content/zh/learn/level_9/_index.md
  content/zh/learn/level_9/lesson_46/_index.md
  content/zh/learn/level_9/lesson_46/content.md
  content/zh/learn/level_9/lesson_46/video.md
  content/zh/learn/level_9/lesson_47/_index.md
  content/zh/learn/level_9/lesson_47/content.md
  content/zh/learn/level_9/lesson_47/video.md
  content/zh/learn/level_9/lesson_48/_index.md
  content/zh/learn/level_9/lesson_48/content.md
  content/zh/learn/level_9/lesson_48/video.md
  content/zh/learn/level_9/lesson_49/_index.md
  content/zh/learn/level_9/lesson_49/content.md
  content/zh/learn/level_9/lesson_49/video.md
  content/zh/learn/level_9/lesson_50/_index.md
  content/zh/learn/level_9/lesson_50/content.md
  content/zh/learn/level_9/lesson_50/video.md
  content/zh/learn/level_9/lesson_51/_index.md
  content/zh/learn/level_9/lesson_51/content.md
  content/zh/learn/level_9/lesson_51/video.md
  content/zh/learn/level_9/lesson_52/_index.md
  content/zh/learn/level_9/lesson_52/content.md
  content/zh/learn/level_9/lesson_52/video.md
  content/zh/learn/level_9/lesson_53/_index.md
  content/zh/learn/level_9/lesson_53/content.md
  content/zh/learn/level_9/lesson_53/video.md
  content/zh/learn/level_9/lesson_54/_index.md
  content/zh/learn/level_9/lesson_54/content.md
  content/zh/learn/level_9/lesson_54/video.md
  content/zh/learn/level_9/lesson_55/_index.md
  content/zh/learn/level_9/lesson_55/content.md
  content/zh/learn/level_9/lesson_55/video.md
  content/zh/learn/level_9/lesson_56/_index.md
  content/zh/learn/level_9/lesson_56/content.md
  content/zh/learn/level_9/lesson_56/video.md
  content/zh/learn/level_9/lesson_57/_index.md
  content/zh/learn/level_9/lesson_57/content.md
  content/zh/learn/level_9/lesson_57/video.md
  content/zh/learn/level_9/lesson_58/_index.md
  content/zh/learn/level_9/lesson_58/content.md
  content/zh/learn/level_9/lesson_58/video.md
  content/zh/learn/level_9/lesson_59/_index.md
  content/zh/learn/level_9/lesson_59/content.md
  content/zh/learn/level_9/lesson_59/video.md
Labels: approved, lgtm, size/L

#2224 Update cloud native course PDF and video learning materials
  content/zh/learn/level_8/_index.md
  content/zh/learn/level_8/lesson_1/_index.md
  content/zh/learn/level_8/lesson_1/content.md
  content/zh/learn/level_8/lesson_1/video.md
  content/zh/learn/level_8/lesson_10/_index.md
  content/zh/learn/level_8/lesson_10/content.md
  content/zh/learn/level_8/lesson_10/video.md
  content/zh/learn/level_8/lesson_11/_index.md
  content/zh/learn/level_8/lesson_11/content.md
  content/zh/learn/level_8/lesson_11/video.md
  content/zh/learn/level_8/lesson_12/_index.md
  content/zh/learn/level_8/lesson_12/content.md
  content/zh/learn/level_8/lesson_12/video.md
  content/zh/learn/level_8/lesson_2/_index.md
  content/zh/learn/level_8/lesson_2/content.md
  content/zh/learn/level_8/lesson_2/video.md
  content/zh/learn/level_8/lesson_3/_index.md
  content/zh/learn/level_8/lesson_3/content.md
  content/zh/learn/level_8/lesson_3/video.md
  content/zh/learn/level_8/lesson_4/_index.md
  content/zh/learn/level_8/lesson_4/content.md
  content/zh/learn/level_8/lesson_4/video.md
  content/zh/learn/level_8/lesson_5/_index.md
  content/zh/learn/level_8/lesson_5/content.md
  content/zh/learn/level_8/lesson_5/video.md
  content/zh/learn/level_8/lesson_6/_index.md
  content/zh/learn/level_8/lesson_6/content.md
  content/zh/learn/level_8/lesson_6/video.md
  content/zh/learn/level_8/lesson_7/_index.md
  content/zh/learn/level_8/lesson_7/content.md
  content/zh/learn/level_8/lesson_7/video.md
  content/zh/learn/level_8/lesson_8/_index.md
  content/zh/learn/level_8/lesson_8/content.md
  content/zh/learn/level_8/lesson_8/video.md
  content/zh/learn/level_8/lesson_9/_index.md
  content/zh/learn/level_8/lesson_9/content.md
  content/zh/learn/level_8/lesson_9/video.md
Labels: approved, lgtm, size/L

#2235 level 9 : cloud native observability
  content/zh/learn/level_9/_index.md
Labels: approved, lgtm, size/XS

#2225 Add Docs: Customize Jenkins Agent
  content/en/docs/devops-user-guide/examples/customize-jenkins-agent.md
  content/zh/docs/devops-user-guide/examples/customize-jenkins-agent.md
Labels: approved, lgtm, size/L, tide/merge-method-squash

#2230 modify spell mistake
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
Labels: approved, lgtm, size/XS

#2238 add new blog of cilium
  content/zh/blogs/cilium-1.11-release.md
Labels: approved, lgtm, size/L

#2236 update the page of live
  content/zh/live/_index.md
  content/zh/live/faas1223-live.md
  content/zh/live/mqtt1230-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2209 Fix typos
  content/en/blogs/x509-certificate-exporter.md
  content/zh/blogs/WeDataSphere-KubeSphere.md
  content/zh/docs/release/release-v321.md
Labels: approved, lgtm, size/XS

#2237 add new blog of openfunction
  content/zh/blogs/faas-openfunction.md
Labels: approved, lgtm, size/L

#2240 multicluster-management
  content/en/blogs/Kubernetes-multicluster-KubeSphere.md
Labels: approved, lgtm, size/XS

#2232 add a blog: Install Kubernetes 1.23, containerd, and Multus CNI the Easy Way
  content/en/blogs/install-kubernetes-containerd-multus.md
  content/en/blogs/install-kubernetes-containerd.md
  static/images/blogs/en/kubekey-containerd/kubernetes-containerd-banner.png
Labels: approved, lgtm, size/L

#2170 Add casdoor into oidc identity-provider
  content/en/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/zh/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
Labels: approved, lgtm, size/XS

#2195 transform-traditional-applications-into-microservices
  content/en/blogs/transform-traditional-applications-into-microservices.md
  static/images/blogs/transform-traditional-applications-into-microservices/00-enable-gateway.png
  static/images/blogs/transform-traditional-applications-into-microservices/01-create-mysql.png
  static/images/blogs/transform-traditional-applications-into-microservices/02-create-mysql.png
  static/images/blogs/transform-traditional-applications-into-microservices/03-set-password.png
  static/images/blogs/transform-traditional-applications-into-microservices/04-create-wp.png
  static/images/blogs/transform-traditional-applications-into-microservices/05-create-wp.png
  static/images/blogs/transform-traditional-applications-into-microservices/06-create-wp.png
  static/images/blogs/transform-traditional-applications-into-microservices/07-nodeport.png
  static/images/blogs/transform-traditional-applications-into-microservices/08-check-app.png
  static/images/blogs/transform-traditional-applications-into-microservices/09-expose-port.png
  static/images/blogs/transform-traditional-applications-into-microservices/10-traffic-topology.png
  static/images/blogs/transform-traditional-applications-into-microservices/traffic-monitoring-cover.png
Labels: approved, lgtm, size/L

#2244 Update externalElasticsearchUrl to externalElasticsearchHost
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/faq/observability/logging.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
Labels: approved, lgtm, size/M

#2248 add new blog of rook-on-kubesphere
  content/zh/blogs/faas-openfunction.md
  content/zh/blogs/rook-on-kubesphere.md
Labels: approved, lgtm, size/L

#2250 upadate the page of live
  content/zh/live/_index.md
  content/zh/live/mqtt1230-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/S
