Repository kubesphere/website, pull requests merged in 2021-05, with the labels that each got.

#1478 Translate use-pipeline-templates-en
  content/zh/docs/devops-user-guide/how-to-use/use-pipeline-templates.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/use-pipeline-templates/ci-stages.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/use-pipeline-templates/ci-template.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/use-pipeline-templates/cicd-stages.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/use-pipeline-templates/cicd-template.png
Labels: lgtm, size/M

#1484 Translate alerting-meassage-node-level-en
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alert-message-page.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_comment.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_detail.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_guide.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_list.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_notification.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_policy.png
Labels: lgtm, size/M

#1491 Fix format
  content/en/docs/pluggable-components/alerting.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/metrics-server.md
  content/en/docs/pluggable-components/network-policy.md
  content/en/docs/pluggable-components/service-mesh.md
  content/en/docs/pluggable-components/service-topology.md
  content/zh/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/service-topology.md
Labels: lgtm, size/S

#1481 Translate alerting-message-en
  content/zh/docs/project-user-guide/alerting/alerting-message.md
  static/images/docs/zh-cn/project-user-guide/alerting/alerting-messages/alerting-messages.png
Labels: lgtm, size/M

#1476 Translate add-edge-nodes-en
  content/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-node-2.png
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-node1.png
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-watcher.png
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/kubeedge_arch.png
Labels: lgtm, size/L

#1497 Add Doc : Deploy RadonDB MySQL on Kubesphere
  content/en/docs/application-store/built-in-apps/radondb-mysql-app.md
  content/zh/docs/application-store/built-in-apps/radondb-mysql-app.md
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/confirm-deployment.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/deploy-radondb-mysql.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-in-app-store.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-running.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-service-terminal.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-service.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-terminal.png
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/set-app-configuration.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/confirm-deployment.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/deploy-radondb-mysql.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-in-app-store.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-running.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-service-terminal.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-service.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/radondb-mysql-terminal.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/set-app-configuration.png
Labels: lgtm, size/L

#1496 Modified file-KubeSphere-alerting
  content/en/docs/pluggable-components/alerting.md
  content/zh/docs/pluggable-components/alerting.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/alerting1.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/cluster-management1.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-alerting-and-notification/edit-yaml1.png
Labels: size/L

#1489 Translate s2i-introduction-en
  content/zh/docs/project-user-guide/image-builder/s2i-introduction.md
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-builder.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-flow.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-runtime-build.png
Labels: lgtm, size/M

#1490 Update Doc: Pipeline Settings per 3.1 UI change
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-github.png
Labels: size/XS

#1488 update content style
  assets/scss/content.scss
Labels: size/XS

#1296 Add Notes in Create Pipeline Using Jenkinsfile/Editing Panels-v3.1
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-graphical-editing-panels/click-custom-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/click-custom-pipeline.png
Labels: lgtm, size/M

#1501 Update readme
  README.md
Labels: approved

#1471 Update EN Doc: Integrate Harbor into Pipeline
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/basic-info.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/image-pushed.png
Labels: size/M

#1487 kubesphere-3.1.0-ga-announcement.md
  content/zh/blogs/kubesphere-3.1.0-ga-announcement.md
Labels: approved, lgtm, size/L

#1504 Fix typo
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
Labels: size/XS

#1502 sync changes in Integrate Harbor doc-3.0
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
Labels: size/M

#1503 Update integrate-harbor-zh
  content/zh/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/advanced-settings1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/basic-info1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/credentials-page2.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/edit-jenkinsfile1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/export-to-file1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/harbor-projects1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account-name1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/set-name1.png
Labels: lgtm, size/M

#1482 Update EN Doc: Create Pipeline Using a Jenkinsfile
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/access-endpoint.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/activity-failure.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/activity-faliure.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/click-service.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/code-quality.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/create-pipeline-2.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/credential-list.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/credential-list.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/devops-prod.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/docker-hub-result.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/generate-github-token-1.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/generate-github-token-2.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/github-result.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/github-token-scope.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/inspect-pipeline-log-1.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/inspect-pipeline-log-1.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/jenkins-edit-1.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/jenkins-edit-1.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-deployments.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-detail.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-detail.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-list.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-list.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-proceed.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/pipeline-proceed.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/project-list.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/project-list.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/remove-behavioral-strategy.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/remove-behavioral-strategy.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/select-repo.jpg
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/select-repo.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/select-token.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/sonarqube-result-detail.png
Labels: lgtm, size/M

#1371 Add Doc-Deploy ClickHouse
  content/en/docs/application-store/external-apps/deploy-clickhouse.md
  static/images/docs/appstore/external-apps/deploy-clickhouse/add-clickhouse.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/add-repo.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/app-running.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/basic-info.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/change-nodeport.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/chart-tab.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/click-deploy-new-app.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/click-deploy.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/clickhouse-cluster.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/clickhouse-service.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/from-app-templates.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/get-username-password.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/pods-running.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/project-overview.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/repo-added.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/statefulset-monitoring.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/statefulsets-running.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/use-clickhouse.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/volume-status.png
  static/images/docs/appstore/external-apps/deploy-clickhouse/volumes.png
Labels: lgtm, size/L

#1505 Add Docs: Deploy ClickHouse (zh)
  content/zh/docs/application-store/external-apps/deploy-clickhouse.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/add-clickhouse.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/add-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/app-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/basic-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/chart-tab.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/click-deploy-new-app.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/click-deploy.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/clickhouse-cluster.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/from-app-templates.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/get-username-password.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/pods-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/project-overview.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/repo-added.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/statefulset-monitoring.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/statefulsets-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/use-clickhouse.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/volume-status.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-clickhouse/volumes.png
Labels: lgtm, size/L

#1512 Sync changes in intergrate-harbor-zh doc-3.0
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
  content/zh/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/credentials-page2.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/export-to-file1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/harbor-projects1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account-name1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/set-name1.png
Labels: lgtm, size/M

#1509 Update Doc: Pipeline Settings in v3.1 per UI changes
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-bitbucket.png
Labels: lgtm, size/XS

#1514 add docs link in v3.0
  config/_default/config.toml
Labels: size/M

#1516 fix file name capitalization
  content/en/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: approved, size/XS

#1521 Update create-a-pipeline-using-jenkinsfile-en doc-3.1
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/advanced-setting1.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/branch-settings-1.png
  static/images/docs/devops-user-guide/using-devops/create-a-pipeline-using-a-jenkinsfile/create-a-pipeline1.png
Labels: lgtm, size/S

#1518 Update create-a-pipeline-using-jenkinsfile-zh
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/commit-changes1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/credential-list1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/fork-github-repo1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/github-token-scope.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/jenkins-edit--1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/jenkins-edit--2.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/remove-behavioral-strategy1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/select-token1.png
Labels: lgtm, size/M

#1517 add version tip
  assets/scss/common.scss
  assets/scss/docs.scss
  config/_default/config.toml
  i18n/en.yaml
  i18n/zh.yaml
  layouts/docs/list.html
  layouts/docs/second.html
  layouts/docs/single.html
  layouts/partials/versionTip.html
Labels: approved, lgtm, size/M

#1508 Translate pipeling-settings-en doc-3.1
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/basic-info-tab1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/behavioral-strategy1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/branch-settings1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-settings1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-trigger--2.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-trigger1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-bitbucket1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-git1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-github1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-gitlab1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-svn1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/git-clone-options1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/parametric-build1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/scan-repo-trigger1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/script-path1.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/webhook-push1.png
Labels: lgtm, size/L

#1523 Add metering view resource consumption part.
  content/zh/docs/toolbox/metering-and-billing/view-resource-consumption.md
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-172746.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173129.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173324.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173415.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173717.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173839.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173958.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174139.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174335.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174551.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174648.png
Labels: lgtm, size/M

#1530 Update kubeedge guide
  content/en/docs/pluggable-components/kubeedge.md
  content/zh/docs/pluggable-components/kubeedge.md
Labels: approved

#1531 Update KubeKey addons value
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
Labels: approved, size/S

#1337 Add doc use-an-oauth2-identity-provider-en.
  content/en/docs/access-control-and-account-management/external-authentication/oauth2.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
  static/images/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/github-login-page.png
  static/images/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/kubesphere-login-page.png
  static/images/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/oauth2.svg
  static/images/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/toolbox.png
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/github-authentication.jpg
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/github-login-page.png
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/logged-in.png
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/oauth2.svg
Labels: lgtm, size/L

#1538 Update pic-deploy-bookinfo-en
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/create-bookinfo1.png
Labels: size/XS

#1541 add prerequisites
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/zh/docs/project-user-guide/grayscale-release/canary-release.md
Labels: approved, lgtm, size/XS

#1533 Translate Create-a-Multi-branch-Pipeline-with-GitLab-en
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/check-log.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/click-import-project.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/click-run.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/commit-changes.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/create-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/credential-created.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/deployment.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/docker-image.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/gitlab-demo.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/gitlab-result.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/jenkinsfile-online.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/new-branch.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/pipeline-logs.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/select-branch.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/select-gitlab.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/service.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/gitlab-multibranch-pipeline/use-git-url.png
Labels: approved, lgtm, size/L

#1529 Add metering guide
  content/en/docs/toolbox/metering-and-billing/view-resource-consumption.md
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/cluster-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/node-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/pod-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/project-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/workload-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/workspace-page.png
Labels: approved, lgtm, size/M

#1537 Update enable-pluggable-components-zh
  content/en/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/quick-start/enable-pluggable-components.md
Labels: lgtm, size/M

#1536 Update uninstall-ks-and-k8s-zh
  content/zh/docs/installing-on-linux/uninstall-kubesphere-and-Kubernetes.md
Labels: lgtm, size/S

#1542 Update workspace management docs
  content/zh/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  content/zh/docs/faq/notices/_index.md
  content/zh/docs/faq/notices/delete-workspace.md
  content/zh/docs/workspace-administration/what-is-workspace.md
Labels: lgtm, size/M

#1545 Add use-an-ldap-service-en.
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  static/images/docs/access-control-and-account-management/external-authentication/use-an-ldap-service/toolbox.png
Labels: size/L

#1550 update the header in Chinese: add the meetup information
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1546 Add workspace deletion desc
  content/en/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  content/en/docs/workspace-administration/what-is-workspace.md
  content/zh/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  content/zh/docs/faq/notices/_index.md
  content/zh/docs/faq/notices/delete-workspace.md
  content/zh/docs/workspace-administration/what-is-workspace.md
  static/images/docs/workspace-administration/workspace-overview/delete-workspace.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-basic-info.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-basic-information.png
Labels: approved, size/L

#1552 Update Doc: Agent Connection per v3.1 UI changes
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/add-cluster.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/agent-en.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/cluster-info.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/select-agent-connection.png
Labels: lgtm, size/XS

#1547 Add Doc: Configure S2I and B2I Webhooks
  content/en/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks.md
  content/zh/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks.md
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/add-payload-url.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/b2i-auto-build.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/b2i-payload-url.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/b2i-trigger-link.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/click-add-webhook.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/click-s2i.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/edit-trigger-service.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/s2i-auto-build.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/s2i-nodeport.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/s2i-trigger-link.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/s2i-trigger-service.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/select-nodeport.png
  static/images/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/webhook-delivery.png
Labels: approved, lgtm, size/L

#1551 Update Doc: Direct Connection per v3.1 UI changes
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/add-cluster.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/cluster-info.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/kubeconfig.jpg
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/kubeconfig.png
Labels: size/S

#1554 Add container, CNI and CSI support list
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/M

#1555 add md block
  content/en/common/_index.md
  content/zh/common/_index.md
  content/zh/common/cni-list.md
  layouts/shortcodes/content.html
Labels: approved, lgtm, size/S

#1557 add content link shortcode
  layouts/shortcodes/contentLink.html
Labels: size/XS

#1560 update the brief introduction for 3.1.0 (initial version), remove the out-of-date guide
  content/en/docs/introduction/what's-new-in-3.1.0.md
  content/en/docs/introduction/what's-new-in-v3.0.md
  content/zh/docs/introduction/what's-new-in-3.1.0.md
  content/zh/docs/introduction/what's-new-in-v3.0.md
Labels: approved, lgtm, size/M

#1562 fix typos
  content/en/blogs/scale-kubernetes-cluster-using-kubekey.md
  content/en/docs/introduction/what's-new-in-3.1.0.md
  content/en/docs/upgrade/overview.md
Labels: approved

#1561 Add requirements page
  content/en/common/container-runtime-requirements.md
  content/en/common/csi-plugins.md
  content/en/common/dependency-requirements.md
  content/en/common/kubernetes-versions.md
  content/en/common/network-requirements.md
  content/en/common/system-requirements.md
  content/en/docs/reference/environment-requirements.md
  static/images/docs/reference/environment-requirements/console-browser.png
Labels: approved, size/L

#1563 Update cn requirements
  content/zh/common/cni-list.md
  content/zh/common/container-runtime-requirements.md
  content/zh/common/csi-plugins.md
  content/zh/common/dependency-requirements.md
  content/zh/common/kubernetes-versions.md
  content/zh/common/network-requirements.md
  content/zh/common/system-requirements.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/reference/environment-requirements.md
Labels: approved, lgtm, size/L

#1566 cherry-pick s2i guides
  content/en/docs/project-user-guide/image-builder/s2i-introduction.md
  content/en/docs/project-user-guide/image-builder/s2i-templates.md
  content/zh/docs/project-user-guide/image-builder/s2i-introduction.md
  content/zh/docs/project-user-guide/image-builder/s2i-templates.md
  layouts/robots.txt
  static/images/docs/project-user-guide/image-builder/s2i-intro/s2i-builder.png
  static/images/docs/project-user-guide/image-builder/s2i-intro/s2i-flow.png
  static/images/docs/project-user-guide/image-builder/s2i-intro/s2i-runtime-build.png
  static/images/docs/project-user-guide/image-builder/s2i-templates/access-nginx.png
  static/images/docs/project-user-guide/image-builder/s2i-templates/template-available.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-builder.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-flow.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-intro/s2i-runtime-build.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-templates/access-nginx.png
  static/images/docs/zh-cn/project-user-guide/image-builder/s2i-templates/template-available.png
Labels: size/XL

#1568 Update docs: Modified fiels and images in radondb-mysql-app
  content/en/docs/application-store/built-in-apps/radondb-mysql-app.md
  content/zh/docs/application-store/built-in-apps/radondb-mysql-app.md
  static/images/docs/appstore/built-in-apps/radondb-mysql-app/set-app-configuration.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-mysql-app/set-app-configuration.png
Labels: lgtm, size/XS

#1571 Add ARM notes and delete old deletion guide
  content/en/docs/faq/installation/uninstall-pluggable-components.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/faq/installation/uninstall-pluggable-components.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: approved

#1569 Update example file link
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, size/M

#1577 Update enable DevOps guide
  content/en/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/devops.md
  static/images/docs/enable-pluggable-components/kubesphere-devops-system/devops.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-devops-system/devops.PNG
Labels: approved, lgtm, size/S

#1578 Fix DevOps image name cap
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-devops-system/devops.png
Labels: approved, size/XS

#1579 Update enable metrics server guide
  content/en/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/service-mesh.md
Labels: approved, size/M

#1581 Update enable Service Mesh guide
  content/en/docs/pluggable-components/service-mesh.md
  content/zh/docs/pluggable-components/service-mesh.md
  static/images/docs/enable-pluggable-components/kubesphere-service-mesh/istio.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-service-mesh/Istio.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-service-mesh/istio.png
Labels: approved, lgtm, size/M

#1573 Update App Store guide
  content/en/docs/faq/applications/remove-built-in-apps.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/zh/docs/faq/applications/remove-built-in-apps.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/project-user-guide/application/deploy-app-from-appstore.md
  static/images/docs/enable-pluggable-components/kubesphere-app-store/app-store.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/app-store.PNG
Labels: approved, lgtm, size/M

#1587 update header for the lastest meetup
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1584 Update enable logging guide
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/logging.md
  static/images/docs/enable-pluggable-components/kubesphere-logging-system/logging.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-logging-system/logging.PNG
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-logging-system/logging.png
Labels: approved, size/L

#1585 Update enable events guide
  content/en/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/events.md
  static/images/docs/enable-pluggable-components/kubesphere-events/event-search.png
  static/images/docs/enable-pluggable-components/kubesphere-events/events.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-events/event-search.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-events/events.PNG
Labels: approved, size/L

#1589 Update auditing log guide
  content/en/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/auditing-logs.md
  static/images/docs/enable-pluggable-components/kubesphere-auditing-logs/auditing-operating.png
  static/images/docs/enable-pluggable-components/kubesphere-auditing-logs/auditing.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-auditing-logs/auditing-operating.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-auditing-logs/auditing.PNG
Labels: approved, size/L

#1588 fix header link
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1548 Add KubeSphere 3.1 GA EN announcement
  content/en/blogs/kubesphere-3.1.0-ga-announcement.md
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/acknowledgement.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/alerting.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/banner.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/edge-node-added.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/kubesphere-and-friends.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/metering-and-billing-2.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/metering-and-billing.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/microservices.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/multi-cluster-architecture.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/notable-changes-in-3.1.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/notification.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/pipeline-templates.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/topology.png
  static/images/blogs/en/kubesphere-3.1.0-ga-announcement/workspace-department.png
Labels: approved, lgtm, size/L

#1576 Add Doc: Create a Multi-cluster Pipeline
  content/en/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/create-devops-project.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/create-workspace.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/credentials-created.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/deploy-to-staging.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/devops-project-created.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/devops-project.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/host-pods.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/pipeline-created.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/pipeline-logs.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/pipeline-name.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/pipeline-panel.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/pipeline-success.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/rohan-pods.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/select-all-clusters.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/shire-pods.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/sonarqube-result.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/use-case-for-multi-cluster.png
  static/images/docs/devops-user-guide/examples/create-multi-cluster-pipeline/workspace-created.png
Labels: size/XL

#1594 Update popular pages
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: approved

#1596 Update kubeedge guide
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/pluggable-components/kubeedge.md
  content/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/pluggable-components/kubeedge.md
Labels: approved, lgtm, size/M

#1598 Update uninstallation link
  content/en/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
  content/zh/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
Labels: approved, size/XS

#1599 Update logging.md
  content/zh/docs/faq/observability/logging.md
Labels: size/S

#1600 Sync logging faq
  content/en/docs/faq/observability/logging.md
  content/zh/docs/faq/observability/logging.md
Labels: approved, size/S

#1603 Update volumes guide
  content/en/docs/project-user-guide/storage/volumes.md
  content/zh/docs/project-user-guide/storage/volumes.md
  static/images/docs/project-user-guide/volume-management/volumes/basic-volume-info.jpg
  static/images/docs/project-user-guide/volume-management/volumes/create-volume.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-creation-method.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-finish-creation.jpg
  static/images/docs/project-user-guide/volume-management/volumes/volume-finished.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/basic-volume-info.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/create-volume.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-creation-method.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-finish-creation.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-finished.jpg
Labels: approved, size/M

#1605 Add export csv file note
  content/en/docs/toolbox/metering-and-billing/view-resource-consumption.md
Labels: approved, size/XS

#1607 Update introduction overview
  content/en/docs/installing-on-linux/introduction/intro.md
  content/zh/docs/installing-on-linux/introduction/intro.md
Labels: approved, size/S

#1593 Add FAQ Doc: Manage Multi-cluster Environment
  content/en/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
  content/en/docs/faq/multi-cluster-management/manage-multi-cluster.md
  content/zh/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
  content/zh/docs/faq/multi-cluster-management/manage-multi-cluster.md
Labels: approved, lgtm, size/L

#1608 Update authentication docs
  content/zh/docs/access-control-and-account-management/configuring-authentication.md
  content/zh/docs/access-control-and-account-management/ldap-identity-provider.md
  content/zh/docs/access-control-and-account-management/oauth2.md
Labels: size/L

#1610 Sync FAQ Doc (Multi-cluster Management) to 3.0 documentation
  content/en/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
  content/en/docs/faq/multi-cluster-management/manage-multi-cluster.md
  content/zh/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
  content/zh/docs/faq/multi-cluster-management/manage-multi-cluster.md
Labels: size/L

#1612 Refactor k8s config guide
  content/en/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/introduction/vars.md
Labels: approved, size/L

#1606 Update Doc: Integrate SonarQube
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/add-credentials.png
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/add-sonarqube.jpg
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/add-sonarqube.png
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/configure-system.jpg
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/configure-system.png
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/manage-jenkins.jpg
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/manage-jenkins.png
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/sonarqube-jenkins-settings.jpg
  static/images/docs/devops-user-guide/tool-integration/integrate-sonarqube-into-pipeline/sonarqube-jenkins-settings.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/add-credentials.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/add-sonarqube.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/configure-system.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/manage-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-jenkins-settings.png
Labels: approved, lgtm, size/M

#1522 Add k3s and ks installation guide
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  static/images/docs/installing-on-linux/on-premises/cluster-management.png
  static/images/docs/installing-on-linux/on-premises/service-components.png
Labels: approved, size/L

#1623 release the page of live
  config/_default/config.toml
  content/zh/live/3.1-live.md
  content/zh/live/_index.md
  content/zh/live/botkube-live.md
  content/zh/live/meetup-chengdu.md
  content/zh/live/meetup-hangzhou.md
  content/zh/live/meetup-shanghai.md
  content/zh/live/nm-live.md
  content/zh/live/poterlb-live.md
  content/zh/live/qingjiao-live.md
  data/zh/footer.yaml
  static/images/live/meetup-hangzhou-kv.png
Labels: approved, lgtm, size/XL

#1628 Integrate the demo videos into GA announcement
  content/en/blogs/kubesphere-3.1.0-ga-announcement.md
Labels: approved, lgtm, size/S

#1631 Update Role and Member Management guide
  content/en/docs/workspace-administration/role-and-member-management.md
  content/zh/docs/workspace-administration/role-and-member-management.md
  static/images/docs/workspace-administration/role-and-member-management/add.png
  static/images/docs/workspace-administration/role-and-member-management/edit-existing-user.png
  static/images/docs/workspace-administration/role-and-member-management/role-list.png
  static/images/docs/workspace-administration/role-and-member-management/role-permissions.png
  static/images/docs/workspace-administration/role-and-member-management/three-dots.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_invite_user.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_create_step1.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_create_step2.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_detail.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_role_edit.png
  static/images/docs/workspace-administration/role-and-member-management/workspace_user_edit.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/add.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/edit-existing-user.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/role-details.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/role-list.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/three-dots.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-invite-user.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-create-step1.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-create-step2.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-detail.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-role-edit.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/role-and-member-management/workspace-user-edit.PNG
Labels: approved, size/L

#1559 fix the wrong picture which is add-fluentd.png
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-fluentd-as-receiver.md
Labels: approved, lgtm, size/XS

#1633 Update KubeEdge guides
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/pluggable-components/kubeedge.md
  content/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/pluggable-components/kubeedge.md
Labels: approved, lgtm, size/L

#1638 Fix typo
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
Labels: approved, lgtm, size/S

#1643 Update blue-green deployment guide
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/zh/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-1.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-2.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-3.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-5.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-1.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-2.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-3.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-5.PNG
Labels: approved, size/M

#1635 Add interlinks and minor content changes
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/faq/observability/byop.md
  content/en/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/M

#1647 Update configmap guide
  content/en/docs/project-user-guide/configuration/configmaps.md
  content/zh/docs/project-user-guide/configuration/configmaps.md
  static/images/docs/project-user-guide/configurations/configmaps/add-data.jpg
  static/images/docs/project-user-guide/configurations/configmaps/configmap-dropdown-menu.jpg
  static/images/docs/project-user-guide/configurations/configmaps/configmap-list.jpg
  static/images/docs/project-user-guide/configurations/configmaps/create-configmap.jpg
  static/images/docs/project-user-guide/configurations/configmaps/detail-page.jpg
  static/images/docs/project-user-guide/configurations/configmaps/detail-page.png
  static/images/docs/project-user-guide/configurations/configmaps/edit-configmap-info.jpg
  static/images/docs/project-user-guide/configurations/configmaps/finish-creating.jpg
  static/images/docs/project-user-guide/configurations/configmaps/key-value.jpg
  static/images/docs/project-user-guide/configurations/configmaps/key-value.png
  static/images/docs/project-user-guide/configurations/configmaps/set-basic-info.jpg
  static/images/docs/project-user-guide/configurations/configmaps/three-dots.png
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/add-data.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/configmap-dropdown-menu.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/configmap-list.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/create-configmap.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/detail-page.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/detail-page.png
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/edit-configmap-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/finish-creating.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/set-basic-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/three-dots.png
Labels: approved, size/L
