Repository kubesphere/website, pull requests merged in 2021-08, with the labels that each got.

#1855 Update toolbox index
  content/en/docs/toolbox/_index.md
  content/zh/docs/toolbox/_index.md
  static/images/docs/toolbox/index/toolbox.jpg
  static/images/docs/toolbox/index/toolbox.png
  static/images/docs/zh-cn/toolbox/index/toolbox.PNG
Labels: size/XS

#1856 Update docs: Event query
  content/en/docs/toolbox/events-query.md
  content/zh/docs/toolbox/events-query.md
  static/images/docs/events/events_query_detail.png
  static/images/docs/events/events_query_guide.png
  static/images/docs/events/events_query_home.png
  static/images/docs/events/events_query_list.png
  static/images/docs/toolbox/event-query/drop-down-list.png
  static/images/docs/toolbox/event-query/event-details.png
  static/images/docs/toolbox/event-query/event-search-list.png
  static/images/docs/toolbox/event-query/event-search.png
  static/images/docs/toolbox/event-query/toolbox.png
  static/images/docs/zh-cn/toolbox/event-query/drop-down-list.png
  static/images/docs/zh-cn/toolbox/event-query/event-details.png
  static/images/docs/zh-cn/toolbox/event-query/event-search-list.png
  static/images/docs/zh-cn/toolbox/event-query/event-search.png
  static/images/docs/zh-cn/toolbox/event-query/events-query-detail.PNG
  static/images/docs/zh-cn/toolbox/event-query/events-query-guide.png
  static/images/docs/zh-cn/toolbox/event-query/events-query-home.png
  static/images/docs/zh-cn/toolbox/event-query/events-query-list.PNG
  static/images/docs/zh-cn/toolbox/event-query/toolbox.png
Labels: lgtm

#1858 Update docs: Alert policies
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-detail.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-rule.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alerting-policy-details-page.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/click-create.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/click-edit.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/drop-down-list.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/refresh.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alert-detail.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alert-rule.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting-policy-details-page.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting-policy-node-level-detail-page.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_alerting_rule.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_basic_info.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_create.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_guide.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_monitoring_target.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_notification_rule.PNG
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/click-create.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/click-edit.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/drop-down-list.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/refresh.png
Labels: lgtm, size/M

#1846 update kubesphere architecture diagram
  static/images/docs/zh-cn/introduction/what-is-kubesphere/kubesphere-feature-overview.jpeg
Labels: approved, size/XS

#1864 update the header of .com.cn
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1824 Add EN Blog-Cilium as CNI
  content/en/blogs/cilium-as-cni.md
  static/images/blogs/en/cilium-as-cni/cilium-arch.png
  static/images/blogs/en/cilium-as-cni/cilium-pods.png
  static/images/blogs/en/cilium-as-cni/demo-service.png
  static/images/blogs/en/cilium-as-cni/edit-access.png
  static/images/blogs/en/cilium-as-cni/get-demo.png
  static/images/blogs/en/cilium-as-cni/hammer.png
  static/images/blogs/en/cilium-as-cni/hubble-installed.png
  static/images/blogs/en/cilium-as-cni/hubble-pods.png
  static/images/blogs/en/cilium-as-cni/hubble-ui.png
  static/images/blogs/en/cilium-as-cni/kubectl.png
  static/images/blogs/en/cilium-as-cni/login.png
  static/images/blogs/en/cilium-as-cni/nodeport.png
  static/images/blogs/en/cilium-as-cni/three-dots.png
Labels: approved, lgtm, size/L

#1866 update footer, header and introduction
  content/en/docs/introduction/what-is-kubesphere.md
  data/en/footer.yaml
  data/zh/footer.yaml
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1868 homepage - video
  assets/scss/index.scss
  layouts/index.html
  static/images/home/poster.png
  static/images/videos/close.png
  static/images/videos/play-b.svg
Labels: approved

#1843 Will Cloud Native WebAssembly Replace Docker
  content/en/blogs/Will Cloud Native WebAssembly Replace Docker_.md
Labels: lgtm, size/M

#1869 add @media
  assets/scss/index.scss
  layouts/index.html
Labels: approved, lgtm, size/L

#1871 first translation tasks
  content/zh/docs/faq/multi-cluster-management/manage-multi-cluster.md
Labels: approved, lgtm

#1873 About the size of vide
  assets/scss/index.scss
  layouts/index.html
Labels: lgtm, size/XS

#1875 Fix Command in v3.1.x
  content/en/docs/multicluster-management/unbind-cluster.md
  content/zh/docs/multicluster-management/unbind-cluster.md
Labels: approved, lgtm, size/XS

#1876 Fix Command in v3.0.0
  content/en/docs/multicluster-management/unbind-cluster.md
  content/zh/docs/multicluster-management/unbind-cluster.md
Labels: approved, lgtm, size/XS

#1882 Fix Indent in GitLab Doc
  content/en/docs/application-store/external-apps/deploy-gitlab.md
  content/zh/docs/application-store/external-apps/deploy-gitlab.md
Labels: approved, lgtm, size/XS

#1865 Add ZH BLog: aws-kubernetes
  content/zh/blogs/aws-kubernetes.md
  static/images/blogs/aws-kubernetes/EC2IP.png
  static/images/blogs/aws-kubernetes/EC2config.png
  static/images/blogs/aws-kubernetes/EC2config2.png
  static/images/blogs/aws-kubernetes/EC2config3.png
  static/images/blogs/aws-kubernetes/LBIPaddr.png
  static/images/blogs/aws-kubernetes/aws.png
  static/images/blogs/aws-kubernetes/internalLB.png
  static/images/blogs/aws-kubernetes/internalLB1.png
  static/images/blogs/aws-kubernetes/internalLB12.png
  static/images/blogs/aws-kubernetes/internetGateway.png
  static/images/blogs/aws-kubernetes/router.png
  static/images/blogs/aws-kubernetes/safeGroup.png
  static/images/blogs/aws-kubernetes/selectFlavor.png
  static/images/blogs/aws-kubernetes/selectISO.png
  static/images/blogs/aws-kubernetes/subnet.png
  static/images/blogs/aws-kubernetes/syncIP.png
  static/images/blogs/aws-kubernetes/targetGroup.png
  static/images/blogs/aws-kubernetes/vpc.png
Labels: approved, lgtm, size/L

#1879 new blog:DevOps-pipeline-remove-Docker-dependencies
  content/zh/blogs/DevOps-pipeline-remove-Docker-dependencies.md
Labels: approved, lgtm, size/L

#1883 Translate aws-kubernetes.
  content/en/blogs/aws-kubernetes.md
  static/images/blogs/en/aws-kubernetes/aws.png
  static/images/blogs/en/aws-kubernetes/ec2-details.png
  static/images/blogs/en/aws-kubernetes/ec2-eip.png
  static/images/blogs/en/aws-kubernetes/ec2-image.png
  static/images/blogs/en/aws-kubernetes/ec2-security-group.png
  static/images/blogs/en/aws-kubernetes/ec2-type.png
  static/images/blogs/en/aws-kubernetes/internet-gateway.png
  static/images/blogs/en/aws-kubernetes/lb-listener.png
  static/images/blogs/en/aws-kubernetes/lb-network-interface.png
  static/images/blogs/en/aws-kubernetes/lb-vpc.png
  static/images/blogs/en/aws-kubernetes/route-table.png
  static/images/blogs/en/aws-kubernetes/security-group.png
  static/images/blogs/en/aws-kubernetes/subnet.png
  static/images/blogs/en/aws-kubernetes/target-group.png
  static/images/blogs/en/aws-kubernetes/vpc.png
Labels: approved, lgtm, size/L

#1872 Second task
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
Labels: approved, lgtm, size/L

#1886 Update Docs: Deploy GitLab
  content/en/docs/application-store/external-apps/deploy-gitlab.md
  content/zh/docs/application-store/external-apps/deploy-gitlab.md
  static/images/docs/appstore/external-apps/deploy-gitlab/access-gitlab.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/access_gitlab.png
  static/images/docs/appstore/external-apps/deploy-gitlab/add-main-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/add-main_repo.png
  static/images/docs/appstore/external-apps/deploy-gitlab/add-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/add_repo.png
  static/images/docs/appstore/external-apps/deploy-gitlab/added-main-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/added-main_repo.png
  static/images/docs/appstore/external-apps/deploy-gitlab/basic-info.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/basic_info.png
  static/images/docs/appstore/external-apps/deploy-gitlab/change-value.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/change_value.png
  static/images/docs/appstore/external-apps/deploy-gitlab/click-eye-icon.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/click-gitlab.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/click_gitlab.png
  static/images/docs/appstore/external-apps/deploy-gitlab/deploy-app.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/deploy_app.png
  static/images/docs/appstore/external-apps/deploy-gitlab/deployments-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/deployments_running.png
  static/images/docs/appstore/external-apps/deploy-gitlab/eye-icon.png
  static/images/docs/appstore/external-apps/deploy-gitlab/from-app-templates.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/from-app_templates.png
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab-console.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab_console.png
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab_running.png
  static/images/docs/appstore/external-apps/deploy-gitlab/initial_password.png
  static/images/docs/appstore/external-apps/deploy-gitlab/password.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/search-secret.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/search-service.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/search_secret.png
  static/images/docs/appstore/external-apps/deploy-gitlab/search_service.png
  static/images/docs/appstore/external-apps/deploy-gitlab/statefulsets-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/statefulsets_running.png
  static/images/docs/appstore/external-apps/deploy-gitlab/view-config.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/view_config.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/access_gitlab.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/basic-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/basic_info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/change-value.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/change_value.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/click-gitlab.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/click_gitlab.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/deployments-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/eye-icon.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/from-app-templates.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/gitlab-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/gitlab_console.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/initial-password.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/search-secret.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/search-service.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/statefulsets-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/view-config.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/view_config.png
Labels: approved, lgtm, size/L

#1888 bugfix videoautoplay
  assets/scss/index.scss
  layouts/index.html
Labels: approved, lgtm, size/XS

#1892 Update ZH Doc: Container Image Settings
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
Labels: approved, lgtm, size/XS

#1862 Update Docs: Traffic Mirroring
  content/en/docs/project-user-guide/grayscale-release/traffic-mirroring.md
  content/zh/docs/project-user-guide/grayscale-release/traffic-mirroring.md
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/new-deployment.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/new-deployment.png
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/remove-traffic-mirroring.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/remove-traffic-mirroring.png
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroing-task.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroing-task.png
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-4.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-4.png
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-6.jpg
  static/images/docs/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-6.png
Labels: approved, lgtm

#1861 Update Docs: Blue-Green Deployment
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/zh/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-4.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-4.png
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-6.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-6.png
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-7.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-7.png
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-job-list.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/blue-green-job-list.png
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/version2-deployment.jpg
  static/images/docs/project-user-guide/grayscale-release/blue-green-deployment/version2-deployment.png
Labels: approved, lgtm, size/S

#1885 Update aws-kubernetes for SEO.
  content/en/blogs/aws-kubernetes.md
Labels: approved, lgtm, size/M

#1889 feat feedback button
  assets/scss/doc.scss
  i18n/en.yaml
  i18n/zh.yaml
  layouts/docs/single.html
Labels: approved, lgtm, size/M

#1877 new blog:changhong-kubernetes-autoscaling-canaryrelease
  content/zh/blogs/changhong-kubernetes-autoscaling-canaryrelease.md
Labels: approved, lgtm, size/L

#1893 Update Will Cloud Native WebAssembly Replace Docker_.md
  content/en/blogs/Will Cloud Native WebAssembly Replace Docker_.md
Labels: approved, lgtm, size/M

#1897 update the page of live
  content/zh/live/_index.md
  content/zh/live/pipy819-live.md
Labels: approved, lgtm, size/M

#1805 add a new blog of kubesphere-argocd
  content/zh/blogs/kubesphere-argocd.md
Labels: approved, lgtm, size/XL

#1898 update the page of live
  content/zh/live/_index.md
  content/zh/live/pipy819-live.md
Labels: approved, lgtm, size/XS

#1895 new blog:zto-kubernetes
  content/zh/blogs/zto-kubernetes.md
Labels: approved, lgtm, size/M

#1880 Add summer 2021 github link to the official website
  config/_default/config.toml
Labels: approved, lgtm, size/S

#1901 update the page of live
  content/zh/live/_index.md
  content/zh/live/apisix826-live.md
  content/zh/live/nm-live.md
  content/zh/live/pipy819-live.md
Labels: approved, lgtm, size/M

#1863 Add EN Doc: Uninstall Pluggable Components
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/L

#1881 Third translation task
  content/zh/docs/installing-on-linux/introduction/vars.md
Labels: approved, lgtm, size/M

#1903 feature: add subscribe Form in blog page and quick-start
  assets/scss/content.scss
  assets/scss/doc.scss
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  layouts/docs/single.html
  layouts/partials/content.html
  static/images/home/modal-noText.svg
Labels: approved, lgtm, size/XXL

#1907 upadate the page of live
  content/zh/live/_index.md
  content/zh/live/apisix826-live.md
  content/zh/live/nebula0902-live.md
  static/images/live/apisix0826-live-cover.png
Labels: approved, lgtm, size/M

#1911 add ilium-cni-benchmark.md
  content/zh/blogs/cilium-cni-benchmark.md
Labels: approved, lgtm, size/L
