Repository kubesphere/website, pull requests merged in 2021-03, with the labels that each got.

#1132 Add New Doc - Deploy MeterSphere
  content/en/docs/application-store/_index.md
  content/en/docs/application-store/external-apps/deploy-metersphere.md
  content/zh/docs/application-store/_index.md
  content/zh/docs/application-store/external-apps/deploy-metersphere.md
  static/images/docs/appstore/external-apps/deploy-metersphere/add-metersphere-repo.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/add-repo.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/added-metersphere-repo.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/basic-info.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/change-value.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/click-metersphere.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/deploy-app.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/deployments-running.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/from-app-templates.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/login-metersphere.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/metersphere-running.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/metersphere-service.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/statefulsets-running.PNG
  static/images/docs/appstore/external-apps/deploy-metersphere/view-config.PNG
Labels: size/L

#1134 add some storage notes based on forum
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/project-user-guide/storage/volumes.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/project-user-guide/storage/volumes.md
Labels: size/S

#1120 KubeSphere Certificate review
  content/en/blogs/kubesphere-certificates.md
  content/en/news/kubesphere-meetup-2020.md
  content/zh/blogs/kubesphere-certificates.md
  content/zh/contribution/_index.md
  static/images/blogs/en/meetup-2020/kubesphere-meetup.png
Labels: size/L

#1138 Update cn installing on linux kubekey and ha structure
  content/zh/docs/installing-on-linux/high-availability-configurations/_index.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/intro.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: size/XL

#1140 Translated "KubeKey" from EN to ZH
  content/zh/docs/installing-on-linux/introduction/kubekey.md
Labels: size/M

#1142 Relocate Images for Application Lifecycle Management ZH
  content/zh/docs/application-store/app-lifecycle-management.md
  static/images/docs/zh-cn/appstore/application-lifecycle-management/account-ready.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/activate-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/activate-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-active.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-category.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-draft.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-in-category-list-expected.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-review-name.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-store.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-templates-page.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-to-be-reviewed.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-to-be-upgraded.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/confirm-category.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/create-review-role.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/create-role.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/create-roles.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/deploy-redis.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/deployed-instance-success.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/deploying-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/deployment-place.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/edit-app-information.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/edit-app-template.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/new-version-redis.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/redis-new-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/redis.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/remove-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/reviewing.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/see-new-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/set-app-type.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/set-category-for-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/submit-for-review.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/submitted-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/suspend-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/suspend-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/test-deployment.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upgrade-an-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upgrade-finish.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upload-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upload-icon.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upload-new-redis-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upload-template.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/uploaded-new-version.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/version-upgraded.PNG
Labels: size/M

#1144 Installing-on-kubernetes overview reviewed
  content/zh/docs/installing-on-kubernetes/introduction/overview.md
Labels: size/M

#1143 Installing-on-linux intro viewed
  content/zh/docs/installing-on-linux/introduction/intro.md
Labels: size/M

#1141 Update Deploy GitLab
  content/en/docs/application-store/_index.md
  content/en/docs/application-store/external-apps/deploy-gitlab.md
  content/en/docs/application-store/external-apps/gitlab-app.md
  content/zh/docs/application-store/_index.md
  content/zh/docs/application-store/external-apps/deploy-gitlab.md
  content/zh/docs/application-store/external-apps/gitlab-app.md
  static/images/docs/appstore/external-apps/deploy-gitlab/access-gitlab.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/add-main-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/add-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/added-main-repo.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/basic-info.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/change-value.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/click-eye-icon.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/click-gitlab.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/deploy-app.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/deployments-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/from-app-templates.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab-console.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/gitlab-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/password.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/search-secret.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/search-service.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/statefulsets-running.PNG
  static/images/docs/appstore/external-apps/deploy-gitlab/view-config.PNG
  static/images/docs/appstore/gitlab/add-ks-repo.png
  static/images/docs/appstore/gitlab/add-repo.png
  static/images/docs/appstore/gitlab/deploy-app.png
  static/images/docs/appstore/gitlab/deploy-gitlab-conf.png
  static/images/docs/appstore/gitlab/deploy-gitlab-done.png
  static/images/docs/appstore/gitlab/deploy-gitlab-info.png
  static/images/docs/appstore/gitlab/deploy-gitlab.png
  static/images/docs/appstore/gitlab/gitlab-password.png
  static/images/docs/appstore/gitlab/kubectl.png
  static/images/docs/appstore/gitlab/nginx-port.png
  static/images/docs/appstore/gitlab/signin-gitlab.png
Labels: size/XL

#1137 Add New Doc: Integrate MeterSphere into Pipelines
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/devops-user-guide/how-to-integrate/integrate-metersphere.md
  content/zh/docs/devops-user-guide/_index.md
  content/zh/docs/devops-user-guide/how-to-integrate/integrate-metersphere.md
  static/images/docs/appstore/external-apps/deploy-metersphere/login-metersphere.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/api-key-created.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/choose-file.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-create-pipeline.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-manage-jenkins.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-manage-plugins.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-new-item.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-pilepine-item.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-pipeline-syntax.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-save.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-show.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/click-upload.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/copy-secret-key.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/create-api-keys.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/create-pipeline.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/create-project.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/create-test-plan.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/demo-plan.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/demo-project.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/edit-jenkinsfile.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/input-values.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/installation-success.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/installed-tab.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/metersphere-in-list.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/pipeline-script.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/pipeline-success.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/run-pipeline.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere-in-list.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/set-item-info.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/set-pipeline-name.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/show-logs.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/snippet-output.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/test-plan-list.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/test-report-detail.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/test-report.PNG
  static/images/docs/devops-user-guide/tool-integration/integrate-metersphere/view-logs.PNG
Labels: lgtm, size/L

#1145 Installing-on-kubernetes prerequisite reviewed
  content/zh/docs/installing-on-kubernetes/introduction/prerequisites.md
Labels: size/S

#1150 Add New Doc-Restore the Host Cluster Access to A Member Cluster
  content/en/docs/faq/_index.md
  content/en/docs/faq/multi-cluster-management/_index.md
  content/en/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
  content/zh/docs/faq/_index.md
  content/zh/docs/faq/multi-cluster-management/_index.md
  content/zh/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
Labels: size/L

#1147 ssh-connection-failure doc translated
  content/zh/docs/faq/installation/ssh-connection-failure.md
Labels: size/M

#1149 remove-built-in-apps doc translated
  content/zh/docs/faq/applications/remove-built-in-apps.md
  static/images/docs/zh-cn/faq/remove-built-in-apps/activate-tomcat.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/click-platform.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/click-tomcat.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/confirm-suspend.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/select-app-store-management.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/suspend-tomcat.png
Labels: size/M

#1152 Update Images in Doc-Build and Deploy a Maven Project
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/run-maven-pipeline.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-credential-list.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-namespace.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-pipeline.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-workload-svc.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-workload.png
Labels: size/XS

#1131 Add NFS server configuration guide
  content/en/docs/api-reference/storage-system-installation/_index.md
  content/en/docs/api-reference/storage-system-installation/nfs-server.md
Labels: lgtm, size/L

#1151 metrics-server doc translated
  content/zh/docs/pluggable-components/metrics-server.md
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-metrics-server/clusters-management.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-metrics-server/edit-yaml.png
Labels: lgtm, size/M

#1161 Added information to services-en.
  content/en/docs/project-user-guide/application-workloads/services.md
  static/images/docs/project-user-guide/workloads/services_display_containers.png
  static/images/docs/project-user-guide/workloads/services_events.png
  static/images/docs/project-user-guide/workloads/services_hide_containers.png
  static/images/docs/project-user-guide/workloads/services_metadata.png
  static/images/docs/project-user-guide/workloads/services_pods.png
  static/images/docs/project-user-guide/workloads/services_refresh_pods.png
  static/images/docs/project-user-guide/workloads/services_resource_status.png
Labels: lgtm, size/S

#1159 Added information to daemonsets-en.
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  static/images/docs/project-user-guide/workloads/daemonsets_autorefresh_start.png
  static/images/docs/project-user-guide/workloads/daemonsets_autorefresh_stop.png
  static/images/docs/project-user-guide/workloads/daemonsets_env_variable.png
  static/images/docs/project-user-guide/workloads/daemonsets_events.png
  static/images/docs/project-user-guide/workloads/daemonsets_metadata.png
  static/images/docs/project-user-guide/workloads/daemonsets_monitoring.png
  static/images/docs/project-user-guide/workloads/daemonsets_refresh.png
  static/images/docs/project-user-guide/workloads/daemonsets_time_range.png
Labels: lgtm, size/M

#1157 Added information to statefulsets-en.
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/project-user-guide/workloads/statefulsets_autorefresh_start.png
  static/images/docs/project-user-guide/workloads/statefulsets_autorefresh_stop.png
  static/images/docs/project-user-guide/workloads/statefulsets_env_variable.png
  static/images/docs/project-user-guide/workloads/statefulsets_events.png
  static/images/docs/project-user-guide/workloads/statefulsets_metadata.png
  static/images/docs/project-user-guide/workloads/statefulsets_monitoring.png
  static/images/docs/project-user-guide/workloads/statefulsets_refresh.png
  static/images/docs/project-user-guide/workloads/statefulsets_time_range.png
Labels: lgtm, size/M

#1156 Added information to deployments-en.
  content/en/docs/project-user-guide/application-workloads/deployments.md
  static/images/docs/project-user-guide/workloads/deployments_autorefresh_start.png
  static/images/docs/project-user-guide/workloads/deployments_autorefresh_stop.png
  static/images/docs/project-user-guide/workloads/deployments_env_variable.png
  static/images/docs/project-user-guide/workloads/deployments_events.png
  static/images/docs/project-user-guide/workloads/deployments_metadata.png
  static/images/docs/project-user-guide/workloads/deployments_monitoring.png
  static/images/docs/project-user-guide/workloads/deployments_refresh.png
  static/images/docs/project-user-guide/workloads/deployments_time_range.png
Labels: lgtm, size/M

#1160 reuse-the-same-app-name-after-deletion doc translated
  content/zh/docs/faq/applications/reuse-the-same-app-name-after-deletion.md
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/confirm-delete.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/delete-redis-1.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/delete-secret.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/error-prompt.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/new-redis-app.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/redis-1.png
  static/images/docs/zh-cn/faq/applications/reuse-the-same-app-name-after-deletion/search-secret.png
Labels: size/M

#1163 uninstall-pluggable-components doc translated
  content/zh/docs/faq/installation/uninstall-pluggable-components.md
Labels: size/L

#1165 Added information to cronjobs-en.
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  static/images/docs/project-user-guide/application-workloads/cronjobs/events.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-records.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/metadata.png
Labels: lgtm, size/S

#1164 Added information to jobs-en.
  content/en/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/project-user-guide/application-workloads/jobs/display.png
  static/images/docs/project-user-guide/application-workloads/jobs/env-variable.png
  static/images/docs/project-user-guide/application-workloads/jobs/events.png
  static/images/docs/project-user-guide/application-workloads/jobs/execution-records.png
  static/images/docs/project-user-guide/application-workloads/jobs/hide.png
  static/images/docs/project-user-guide/application-workloads/jobs/metadata.png
  static/images/docs/project-user-guide/application-workloads/jobs/refresh.png
  static/images/docs/project-user-guide/application-workloads/jobs/resource-status.png
Labels: size/M

#1167 adjust prometheus uninstall command
  content/en/docs/faq/observability/byop.md
Labels: lgtm, size/XS

#1169 Added information and updated images in routes-en.
  content/en/docs/project-user-guide/application-workloads/routes.md
  static/images/docs/project-user-guide/application-workloads/routes/add-metadata.png
  static/images/docs/project-user-guide/application-workloads/routes/auto-generate.png
  static/images/docs/project-user-guide/application-workloads/routes/basic-info.png
  static/images/docs/project-user-guide/application-workloads/routes/create-route.png
  static/images/docs/project-user-guide/application-workloads/routes/edit-route.png
  static/images/docs/project-user-guide/application-workloads/routes/events.png
  static/images/docs/project-user-guide/application-workloads/routes/metadata.png
  static/images/docs/project-user-guide/application-workloads/routes/obtain-address-loadbalancer.png
  static/images/docs/project-user-guide/application-workloads/routes/obtain-address-nodeport.png
  static/images/docs/project-user-guide/application-workloads/routes/resource-status.png
  static/images/docs/project-user-guide/application-workloads/routes/route-list.png
  static/images/docs/project-user-guide/application-workloads/routes/specify-domain.png
Labels: size/S

#1166 keepalived-haproxy doc translated
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: size/L

#1172 Add KubeSphere API doc link
  content/en/docs/api-reference/api-docs.md
  content/zh/docs/api-reference/api-docs.md
Labels: approved, lgtm, size/XS

#1136 Add a blog of using KubeKey to install KubeSphere with NFS storage
  content/en/blogs/install-nfs-server-client-for-kubesphere-cluster.md
  static/images/blogs/en/install-nfs-server-client-for-kubesphere-cluster/nfs-client-pod.png
  static/images/blogs/en/install-nfs-server-client-for-kubesphere-cluster/nfs-client-pvc.png
  static/images/blogs/en/install-nfs-server-client-for-kubesphere-cluster/nfs-storage-class.png
Labels: approved, lgtm, size/L

#1154 Add GlusterFS server configuration guide
  content/en/docs/api-reference/storage-system-installation/glusterfs-server.md
Labels: lgtm, size/XL

#1170 services doc zh modified
  content/zh/docs/project-user-guide/application-workloads/services.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services-events.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services-matadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services-pods.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services-resource-status.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services_display_containers.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services_hide_containers.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services_refresh_pods.png
Labels: size/S

#1162 update quick-start for en && zh
  content/en/contribution/_index.md
  content/zh/contribution/_index.md
Labels: lgtm, size/XS

#1171 deployments doc zh modified
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments-env-variables.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments-events.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments-matadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments-monitoring.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments-time-range.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments_autorefresh_start.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments_autorefresh_stop.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/deployments_refresh.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_autorefresh_start.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_autorefresh_stop.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_refresh.png
Labels: size/M

#1179 daemonsets-doc-zh modified
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_autorefresh_start.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_autorefresh_stop.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_env_variable.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_events.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_metadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_monitoring.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_refresh.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_time_range.png
Labels: size/M

#1181 remove-nodes doc zh reviewed
  content/zh/docs/installing-on-linux/cluster-operation/remove-nodes.md
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/delete-nodes/cordon.png
Labels: size/M

#1178 Add Doc: Import a GKE Cluster
  content/en/docs/multicluster-management/_index.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/click-add-cluster.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/click-edit.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/gke-cluster-imported.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/input-info.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/search-config.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-gke/select-method.png
Labels: lgtm, size/L

#1182 add-new-nodes zh reviewed
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/installing-on-linux/cluster-operation/add-new-nodes.md
Labels: lgtm, size/L

#1180 composing-app doc zh translated
  content/en/docs/project-user-guide/application/compose-app.md
  content/zh/docs/project-user-guide/application/compose-app.md
  content/zh/docs/quick-start/wordpress-deployment.md
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/click-to-visit.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/container-image.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/create-composing-app.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/dashboard.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/microservices-done.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/product-page.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/review-page.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/route.png
  static/images/docs/zh-cn/project-user-guide/applications/create-a-microservices-based-app/status-active.png
Labels: size/L

#1186 Refactro canary release and bookinfo quickstart
  content/en/blogs/install-nfs-server-client-for-kubesphere-cluster.md
  content/en/docs/application-store/built-in-apps/minio-app.md
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/en/docs/application-store/built-in-apps/nginx-app.md
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/faq/observability/monitoring.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/project-user-guide/application-workloads/services.md
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/en/docs/quick-start/wordpress-deployment.md
  content/tr/conferences/app-template.md
  static/images/docs/project-user-guide/grayscale-release/canary-release/finish-canary-release.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/job-offline.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/take-over-release.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/take-over-traffic.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/topology.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/tracing-kubesphere.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/tracing.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/traffic-management.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/traffic.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/bookinfo.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/canary.gif
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-bookinfo.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-to-visit.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/create-bookinfo.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/detail-page.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/normal-user.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/ratings-page.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/running.png
Labels: size/L

#1176 TiDB-doc-zh modified
  content/zh/docs/application-store/external-apps/deploy-tidb.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/add-pingcap-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/add-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/added-pingcap-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/basic-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/check-config-file.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/click-tidb-cluster.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/click-tidb-operator.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/deploy-app-again.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/deploy-app.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/download-yaml-file.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/from-app-templates-2.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/from-app-templates.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/select-version.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-app-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-config.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-deployment.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-operator-running.png
Labels: size/L

#1185 Update Doc-Import an AWS EKS Cluster
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  static/images/docs/eks-kubeconfig.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/click-add-cluster.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/click-edit.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-kubeconfig.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-overview.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/input-info.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-eks/search-config.png
Labels: size/L

#1153 Written horizontal-pod-autoscaling-en.
  content/en/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/add-container-image.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/busybox.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/cancel-hpa.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/cpu-request.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-deployment.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-service.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/deployment-name.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/horizontal-pod-autoscaling.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-deployment.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-parameters.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-decrease.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-increase.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/service-name.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/start-command.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/stateless-service.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/target-cpu-utilization.png
Labels: size/L

#1190 Update Doc-Create Pipeline Using Jenkinsfile
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
Labels: size/S

#1187 wordpress-doc-zh reviewed
  content/zh/docs/quick-start/wordpress-deployment.md
  static/images/docs/zh-cn/quickstart/wordpress-deployment/WordPress.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/access-method.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/add-container.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/add-service.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/add-volume-page.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/advanced-setting.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/advanced.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/application-created.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/basic-info.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/choose-existing-volume.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/components-finished.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/composing-app.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/container-image-page.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/container-image.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/create-secret.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/edit-internet-access.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/environment-var.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/environment-varss.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/ingress-create.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/key-value.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/mount-volume-page.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/mysql-finished.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/mysql-running.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/mysqlname.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/name-wordpress.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/nodeport-number.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volume-settings.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volume-template.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volumes.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/wordpress-deployment.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/wordpress-page.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/wordpress-secrets.png
Labels: size/L

#1189 deploy-and-access-bookinfo zh reviewed
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/bookinfo.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-bookinfo.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-to-visit.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/create-bookinfo.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/detail-page.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/normal-user.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/ratings-page.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/running.png
Labels: size/L

#1197 quickstart-intro zh reviewed
  content/zh/docs/quick-start/_index.md
Labels: size/S

#1191 canary-release zh reviewed
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/zh/docs/project-user-guide/grayscale-release/canary-release.md
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary.gif
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/finish-canary-release.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/take-over-release.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/topology.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/tracing-kubesphere.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/tracing.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/traffic-management.png
Labels: size/L

#1194 multioverview zh reviewed
  content/zh/docs/installing-on-linux/introduction/multioverview.md
Labels: size/M

#1193 Add Doc-Import an Aliyun ACK Cluster
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/ack-cluster-imported.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/click-add-cluster.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/click-edit.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/input-info.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/kubeconfig.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/search-config.png
  static/images/docs/multicluster-management/import-cloud-hosted-k8s/import-ack/select-method.png
Labels: lgtm, size/L

#1195 intro zh reviewed
  content/zh/docs/installing-on-linux/introduction/intro.md
Labels: size/M

#1200 jobs-zh modified
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/display.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/env-variable.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/events.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/execution-records.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/hide.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/metadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/refresh.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/resource-status.png
Labels: size/M

#1203 remove unexpected words "所"
  content/zh/docs/introduction/features.md
Labels: approved, lgtm, size/XS

#1202 cronjob-en modified
  content/en/docs/project-user-guide/application-workloads/cronjob.md
Labels: size/XS

#1183 fix multiple H1 in doc
  assets/scss/doc.scss
  layouts/docs/single.html
Labels: size/XS

#1209 add hotjar tracking
  config/upstream/config.toml
  layouts/partials/head.html
Labels: approved, lgtm, size/S

#1205 Add FAQ-Install Plugins to Jenkins in KubeSphere
  content/en/docs/faq/_index.md
  content/en/docs/faq/devops/_index.md
  content/en/docs/faq/devops/install-jenkins-plugins.md
  content/zh/docs/faq/_index.md
  content/zh/docs/faq/devops/_index.md
  content/zh/docs/faq/devops/install-jenkins-plugins.md
  static/images/docs/faq/devops/install-plugins-to-jenkins/available-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-advanced-tab.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-manage-jenkins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-manage-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/installed-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/update-plugins.png
Labels: lgtm, size/L

#1019 learn: add lesson 14 files.
  content/zh/learn/level_1/lesson_14/_index.md
  content/zh/learn/level_1/lesson_14/content.md
  content/zh/learn/level_1/lesson_14/courseware.md
  content/zh/learn/level_1/lesson_14/video.md
Labels: approved, lgtm, size/S

#1139 words to modify
  content/en/case/maxnerva.md
Labels: lgtm, size/XS

#1210 routes-zh translated
  content/zh/docs/project-user-guide/application-workloads/routes.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/access-method-loadbalancer.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/access-method-nodeport.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/access-route-loadbalancer.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/access-route-nodeport.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/add-metadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/auto-generate.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/basic-info.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/create-route.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/edit-route.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/events.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/metadata.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/obtain-address-loadbalancer.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/obtain-address-nodeport.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/resource-status.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/route-list.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/set-gateway.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/routes/specify-domain.png
Labels: size/L

#1213 gitlab-en translated
  content/zh/docs/application-store/external-apps/deploy-gitlab.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/add-main-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/add-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/added-main-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/basic-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/change-value.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/click-gitlab.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/deploy-app.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/from-app-templates.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-gitlab/view-config.png
Labels: size/M

#1211 hpa-zh translated
  content/zh/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/add-container-image.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/busybox.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/cancel-hpa.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/cpu-request.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-deployment.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-service.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/deployment-name.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/horizontal-pod-autoscaling.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-deployment.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-parameters.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-decrease.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-increase.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/service-name.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/start-command.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/stateless-service.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/target-cpu-utilization.png
Labels: size/L

#1214 metersphere-en translated
  content/zh/docs/application-store/external-apps/deploy-metersphere.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/add-metersphere-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/add-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/added-metersphere-repo.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/basic-info.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/change-value.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/click-metersphere.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/deploy-app.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/from-app-templates.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/metersphere-service.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/view-config.png
Labels: size/M

#1102 case localization
  content/zh/case/_index.md
  content/zh/case/anchnet.md
  content/zh/case/aqara.md
  content/zh/case/benlai.md
Labels: lgtm, size/L

#1173 Add a blog of configuring NFS sc and using NFS PVC on ks console
  content/en/blogs/add-nfs-sc-and-create-nfs-pvc-on-kubesphere-console.md
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/banner-page.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/bound-pvc.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/create-nfs-pvc.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/deployment-ready.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/image.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/pvc-mounted.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/resource-status.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/select-pvc.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/storage-class-nfs.png
  static/images/blogs/en/add-nfs-storage-class-on-kubesphere-console/volumes.png
Labels: lgtm, size/L

#1220 Update doc style guide
  KubeSphere Documentation Style Guide.md
Labels: size/XS

#1148 Refactor storage installation guides on Linux
  content/en/docs/installing-on-linux/cluster-operation/_index.md
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
  content/en/docs/installing-on-linux/introduction/port-firewall.md
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
  content/en/docs/installing-on-linux/introduction/vars.md
  content/en/docs/installing-on-linux/on-premises/_index.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/_index.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-gluster-fs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/en/docs/installing-on-linux/public-cloud/_index.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/installing-on-linux/uninstall-kubesphere-and-Kubernetes.md
  static/images/docs/installing-on-linux/persistent-storage-configurations/glusterfs-client/storage-class-available.png
  static/images/docs/installing-on-linux/persistent-storage-configurations/glusterfs-client/volumes-in-use.png
  static/images/docs/installing-on-linux/persistent-storage-configurations/nfs-client/nfs-pod.png
  static/images/docs/installing-on-linux/persistent-storage-configurations/nfs-client/nfs-storage-class.png
  static/images/docs/installing-on-linux/persistent-storage-configurations/qingcloud-csi/qingcloud-csi-pod.png
  static/images/docs/installing-on-linux/persistent-storage-configurations/qingcloud-csi/qingcloud-csi-storage-class.png
Labels: lgtm, size/XXL

#1226 understand-persistent-storage-en translated
  content/zh/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
Labels: size/M

#1228 understand-persistent-storage-en modified
  content/en/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
Labels: lgtm, size/XS

#1217 NFS-server-en translated
  content/zh/docs/api-reference/storage-system-installation/nfs-server.md
Labels: size/M

#1219 glusterFS-en translated
  content/zh/docs/api-reference/storage-system-installation/glusterfs-server.md
Labels: size/L

#1229 nfs-client-en translated
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/nfs-client/nfs-pod.png
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/nfs-client/nfs-storage-class.png
Labels: size/L

#1234 qingcloud-csi-en modified
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
Labels: size/XS

#1232 qingcloud-csi-en translated
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/qingcloud-csi/access-key.png
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/qingcloud-csi/qingcloud-csi-pod.png
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/qingcloud-csi/qingcloud-csi-storage-class.png
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/qingcloud-csi/storage-zone.jpg
Labels: size/L

#1235 install-glusterfs-en modified
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
Labels: lgtm, size/XS

#1231 install-glusterfs-en translated
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/glusterfs-client/storage-class-available.png
  static/images/docs/zh-cn/installing-on-linux/persistent-storage-configurations/glusterfs-client/volumes-in-use.png
Labels: size/L

#1206 blog modified
  content/zh/blogs/deep-dive-into-the-K8s-request-and-limit.md
Labels: lgtm, size/XS

#1240 fix a kubekey link
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
Labels: size/XS

#1241 Cherry-pick link fix
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
Labels: size/XS

#1236 aliyun-ack-en translated
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/ack-cluster-imported.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/kubeconfig.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/search-config.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/select-method.png
Labels: size/M

#1239 import-aws-eks-en typo fixed
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: size/XS

#1243 gke-en translated
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/gke-cluster-imported.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/search-config.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/select-method.png
Labels: size/M

#1244 import-aws-eks-en typo fixed
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: size/XS

#1245 aliyun-ack-en translated
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/ack-cluster-imported.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/kubeconfig.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/search-config.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-ack/select-method.png
Labels: size/M

#1246 gke-en translated
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/gke-cluster-imported.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/search-config.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-gke/select-method.png
Labels: size/M

#1250 Update cronjob file name
  content/en/docs/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/project-user-guide/application-workloads/cronjobs.md
Labels: size/XS

#1249 eks-en typo fixed
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: lgtm, size/XS

#1204 “GPU-Operator.md“
  content/zh/blogs/GPU-Operator.md
Labels: approved, lgtm, size/XL

#1255 Update Hua Xia Bank Case
  content/en/case/huaxia-bank.md
Labels: size/M

#1230 Add Doc-How to Create a DevOps Kubeconfig on AWS
  content/en/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  content/zh/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  static/images/docs/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
  static/images/docs/faq/devops/create-devops-kubeconfig-on-aws/get-token.jpg
Labels: size/L

#1266 Cherry-pick Huaxia Case to release-3.0
  content/en/case/huaxia-bank.md
Labels: size/M

#1267 Sync Doc-How to Create DevOps Kubeconfig on AWS to documentation 3.0
  content/en/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  content/zh/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  static/images/docs/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
  static/images/docs/faq/devops/create-devops-kubeconfig-on-aws/get-token.jpg
Labels: lgtm, size/L

#1268 deploy-metersphere-zh pics updated
  content/zh/docs/application-store/external-apps/deploy-metersphere.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/deployments-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/login-metersphere.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/metersphere-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/metersphere-service.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/statefulsets-running.png
Labels: size/S

#1252 restore-host-cluster-access-en translated
  content/zh/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
Labels: lgtm, size/M

#1248 aws-gke-en translated
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-kubeconfig.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-overview.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/search-config.png
Labels: size/L

#1259 integrate-metersphere-en translated
  content/zh/docs/devops-user-guide/how-to-integrate/integrate-metersphere.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/api-key-created.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/choose-file.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-create-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-manage-jenkins.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-manage-plugins.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-new-item.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-pilepine-item.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-pipeline-syntax.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-save.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-show.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-upload.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/copy-secret-key.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-api-keys.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-project.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-test-plan.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/demo-plan.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/demo-project.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/edit-jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/input-values.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/installation-success.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/installed-tab.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/metersphere-in-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/pipeline-script.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/pipeline-success.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/run-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere-in-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/set-item-info.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/set-pipeline-name.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/show-logs.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/snippet-output.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-plan-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-report-detail.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-report.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/view-logs.PNG
Labels: size/L

#1273 eks-en typo fixed: Cherry-pick pr 1249
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: size/XS

#1274 Add eks cn to release-3.0
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/click-add-cluster.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/click-edit.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-kubeconfig.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/eks-overview.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/input-info.png
  static/images/docs/zh-cn/multicluster-management/import-cloud-hosted-k8s/import-eks/search-config.png
Labels: size/L

#1275 integrate-metersphere-en translated
  content/zh/docs/devops-user-guide/how-to-integrate/integrate-metersphere.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/api-key-created.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/choose-file.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-create-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-manage-jenkins.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-manage-plugins.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-new-item.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-pilepine-item.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-pipeline-syntax.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-save.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-show.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/click-upload.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/copy-secret-key.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-api-keys.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-project.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/create-test-plan.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/demo-plan.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/demo-project.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/edit-jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/input-values.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/installation-success.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/installed-tab.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/metersphere-in-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/pipeline-script.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/pipeline-success.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/run-pipeline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere-in-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/select-metersphere.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/set-item-info.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/set-pipeline-name.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/show-logs.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/snippet-output.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-plan-list.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-report-detail.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/test-report.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-metersphere/view-logs.PNG
Labels: size/L

#1277 Added restore-host-cluster-access-zh to release-3.0
  content/zh/docs/faq/multi-cluster-management/host-cluster-access-member-cluster.md
Labels: size/M

#1276 deploy-metersphere-zh pics updated
  content/zh/docs/application-store/external-apps/deploy-metersphere.md
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/deployments-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/login-metersphere.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/metersphere-running.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/metersphere-service.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-metersphere/statefulsets-running.png
Labels: size/S

#1279 update footer
  assets/scss/footer.scss
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: size/M

#1256 update user case list
  content/en/_index.md
  content/zh/_index.md
  content/zh/case/_index.md
Labels: approved, lgtm, size/M

#1285 Add notification management placeholder file
  content/en/docs/cluster-administration/platform-settings/_index.md
  content/en/docs/cluster-administration/platform-settings/customize-basic-information.md
  content/en/docs/cluster-administration/platform-settings/notification-management/_index.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
  content/zh/docs/cluster-administration/platform-settings/_index.md
  content/zh/docs/cluster-administration/platform-settings/customize-basic-information.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/_index.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
Labels: size/L

#1286 Update enable alerting in doc 3.1
  content/en/docs/faq/installation/telemetry.md
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/pluggable-components/alerting.md
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/en/docs/pluggable-components/metrics-server.md
  content/en/docs/pluggable-components/network-policy.md
  content/en/docs/pluggable-components/service-mesh.md
  content/en/docs/quick-start/enable-pluggable-components.md
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/alerting.png
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/clusters-management.png
  static/images/docs/enable-pluggable-components/kubesphere-alerting-and-notification/edit-yaml.png
  static/images/docs/enable-pluggable-components/kubesphere-alerting/alerting-section.png
Labels: size/L

#1253 update footer
  assets/scss/footer.scss
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: size/M

#1262 SEO with sitemap
  config/_default/config.toml
  content/en/api/_index.md
  content/tr/forum/_index.md
  content/tr/reason/_index.md
  content/tr/trends/_index.md
  content/zh/reference/_index.md
  content/zh/reference/api-changes/_index.md
  content/zh/reference/api-changes/logging.md
  content/zh/reference/api-changes/monitoring.md
  content/zh/reference/api-docs.md
  content/zh/reference/glossary.md
Labels: size/L

#1264 SEO with H tags
  assets/scss/doc.scss
  assets/scss/docs.scss
  layouts/partials/section.html
Labels: size/XS

#1271 remove links in footer
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: size/S

#1218 update element class for gtag
  assets/scss/header.scss
  layouts/partials/header.html
Labels: size/S

#1287 SEO with sitemap
  config/_default/config.toml
  content/en/api/_index.md
  content/tr/forum/_index.md
  content/tr/reason/_index.md
  content/tr/trends/_index.md
  content/zh/reference/_index.md
  content/zh/reference/api-changes/_index.md
  content/zh/reference/api-changes/logging.md
  content/zh/reference/api-changes/monitoring.md
  content/zh/reference/api-docs.md
  content/zh/reference/glossary.md
Labels: lgtm, size/L

#1288 fix docs link
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: lgtm, size/M

#1289 fix docs link
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: size/M

#1290 update SEO
  assets/scss/doc.scss
  assets/scss/docs.scss
  data/en/footer.yaml
  data/zh/footer.yaml
  layouts/partials/section.html
Labels: size/S

#1291 Fix reference part title
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/introduction/architecture.md
  content/en/docs/reference/_index.md
  content/en/docs/reference/api-changes/_index.md
  content/en/docs/reference/api-changes/logging.md
  content/en/docs/reference/api-changes/monitoring.md
  content/en/docs/reference/api-docs.md
  content/en/docs/reference/glossary.md
  content/en/docs/reference/storage-system-installation/_index.md
  content/en/docs/reference/storage-system-installation/glusterfs-server.md
  content/en/docs/reference/storage-system-installation/nfs-server.md
  content/en/docs/release/release-v202.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/introduction/architecture.md
  content/zh/docs/release/release-v202.md
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: size/S

#1282 monitoring-zh reviewed
  content/zh/docs/faq/observability/monitoring.md
Labels: size/M

#1292 Titles changes for SEO
  content/en/_index.md
  content/en/devops/_index.md
Labels: approved, lgtm, size/XS

#1294 monitoring-zh reviewed
  content/zh/docs/faq/observability/monitoring.md
Labels: size/M

#1295 logging-zh reviewed
  content/zh/docs/faq/observability/logging.md
Labels: size/L

#1281 logging-zh reviewed
  content/zh/docs/faq/observability/logging.md
Labels: size/L
