Repository kubesphere/website, pull requests merged in 2021-01, with the labels that each got.

#855 Update agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
Labels: dco-signoff: yes, size/XS

#845 StatefulSets and DaemonSets ZH Updated.
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/project-user-guide-zh/workloads-zh/update-strategy.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonset-request-limit.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_detail.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_detail_operation_btn.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_detail_pod.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_detail_state.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_form_1.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_form_2_container_1.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_form_2_container_btn.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_form_3.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_form_4.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/daemonsets_list.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulset-request-limit.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_detail.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_detail_operation_btn.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_detail_pod.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_detail_state.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_1.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_2.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_2_container_1.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_2_container_btn.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_3.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_form_4.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/statefulsets_list.png
Labels: dco-signoff: yes, lgtm, size/L

#856 Update some wording
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
Labels: dco-signoff: yes

#857 Update all-in-one
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: dco-signoff: yes, size/M

#858 Update minimal installation on k8s
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  static/images/docs/zh-cn/quickstart/minimal-kubesphere-on-k8s/kubesphere-components-zh.png
Labels: dco-signoff: yes, size/M

#815 Polish direct connection and agent connection guide
  content/en/docs/multicluster-management/enable-multicluster/_index.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/multicluster-management/enable-multicluster/retrieve-kubeconfig.md
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/add-cluster.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/agent-en.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/cluster-imported.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/agent-connection/cluster-info.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/add-cluster.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/cluster-imported.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/cluster-info.png
  static/images/docs/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/kubeconfig.jpg
Labels: dco-signoff: yes, size/L

#863 Make desc more clear in multicluster management
  content/en/docs/multicluster-management/enable-multicluster/_index.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
Labels: dco-signoff: yes

#862 Translated change-console-language-zh.
  content/zh/docs/faq/console/change-console-language.md
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/basic-info-page.jpg
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/user-settings.jpg
  static/images/docs/zh-cn/faq/kubesphere-web-console/supported-browsers/console-browser.png
Labels: dco-signoff: yes, size/M

#864 Translated forgot-password-zh.
  content/zh/docs/faq/access-control/forgot-password.md
  static/images/docs/zh-cn/faq/forgot-password/modify-password.png
Labels: dco-signoff: yes, size/S

#865 fix some words and add zhcn uninstalling guide
  content/en/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
  content/en/docs/upgrade/overview.md
  content/en/docs/workspace-administration/app-repository/_index.md
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  content/en/docs/workspace-administration/upload-helm-based-application.md
  content/zh/case/vng.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/zh/docs/installing-on-kubernetes/uninstall-kubesphere-from-k8s.md
  content/zh/docs/introduction/what-is-kubesphere.md
  content/zh/docs/quick-start/_index.md
  content/zh/docs/quick-start/enable-pluggable-components.md
Labels: dco-signoff: yes, size/M

#859 Services ZH translated.
  content/en/docs/project-user-guide/application-workloads/services.md
  content/zh/docs/project-user-guide/application-workloads/services.md
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/create-service-type.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/services-lists.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-detail.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-finish.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-form-1.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-form-2.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-form-3.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-form-4.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/stateless-form.PNG
Labels: dco-signoff: yes, lgtm, size/L

#866 fix a link
  content/en/docs/project-user-guide/application-workloads/services.md
  content/zh/docs/project-user-guide/application-workloads/services.md
Labels: dco-signoff: yes

#867 Minor fix
  content/en/docs/installing-on-kubernetes/introduction/overview.md
  content/en/docs/installing-on-kubernetes/introduction/prerequisites.md
  static/images/docs/installing-on-kubernetes/introduction/overview/kubesphere+k8s.png
  static/images/docs/installing-on-kubernetes/introduction/overview/login.png
Labels: dco-signoff: yes

#870 Update zhcn multitenant quickstart
  content/en/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/devops-工程.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/nodeport.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建-devops-工程.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建企业空间.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建帐户.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建角色.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建项目.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/完成创建企业空间.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/完成网关设置.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/工程列表.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/帐户列表.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/查看项目.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/编辑帐户角色.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/编辑权限.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/编辑角色.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置密码.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置网关.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置配额.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/访问控制.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请-devops-成员.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请列表.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请成员.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请成员至项目.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/项目.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/项目概览.jpg
Labels: dco-signoff: yes, size/L

#872 Add aws news
  content/en/news/_index.md
  content/en/news/kubesphere-available-on-aws-quickstart.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#860 Translated install-kubesphere-on-qingcloud-vms-zh.
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/3-master.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/active-listener.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/active.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/apply-change.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/bind-eip.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/cluster-node.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/create-lb.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/ha-architecture.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/listener.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/listener2.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/qingcloud-lb.png
  static/images/docs/zh-cn/installing-on-linux/installing-on-public-cloud/deploy-kubesphere-on-qingcloud-instances/six-instances.png
Labels: dco-signoff: no, lgtm, size/L

#868 Jobs ZH updated.
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/project-user-guide/application-workloads/jobs/add-container-image-job-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/container-log-zh.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/create-job-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/execution-record-zh. jpg.png
  static/images/docs/project-user-guide/application-workloads/jobs/execution-record-zh.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/job-container-settings-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-basic-info-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-job-settings-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-list-new-zh.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-operation-zh.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/start-command-job-zh.jpg
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/add-container-image-job.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/container-log-check.jpg
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/container-log.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/create-job.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/execution-record.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/job-container-settings.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/job-create-basic-info.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/job-create-job-settings.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/job-list-new.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/job-operation.PNG
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/start-command-job.PNG
Labels: dco-signoff: yes, lgtm, size/L

#805 Add Helm developer guide
  content/en/docs/application-store/app-developer-guide/helm-developer-guide.md
  content/zh/docs/application-store/app-developer-guide/helm-developer-guide.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#877 腾讯云限制PVC申请需要为10G倍数的问题
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-tencent-tke.md
Labels: approved, dco-signoff: no, lgtm, size/S

#875 Direct Connection ZH and Retrieve KubeConfig ZH updated.
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/retrieve-kubeconfig.md
  static/images/docs/direct_import_en.png
  static/images/docs/zh-cn/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/add-cluster.PNG
  static/images/docs/zh-cn/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/cluster-imported.PNG
  static/images/docs/zh-cn/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/cluster-info.PNG
  static/images/docs/zh-cn/multicluster-management/enable-multicluster-management-in-kubesphere/direct-connection/kubeconfig.PNG
Labels: dco-signoff: yes, lgtm, size/L

#760 Add EN OAuth2 identity provider guide
  content/en/docs/access-control-and-account-management/oauth2.md
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/github-authentication.jpg
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/github-login-page.png
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/logged-in.png
  static/images/docs/access-control-and-account-management/oauth2-identity-provider/oauth2.svg
Labels: dco-signoff: yes, lgtm, size/L

#882 Fix some words
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/en/docs/workspace-administration/upload-helm-based-application.md
  content/zh/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: yes

#883 Add notes
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
Labels: dco-signoff: yes

#880 Reviewed nodes-zh.
  content/zh/docs/cluster-administration/nodes.md
  static/images/docs/zh-cn/cluster-administration/node-management/add-taints.png
  static/images/docs/zh-cn/cluster-administration/node-management/assign_pods_to_node.png
  static/images/docs/zh-cn/cluster-administration/node-management/clusters-management-select.png
  static/images/docs/zh-cn/cluster-administration/node-management/drop-down-list-node.png
  static/images/docs/zh-cn/cluster-administration/node-management/label_node.png
  static/images/docs/zh-cn/cluster-administration/node-management/node_detail.png
  static/images/docs/zh-cn/cluster-administration/node-management/node_status.png
  static/images/docs/zh-cn/cluster-administration/node-management/select-a-cluster.png
  static/images/docs/zh-cn/cluster-administration/node-management/taint-management.png
Labels: dco-signoff: yes, size/M

#884 Overview translated.
  content/en/docs/project-user-guide/grayscale-release/overview.md
  content/zh/docs/project-user-guide/grayscale-release/overview.md
Labels: dco-signoff: yes, size/M

#876 Translated cluster-status-monitoring-zh.
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/apiserver-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-nodes.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-resources-usage.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-status-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/clusters-management.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/component-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cpu-load-average.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cpu-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/disk-throughput.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/disk-usage.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/etcd-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/inode-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/iops.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/memory-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/netework-bandwidth.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/node-usage-ranking.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/physical-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/platform.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/pod-status.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/running-status.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/scheduler-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/service-components-status.png
Labels: dco-signoff: yes, lgtm, size/L

#886 Translate cronjob.md
  content/zh/docs/project-user-guide/application-workloads/cronjob.md
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/container-log-1.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/container-log-2.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/cronjob-action.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/cronjob-create-basic-info.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/cronjob-list-new.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/cronjob-list.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/execution-record.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/finish-image.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/input-busybox.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/job-detail-page.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/job-list.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/start-command.png
Labels: dco-signoff: yes, lgtm, size/L

#888 update alerting title
  content/en/docs/cluster-administration/cluster-settings/mail-server.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/en/docs/pluggable-components/alerting-notification.md
  content/en/docs/project-user-guide/alerting/alerting-message.md
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  content/en/docs/toolbox/auditing/auditing-rule.md
Labels: dco-signoff: yes

#885 Reviewed application-resources-monitoring-zh.
  content/zh/docs/cluster-administration/application-resources-monitoring.md
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/application-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/cluster-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/clusters-management.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/platform.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/time-range.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/usage-ranking.png
Labels: dco-signoff: yes, size/M

#889 refactor: modify document of install-ks-on-tencent-tke
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-ks-on-tencent-tke.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#890 title fix in custom app monitoring
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/en/docs/project-user-guide/custom-application-monitoring/introduction.md
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/overview.md
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/querying.md
Labels: dco-signoff: yes, size/M

#891 Blue-green Deployment translated.
  content/zh/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-0.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-1.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-2.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-3.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-4.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-5.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-6.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-7.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/blue-green-job-list.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/blue-green-deployment/version2-deployment.PNG
Labels: dco-signoff: yes, size/M

#892 Cluster Visibility and Authorization translated.
  content/en/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  static/images/docs/zh-cn/cluster-administration/cluster-settings/cluster-visibility-and-authorization/assign-workspace.PNG
  static/images/docs/zh-cn/cluster-administration/cluster-settings/cluster-visibility-and-authorization/create-project.png
  static/images/docs/zh-cn/cluster-administration/cluster-settings/cluster-visibility-and-authorization/create-workspace.PNG
  static/images/docs/zh-cn/cluster-administration/cluster-settings/cluster-visibility-and-authorization/select-a-cluster.PNG
  static/images/docs/zh-cn/cluster-administration/cluster-settings/cluster-visibility-and-authorization/workspace-list.PNG
Labels: dco-signoff: yes, size/M

#895 Update upgrade word
  content/en/docs/upgrade/_index.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: yes

#897 Update pluggable components
  content/en/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/quick-start/enable-pluggable-components.md
  static/images/docs/quickstart/enable-pluggable-components/clusters-management.png
  static/images/docs/quickstart/enable-pluggable-components/component-status-page.png
  static/images/docs/quickstart/enable-pluggable-components/component-status.png
  static/images/docs/quickstart/enable-pluggable-components/crds.png
  static/images/docs/quickstart/enable-pluggable-components/edit-yaml.png
  static/images/docs/quickstart/enable-pluggable-components/enable-components.png
  static/images/docs/zh-cn/quickstart/enable-pluggable-components/CRD.png
  static/images/docs/zh-cn/quickstart/enable-pluggable-components/启用组件.png
  static/images/docs/zh-cn/quickstart/enable-pluggable-components/服务组件.jpg
  static/images/docs/zh-cn/quickstart/enable-pluggable-components/编辑配置文件.png
  static/images/docs/zh-cn/quickstart/enable-pluggable-components/集群管理.png
Labels: dco-signoff: yes

#896 Notification Manager translated.
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
Labels: dco-signoff: yes, size/M

#900 Word3
  content/en/docs/quick-start/wordpress-deployment.md
  static/images/docs/quickstart/wordpress-deployment/WordPress.png
  static/images/docs/quickstart/wordpress-deployment/access-method.png
  static/images/docs/quickstart/wordpress-deployment/add-container.png
  static/images/docs/quickstart/wordpress-deployment/add-service.png
  static/images/docs/quickstart/wordpress-deployment/add-volume-page.png
  static/images/docs/quickstart/wordpress-deployment/advanced-settings.png
  static/images/docs/quickstart/wordpress-deployment/advanced.png
  static/images/docs/quickstart/wordpress-deployment/application-created.png
  static/images/docs/quickstart/wordpress-deployment/basic-info.png
  static/images/docs/quickstart/wordpress-deployment/choose-existing-volume.png
  static/images/docs/quickstart/wordpress-deployment/components-finished.png
  static/images/docs/quickstart/wordpress-deployment/composing-app.png
  static/images/docs/quickstart/wordpress-deployment/container-image-page.png
  static/images/docs/quickstart/wordpress-deployment/container-image.png
  static/images/docs/quickstart/wordpress-deployment/create-secrets.png
  static/images/docs/quickstart/wordpress-deployment/edit-internet-access.png
  static/images/docs/quickstart/wordpress-deployment/environment-var.png
  static/images/docs/quickstart/wordpress-deployment/environment-varss.png
  static/images/docs/quickstart/wordpress-deployment/ingress-create.png
  static/images/docs/quickstart/wordpress-deployment/key-value.png
  static/images/docs/quickstart/wordpress-deployment/mount-volume-page.png
  static/images/docs/quickstart/wordpress-deployment/mysql-finished.png
  static/images/docs/quickstart/wordpress-deployment/mysql-running.png
  static/images/docs/quickstart/wordpress-deployment/mysqlname.png
  static/images/docs/quickstart/wordpress-deployment/name-wordpress.png
  static/images/docs/quickstart/wordpress-deployment/nodeport-number.png
  static/images/docs/quickstart/wordpress-deployment/volume-settings.png
  static/images/docs/quickstart/wordpress-deployment/volume-template.jpg
  static/images/docs/quickstart/wordpress-deployment/volumes.png
  static/images/docs/quickstart/wordpress-deployment/wordpress-deployment.png
  static/images/docs/quickstart/wordpress-deployment/wordpress-page.png
  static/images/docs/quickstart/wordpress-deployment/wordpress-secrets.png
Labels: dco-signoff: yes, size/L

#899 History translated.
  content/zh/docs/toolbox/history.md
  static/images/docs/zh-cn/toolbox/history/recent-history.PNG
  static/images/docs/zh-cn/toolbox/history/toolbox.PNG
Labels: dco-signoff: yes, size/S

#898 Alertmanager translated.
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
Labels: dco-signoff: yes, size/M

#902 delete outdated command
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
Labels: dco-signoff: yes

#901 Adjust the layout.
  content/zh/blogs/netapp.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#904 update introduction of KubeSphere
  content/en/docs/introduction/what-is-kubesphere.md
  content/zh/docs/introduction/ecosystem.md
  content/zh/docs/introduction/what's-new-in-v3.0.md
  content/zh/docs/introduction/what-is-kubesphere.md
  static/images/docs/introduction/feature-overview.png
  static/images/docs/introduction/kubesphere-ecosystem.png
Labels: approved, dco-signoff: yes, size/M

#879 Add k8s installation blog using kubekey
  content/en/blogs/install-kubernetes-using-kubekey.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#893 Add components overview
  content/en/docs/pluggable-components/overview.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#903 Add workspace notes
  content/en/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/select-a-cluster.png
  static/images/docs/cluster-administration/cluster-settings/cluster-visibility-and-authorization/select-cluster.jpg
Labels: dco-signoff: yes, size/S

#906 Event Query translated.
  content/zh/docs/toolbox/events-query.md
  static/images/docs/zh-cn/toolbox/event-query/events-query-detail.PNG
  static/images/docs/zh-cn/toolbox/event-query/events-query-guide.png
  static/images/docs/zh-cn/toolbox/event-query/events-query-home.png
  static/images/docs/zh-cn/toolbox/event-query/events-query-list.PNG
Labels: dco-signoff: yes, size/M

#910 Audit Log Query translated.
  content/zh/docs/toolbox/auditing/auditing-query.md
  static/images/docs/zh-cn/toolbox/auditing/auditing-log-query/audit-log-detail.PNG
  static/images/docs/zh-cn/toolbox/auditing/auditing-log-query/auditing-log-filter.PNG
  static/images/docs/zh-cn/toolbox/auditing/auditing-log-query/auditing-operating-ui.PNG
  static/images/docs/zh-cn/toolbox/auditing/auditing-log-query/auditing-operating.PNG
  static/images/docs/zh-cn/toolbox/auditing/auditing-log-query/user-changed.PNG
Labels: dco-signoff: no, size/M

#907 Web Kubectl translated.
  content/en/docs/toolbox/web-kubectl.md
  content/zh/docs/toolbox/web-kubectl.md
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-cluster-select.PNG
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-enter.PNG
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-example.PNG
Labels: dco-signoff: yes, size/M

#911 Translated configmaps-zh.
  content/zh/docs/project-user-guide/configuration/configmaps.md
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/add-data.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/configmap-dropdown-menu.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/configmap-list.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/create-configmap.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/detail-page.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/edit-configmap-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/finish-creating.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/key-value.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/set-basic-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/configmaps/use-configmap.jpg
Labels: dco-signoff: yes, lgtm, size/M

#835 Add some notes for using app store
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/pluggable-components/app-store.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#908 Translated traffic-mirroring-zh.
  content/zh/docs/project-user-guide/grayscale-release/traffic-mirroring.md
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/new-deployment.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/remove-traffic-mirroring.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-1.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-2.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-3.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-4.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-5.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-6.jpg
  static/images/docs/zh-cn/project-user-guide/grayscale-release/traffic-mirroring/traffic-mirroring-task.jpg
Labels: dco-signoff: yes, size/M

#912 Update guide names
  content/zh/docs/project-user-guide/configuration/configmaps.md
  content/zh/docs/project-user-guide/grayscale-release/traffic-mirroring.md
Labels: dco-signoff: yes

#905 Translated secrets-zh.
  content/zh/docs/project-user-guide/configuration/secrets.md
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/account-password-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/add-data.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/create-secrets.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/custom-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/default-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/docker-hub-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/github-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/image-registry-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/input-key.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/secret-create.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/secret-detail-page.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/secret-dropdown-menu.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/secret-list.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/secret-type.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/set-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/tls.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/use-secret-image.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/secrets/use-secret-repository.jpg
Labels: dco-signoff: yes, size/L

#913 Relocated images.
  content/zh/docs/project-user-guide/configuration/configmaps.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#909 add learn page
  assets/scss/learn-page.scss
  assets/scss/learn.scss
  assets/scss/mixin.scss
  content/zh/learn/_index.md
  content/zh/learn/level_1/_index.md
  content/zh/learn/level_1/lesson_1/_index.md
  content/zh/learn/level_1/lesson_1/content.md
  content/zh/learn/level_1/lesson_1/courseware.md
  content/zh/learn/level_1/lesson_1/examination.md
  content/zh/learn/level_1/lesson_1/video.md
  content/zh/learn/level_1/lesson_2/_index.md
  content/zh/learn/level_1/lesson_2/content.md
  content/zh/learn/level_1/lesson_2/courseware.md
  content/zh/learn/level_1/lesson_2/video.md
  content/zh/learn/level_2/_index.md
  content/zh/learn/level_2/lesson_3/_index.md
  content/zh/learn/level_2/lesson_3/content.md
  content/zh/learn/level_2/lesson_3/examination.md
  content/zh/learn/level_2/lesson_3/video.md
  content/zh/learn/level_2/lesson_4/_index.md
  content/zh/learn/level_2/lesson_4/courseware.md
  content/zh/learn/level_2/lesson_4/video.md
  i18n/en.yaml
  i18n/zh.yaml
  layouts/learn/list.html
  layouts/learn/single.html
  layouts/partials/css.html
  layouts/partials/header.html
  static/images/learn/banner.png
  static/images/learn/base.svg
  static/images/learn/icon-download-active.svg
  static/images/learn/icon-download.svg
  static/images/learn/icon-image-active.svg
  static/images/learn/icon-image.svg
  static/images/learn/icon-ppt-active.svg
  static/images/learn/icon-ppt.svg
  static/images/learn/molecule.svg
  static/images/learn/orbit.svg
  static/images/learn/pendulum.svg
  static/images/learn/profession.svg
  static/images/learn/section3.png
  static/images/learn/three-dimensional.svg
  static/images/learn/time.svg
  static/images/learn/video.svg
Labels: dco-signoff: yes, size/XXL

#915 fix some format and title issues
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/storage-configuration.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-ks-installer.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
Labels: dco-signoff: yes

#914 Log Query translated.
  content/en/docs/toolbox/log-query.md
  content/zh/docs/toolbox/log-query.md
  static/images/docs/toolbox/log-query/log-query-drill-container.png
  static/images/docs/toolbox/log-query/log-query-drill.png
  static/images/docs/toolbox/log-query/log-query-guide.png
  static/images/docs/toolbox/log-query/log-query-inspect-other-pods.png
  static/images/docs/toolbox/log-query/log-query-interface.png
  static/images/docs/toolbox/log-query/log-query-log-detail.png
  static/images/docs/toolbox/log-query/log-query-log-search.png
  static/images/docs/toolbox/log-query/log-query-time-range.png
  static/images/docs/zh-cn/toolbox/log-query/log-query-drill-container.png
  static/images/docs/zh-cn/toolbox/log-query/log-query-drill.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-guide.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-inspect-other-pods.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-interface.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-log-detail.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-log-search.PNG
  static/images/docs/zh-cn/toolbox/log-query/log-query-time-range.PNG
Labels: dco-signoff: yes, lgtm, size/M

#919 Toolbox Index translated.
  content/zh/docs/toolbox/_index.md
  static/images/docs/zh-cn/toolbox/index/toolbox.PNG
Labels: dco-signoff: yes, lgtm, size/M

#916 Receive and Customize Auditing Logs translated.
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/zh/docs/toolbox/auditing/auditing-receive-customize.md
Labels: dco-signoff: yes, lgtm, size/M

#921 Update harbor deployment guide wording and format
  content/en/docs/application-store/built-in-apps/harbor-app.md
  content/en/docs/application-store/built-in-apps/memcached-app.md
  content/zh/docs/application-store/built-in-apps/harbor-app.md
  static/images/docs/appstore/built-in-apps/harbor-app/app-store.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/click-deploy.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/creating-harbor.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/deploy-harbor.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/find-harbor.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/harbor-config.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/harbor-dashboard.jpg
  static/images/docs/appstore/built-in-apps/harbor-app/harbor-login.jpg
Labels: dco-signoff: yes, size/L

#923 Overview translated.
  content/zh/docs/pluggable-components/overview.md
Labels: dco-signoff: yes, lgtm, size/M

#922 Translated volumes-zh.
  content/en/docs/project-user-guide/storage/volumes.md
  content/zh/docs/project-user-guide/storage/volumes.md
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/basic-volume-info.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/create-volume.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/delete-volume.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/local-pending.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/select-storage-class.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-creation-method.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-detail-page.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-finish-creation.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-finished.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-monitoring.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-page.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volume-status.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volumes/volumebindingmode.jpg
Labels: dco-signoff: yes, lgtm, size/L

#917 Auditing Rules translated.
  content/en/docs/toolbox/auditing/auditing-rule.md
  content/zh/docs/toolbox/auditing/auditing-rule.md
  static/images/docs/zh-cn/toolbox/auditing/auditing-rules/alerting-archiving-rule.PNG
  static/images/docs/zh-cn/toolbox/auditing/auditing-rules/auditing-crd.PNG
Labels: dco-signoff: no, size/L

#925 Update cn components index
  content/zh/docs/pluggable-components/_index.md
Labels: dco-signoff: yes

#926 Translated snapshots-zh.
  content/zh/docs/project-user-guide/storage/volume-snapshots.md
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/apply-volume.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/create-by-snapshot.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/drop-down-list-select.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/pvc-create.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/select-volume.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/snapshot-list.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/snapshot-name.jpg
  static/images/docs/zh-cn/project-user-guide/volume-management/volume-snapshots/volumes-page.jpg
Labels: dco-signoff: yes, lgtm, size/M

#931 Translated image-registry-zh.
  content/zh/docs/project-user-guide/configuration/image-registry.md
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/create-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/harbor-address.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/image-registry-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/open-dashboard.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/qingcloud-registry.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/use-image-registry.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/validate-registry-address.jpg
Labels: dco-signoff: yes, lgtm, size/M

#932 fix some titles
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/project-user-guide/application-workloads/cronjob.md
  content/en/docs/project-user-guide/configuration/configmaps.md
  content/en/docs/project-user-guide/configuration/image-registry.md
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/en/docs/project-user-guide/grayscale-release/traffic-mirroring.md
Labels: dco-signoff: yes

#929 Add devops overview
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/overview/sonarqube-result-detail.jpg
Labels: approved, dco-signoff: no, lgtm, size/M

#933 Persistent Storage Configuration translated.
  content/zh/docs/installing-on-linux/introduction/storage-configuration.md
  static/images/docs/zh-cn/installing-on-linux/introduction/persistent-storage-configurations/access-key.PNG
  static/images/docs/zh-cn/installing-on-linux/introduction/persistent-storage-configurations/storage-zone.PNG
Labels: dco-signoff: yes, lgtm, size/L

#936 Update linux overview installation
  content/en/docs/installing-on-linux/introduction/intro.md
Labels: dco-signoff: yes

#935 Translated alerting-policy-zh.
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  content/zh/docs/project-user-guide/alerting/alerting-policy.md
  static/images/docs/zh-cn/alerting/alerting_policy_workload_level_alerting_rule.png
  static/images/docs/zh-cn/alerting/alerting_policy_workload_level_basic_info.png
  static/images/docs/zh-cn/alerting/alerting_policy_workload_level_create.png
  static/images/docs/zh-cn/alerting/alerting_policy_workload_level_monitoring_target.png
  static/images/docs/zh-cn/alerting/alerting_policy_workload_level_notification_rule.png
Labels: dco-signoff: yes, lgtm, size/M

#937 Translated alerting-message-zh.
  content/zh/docs/project-user-guide/alerting/alerting-message.md
  static/images/docs/zh-cn/alerting/alerting_message_workload_level_comment.png
  static/images/docs/zh-cn/alerting/alerting_message_workload_level_detail.png
  static/images/docs/zh-cn/alerting/alerting_message_workload_level_list.png
  static/images/docs/zh-cn/alerting/alerting_message_workload_level_notification.png
  static/images/docs/zh-cn/alerting/alerting_message_workload_level_policy.png
Labels: dco-signoff: yes, lgtm, size/M

#939 fix format
  content/zh/docs/project-user-guide/alerting/alerting-policy.md
Labels: dco-signoff: yes

#941 Upgrade Overview ZH updated.
  content/zh/docs/upgrade/overview.md
Labels: dco-signoff: yes, lgtm, size/S

#940 Persistent Volumes and Storage Classes translated
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/cluster-management-select.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/create-custom-storage-class.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/create-storage-class-basic-info.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/create-storage-class-settings.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/create-storage-class-storage-system.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/custom-storage-class.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/storage-class.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/storage-system.PNG
  static/images/docs/zh-cn/cluster-administration/persistent-volumes-and-storage-classes/storage-volume-qingcloud.PNG
Labels: dco-signoff: yes, lgtm, size/L

#942 Upgrade with KubeKey ZH updated.
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: dco-signoff: no, size/M

#943 Upgrade with ks-installer ZH updated.
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
Labels: dco-signoff: yes, size/M

#944 fix wording in API doc
  content/en/docs/api-reference/api-docs.md
  content/zh/docs/api-reference/api-docs.md
  static/images/docs/api-reference/kubesphere-api/ks-apiserver.png
Labels: dco-signoff: yes

#946 Air-Gapped Upgrade with KubeKey translated.
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: dco-signoff: yes, lgtm, size/L

#945 Translated introduction-zh.
  content/zh/docs/project-user-guide/custom-application-monitoring/introduction.md
Labels: dco-signoff: yes, lgtm, size/M

#947 Air-Gapped Upgrade with ks-installer translated.
  content/zh/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
  static/images/docs/zh-cn/upgrade/air-gapped-upgrade-with-ks-installer/kubesphere-login.PNG
Labels: dco-signoff: yes, lgtm, size/M

#948 Changes after Upgrade & Index translated.
  content/zh/docs/upgrade/_index.md
  content/zh/docs/upgrade/what-changed.md
Labels: dco-signoff: yes, lgtm, size/S

#928 add popular docs link
  assets/scss/docs.scss
  content/en/docs/_index.md
  i18n/zh.yaml
  layouts/docs/list.html
  static/images/docs/22-hover.svg
  static/images/docs/22.svg
  static/images/docs/26.svg
Labels: dco-signoff: yes, size/L

#949 Update doc
  content/en/docs/_index.md
Labels: dco-signoff: yes

#950 Update cn doc
  content/zh/docs/_index.md
Labels: dco-signoff: yes

#951 fix a link
  content/zh/docs/pluggable-components/devops.md
Labels: dco-signoff: yes

#952 Update title
  content/en/docs/_index.md
  content/zh/docs/_index.md
Labels: dco-signoff: yes

#955 fix article use
  content/en/docs/pluggable-components/_index.md
  content/en/docs/pluggable-components/service-mesh.md
Labels: dco-signoff: yes

#956 fix issue 550
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#930 add add-on error faq
  content/en/docs/faq/installation/install-addon-through-yaml-using-kubekey.md
  content/zh/docs/faq/installation/install-addon-through-yaml-using-kubekey.md
Labels: dco-signoff: yes, size/M

#957 Update reference wording
  content/en/docs/api-reference/api-changes/logging.md
  content/en/docs/api-reference/api-changes/monitoring.md
  content/en/docs/api-reference/glossary.md
  content/zh/docs/api-reference/api-changes/logging.md
  content/zh/docs/api-reference/api-changes/monitoring.md
  content/zh/docs/api-reference/glossary.md
Labels: dco-signoff: yes, size/L

#958 Update inde
  content/en/docs/api-reference/_index.md
  content/en/docs/api-reference/api-docs.md
  content/en/docs/api-reference/glossary.md
  content/en/docs/faq/_index.md
  content/zh/docs/api-reference/_index.md
  content/zh/docs/api-reference/api-docs.md
  content/zh/docs/api-reference/glossary.md
  content/zh/docs/faq/_index.md
Labels: dco-signoff: yes, size/M

#959 Deploy etcd translated.
  content/zh/docs/application-store/built-in-apps/etcd-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/deploy-etcd.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/deployment-location.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/etcd-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/etcd-command.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/etcd-running.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/etcd-statefulset.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/etcd-terminal.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/project-overview.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-etcd-on-ks/specify-volume.PNG
Labels: dco-signoff: yes, size/M

#831 Add project quota and limit range ranges
  content/en/docs/project-administration/container-limit-ranges.md
  content/en/docs/project-administration/project-quota.md
  content/en/docs/workspace-administration/project-quotas.md
  static/images/docs/project-administration/container-limit-ranges/change-limit-range.jpg
  static/images/docs/project-administration/container-limit-ranges/default-limit-range.jpg
  static/images/docs/project-administration/container-limit-ranges/limit-ranges.jpg
  static/images/docs/project-administration/container-limit-ranges/view-limit-ranges.jpg
  static/images/docs/project-administration/container-limit-ranges/workload-values.jpg
  static/images/docs/workspace-administration/project-quotas/edit-quotas.jpg
  static/images/docs/workspace-administration/project-quotas/project-quotas.jpg
  static/images/docs/workspace-administration/project-quotas/resrouce-quotas.jpg
  static/images/docs/workspace-administration/project-quotas/set-other-resouce-quotas.jpg
  static/images/docs/workspace-administration/project-quotas/set-project-quotas.jpg
Labels: dco-signoff: yes, size/L

#775 Update project network isolation
  content/en/docs/project-administration/project-network-isolation.md
  content/zh/docs/project-administration/project-network-isolation.md
  static/images/docs/project-administration/network-isolation-off.png
  static/images/docs/project-administration/network-isolation-on.png
  static/images/docs/project-administration/project-network-isolation/egress-CIDR-added.jpg
  static/images/docs/project-administration/project-network-isolation/egress-CIDR.jpg
  static/images/docs/project-administration/project-network-isolation/egress-rule-added.jpg
  static/images/docs/project-administration/project-network-isolation/engress-rule.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-CIDR.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-cidr-set.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-rule-added.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-rule.jpg
  static/images/docs/project-administration/project-network-isolation/isolation-off.jpg
  static/images/docs/project-administration/project-network-isolation/project-network-isolation.jpg
Labels: dco-signoff: no, size/L

#961 minor typo fix
  content/en/docs/project-administration/project-network-isolation.md
Labels: dco-signoff: yes

#938 Update resource requirement in multicluster guide
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
Labels: dco-signoff: yes, size/S

#962 Update cn resource requirements
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/zh/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
Labels: dco-signoff: yes

#887 Rewrite add and delete nodes
  content/en/docs/installing-on-linux/cluster-operation/_index.md
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
  static/images/docs/installing-on-linux/add-and-delete-nodes/delete-nodes/cordon.jpg
Labels: dco-signoff: yes, size/L

#964 Port
  content/en/docs/installing-on-linux/introduction/port-firewall.md
Labels: dco-signoff: yes

#966 Update install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: approved, dco-signoff: no, lgtm, size/XS

#934 Add scaling blog using KubeKey
  content/en/blogs/scale-kubernetes-cluster-using-kubekey.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#970 Update KubeSphere introduction
  content/en/docs/introduction/advantages.md
  content/en/docs/introduction/architecture.md
  content/en/docs/introduction/ecosystem.md
  content/en/docs/introduction/features.md
  content/en/docs/introduction/scenarios.md
  content/en/docs/introduction/what's-new-in-v3.0.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/zh/blogs/kubesphere-3.0.0-ga-announcement.md
  content/zh/docs/introduction/advantages.md
  content/zh/docs/introduction/architecture.md
  content/zh/docs/introduction/ecosystem.md
  content/zh/docs/introduction/features.md
  content/zh/docs/introduction/scenarios.md
  content/zh/docs/introduction/what's-new-in-v3.0.md
  content/zh/docs/introduction/what-is-kubesphere.md
  static/images/docs/introduction/kubesphere-ecosystem/kubesphere-ecosystem.png
  static/images/docs/introduction/what-is-kubesphere/architecture-1.png
  static/images/docs/introduction/what-is-kubesphere/cncf-landscape.png
  static/images/docs/zh-cn/introduction/kubesphere-ecosystem/kubesphere-ecosystem.png
  static/images/docs/zh-cn/introduction/what-is-kubesphere/cncf-landscape.png
  static/images/docs/zh-cn/introduction/what-is-kubesphere/feature-overview.png
Labels: dco-signoff: yes, size/L

#969 Update how-to-get-real-ip-in-pod.md
  content/zh/blogs/how-to-get-real-ip-in-pod.md
Labels: dco-signoff: yes, lgtm, size/XS

#968 Deploy MinIO translated.
  content/zh/docs/application-store/built-in-apps/minio-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/config-file.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/deploy-minio-2.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/deploy-minio.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/edit-internet-access.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-app.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-browser-interface.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-browser.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-deploy.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-detail.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-in-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/minio-in-list.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/nodeport.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/port-exposed.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-minio-on-ks/template-list.PNG
Labels: dco-signoff: yes, lgtm, size/M

#971 add banner
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/blogs/scale-kubernetes-cluster-using-kubekey.md
Labels: dco-signoff: yes

#965 Deploy Memcached translated.
  content/zh/docs/application-store/built-in-apps/memcached-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/deploying-memcached.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/deployment-confirm.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/edit-config.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/in-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/memcached-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/memcached-port-pod.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/memcached-running.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-memcached-on-ks/memcached-service.PNG
Labels: dco-signoff: yes, size/M

#972 Deploy MongoDB translated.
  content/zh/docs/application-store/built-in-apps/mongodb-app.md
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署mongoDB.md
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/confirm-deployment.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/deploy-mongodb.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/mongodb-in-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/mongodb-running.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/mongodb-service-terminal.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/mongodb-service.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/mongodb-terminal.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/mongodb-app/set-app-configuration.PNG
Labels: dco-signoff: yes, size/L

#973 Deploy NGINX translated.
  content/zh/docs/application-store/built-in-apps/nginx-app.md
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署Nginx.md
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/access-nginx.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/confirm-deployment.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/deploy-nginx.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/edit-config-nginx.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/edit-internet-access.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/exposed-port.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/manifest-file.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/nginx-in-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/nginx-running.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/nginx-service.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/nginx-app/nodeport.PNG
Labels: dco-signoff: no, size/L

#974 Deploy Redis translated.
  content/zh/docs/application-store/built-in-apps/redis-app.md
  content/zh/docs/application-store/built-in-apps/在kubesphere中部署Redis.md
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/access-redis.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/config-redis.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/confirm-deployment.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/deploy-redis.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/redis-in-app-store.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/redis-running.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/redis-terminal.PNG
  static/images/docs/zh-cn/appstore/built-in-apps/redis-app/use-redis.PNG
Labels: dco-signoff: no, size/L

#975 Helm Developer Guide translated.
  content/en/docs/application-store/app-developer-guide/helm-developer-guide.md
  content/zh/docs/application-store/app-developer-guide/_index.md
  content/zh/docs/application-store/app-developer-guide/helm-developer-guide.md
Labels: dco-signoff: yes, size/M

#977 add use case
  content/zh/docs/introduction/scenarios.md
  static/images/docs/zh-cn/introduction/use-cases/sonarqube.png
  static/images/docs/zh-cn/introduction/use-cases/中央控制平面.png
  static/images/docs/zh-cn/introduction/use-cases/流水线.png
  static/images/docs/zh-cn/introduction/use-cases/灰度发布.jpg
  static/images/docs/zh-cn/introduction/use-cases/集群监控.jpg
  static/images/docs/zh-cn/introduction/use-cases/高可用.png
Labels: dco-signoff: yes

#978 fix typos
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: dco-signoff: yes

#981 App Store Index updated.
  content/zh/docs/application-store/_index.md
Labels: dco-signoff: yes, size/S

#976 Helm Specifications translated.
  content/en/docs/application-store/app-developer-guide/helm-specification.md
  content/zh/docs/application-store/app-developer-guide/helm-specification.md
Labels: dco-signoff: no, size/L

#980 add Ack
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack.md
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-cluster.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-components.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-kubeconfig.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-lb-ip.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-lb.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-template.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-worker-config.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ack-worker-password.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/create-ack-cluster.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ks-UI.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ks-console-service.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/ks-console.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/network-and-apiserver.png
  static/images/docs/zh-cn/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack/standard-template.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#982 Project Quotas translated.
  content/zh/docs/workspace-administration/project-quotas.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/project-quotas/edit-quotas.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/project-quotas/project-quotas.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/project-quotas/resource-quotas.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/project-quotas/set-other-resource-quotas.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/project-quotas/set-project-quotas.PNG
Labels: size/M

#984 Workspace Network Isolation translated.
  content/zh/docs/workspace-administration/workspace-network-isolation.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-network-isolation/workspace-isolation.PNG
Labels: size/M

#985 Update glossary
  content/en/docs/api-reference/glossary.md
  content/en/docs/workspace-administration/workspace-network-isolation.md
  content/zh/docs/api-reference/glossary.md
Labels: size/L

#983 Container Limit Ranges translated.
  content/zh/docs/project-administration/container-limit-ranges.md
  static/images/docs/zh-cn/project-administration/container-limit-ranges/change-limit-ranges.PNG
  static/images/docs/zh-cn/project-administration/container-limit-ranges/default-limit-range.PNG
  static/images/docs/zh-cn/project-administration/container-limit-ranges/limit-ranges.PNG
  static/images/docs/zh-cn/project-administration/container-limit-ranges/view-limit-ranges.PNG
  static/images/docs/zh-cn/project-administration/container-limit-ranges/workload-values.PNG
Labels: size/M

#987 Add upload apps to KubeSphere github
  content/en/docs/workspace-administration/app-repository/upload-app-to-public-repository.md
Labels: approved, lgtm, size/M

#810 add unbind cluster guide
  content/en/docs/multicluster-management/unbind-cluster.md
  content/zh/docs/multicluster-management/unbind-cluster.md
  static/images/docs/multicluster-management/unbind-a-cluster/clusters-management.jpg
  static/images/docs/multicluster-management/unbind-a-cluster/unbind-cluster.jpg
Labels: approved, dco-signoff: yes, lgtm, size/M

#988 Add kubesphere github app upload cn guide and update index
  content/en/docs/workspace-administration/_index.md
  content/en/docs/workspace-administration/app-repository/upload-app-to-public-repository.md
  content/en/docs/workspace-administration/role-and-member-management.md
  content/zh/docs/workspace-administration/app-repository/upload-app-to-public-repository.md
  content/zh/docs/workspace-administration/role-and-member-management.md
Labels: size/M

#989 fix typo
  content/en/docs/access-control-and-account-management/oauth2.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/multicluster-management/unbind-cluster.md
Labels: size/S

#993 Project Administration Index translated.
  content/zh/docs/project-administration/_index.md
Labels: size/S

#995 Workspace Administration Index translated.
  content/zh/docs/workspace-administration/_index.md
Labels: size/M

#999 Monitoring and Index translated.
  content/zh/docs/api-reference/_index.md
  content/zh/docs/api-reference/api-changes/monitoring.md
Labels: size/M

#997 Reference/Logging translated.
  content/zh/docs/api-reference/api-changes/_index.md
  content/zh/docs/api-reference/api-changes/logging.md
Labels: size/S

#990 change image
  static/images/home/applications2.png
Labels: approved, lgtm, size/XS

#1002 Adjust the layout in logging.md
  content/zh/docs/faq/observability/logging.md
Labels: lgtm, size/XS

#996 KubeSphere API translated.
  content/zh/docs/api-reference/api-docs.md
Labels: size/M

#1000 fix header
  layouts/_default/baseof.html
  layouts/docs/single.html
  layouts/partials/content.html
  layouts/partials/footer.html
Labels: approved, lgtm, size/S

#1007 fix header in doc page
  layouts/docs/single.html
  layouts/partials/footer.html
Labels: approved, lgtm, size/S

#991 Project Network Isolation translated.
  content/zh/docs/project-administration/project-network-isolation.md
  static/images/docs/zh-cn/project-administration/project-network-isolation/egress-CIDR-added.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/egress-CIDR.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/egress-rule-added.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/egress-rule.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/ingress-CIDR.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/ingress-cidr-set.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/ingress-rule-added.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/ingress-rule.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/isolation-off.PNG
  static/images/docs/zh-cn/project-administration/project-network-isolation/project-network-isolation.PNG
Labels: size/L

#1009 Adjust the layout in dockershim-out-of-kubernetes.md
  content/zh/blogs/dockershim-out-of-kubernetes.md
Labels: approved, lgtm, size/M

#998 Add a blog for using kubekey to add master nodes for HA
  content/en/blogs/add-master-for-ha-using-kubekey.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
Labels: approved, lgtm, size/L

#1010 update doc menu event
  layouts/docs/single.html
Labels: approved, lgtm, size/XS

#1005 DevOps Overview translated.
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list.PNG
Labels: lgtm, size/M

#1006 Unbind a Cluster translated.
  content/zh/docs/multicluster-management/unbind-cluster.md
  static/images/docs/zh-cn/multicluster-management/unbind-a-cluster/cluster-management.PNG
  static/images/docs/zh-cn/multicluster-management/unbind-a-cluster/unbind-cluster.PNG
Labels: lgtm, size/M

#1013 Update log collection introduction wording
  content/en/docs/cluster-administration/cluster-settings/log-collections/_index.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  static/images/docs/cluster-administration/cluster-settings/log-collections/introduction/change-status.png
  static/images/docs/cluster-administration/cluster-settings/log-collections/introduction/log-collections-events.png
  static/images/docs/cluster-administration/cluster-settings/log-collections/introduction/log-collections.png
  static/images/docs/cluster-administration/cluster-settings/log-collections/introduction/more.png
Labels: size/M

#1012 how to add existing k8s namespaces to a workspace faq
  content/en/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  content/zh/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  static/images/docs/faq/access-control-and-account-management/add-exisiting-namespaces-to-a-kubesphere-workspace/assign-workspace.jpg
  static/images/docs/faq/access-control-and-account-management/add-exisiting-namespaces-to-a-kubesphere-workspace/project-page.jpg
  static/images/docs/faq/access-control-and-account-management/add-exisiting-namespaces-to-a-kubesphere-workspace/select-workspace.jpg
  static/images/docs/faq/access-control-and-account-management/add-exisiting-namespaces-to-a-kubesphere-workspace/user-projects.jpg
Labels: approved, lgtm, size/L

#1024 Build and Deploy a Go Project translated.
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-dockerhub-id.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-kubeconfig.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-pipeline-2.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/credential-docker-create.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/docker-image-1.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/docker-image-2.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/dockerhub-create-token.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/dockerhub-settings.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/dockerhub-token-copy.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/dockerhub-token-ok.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/pipeline-running.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/run-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/set-pipeline-name.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/view-deployment.PNG
Labels: lgtm, size/M

#1017 Add platform settings info
  content/en/docs/cluster-administration/platform-settings.md
  content/zh/docs/cluster-administration/platform-settings.md
Labels: approved, lgtm, size/S

#1025 Add kafka receiver cn
  content/en/docs/cluster-administration/cluster-settings/log-collections/add-kafka-as-receiver.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-kafka-as-receiver.md
Labels: size/M

#1018 Create Pipeline with Graphical Editing Panel translated.
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/overview/sonarqube-result-detail.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/access-service.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/add-artifact-stage.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/add-nested-step-2.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/add-nested-step.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/add-parameter.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/artifact-info.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/basic-info.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/build-and-push-image.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/code-analysis-stage.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/complete.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/container.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/create-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/credential-list.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/deploy-to-dev.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/docker-credential.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/dockerhub-image.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/download-artifact.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/edit-panel.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/edit-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/enter-repo-url.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/first-stage-set.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/graphical-panel.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/input-message.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/inspect-logs.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/kubernetesDeploy.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/login-docker-command.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/maven-container.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/maven-set.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/nested-step-maven.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/nested-step.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/pipeline-done.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/pipeline-list.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/pipeline-successful.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/push-snapshot-to-docker.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/run-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/service-exposed.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/shell-command.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/shell.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonar-ready.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonar-token.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonar.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonarqube-credentials.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonarqube-result-detail.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/sonarqube-shell-new.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/timeout.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/unit-test-set.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/unit-test.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/view-deployment.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/waitforqualitygate.PNG
Labels: lgtm, size/L

#1034 Add Kubernetes Namespace to KubeSphere Workspace translated.
  content/en/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  content/zh/docs/faq/access-control/add-kubernetes-namespace-to-kubesphere-workspace.md
  static/images/docs/zh-cn/faq/access-control-and-account-management/add-kubernetes-namespace-to-kubesphere-workspace/assign-workspace.PNG
  static/images/docs/zh-cn/faq/access-control-and-account-management/add-kubernetes-namespace-to-kubesphere-workspace/project-page.PNG
  static/images/docs/zh-cn/faq/access-control-and-account-management/add-kubernetes-namespace-to-kubesphere-workspace/select-workspace.PNG
  static/images/docs/zh-cn/faq/access-control-and-account-management/add-kubernetes-namespace-to-kubesphere-workspace/user-projects.PNG
Labels: size/M

#1041 Add faq cn
  content/en/docs/faq/_index.md
  content/en/docs/faq/access-control/session-timeout.md
  content/en/docs/faq/observability/byop.md
  content/zh/docs/faq/_index.md
  content/zh/docs/faq/access-control/session-timeout.md
  content/zh/docs/faq/console/console-web-browser.md
  content/zh/docs/faq/observability/byop.md
Labels: size/L

#1027 lesson 1_container history brief
  content/zh/learn/level_2/Container_foundations/lesson_1/_index.md
  content/zh/learn/level_2/Container_foundations/lesson_1/content.md
  content/zh/learn/level_2/Container_foundations/lesson_1/video.md
  content/zh/learn/level_2/Container_foundations/lesson_2/_index.md
  content/zh/learn/level_2/Container_foundations/lesson_2/content.md
  content/zh/learn/level_2/Container_foundations/lesson_2/video.md
Labels: approved, lgtm, size/M

#1048 Deploy Apps in Multi-cluster Project Using Jenkinsfile translated.
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-dockerhub-id.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-kubeconfig.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-pipeline-2.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/credential-docker-create.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/dockerhub-create-token.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/dockerhub-settings.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/dockerhub-token-copy.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/dockerhub-token-ok.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/set-pipeline-name.PNG
Labels: lgtm, size/M

#1047 Canary Release translated.
  content/zh/docs/project-user-guide/grayscale-release/canary-release.md
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-0.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-3.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-4.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-5.gif
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-6.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-job.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/create-canary-release.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/deployment-list-1.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/job-offline.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/set-task-name.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/take-over-traffic.PNG
Labels: size/M
