Repository kubesphere/website, pull requests merged in 2021-07, with the labels that each got.

#1757 update the title, landing page, and footer
  content/en/_index.md
  content/en/docs/_index.md
  content/zh/_index.md
  content/zh/docs/_index.md
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: approved, lgtm, size/L

#1774 add a new blog of Serverless-DevOps-KubeSphere
  content/zh/blogs/Serverless-DevOps-KubeSphere.md
Labels: approved, lgtm, size/L

#1749 Content SEO changes and interlinks
  content/en/blogs/argo-cd-a-tool-for-devops.md
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/blogs/multi-cluster-deployment.md
  content/en/docs/project-administration/container-limit-ranges.md
  content/en/docs/project-user-guide/grayscale-release/blue-green-deployment.md
  content/en/docs/workspace-administration/project-quotas.md
  content/en/service-mesh/_index.md
Labels: approved, lgtm, size/M

#1776 Update Doc: Image Registries
  content/en/docs/project-user-guide/configuration/image-registry.md
  content/zh/docs/project-user-guide/configuration/image-registry.md
  static/images/docs/project-user-guide/configurations/image-registries/create-secret.jpg
  static/images/docs/project-user-guide/configurations/image-registries/create-secret.png
  static/images/docs/project-user-guide/configurations/image-registries/harbor-address.jpg
  static/images/docs/project-user-guide/configurations/image-registries/harbor-address.png
  static/images/docs/project-user-guide/configurations/image-registries/image-registry-info.jpg
  static/images/docs/project-user-guide/configurations/image-registries/image-registry-info.png
  static/images/docs/project-user-guide/configurations/image-registries/open-dashboard.jpg
  static/images/docs/project-user-guide/configurations/image-registries/open-dashboard.png
  static/images/docs/project-user-guide/configurations/image-registries/use-image-registry.jpg
  static/images/docs/project-user-guide/configurations/image-registries/use-image-registry.png
  static/images/docs/project-user-guide/configurations/image-registries/validate-registry-address.jpg
  static/images/docs/project-user-guide/configurations/image-registries/validate-registry-address.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/create-secret.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/create-secret.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/harbor-address.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/harbor-address.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/image-registry-info.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/image-registry-info.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/open-dashboard.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/open-dashboard.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/use-image-registry.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/use-image-registry.png
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/validate-registry-address.jpg
  static/images/docs/zh-cn/project-user-guide/configurations/image-registries/validate-registry-address.png
Labels: approved, lgtm, size/M

#1773 Update Doc: Kubernetes HPA on KubeSphere
  content/en/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  content/zh/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/busybox.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/cancel-hpa.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/cpu-request.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-deployment.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/create-service.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/deployment-name.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/horizontal-pod-autoscaling.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-deployment.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/hpa-parameters.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-decrease.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/pods-increase.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/service-name.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/start-command.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/stateless-service.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/target-cpu-utilization.png
  static/images/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling/three-dots.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/horizontal-pod-autoscaling/three-dots.png
Labels: lgtm, size/XS

#1772 Update Doc: Container Image Settings
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
  static/images/docs/project-user-guide/application-workloads/container-image-settings/add-image.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/container-security-context.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/cube-icon.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/env-variables.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/exec-check.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/health-checker.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/http-check.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/image-policy.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/minus-icon.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/plus-icon.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/pod-replicas.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/requests-limits.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/start-command.png
  static/images/docs/project-user-guide/application-workloads/container-image-settings/tcp-port.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/cube-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/minus-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/container-image-settings/plus-icon.png
Labels: approved, lgtm, size/M

#1771 Update Doc: CronJobs
  content/en/docs/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/project-user-guide/application-workloads/cronjobs.md
  static/images/docs/project-user-guide/application-workloads/cronjobs/basic-info.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/click-create.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/container-log-1.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/container-log-2.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-action.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-create-basic-info.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-list-new.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob-list.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/cronjob.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/down-arrow.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/events.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/exe-records.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/execution-record.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/finish-image.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/image-set.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/input-busybox.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-detail-page.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-detail.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-list.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/job-records.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/jobs.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/log-detail.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/metadata.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/modify.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/set-image.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/start-command.jpg
  static/images/docs/project-user-guide/application-workloads/cronjobs/start-command.png
  static/images/docs/project-user-guide/application-workloads/cronjobs/view-log.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/down-arrow.png
Labels: lgtm, size/M

#1769 Update Doc: Jobs
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  static/images/docs/project-user-guide/application-workloads/jobs/add-container-image-job.png
  static/images/docs/project-user-guide/application-workloads/jobs/basic-info.png
  static/images/docs/project-user-guide/application-workloads/jobs/click-create.png
  static/images/docs/project-user-guide/application-workloads/jobs/container-log-check.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/container-log.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/create-job.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/down-arrow.png
  static/images/docs/project-user-guide/application-workloads/jobs/env-variable.png
  static/images/docs/project-user-guide/application-workloads/jobs/env-variables.png
  static/images/docs/project-user-guide/application-workloads/jobs/events.png
  static/images/docs/project-user-guide/application-workloads/jobs/exe-records.png
  static/images/docs/project-user-guide/application-workloads/jobs/execution-record.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/execution-records.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-container-settings.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-basic-info.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-create-job-settings.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-in-list.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-list-new.png
  static/images/docs/project-user-guide/application-workloads/jobs/job-operation.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/job-settings.png
  static/images/docs/project-user-guide/application-workloads/jobs/log.png
  static/images/docs/project-user-guide/application-workloads/jobs/metadata.png
  static/images/docs/project-user-guide/application-workloads/jobs/modify-job.png
  static/images/docs/project-user-guide/application-workloads/jobs/res-status.png
  static/images/docs/project-user-guide/application-workloads/jobs/resource-status.png
  static/images/docs/project-user-guide/application-workloads/jobs/restart-policy.png
  static/images/docs/project-user-guide/application-workloads/jobs/set-image.png
  static/images/docs/project-user-guide/application-workloads/jobs/start-command-job.jpg
  static/images/docs/project-user-guide/application-workloads/jobs/start-command.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/jobs/down-arrow.png
Labels: lgtm, size/M

#1766 Update Doc: Services
  content/en/docs/project-user-guide/application-workloads/services.md
  content/zh/docs/project-user-guide/application-workloads/services.md
  static/images/docs/project-user-guide/application-workloads/services/advanced-settings.png
  static/images/docs/project-user-guide/application-workloads/services/click-create.png
  static/images/docs/project-user-guide/application-workloads/services/click-dots.png
  static/images/docs/project-user-guide/application-workloads/services/detail-page.png
  static/images/docs/project-user-guide/application-workloads/services/display.png
  static/images/docs/project-user-guide/application-workloads/services/enter-name.png
  static/images/docs/project-user-guide/application-workloads/services/events.png
  static/images/docs/project-user-guide/application-workloads/services/hide.png
  static/images/docs/project-user-guide/application-workloads/services/metadata.png
  static/images/docs/project-user-guide/application-workloads/services/refresh.png
  static/images/docs/project-user-guide/application-workloads/services/resource-status.png
  static/images/docs/project-user-guide/application-workloads/services/see-pod.png
  static/images/docs/project-user-guide/application-workloads/services/service-types.png
  static/images/docs/project-user-guide/application-workloads/services/set-image.png
  static/images/docs/project-user-guide/application-workloads/services/set-volumes.png
  static/images/docs/project-user-guide/application-workloads/services/stateless-service.png
  static/images/docs/project-user-guide/application-workloads/services/three-dots.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/services/three-dots.png
Labels: lgtm, size/M

#1763 Update Doc: DaemonSets
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/daemonsets.md
  static/images/docs/project-user-guide/application-workloads/daemonsets/advanced-settings.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/basic-info.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/click-add-image.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/click-create.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/click-dots.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/click-more.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/click-time-interval.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/detail-page.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/enter-image.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/env-variables.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/events.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/metadata.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/monitoring.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/mount-volumes.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/pod-detail.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/refresh.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/resource-status.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/set-requests-limits.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/start-refresh.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/stop-refresh.png
  static/images/docs/project-user-guide/application-workloads/daemonsets/three-dots.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/daemonsets/three-dots.png
Labels: approved, lgtm, size/M

#1758 Update Doc: Deployments
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  static/images/docs/project-user-guide/application-workloads/deployments/add-container-image.png
  static/images/docs/project-user-guide/application-workloads/deployments/advanced-settings.png
  static/images/docs/project-user-guide/application-workloads/deployments/click-more.png
  static/images/docs/project-user-guide/application-workloads/deployments/click-to-modify.png
  static/images/docs/project-user-guide/application-workloads/deployments/deploy-details.png
  static/images/docs/project-user-guide/application-workloads/deployments/deployments.png
  static/images/docs/project-user-guide/application-workloads/deployments/deployments_autorefresh_start.png
  static/images/docs/project-user-guide/application-workloads/deployments/deployments_autorefresh_stop.png
  static/images/docs/project-user-guide/application-workloads/deployments/deployments_refresh.png
  static/images/docs/project-user-guide/application-workloads/deployments/down-arrow.png
  static/images/docs/project-user-guide/application-workloads/deployments/enter-info.png
  static/images/docs/project-user-guide/application-workloads/deployments/enter-nginx.png
  static/images/docs/project-user-guide/application-workloads/deployments/env-variables.png
  static/images/docs/project-user-guide/application-workloads/deployments/events.png
  static/images/docs/project-user-guide/application-workloads/deployments/meta-data.png
  static/images/docs/project-user-guide/application-workloads/deployments/minus-icon.png
  static/images/docs/project-user-guide/application-workloads/deployments/monitoring.png
  static/images/docs/project-user-guide/application-workloads/deployments/mount-volumes.png
  static/images/docs/project-user-guide/application-workloads/deployments/plus-icon.png
  static/images/docs/project-user-guide/application-workloads/deployments/pods.png
  static/images/docs/project-user-guide/application-workloads/deployments/resource-status.png
  static/images/docs/project-user-guide/application-workloads/deployments/set-replicas.png
  static/images/docs/project-user-guide/application-workloads/deployments/set-requests-limits.png
  static/images/docs/project-user-guide/application-workloads/deployments/three-dots.png
  static/images/docs/project-user-guide/application-workloads/deployments/time-interval.png
  static/images/docs/project-user-guide/application-workloads/deployments/up-arrow.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/down-arrow.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/minus-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/plus-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/three-dots.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/deployments/up-arrow.png
Labels: lgtm, size/M

#1762 Update Doc: StatefulSets
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  static/images/docs/project-user-guide/application-workloads/statefulsets/advanced-settings.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/click-add-image.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/click-create.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/click-dots.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/click-more.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/detail-page.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/down-arrow.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/enter-name.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/enter-nginx.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/env-variables.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/events.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/metadata.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/minus-icon.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/monitoring.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/mount-volume.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/plus-icon.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/pod-detail.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/refresh.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/resource-status.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/set-interval.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/set-replicas.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/set-requests-limits.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/start-refresh.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/stop-refresh.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/three-dots.png
  static/images/docs/project-user-guide/application-workloads/statefulsets/up-arrow.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/down-arrow.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/minus-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/plus-icon.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/three-dots.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/statefulsets/up-arrow.png
Labels: approved, lgtm, size/M

#1781 add a new blog of WebAssembly
  content/zh/blogs/can-WebAssembly-replace-Docker.md
Labels: approved, lgtm, size/L

#1778 StatefulSets Doc Hot Fix
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
Labels: approved, lgtm, size/XS

#1788 update docs style
  assets/scss/docs.scss
Labels: size/XS

#1791 fix broken links on Chinese landingp page
  content/zh/_index.md
Labels: approved, lgtm, size/XS

#1797 add a piece of news: Announcing KubeSphere 3.1.0 on AWS Quick Start!
  content/en/news/_index.md
  content/en/news/kubesphere-310-on-aws-quick-start.md
  static/images/news/aws-quick-start/kubesphere-aws.png
  static/images/news/aws-quick-start/metering-and-billing.png
  static/images/news/aws-quick-start/qingcloud-kubesphere-architecture.png
  static/images/news/aws-quick-start/quick-start-cover.png
Labels: approved, lgtm, size/M

#1795 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-beijing.md
Labels: approved, lgtm, size/M

#1796 add a new blog of nebulagraph-kubesphere
  content/zh/blogs/nebulagraph-kubesphere.md
Labels: approved, lgtm, size/L

#1800 Fix minor wording error
  content/en/docs/workspace-administration/what-is-workspace.md
Labels: size/XS

#1802 Minor Update in Doc: Import an Aliyun ACK Cluster
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
Labels: size/S

#1804 Fix fail-loaded images
  content/zh/docs/toolbox/web-kubectl.md
Labels: approved, lgtm, size/XS

#1803 Update image icons
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
Labels: approved, lgtm, size/XS

#1782 add a new blog of Kubernetes-multicluster-KubeSphere
  content/zh/blogs/Kubernetes-multicluster-KubeSphere.md
Labels: approved, lgtm, size/L

#1799 add keywords and description for GPU-Operator.md
  content/zh/blogs/GPU-Operator.md
  content/zh/blogs/x509-certificate-exporter.md
Labels: approved, lgtm, size/L

#1812 add a new blog of WeDataSphere-KubeSphere
  content/zh/blogs/WeDataSphere-KubeSphere.md
Labels: approved, lgtm, size/L

#1807 add a new blog of cilium-kubesphere-kubernetes
  content/zh/blogs/cilium-kubesphere-kubernetes.md
Labels: approved, lgtm, size/L

#1813 Update 3.1.1 ZH and EN release notes.
  content/en/docs/release/release-v200.md
  content/en/docs/release/release-v201.md
  content/en/docs/release/release-v202.md
  content/en/docs/release/release-v210.md
  content/en/docs/release/release-v211.md
  content/en/docs/release/release-v300.md
  content/en/docs/release/release-v310.md
  content/en/docs/release/release-v311.md
  content/zh/docs/release/release-v200.md
  content/zh/docs/release/release-v201.md
  content/zh/docs/release/release-v202.md
  content/zh/docs/release/release-v210.md
  content/zh/docs/release/release-v211.md
  content/zh/docs/release/release-v300.md
  content/zh/docs/release/release-v310.md
  content/zh/docs/release/release-v311.md
Labels: approved, size/L

#1767 Update docs: Disk-log-collection
  content/en/docs/project-administration/disk-log-collection.md
  content/zh/docs/project-administration/disk-log-collection.md
  static/images/docs/project-administration/disk-log-collection/alpine-image.png
  static/images/docs/project-administration/disk-log-collection/arrow.png
  static/images/docs/project-administration/disk-log-collection/enable-disk-log-collection.png
  static/images/docs/project-administration/disk-log-collection/fuzzy-match.png
  static/images/docs/project-administration/disk-log-collection/log-icon.png
  static/images/docs/project-administration/disk-log-collection/log-toggle-switch.png
  static/images/docs/project-administration/disk-log-collection/run-command.png
  static/images/docs/project-administration/disk-log-collection/toggle-switch.png
  static/images/docs/project-administration/disk-log-collection/toolbox.png
  static/images/docs/project-administration/disk-log-collection/volume-example.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/alpine-image.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/arrow.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/fuzzy-match.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/log-icon.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/log-toggle-switch.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/run-command.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/toggle-switch.png
  static/images/docs/zh-cn/project-administration/disk-log-collection/toolbox.png
Labels: approved, lgtm, size/M

#1801 Update doc: Workspace-overview
  content/en/docs/workspace-administration/what-is-workspace.md
Labels: approved, lgtm, size/XS

#1761 Update docs: Querying-auditing-logs
  content/en/docs/toolbox/auditing/auditing-query.md
  content/zh/docs/toolbox/auditing/auditing-query.md
  static/images/docs/toolbox/auditing-log-detail.png
  static/images/docs/toolbox/auditing-operating-ui.jpg
  static/images/docs/toolbox/auditing-query/auditing-log-details.png
  static/images/docs/toolbox/auditing-query/auditing-logs.png
  static/images/docs/toolbox/auditing-query/services-created.png
  static/images/docs/toolbox/auditing-query/toolbox.png
  static/images/docs/zh-cn/toolbox/auditing/auditing-logs/审计日志详情.png
  static/images/docs/zh-cn/toolbox/auditing/auditing-logs/操作审计.png
  static/images/docs/zh-cn/toolbox/auditing/auditing-logs/过滤审计日志.png
Labels: approved, lgtm, size/L

#1819 update header
  assets/scss/header.scss
  config/_default/config.toml
  layouts/partials/header.html
  static/images/header/github-star-hover.svg
  static/images/header/github-star.svg
Labels: size/M

#1815 Update docs: Minimal KS on K8s-3.1.1
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  static/images/docs/quickstart/minimal-installation-on-k8s/kubesphere-components.png
  static/images/docs/zh-cn/quickstart/minimal-kubesphere-on-k8s/kubesphere-components-zh.png
  static/images/docs/zh-cn/quickstart/minimal-kubesphere-on-k8s/kubesphere-components.png
Labels: approved, lgtm, size/M

#1814 Update Docs: All-in-one installation on Linux-3.1.1
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  static/images/docs/quickstart/all-in-one-installation/Installation-complete.png
  static/images/docs/quickstart/all-in-one-installation/kubesphere-components.png
  static/images/docs/zh-cn/quickstart/all-in-one-on-linux/Installation-complete.png
  static/images/docs/zh-cn/quickstart/all-in-one-on-linux/service-components.jpg
  static/images/docs/zh-cn/quickstart/all-in-one-on-linux/service-components.png
Labels: approved, lgtm, priority/high, size/L

#1822 Change version v3.1.0 to v3.1.1
  content/en/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/quick-start/enable-pluggable-components.md
Labels: approved, lgtm, size/M

#1738 Updated metering-and-billing-zh
  content/zh/docs/toolbox/metering-and-billing/view-resource-consumption.md
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/cluster-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/deployment-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/hammer-icon.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-172746.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173129.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173324.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173415.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173717.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173839.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-173958.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174139.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174335.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/ksnip_20210508-174648.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/node-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/pod-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/project-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/workload-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/workspace-page.png
Labels: approved, lgtm, size/M

#1829 Update SonarQube Docs
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
Labels: lgtm, size/XS

#1825 Update Docs: View resource consumption
  content/en/docs/toolbox/metering-and-billing/view-resource-consumption.md
  content/zh/docs/toolbox/metering-and-billing/view-resource-consumption.md
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/cluster-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/node-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/pod-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/project-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/toolbox.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/workload-page.png
  static/images/docs/toolbox/metering-and-billing/view-resource-consumption/workspace-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/cluster-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/deployment-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/hammer-icon.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/node-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/pod-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/project-page.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/toolbox.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/view-resource-consumption/workspace-page.png
Labels: size/M

#1821 add a new case of zto
  content/zh/case/_index.md
  content/zh/case/zto.md
Labels: approved, lgtm, size/L

#1787 Update Doc: Binary to Image
  content/en/docs/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/advanced-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/advanced-settings.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/buidling-settings-2.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/buidling-settings-2.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/build-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/build-settings.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building-status.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building-status.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/building.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/container-settings.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/container-settings.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/create-service.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/create-service.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/deployment.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/deployment.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image-pushed.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image-pushed.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/docker-image.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/down-arrow.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/exposed-port.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/exposed-port.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-builder.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-builder.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-success.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/image-success.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-log.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-log.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-logs.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/inspect-logs.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job-created.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job-created.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/job.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/service.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/service.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/successful.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/successful.png
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/upload-artifact.jpg
  static/images/docs/project-user-guide/image-builder/b2i-publish-artifact-to-kubernetes/upload-artifact.png
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/down-arrow.png
Labels: size/M

#1786 Update Doc: Source to Image
  content/en/docs/project-user-guide/image-builder/source-to-image.md
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-log.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-log.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-settings.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/build-settings.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/building.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/building.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/copy-repo-code.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/copy-repo-code.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-finish.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-finish.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-service.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/create-service.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/deployment.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/deployment.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/docker-image.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/docker-image.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/down-arrow.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/fork-repository.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/fork-repository.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/health-checker.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/health-checker.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/job.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/job.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/select-lang-type.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/select-lang-type.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-detail.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-detail.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-settings.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service-settings.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/service.png
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/success-result.jpg
  static/images/docs/project-user-guide/image-builder/s2i-publish-app-without-dockerfile/success-result.png
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/down-arrow.png
Labels: size/M

#1785 Update Doc: Visualization-Querying
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/querying.md
  content/zh/docs/project-user-guide/custom-application-monitoring/visualization/querying.md
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/querying/query-editor-1.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/querying/query-editor-1.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/querying/query-editor-2.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/querying/query-editor-2.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/querying/graph-chart-edit.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/querying/text-chart-edit.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/querying/查询编辑器-图形图表.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/querying/查询编辑器-文本图表.jpg
Labels: size/XS

#1784 Update Doc: Visualization-Charts
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/panel.md
  content/zh/docs/project-user-guide/custom-application-monitoring/visualization/panel.md
  static/images/docs/project-user-guide/custom-application-monitoring/graph-chart.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/text-chart-1.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/charts/graph-chart.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/charts/text-chart.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/charts/graph-chart.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/charts/text-chart.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/charts/图形图表.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/charts/文本图表.jpg
Labels: size/XS

#1783 Update Doc: Visualization - Overview
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/overview.md
  content/zh/docs/project-user-guide/custom-application-monitoring/visualization/overview.md
  static/images/docs/project-user-guide/custom-application-monitoring/dashboard-layout-2.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/dashboard-layout-3.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/dashboard-layout-4.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/dashboard-layout.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/edit-dashboard.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/new-dashboard-2.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/new-dashboard.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/add-charts.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/create-dashboard.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/detail-column.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/down-arrow.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/edit-mode.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/edit-settings.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/plus-btn.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/six-dots.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/text-charts.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/up-arrow.png
  static/images/docs/project-user-guide/custom-application-monitoring/visualization/overview/view-charts.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/add-items.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/add-text-chart.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/chart-detail.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/create-dashboard.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/down-arrow.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/edit-dashboard.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/edit-yaml.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/middle-column.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/plus-btn.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/six-dots.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/up-arrow.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/中间栏.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/右侧详情栏.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/左侧文本栏.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/监控面板.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/编辑监控面板.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/面板配置文件.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/visualization/overview/顶部栏.jpg
Labels: size/M

#1831 Update Docs: Canary Release
  content/en/docs/project-user-guide/grayscale-release/canary-release.md
  content/zh/docs/project-user-guide/grayscale-release/canary-release.md
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-4.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-4.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-5.gif
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-5.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-6.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-6.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-job.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/canary-release-job.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/deployment-list-1.jpg
  static/images/docs/project-user-guide/grayscale-release/canary-release/deployment-list-1.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/three-dots.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/topology.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/tracing-kubesphere.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/tracing.png
  static/images/docs/project-user-guide/grayscale-release/canary-release/traffic-management.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release-6.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/canary-release_6.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/deployment-list-1.PNG
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/deployment-list_1.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/three-dots.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/topology.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/tracing-kubesphere.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/tracing.png
  static/images/docs/zh-cn/project-user-guide/grayscale-release/canary-release/traffic-management.png
Labels: size/S

#1827 Update App Number and Image in Relevant Docs
  content/en/docs/faq/applications/remove-built-in-apps.md
  content/en/docs/pluggable-components/app-store.md
  content/zh/docs/application-store/app-lifecycle-management.md
  content/zh/docs/faq/applications/remove-built-in-apps.md
  content/zh/docs/pluggable-components/app-store.md
  static/images/docs/appstore/application-lifecycle-management/app-store.png
  static/images/docs/enable-pluggable-components/kubesphere-app-store/app-store.png
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-store-1.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-store.png
  static/images/docs/zh-cn/enable-pluggable-components/kubesphere-app-store/app-store-page.png
Labels: size/S

#1792 Update Doc: Project Network Isolation
  content/en/docs/project-administration/project-network-isolation.md
  static/images/docs/project-administration/project-network-isolation/egress-CIDR-added.jpg
  static/images/docs/project-administration/project-network-isolation/egress-CIDR-added.png
  static/images/docs/project-administration/project-network-isolation/egress-CIDR.jpg
  static/images/docs/project-administration/project-network-isolation/egress-CIDR.png
  static/images/docs/project-administration/project-network-isolation/egress-rule-added.jpg
  static/images/docs/project-administration/project-network-isolation/egress-rule-added.png
  static/images/docs/project-administration/project-network-isolation/engress-rule.jpg
  static/images/docs/project-administration/project-network-isolation/engress-rule.png
  static/images/docs/project-administration/project-network-isolation/ingress-CIDR.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-CIDR.png
  static/images/docs/project-administration/project-network-isolation/ingress-cidr-set.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-cidr-set.png
  static/images/docs/project-administration/project-network-isolation/ingress-rule-added.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-rule-added.png
  static/images/docs/project-administration/project-network-isolation/ingress-rule.jpg
  static/images/docs/project-administration/project-network-isolation/ingress-rule.png
  static/images/docs/project-administration/project-network-isolation/isolation-off.jpg
  static/images/docs/project-administration/project-network-isolation/isolation-off.png
  static/images/docs/project-administration/project-network-isolation/project-network-isolation.jpg
  static/images/docs/project-administration/project-network-isolation/project-network-isolation.png
Labels: size/S

#1834 Update version v3.1.0 to v3.1.1
  content/en/common/kubernetes-versions.md
  content/en/common/system-requirements.md
  content/zh/common/kubernetes-versions.md
  content/zh/common/system-requirements.md
Labels: lgtm, size/M

#1833 Update docs: Change console language
  content/en/docs/faq/console/change-console-language.md
  content/zh/docs/faq/console/change-console-language.md
  static/images/docs/faq/kubesphere-web-console/change-console-language/basic-information-page.png
  static/images/docs/faq/kubesphere-web-console/change-console-language/check-mark.png
  static/images/docs/faq/kubesphere-web-console/change-console-language/user-settings.png
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/basic-information-page.png
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/check-mark.png
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/user-settings.png
Labels: lgtm, size/S

#1835 Add Docs : Deploy RadonDB PostgreSQL on Kubesphere
  content/en/docs/application-store/built-in-apps/radondb-postgresql-app.md
  content/zh/docs/application-store/built-in-apps/radondb-postgresql-app.md
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/confirm-deployment.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/deploy-radondb-postgresql.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/pods-running.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/project-overview.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-in-app-store.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-running.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-service-terminal.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-service.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-terminal.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/set-app-configuration.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/statefulset-monitoring.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/statefulsets-running.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/volume-status.png
  static/images/docs/appstore/built-in-apps/radondb-postgresql-app/volumes.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/confirm-deployment.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/deploy-radondb-postgresql.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/pods-running.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/project-overview.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-in-app-store.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-running.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-service-terminal.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-service.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/radondb-postgresql-terminal.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/set-app-configuration.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/statefulset-monitoring.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/statefulsets-running.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/volume-status.png
  static/images/docs/zh-cn/appstore/built-in-apps/radondb-postgresql-app/volumes.png
Labels: approved, lgtm, size/L

#1841 Update docs: Alerting policies
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  static/images/docs/project-user-guide/alerting/alerting-policies/rule-template.png
Labels: lgtm, size/XS

#1838 Update docs: Remove nodes
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
  content/zh/docs/installing-on-linux/cluster-operation/remove-nodes.md
  static/images/docs/installing-on-linux/add-and-delete-nodes/delete-nodes/cordon.jpg
  static/images/docs/installing-on-linux/add-and-delete-nodes/delete-nodes/cordon.png
  static/images/docs/zh-cn/installing-on-linux/add-and-delete-nodes/delete-nodes/cordon.png
Labels: lgtm, size/XS

#1756 Add workspace-quotas-zh
  content/zh/docs/workspace-administration/workspace-quotas.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-quotas/edit-workspace-quotas.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-quotas/slider.png
Labels: approved, lgtm, size/M

#1732 Translated install-ks-and-k3s-en
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  static/images/docs/zh-cn/installing-on-linux/on-premises/cluster-management.png
  static/images/docs/zh-cn/installing-on-linux/on-premises/service-components.png
Labels: approved, lgtm, size/M

#1840 Update docs: Cluster status monitoring
  content/en/docs/cluster-administration/cluster-status-monitoring.md
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  static/images/docs/cluster-administration/cluster-status-monitoring/apiserver-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cluster-resources-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cpu-load-average.png
  static/images/docs/cluster-administration/cluster-status-monitoring/cpu-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/disk-throughput.png
  static/images/docs/cluster-administration/cluster-status-monitoring/disk-usage.png
  static/images/docs/cluster-administration/cluster-status-monitoring/etcd-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/inode-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/iops.png
  static/images/docs/cluster-administration/cluster-status-monitoring/memory-utilization.png
  static/images/docs/cluster-administration/cluster-status-monitoring/netework-bandwidth.png
  static/images/docs/cluster-administration/cluster-status-monitoring/node-usage-ranking.png
  static/images/docs/cluster-administration/cluster-status-monitoring/platform.png
  static/images/docs/cluster-administration/cluster-status-monitoring/pod-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring/running-status.png
  static/images/docs/cluster-administration/cluster-status-monitoring/scheduler-monitoring.png
  static/images/docs/cluster-administration/cluster-status-monitoring/status.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/apiserver-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-nodes.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-resources-usage.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cluster-status-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/component-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cpu-load-average.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/cpu-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/disk-throughput.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/disk-usage.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/etcd-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/inode-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/iops.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/memory-utilization.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/netework-bandwidth.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/node-usage-ranking.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/physical-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/platform.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/pod-status.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/running-status.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/scheduler-monitorin.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/scheduler-monitoring.png
  static/images/docs/zh-cn/cluster-administration/cluster-status-monitoring/service-components-status.png
Labels: approved, lgtm, size/S

#1845 Remove docs: Notification manager
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/notification-manager.md
Labels: size/XL

#1848 Update Description in Multi-cluster FAQ Doc
  content/en/docs/faq/multi-cluster-management/manage-multi-cluster.md
Labels: lgtm, size/XS

#1849 Remove GitOps and Minor Updates
  content/en/_index.md
  content/en/devops/_index.md
  content/zh/devops/_index.md
Labels: lgtm, size/XS

#1826 Update docs: Deploy bookinfo
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-bookinfo.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-bookinfo1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-to-visit.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-to-visit1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/create-bookinfo.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/create-bookinfo1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/detail-page.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/detail-page1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/edit-icon.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/running.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/running1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-to-visit.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-to-visit1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/create-bookinfo.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/detail-page1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/details-page.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/edit-icon.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/running.png
Labels: approved, lgtm, size/M

#1809 Update Docs: Enable-billing-3.1.1
  content/en/docs/toolbox/metering-and-billing/enable-billing.md
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
  static/images/docs/toolbox/metering-and-billing/enable-billing/billing-dashboard.png
  static/images/docs/toolbox/metering-and-billing/enable-billing/metering-and-billing.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/enable-billing/metering-and-billing.png
  static/images/docs/zh-cn/toolbox/metering-and-billing/enable-billing/计量计费信息.png
Labels: approved, lgtm, size/L

#1851 Add a doc: Configure webhook notifications
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
Labels: approved, lgtm, size/M
