Repository kubesphere/website, pull requests merged in 2021-02, with the labels that each got.

#1045 Binary to Image translated.
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/advanced-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/build-binary.png
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/build-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/building-settings-2.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/container-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/create-service.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/image-builder.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/service-build.png
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/upload-artifact.PNG
Labels: lgtm, size/L

#1040 Monitor MySQL translated.
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/_index.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/check-if-mysql-running.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/click-deploy.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/click-next.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/create-mysql-dashboard.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-deploy-2.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-deploy.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-next.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-is-running.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/find-mysql-exporter.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/find-mysql.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/go-to-app-store.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/monitor-mysql-done.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-conn-params.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/navigate-to-custom-monitoring.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/save-mysql-template.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/set-servicemonitor-to-true.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/uncommet-mysqlrootpassword.PNG
Labels: lgtm, size/L

#1044 Monitor a Sample Web Application translated.
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/app-template-create.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-create-app-template.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-sample-web-1.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-upload-app-template-2.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-upload-app-template-4.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-upload-app-template-5.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-upload-app-template-6.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/click-upload-app-template.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-1.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-10.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-2.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-3.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-4.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-5.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-6.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-7.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-8.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/create-dashboard-9.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-1.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-2.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-3.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-4.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-5.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-sample-web-app/deploy-sample-web-6.PNG
Labels: lgtm, size/L

#1032 Source to Image translated.
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build-process.png
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/building.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/copy-repo-code.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/create-finish.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/create-service.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/fork-repository.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/health-checker.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/select-lang-type.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/service-settings.PNG
Labels: lgtm, size/L

#1052 fix command line error when importing aws eks
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: approved, size/XS

#1054 add some faq
  content/zh/docs/faq/access-control/cannot-login.md
  static/images/docs/faq/access-control-and-account-management/cannot-login/account-not-active.png
  static/images/docs/faq/access-control-and-account-management/cannot-login/wrong-password.png
Labels: lgtm, size/L

#1053 Mail Server ZH reviewed.
  content/zh/docs/cluster-administration/cluster-settings/mail-server.md
  static/images/docs/alerting/mail_server_config-zh.png
  static/images/docs/zh-cn/cluster-administration/cluster-settings/mail-server/mail-server-config.PNG
  static/images/docs/zh-cn/cluster-administration/cluster-settings/mail-server/mail_server_guide.png
Labels: lgtm, size/M

#1050 Cluster Shutdown and Restart ZH reviewed.
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/zh/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
Labels: lgtm, size/M

#1056 alter statement
  content/zh/docs/introduction/what-is-kubesphere.md
Labels: approved, lgtm, size/XS

#1055 Update wording of integrate harbor into pipelines guide
  content/en/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/advanced-settings.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/basic-info.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/create-credentials.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/create-pipeline.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/credentials-page.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/export-to-file.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/harbor-projects.jpg
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/robot-account-name.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/robot-account.png
  static/images/docs/devops-user-guide/tool-integration/integrate-harbor-into-pipeline/set-name.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-harbor-on-ks/harbor-dashboard.jpg
Labels: lgtm, size/L

#1058 KubeSphere Meetup 2020
  content/en/news/_index.md
  content/en/news/kubesphere-meetup-2020.md
  static/images/news/meetup-2020/1.pic.jpg
  static/images/news/meetup-2020/Snip20210201_10.png
  static/images/news/meetup-2020/Snip20210201_11.png
  static/images/news/meetup-2020/Snip20210201_12.png
  static/images/news/meetup-2020/Snip20210201_13.png
  static/images/news/meetup-2020/Snip20210201_14.png
  static/images/news/meetup-2020/Snip20210201_15.png
  static/images/news/meetup-2020/Snip20210201_16.png
  static/images/news/meetup-2020/Snip20210201_17.png
  static/images/news/meetup-2020/Snip20210201_18.png
  static/images/news/meetup-2020/Snip20210201_19.png
  static/images/news/meetup-2020/Snip20210201_20.png
  static/images/news/meetup-2020/Snip20210201_21.png
  static/images/news/meetup-2020/Snip20210201_22.png
  static/images/news/meetup-2020/Snip20210201_23.png
  static/images/news/meetup-2020/Snip20210201_24.png
  static/images/news/meetup-2020/Snip20210201_25.png
  static/images/news/meetup-2020/Snip20210201_26.png
  static/images/news/meetup-2020/Snip20210201_8.png
  static/images/news/meetup-2020/Snip20210201_9.png
Labels: lgtm, size/M

#1031 Add using keepalived and haproxy to create an HA cluster blog
  content/en/blogs/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: approved, lgtm, size/L

#1033 S2I complete
  content/zh/learn/level_1/lesson_6/_index.md
  content/zh/learn/level_1/lesson_6/content.md
  content/zh/learn/level_1/lesson_6/courseware.md
  content/zh/learn/level_1/lesson_6/examination.md
  content/zh/learn/level_1/lesson_6/video.md
Labels: approved, lgtm, size/M

#1022 learn : add lesson 27 files.
  content/zh/learn/level_2/lesson_27/_index.md
  content/zh/learn/level_2/lesson_27/content.md
  content/zh/learn/level_2/lesson_27/courseware.md
  content/zh/learn/level_2/lesson_27/video.md
Labels: approved, lgtm, size/M

#1057 Alerting Policy and Message ZH reviewed.
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/alerting-zh/alerting_message_node_level_comment.png
  static/images/docs/alerting-zh/alerting_policy_node_level_notification_rule.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_comment.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_detail.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_guide.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_list.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_notification.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-message-node-level/alerting_message_node_level_policy.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting-policy-node-level-detail-page.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_alerting_rule.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_basic_info.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_create.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_guide.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_monitoring_target.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alerting_policy_node_level_notification_rule.PNG
Labels: lgtm, size/L

#1060 Cluster Administration Index reviewed.
  content/en/docs/cluster-administration/_index.md
  content/zh/docs/cluster-administration/_index.md
Labels: lgtm, size/M

#1066 Integrate Harbor into Pipelines ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-integrate/harbor.md
  static/images/devops-zh/create-pipline-3.png
  static/images/devops-zh/edit-Jenkinsfile.png
  static/images/devops-zh/harbor-login.png
  static/images/devops-zh/ks-console-create-credential.png
  static/images/devops-zh/ks-console-create-pipline.png
  static/images/devops-zh/run-pipline.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/advanced-settings.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/basic-info.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/create-credentials.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/credentials-page.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/export-to-file.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/harbor-projects.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account-name.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/robot-account.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-harbor-into-pipelines/set-name.png
Labels: lgtm, size/L

#1059 CronJobs ZH reviewed.
  content/zh/docs/project-user-guide/application-workloads/cronjob.md
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/execution-record.png
  static/images/docs/project-user-guide-zh/application-workloads-zh/cronjobs-zh/job-list.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/container-log-1.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/container-log-2.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/cronjob-action.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/cronjob-create-basic-info.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/cronjob-list-new.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/cronjob-list.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/execution-record.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/finish-image.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/input-busybox.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/job-detail-page.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/job-list.png
  static/images/docs/zh-cn/project-user-guide/application-workloads/cronjobs/start-command.png
Labels: size/L

#1067 Integrate SonarQube into Pipelines ZH reviewed.
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/access-sonarqube-console.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/add-sonarqube.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/configure-system.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/generate-a-token.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/jenkins-login-page.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/jenkins-projet-key.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/log-in-page.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/manage-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-config-1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-config-2.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-config-3.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-create-project.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-example.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-install.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-jenkins-settings.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-view-result.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-webhook-1.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-webhook-2.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/token-created.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/webhook-page-info.png
Labels: size/L

#1070 Add advantages cn version
  content/en/docs/introduction/advantages.md
  content/zh/docs/introduction/advantages.md
Labels: size/L

#689 Add live page
  assets/scss/live-detail.scss
  assets/scss/live.scss
  assets/scss/mixin.scss
  content/zh/live/_index.md
  content/zh/live/test.md
  i18n/en.yaml
  i18n/zh.yaml
  layouts/live/list.html
  layouts/live/single.html
  static/images/live/30.svg
  static/images/live/background.jpg
  static/images/live/base.svg
  static/images/live/clock.svg
  static/images/live/friend.jpeg
  static/images/live/notice.svg
  static/images/live/over.svg
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1069 Bring Your Own Prometheus translated.
  content/en/docs/faq/observability/byop.md
  content/zh/docs/faq/observability/byop.md
Labels: lgtm, size/M

#1071 Build and Deploy a Maven Project translated.
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/maven-project-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/run-maven-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-credential-lists.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-namespace.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-workload-svc.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-workload.PNG
Labels: size/L

#1078 Credential Management ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-use/credential-management.md
  static/images/docs/devops-user-guide-zh/credential-management-zh/create-credential-step1.png
  static/images/docs/devops-user-guide-zh/credential-management-zh/credential-detail-page.png
  static/images/docs/devops-user-guide-zh/credential-management-zh/credentials-list.png
  static/images/docs/devops-user-guide-zh/credential-management-zh/dockerhub-credentials.png
  static/images/docs/devops-user-guide-zh/credential-management-zh/edit-credentials.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/create-credential-page.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/create-credential-step1.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential-detail-page.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential-list.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/dockerhub-credentials.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/edit-credentials.PNG
Labels: size/M

#1073 DevOps Project Management ZH reviewed.
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management.md
  static/images/docs/devops-user-guide-zh/using-devops-zh/devops-project-management-zh/create-devops.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/devops-project-management-zh/devops-detail-page.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/devops-project-management-zh/devops-list.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/devops-project-management-zh/devops-project-create.png
  static/images/docs/devops-user-guide-zh/using-devops-zh/devops-project-management-zh/project-basic-info.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info.PNG
Labels: size/M

#1074 Role and Member Management ZH reviewed.
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  static/images/docs/devops-admin-zh/devops_invite_member.png
  static/images/docs/devops-admin-zh/devops_list_member.png
  static/images/docs/devops-admin-zh/devops_role_list.png
  static/images/docs/devops-admin-zh/devops_role_step1.png
  static/images/docs/devops-admin-zh/devops_role_step2.png
  static/images/docs/devops-admin-zh/devops_user_edit.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-invite-member.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-list.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step1.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step2.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-user-edit.PNG
Labels: lgtm, size/M

#1080 Jenkins System Settings ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-use/jenkins-setting.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/app-config.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/cluster-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/configuration-as-code.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/edit-configmap.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/edit-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/jenkins-dashboard.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/manage-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/more-list.png
Labels: lgtm, size/M

#1081 Choose Jenkins Agent ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-use/choose-jenkins-agent.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/choose-jenkins-agent/jenkins-agent.PNG
Labels: size/M

#1082 Update intro.md
  content/zh/docs/installing-on-linux/introduction/intro.md
Labels: approved, lgtm, size/XS

#1083 Set Email Server for KubeSphere Pipelines ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-use/jenkins-email.md
  static/images/docs/devops-user-guide-zh/jenkins-email-zh/workloads-list.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/clusters-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/set-jenkins-email.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/workloads-list.PNG
Labels: size/M

#1084 Set CI Node for Dependency Caching ZH reviewed.
  content/zh/docs/devops-user-guide/how-to-use/set-ci-node.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/add-ci-label.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/add-taint.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/clusters-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/node-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/select-ci-node.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/select-taint-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/taint-result.png
Labels: size/M

#854 Add deep dive into the K8s request and limit blog.
  content/zh/blogs/deep-dive-into-the-K8s-request-and-limit.md
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210101-144857.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210101-145934.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210101-153255.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210101-153523.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210122-193909.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210122-194358.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210122-194612.png
  static/images/blogs/deep-dive-into-the-K8s-request-and-limit/ksnip_20210122-194745.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#1086 DevOps Website translated.
  content/en/devops/_index.md
  content/zh/devops/_index.md
Labels: lgtm, size/M

#1091 add user logos
  content/en/case/_index.md
  static/images/case/section6-hongya.png
  static/images/case/section6-ruijie.png
  static/images/case/section6-supaur.png
  static/images/case/section6-uisee.png
  static/images/case/section6-xiaodiketang.png
  static/images/case/section6-yaowang.png
  static/images/case/section6-zto.png
Labels: approved, size/S

#1092 add kubesphere certificates
  content/zh/blogs/kubesphere-certificates.md
Labels: approved, size/L

#1089 Update add node guide
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
Labels: size/L

#1095 DevOps Index ZH reviewed.
  content/en/docs/devops-user-guide/_index.md
  content/zh/docs/devops-user-guide/_index.md
Labels: size/M

#1090 Images updated in S2I, B2I and Deploy Apps in a Multi-cluster Project ZH files.
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/multi-cluster-ok.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/access-service.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/building-status.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/building.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/deployment.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/docker-image-pushed.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/docker-image.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/exposed-port.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/image-success.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/inspect-log.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/inspect-logs.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/job-created.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/job.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/service.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/binary-to-image/successful.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build-log.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/building.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/deployment.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/docker-image.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/job.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/service-detail.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/service.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/successful-result.PNG
Labels: size/M

#1077 Add microservices-based composing guide
  content/en/docs/project-user-guide/application/compose-app.md
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/click-to-visit.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/container-image.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/create-composing-app.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/dashboard.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/microservices-done.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/product-page.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/review-page.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/route.png
  static/images/docs/project-user-guide/applications/create-a-microservices-based-app/status-active.png
Labels: size/L

#1101 Add KubeKey intro
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
Labels: size/L

#1104 Refactor ha part
  content/en/blogs/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/high-availability-configurations/_index.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  static/images/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy/architecture-ha-k8s-cluster.png
  static/images/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-lb/ha-architecture.png
Labels: size/L

#1105 Add uninstalling guide
  content/en/docs/faq/installation/uninstall-pluggable-components.md
Labels: size/L

#1109 Add SSH connection failure faq
  content/en/docs/faq/installation/ssh-connection-failure.md
Labels: size/M

#1111 Pipeline Settings TBD.
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
Labels: size/XS

#1108 Deploy TiDB Operator and a TiDB cluster EN added.
  content/en/docs/application-store/external-apps/deploy-tidb.md
  content/zh/docs/application-store/external-apps/_index.md
  content/zh/docs/application-store/external-apps/deploy-tidb.md
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/add-pingcap-repo.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/add-repo.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/added-pingcap-repo.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/basic-info.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/check-config-file.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/click-tidb-cluster.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/click-tidb-operator.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/deploy-app-again.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/deploy-app.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/download-yaml-file.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/from-app-templates-2.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/from-app-templates.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/pd-metrics.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/select-version.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-app-running.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-config.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-deployments-running.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-cluster-info.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-deployment.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-grafana.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-metrics.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-operator-running.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-pod-list.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-project-resource-usage.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-service-grafana.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-service.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-statefulsets.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tidb-storage-usage.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tikv-metrics.PNG
  static/images/docs/appstore/external-apps/deploy-tidb-operator-and-cluster/tikv-volume-status.PNG
Labels: size/L

#1112 Add disk log collection doc
  content/en/docs/project-administration/disk-log-collection.md
  content/zh/docs/project-administration/disk-log-collection.md
  static/images/docs/project-administration/disk-log-collection/alpine-image.png
  static/images/docs/project-administration/disk-log-collection/container-log.png
  static/images/docs/project-administration/disk-log-collection/enable-disk-log-collection.png
  static/images/docs/project-administration/disk-log-collection/fuzzy-match.png
  static/images/docs/project-administration/disk-log-collection/inspect-logs.png
  static/images/docs/project-administration/disk-log-collection/mount-volumes.png
  static/images/docs/project-administration/disk-log-collection/run-command.png
  static/images/docs/project-administration/disk-log-collection/volume-example.png
Labels: size/L

#1113 added note in SonarQube tutorial.
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
Labels: lgtm, size/S

#1061 Add KubeEye blog
  content/en/blogs/kubeeye-automatic-cluster-diagnostic-tool.md
  static/images/blogs/en/kubeeye-diagnostics-tool-introduction/kubeeye-architecture.png
  static/images/blogs/en/kubeeye-diagnostics-tool-introduction/kubeeye-logo-vertical-blog-banner.jpg
  static/images/blogs/en/kubeeye-diagnostics-tool-introduction/kubeeye-logo.png
Labels: approved, lgtm, size/L

#1106 Written routes-en
  content/en/docs/project-user-guide/application-workloads/ingress.md
  content/en/docs/project-user-guide/application-workloads/routes.md
  static/images/docs/project-user-guide/application-workloads/routes/access-method-loadbalancer.png
  static/images/docs/project-user-guide/application-workloads/routes/access-method-nodeport.png
  static/images/docs/project-user-guide/application-workloads/routes/access-route-loadbalancer.png
  static/images/docs/project-user-guide/application-workloads/routes/access-route-nodeport.png
  static/images/docs/project-user-guide/application-workloads/routes/add-metadata.png
  static/images/docs/project-user-guide/application-workloads/routes/auto-generate.png
  static/images/docs/project-user-guide/application-workloads/routes/basic-info.png
  static/images/docs/project-user-guide/application-workloads/routes/create-route.png
  static/images/docs/project-user-guide/application-workloads/routes/edit-route.png
  static/images/docs/project-user-guide/application-workloads/routes/obtain-address-loadbalancer.png
  static/images/docs/project-user-guide/application-workloads/routes/obtain-address-nodeport.png
  static/images/docs/project-user-guide/application-workloads/routes/route-list.png
  static/images/docs/project-user-guide/application-workloads/routes/set-gateway.png
  static/images/docs/project-user-guide/application-workloads/routes/specify-domain.png
Labels: lgtm, size/L

#1114 Update installing on Linux index
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/project-administration/_index.md
  content/zh/docs/project-administration/_index.md
Labels: size/M

#1116 Update Deploy Harbor EN/ZH files.
  content/en/docs/application-store/built-in-apps/harbor-app.md
  content/zh/docs/application-store/built-in-apps/harbor-app.md
Labels: size/XS

#1115 Added Remove Built-in Apps FAQ doc.
  content/en/docs/faq/applications/_index.md
  content/en/docs/faq/applications/remove-built-in-apps.md
  content/zh/docs/faq/applications/_index.md
  content/zh/docs/faq/applications/remove-built-in-apps.md
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/activate-tomcat.PNG
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/click-platform.PNG
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/click-tomcat.PNG
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/confirm-suspend.PNG
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/select-app-store-management.PNG
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/suspend-tomcat.PNG
Labels: lgtm, size/L

#1118 Add enable metrics server guide
  content/en/docs/pluggable-components/_index.md
  content/en/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/pluggable-components/metrics-server.md
  static/images/docs/enable-pluggable-components/metrics-server/clusters-management.png
  static/images/docs/enable-pluggable-components/metrics-server/edit-yaml.png
Labels: size/L

#1121 fix some links and index pages
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/docs/faq/_index.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/project-user-guide/configuration/image-registry.md
  content/zh/docs/faq/_index.md
  content/zh/docs/installing-on-linux/_index.md
Labels: size/M

#1123 Added New Docs into Corresponding Indexes.
  content/en/docs/application-store/_index.md
  content/zh/docs/application-store/_index.md
  content/zh/docs/faq/_index.md
Labels: lgtm, size/S

#1117 Add an FAQ Doc: Use the Same App Name after Its Deletion.
  content/en/docs/faq/applications/remove-built-in-apps.md
  content/en/docs/faq/applications/use-the-same-app-name-after-deletion.md
  content/zh/docs/faq/applications/remove-built-in-apps.md
  content/zh/docs/faq/applications/use-the-same-app-name-after-deletion.md
  static/images/docs/faq/applications/remove-built-in-apps/activate-tomcat.PNG
  static/images/docs/faq/applications/remove-built-in-apps/click-platform.PNG
  static/images/docs/faq/applications/remove-built-in-apps/click-tomcat.PNG
  static/images/docs/faq/applications/remove-built-in-apps/confirm-suspend.PNG
  static/images/docs/faq/applications/remove-built-in-apps/select-app-store-management.PNG
  static/images/docs/faq/applications/remove-built-in-apps/suspend-tomcat.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/confirm-delete.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/delete-redis-1.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/delete-secret.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/error-prompt.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/new-redis-app.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/redis-1.PNG
  static/images/docs/faq/applications/use-the-same-app-name-after-deletion/search-secret.PNG
Labels: size/L

#1124 fix some links
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/en/docs/faq/installation/telemetry.md
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/release/release-v202.md
  content/zh/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/zh/docs/faq/installation/telemetry.md
  content/zh/docs/release/release-v202.md
Labels: size/S

#1126 Doc Title Updated to 'Reuse the Same App Name after Its Deletion' and Index updated
  content/en/docs/faq/_index.md
  content/en/docs/faq/applications/reuse-the-same-app-name-after-deletion.md
  content/zh/docs/faq/_index.md
  content/zh/docs/faq/applications/reuse-the-same-app-name-after-deletion.md
Labels: size/M
