Repository kubesphere/website, pull requests merged in 2021-11, with the labels that each got.

#1997 Add DingTalk Notifications EN Doc
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
Labels: approved, lgtm, size/M

#1998 Add WeCom Notifications EN Doc
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
Labels: approved, lgtm, size/M

#2022 [Release-3.2] Add Descriptions of Multi-cluster New Features in Docs
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/project-administration/project-and-multicluster-project.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/project-administration/project-and-multicluster-project.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
  static/images/docs/common-icons/three-dots.png
  static/images/docs/zh-cn/project-administration/project-and-multicluster-project/multi-cluster-list.png
Labels: approved, lgtm, size/L

#2026 [Release-3.2] Add EN Doc: Cluster Gateway
  content/en/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
  static/images/docs/common-icons/replica-minus-icon.png
  static/images/docs/common-icons/replica-plus-icon.png
Labels: approved, lgtm, size/L

#2027 [Release-3.2] Add Description of Manage Volume Instances in Doc
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
Labels: approved, lgtm, size/M

#2032 feat: Add a Link to v3.1.0 for document menu
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#2038 update the page of live
  content/zh/live/3.1-live.md
  content/zh/live/_index.md
  content/zh/live/ai-cic.md
  content/zh/live/apisix-chengdu.md
  content/zh/live/apisix826-live.md
  content/zh/live/baas-chengdu.md
  content/zh/live/botkube-live.md
  content/zh/live/ckacks1021-live.md
  content/zh/live/devops-shanghai.md
  content/zh/live/driverless-cic.md
  content/zh/live/edgebox-cic.md
  content/zh/live/faas-hangzhou.md
  content/zh/live/go1104-live.md
  content/zh/live/hangzhou1023-blockchain.md
  content/zh/live/hangzhou1023-devops.md
  content/zh/live/hangzhou1023-juicefs.md
  content/zh/live/hangzhou1023-mysql.md
  content/zh/live/hangzhou1023-sealer.md
  content/zh/live/hpa-chengdu.md
  content/zh/live/kubeedge-hangzhou.md
  content/zh/live/kubeovn1028-live.md
  content/zh/live/medialive-shanghai.md
  content/zh/live/milvus-hangzhou.md
  content/zh/live/multicluster-chengdu.md
  content/zh/live/multicluster-shanghai.md
  content/zh/live/mysql-hangzhou.md
  content/zh/live/mysql-shanghai.md
  content/zh/live/nebula0902-live.md
  content/zh/live/nebulagraph-hangzhou.md
  content/zh/live/neonio-shanghai.md
  content/zh/live/nm-cic.md
  content/zh/live/pipy819-live.md
  content/zh/live/qke-ack.md
  content/zh/live/ray-shanghai.md
  content/zh/live/segmentfault.md
  content/zh/live/tideng-chengdu.md
  content/zh/live/uisee0916-live.md
  content/zh/live/uisee0923-live.md
  content/zh/live/wasm0909-live.md
  content/zh/live/webassembly.md
  content/zh/live/yunda1014-live.md
  content/zh/live/zhongtong-shanghai.md
  static/images/live/cloudnative-live-cover.png
Labels: approved, lgtm, size/L

#2039 Unify Wording in Multi-cluster Chapter
  content/en/docs/introduction/features.md
  content/en/docs/introduction/scenarios.md
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/project-administration/project-gateway.md
  content/zh/docs/introduction/features.md
  content/zh/docs/introduction/scenarios.md
  content/zh/docs/project-administration/project-gateway.md
Labels: approved, lgtm, size/M

#2036 Update Installation Parameters to KS v3.2.0
  content/en/docs/faq/console/edit-resources-in-system-workspace.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/introduction/vars.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/faq/console/edit-resources-in-system-workspace.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/zh/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/XXL

#2030 deploy-clickhouse zh&en : Update the expected output
  content/en/docs/application-store/external-apps/deploy-clickhouse.md
  content/zh/docs/application-store/external-apps/deploy-clickhouse.md
Labels: approved, lgtm, size/M

#2041 Update KCD China News
  content/en/news/_index.md
  content/en/news/kubernetes-community-days-china.md
  static/images/news/kcd-china/guest-speakers.png
  static/images/news/kcd-china/kcd-beijing-organizers.png
  static/images/news/kcd-china/kcd-china-event.png
  static/images/news/kcd-china/kcd-event-2.png
  static/images/news/kcd-china/kcd-event-3.png
  static/images/news/kcd-china/kcd-event.png
Labels: approved, lgtm, size/M

#2049 Typo fixing from Webniar to Webinar
  data/zh/video.json
Labels: approved, lgtm, size/XS

#2045 feat: Update document link
  config/_default/config.toml
Labels: approved, lgtm, size/M

#2052 Fix Some Commands
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: approved, lgtm, size/S

#2053 new blog of kubesphere-3.2.0-ga-announcement
  content/zh/blogs/kubesphere-3.2.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2056 Update Docs per UI Text Changes
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/project-user-guide/application-workloads/cronjobs.md
  content/en/docs/project-user-guide/application-workloads/daemonsets.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/project-user-guide/application-workloads/routes.md
  content/en/docs/project-user-guide/application-workloads/services.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/en/docs/project-user-guide/application/compose-app.md
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/en/docs/project-user-guide/configuration/configmaps.md
  content/en/docs/project-user-guide/configuration/image-registry.md
  content/en/docs/project-user-guide/configuration/secrets.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/en/docs/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/project-user-guide/image-builder/source-to-image.md
  content/en/docs/project-user-guide/storage/volume-snapshots.md
  content/en/docs/project-user-guide/storage/volumes.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  content/zh/docs/project-user-guide/application-workloads/routes.md
  content/zh/docs/project-user-guide/application-workloads/services.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/project-user-guide/application/compose-app.md
  content/zh/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/zh/docs/project-user-guide/application/deploy-app-from-template.md
  content/zh/docs/project-user-guide/configuration/configmaps.md
  content/zh/docs/project-user-guide/configuration/image-registry.md
  content/zh/docs/project-user-guide/configuration/secrets.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  content/zh/docs/project-user-guide/storage/volumes.md
  static/images/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider/kubesphere-login-page.png
Labels: approved, lgtm, size/L

#2059 Translate 3.2.0 release note.
  content/zh/docs/release/release-v320.md
Labels: approved, lgtm, size/L

#2061 add Baidu Analytics
  config/upstream-zh/config.toml
  layouts/partials/head.html
Labels: approved, lgtm, size/S

#2066 update the header to the 3.2.0 GA notification
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2067 add two approvers to the OWNER list, update the hearder to v3.2.0
  OWNERS
  content/zh/blogs/kubesphere-3.2.0-ga-announcement.md
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2060 new blog of ebpf-guide
  content/zh/blogs/ebpf-guide.md
Labels: approved, lgtm, size/L

#2062 new blog of ebpf-machine-bytecode
  content/zh/blogs/ebpf-machine-bytecode.md
  content/zh/blogs/kubesphere-3.2.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2040 new blog of calico-ebpf
  content/zh/blogs/calico-ebpf.md
  content/zh/live/go1104-live.md
Labels: approved, lgtm, size/L

#2037 new blog of mysql-on-k8s
  content/zh/blogs/mysql-on-k8s.md
Labels: approved, lgtm, size/L

#2068 new blog of kubernetes-client-go-workqueue
  content/zh/blogs/kubernetes-client-go-workqueue.md
Labels: approved, lgtm, size/XL

#2057 Optimize Docs According to the Latest UI
  content/en/docs/application-store/app-lifecycle-management.md
  content/en/docs/application-store/built-in-apps/etcd-app.md
  content/en/docs/application-store/built-in-apps/harbor-app.md
  content/en/docs/application-store/built-in-apps/memcached-app.md
  content/en/docs/application-store/built-in-apps/minio-app.md
  content/en/docs/application-store/built-in-apps/mongodb-app.md
  content/en/docs/application-store/built-in-apps/mysql-app.md
  content/en/docs/application-store/built-in-apps/nginx-app.md
  content/en/docs/application-store/built-in-apps/postgresql-app.md
  content/en/docs/application-store/built-in-apps/rabbitmq-app.md
  content/en/docs/application-store/built-in-apps/radondb-mysql-app.md
  content/en/docs/application-store/built-in-apps/radondb-postgresql-app.md
  content/en/docs/application-store/built-in-apps/redis-app.md
  content/en/docs/application-store/built-in-apps/tomcat-app.md
  content/en/docs/application-store/external-apps/deploy-clickhouse.md
  content/en/docs/application-store/external-apps/deploy-gitlab.md
  content/en/docs/application-store/external-apps/deploy-litmus.md
  content/en/docs/application-store/external-apps/deploy-metersphere.md
  content/en/docs/application-store/external-apps/deploy-tidb.md
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/en/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  content/en/docs/project-administration/project-and-multicluster-project.md
  content/en/docs/project-administration/project-network-isolation.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/quick-start/wordpress-deployment.md
  content/en/docs/toolbox/metering-and-billing/view-resource-consumption.md
Labels: approved, lgtm, size/L

#2035 Refactor documents under 'account management and permission control'
  content/en/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/en/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/zh/docs/access-control-and-account-management/_index.md
  content/zh/docs/access-control-and-account-management/configuring-authentication.md
  content/zh/docs/access-control-and-account-management/external-authentication/_index.md
  content/zh/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/zh/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
  content/zh/docs/access-control-and-account-management/ldap-identity-provider.md
  content/zh/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/zh/docs/access-control-and-account-management/oidc-identity-provider.md
  content/zh/docs/access-control-and-account-management/use-an-oauth2-identity-provider.md
Labels: approved, lgtm, size/XL

#2069 new blog of kubernetes-client-go-indexer-threadsafestore
  content/zh/blogs/kubernetes-client-go-indexer-threadsafestore.md
Labels: approved, lgtm, size/L

#2071 Fix a Minor Issue
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
Labels: approved, lgtm, size/XS

#2034 add a new blog
  content/zh/blogs/transform-traditional-applications-into-microservices.md
Labels: approved, lgtm, size/L

#2033 add new blog of calico-guide
  content/zh/blogs/calico-guide.md
Labels: approved, lgtm, size/XL

#2074 Sync DingTalk Notifications EN Doc to 3.2.0
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
Labels: approved, lgtm, size/M

#2077 Add Tutorial Videos in 3.1.x ZH Docs
  content/zh/docs/cluster-administration/cluster-status-monitoring.md
  content/zh/docs/cluster-administration/nodes.md
  content/zh/docs/toolbox/metering-and-billing/view-resource-consumption.md
Labels: approved, lgtm, size/S

#2028 Review Translation x509-certificate-exporter
  content/en/blogs/x509-certificate-exporter.md
  static/images/blogs/en/x509-certificate-exporter/00-access-control.png
  static/images/blogs/en/x509-certificate-exporter/01-create-user.png
  static/images/blogs/en/x509-certificate-exporter/02-three-users.png
  static/images/blogs/en/x509-certificate-exporter/03-ws-manager.png
  static/images/blogs/en/x509-certificate-exporter/04-create-workspace.png
  static/images/blogs/en/x509-certificate-exporter/05-invite-member.png
  static/images/blogs/en/x509-certificate-exporter/06-assign-role.png
  static/images/blogs/en/x509-certificate-exporter/07-create-project.png
  static/images/blogs/en/x509-certificate-exporter/08-enter-project-name.png
  static/images/blogs/en/x509-certificate-exporter/09-view-project-info.png
  static/images/blogs/en/x509-certificate-exporter/10-invite-project-member.png
  static/images/blogs/en/x509-certificate-exporter/11-assign-project-role.png
  static/images/blogs/en/x509-certificate-exporter/12-add-repo.png
  static/images/blogs/en/x509-certificate-exporter/13-add-repo2.png
  static/images/blogs/en/x509-certificate-exporter/14-view-repo.png
  static/images/blogs/en/x509-certificate-exporter/15-create-app.png
  static/images/blogs/en/x509-certificate-exporter/16-create-app2.png
  static/images/blogs/en/x509-certificate-exporter/17-select-enix.png
  static/images/blogs/en/x509-certificate-exporter/18-select-x509.png
  static/images/blogs/en/x509-certificate-exporter/19-deploy-x590.png
  static/images/blogs/en/x509-certificate-exporter/20-set-app-name.png
  static/images/blogs/en/x509-certificate-exporter/21-app-settings.png
  static/images/blogs/en/x509-certificate-exporter/22-explain-parameters.png
  static/images/blogs/en/x509-certificate-exporter/23-view-created-app.png
  static/images/blogs/en/x509-certificate-exporter/24-monitoring-alerting.png
  static/images/blogs/en/x509-certificate-exporter/25-create-alerting-policy.png
  static/images/blogs/en/x509-certificate-exporter/26-custom-rule.png
  static/images/blogs/en/x509-certificate-exporter/27-message-settings.png
  static/images/blogs/en/x509-certificate-exporter/28-view-created-alerting-rule.png
  static/images/blogs/en/x509-certificate-exporter/29-built-in-alerting-policy.png
  static/images/blogs/en/x509-certificate-exporter/30-view-alerting-rule.png
  static/images/blogs/en/x509-certificate-exporter/x509-certificate-exporter-cover-image.png
Labels: approved, lgtm, size/L

#2072 new blog of ebpf-software-stack
  content/zh/blogs/Kubernetes-multicluster-KubeSphere.md
  content/zh/blogs/ebpf-machine-bytecode.md
  content/zh/blogs/ebpf-software-stack.md
Labels: approved, lgtm, size/L

#2018 fix: port type is int in config-sample.yaml
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
Labels: approved, lgtm, size/XS

#2076 fix:translate configure-webhook.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
Labels: approved, lgtm, size/M

#2075 Add Docs: Customize Cluster Name in Notification Messages
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
  content/en/docs/cluster-administration/platform-settings/notification-management/customize-cluster-name.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/customize-cluster-name.md
Labels: approved, lgtm, size/L

#2082 typo fixed
  content/en/blogs/Kubernetes-Backup-and-Restore-with-Kasten-K10 on-KubeSphere.md
Labels: approved, lgtm, size/S

#2085 Fix typo and update ZH docs
  content/zh/docs/release/release-v320.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/S

#2083 Update Docs per UI Changes
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
Labels: approved, lgtm, size/M

#2081 update the page of live
  content/zh/live/_index.md
  content/zh/live/go1104-live.md
  content/zh/live/rook1111-live.md
  static/images/live/cloudnative-live-banner.png
  static/images/live/cloudnative-live-cover.png
Labels: approved, lgtm, size/M

#2089 Disable the topographer extension.
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#2091 fix: Hugo render failed when we add a case blog
  layouts/case/single.html
Labels: approved, lgtm, size/M

#2092 Add Tutorial Video in 3.1.x ZH Doc
  content/zh/docs/cluster-administration/application-resources-monitoring.md
Labels: approved, lgtm, size/XS

#2080 Update HA Docs
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
Labels: approved, lgtm, size/S

#2086 Update Enable Logging Docs
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/logging.md
Labels: approved, lgtm, size/M

#2063 Change externalElasticsearchUrl to externalElasticsearchHost
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/faq/observability/logging.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
Labels: approved, lgtm, size/M

#2095 add new case of segmentfault
  content/zh/case/_index.md
  content/zh/case/segmentfault.md
  static/images/case/segmentfault-logo.png
Labels: approved, lgtm, size/L

#2078 Update the directory
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
Labels: approved, lgtm, size/XS

#2100 Update Commands in 3.2.0 Docs per DevOps SVC Changes
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-setting.md
  content/en/docs/faq/devops/install-jenkins-plugins.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-setting.md
  content/zh/docs/faq/devops/install-jenkins-plugins.md
Labels: approved, lgtm, size/S

#2102 Update DevOps Docs per SVC Changes
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, area/devops, lgtm, size/S

#2099 update-kubesphere-3.2.0-ga-announcement
  content/en/blogs/Brand-new KubeSphere 3.2.0 Brings AI-oriented GPU Scheduling and Ever More Flexible Gateways.md
  content/en/blogs/KubeSphere3.2.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2105 update-kubesphere-3.2.0-ga-announcement
  content/en/blogs/Brand-new KubeSphere 3.2.0 Brings AI-oriented GPU Scheduling and Ever More Flexible Gateways.md
  content/en/blogs/KubeSphere3.2.0-ga-announcement.md
  static/images/blogs/en/release-announcement3.2.0/00-GPU-scheduling-quota-manage.png
  static/images/blogs/en/release-announcement3.2.0/01-Grafana-dashboard.png
  static/images/blogs/en/release-announcement3.2.0/02-GPU-overview.png
  static/images/blogs/en/release-announcement3.2.0/03-platform-settings.png
  static/images/blogs/en/release-announcement3.2.0/04-cluster-manage.png
  static/images/blogs/en/release-announcement3.2.0/05-federated-deployment.png
  static/images/blogs/en/release-announcement3.2.0/06-view-federation.png
  static/images/blogs/en/release-announcement3.2.0/07-volume-manage.png
  static/images/blogs/en/release-announcement3.2.0/08-storage-class-settings.png
  static/images/blogs/en/release-announcement3.2.0/09-volumes.png
  static/images/blogs/en/release-announcement3.2.0/10-gateway-settings.png
  static/images/blogs/en/release-announcement3.2.0/11-gateway-settings2.png
  static/images/blogs/en/release-announcement3.2.0/12-app-store.png
  static/images/blogs/en/release-announcement3.2.0/3.2.0GA.png
  static/images/blogs/en/release-announcement3.2.0/v3.2.0-GA-cover.png
  static/images/blogs/en/release-announcement3.2.0/v3.2.0-contributors.png
Labels: approved, lgtm, size/L

#2106 update-kubesphere-3.2.0-ga-announcement
  content/en/blogs/kubesphere-3.2.0-ga-announcement.md
Labels: approved, lgtm, size/XS

#2108 update the tag of blogs
  content/zh/blogs/deep-dive-into-the-K8s-request-and-limit.md
  content/zh/blogs/ebpf-software-stack.md
  content/zh/blogs/edge-node-monitoring.md
  content/zh/blogs/kubernetes-kubesphere-ha.md
  content/zh/blogs/kubesphere-certificates.md
  content/zh/blogs/kubesphere-release-note-post.md
  content/zh/blogs/kubesphere-values.md
Labels: approved, lgtm, size/S

#2107 new blog of ambassador certificate
  content/zh/blogs/kubesphere-ambassador-certificates.md
Labels: approved, lgtm, size/M

#2094 feat: Add subescribe form in all blog pages and document pages
  assets/scss/content.scss
  assets/scss/doc.scss
  config/_default/config.toml
  config/upstream-zh/config.toml
  layouts/docs/single.html
  layouts/partials/content.html
Labels: approved, lgtm, size/L

#2097 add new case of msxf
  content/zh/case/_index.md
  content/zh/case/msxf.md
  content/zh/case/qunar.md
  static/images/case/logo-msxf.png
  static/images/case/logo-qunar.png
  static/images/case/qunar-logo.png
Labels: approved, lgtm, size/L

#2103 Update Jenkins Terms in DevOps Docs
  content/en/docs/devops-user-guide/how-to-use/choose-jenkins-agent.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  content/zh/docs/devops-user-guide/how-to-use/choose-jenkins-agent.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
Labels: approved, area/devops, lgtm, size/S

#2110 Update 3.2.0 Image List in Docs
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/L

#2111 Revert externalElasticsearchHost to externalElasticsearchUrl
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/faq/observability/logging.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
Labels: approved, lgtm, size/M

#2098 Using kubectl to replace kubernetesDeploy in the Pipeline CD examples
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/en/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/en/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  content/en/docs/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/project-user-guide/image-builder/source-to-image.md
  content/zh/blogs/DevOps-pipeline-remove-Docker-dependencies.md
  content/zh/blogs/create-pipeline-across-multi-clusters.md
  content/zh/blogs/kubesphere-argocd.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
Labels: approved, area/devops, lgtm, size/L

#2118 change the capitalization of the doc
  content/en/blogs/serverless-way-for-kubernetes-log-alert.md
  content/zh/blogs/serverless-way-for-kubernetes-log-alert.md
Labels: approved, lgtm, size/XS

#2120 Unify Wording in 3.2.0 DevOps ZH Docs
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management.md
Labels: approved, area/devops, lgtm

#2117 update the page of live
  content/zh/live/_index.md
  content/zh/live/rook1111-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/S

#2125 Translate How to Use Kubernetes Project Gateways and Routes.
  content/en/blogs/how-to-use-kubernetes-project-gateways-and-routes.md
  content/zh/blogs/how-to-use-kubernetes-project-gateways-and-routes.md
  static/images/blogs/how-to-use-kubernetes-project-gateways-and-routes/create-route.png
  static/images/blogs/how-to-use-kubernetes-project-gateways-and-routes/deployment-list.png
  static/images/blogs/how-to-use-kubernetes-project-gateways-and-routes/routing-rules.png
  static/images/blogs/how-to-use-kubernetes-project-gateways-and-routes/snapshot.png
Labels: approved, lgtm, size/L

#1924 fix containerd still uses "k8s.gcr.io/pause"
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/zh/blogs/dockershim-out-of-kubernetes.md
Labels: approved, lgtm, size/XS

#2122 Update Gateway Docs
  content/en/docs/project-administration/project-gateway.md
  content/zh/docs/project-administration/project-gateway.md
Labels: approved, lgtm, size/S

#2126 Fix: v3.2.0 chinese version of quickstarts document
  content/zh/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
Labels: approved, lgtm, size/M

#2112 Add Tutorial Videos in 3.1.x ZH Docs
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/pluggable-components/overview.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: approved, lgtm, size/S

#2115 Update PV ZH Doc
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
Labels: approved, lgtm, size/M

#2131 Unify 3.2.0 ZH DevOps Wording
  content/zh/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/zh/docs/cluster-administration/application-resources-monitoring.md
  content/zh/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  content/zh/docs/introduction/features.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/reference/glossary.md
  content/zh/docs/release/release-v310.md
  content/zh/docs/release/release-v311.md
  content/zh/docs/toolbox/auditing/auditing-rule.md
  content/zh/docs/workspace-administration/department-management.md
  content/zh/docs/workspace-administration/role-and-member-management.md
  content/zh/docs/workspace-administration/what-is-workspace.md
  content/zh/docs/workspace-administration/workspace-quotas.md
Labels: approved, lgtm, size/M

#2133 new blog of kubesphere-contributor-certificates
  content/zh/blogs/kubesphere-contributor-certificates.md
Labels: approved, lgtm, size/L

#2129 fix: Let meetup card auto slide
  assets/scss/live.scss
  layouts/live/list.html
  layouts/partials/css.html
  layouts/partials/head.html
  static/swiper/swiper-bundle.min.css
  static/swiper/swiper-bundle.min.js
Labels: approved, lgtm, size/L

#2123 update the version and description in what's-new-in-3.2.0.md
  content/en/docs/introduction/what's-new-in-3.1.0.md
  content/en/docs/introduction/what's-new-in-3.2.0.md
  content/zh/docs/introduction/what's-new-in-3.1.0.md
  content/zh/docs/introduction/what's-new-in-3.2.0.md
Labels: approved, lgtm, size/M

#2114 Update Set Up External Auth Docs
  content/en/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/en/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
  content/zh/docs/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/zh/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
Labels: approved, lgtm, size/XL

#2137 Fix serial number error
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#2132 new blog of juicefs
  content/zh/blogs/kubesphere-juicefs.md
Labels: approved, lgtm, size/L

#1976 ninth task
  content/zh/docs/project-user-guide/image-builder/s2i-templates.md
Labels: approved, lgtm, size/L

#2141 SEO amends
  content/en/blogs/aws-kubernetes.md
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: approved, lgtm, size/S

#2140 new blog of kubesphere-nocalhost
  content/zh/blogs/kubesphere-nocalhost.md
Labels: approved, lgtm, size/L

#2144 fix: Update button size
  assets/scss/live.scss
  layouts/live/list.html
Labels: approved, lgtm, size/S

#2143 add openelb-joins-cncf-sandbox-project.md
  content/zh/blogs/openelb-joins-cncf-sandbox-project.md
Labels: approved, lgtm, size/M

#2148 update the page of live
  content/zh/live/meetup-beijing.md
  content/zh/live/meetup-chengdu.md
  content/zh/live/meetup-hangzhou.md
  content/zh/live/meetup-hangzhou1023.md
  content/zh/live/meetup-shanghai.md
Labels: approved, lgtm, size/S

#2149 new blog of kubesphere-member-certificates
  content/zh/blogs/kubesphere-member-certificates.md
Labels: approved, lgtm, size/M

#2154 FAQ about missing some log in realtime container log console
  content/zh/docs/faq/observability/logging.md
Labels: approved, lgtm, size/XS

#2157 add use-apache-apisix-ingress-in-kubesphere.md
  content/zh/blogs/use-apache-apisix-ingress-in-kubesphere.md
Labels: approved, lgtm, size/L
