Repository kubesphere/website, pull requests merged in 2021-06, with the labels that each got.

#1649 Update project and multicluster project guide
  content/en/docs/project-administration/project-and-multicluster-project.md
  content/zh/docs/project-administration/project-and-multicluster-project.md
  static/images/docs/project-admin/basic-info-multicluster.jpg
  static/images/docs/project-admin/basic-info-page.jpg
  static/images/docs/project-admin/create-multicluster-project-page.jpg
  static/images/docs/project-admin/create-multicluster-project.jpg
  static/images/docs/project-admin/create-project-page.jpg
  static/images/docs/project-admin/create-project.jpg
  static/images/docs/project-admin/multicluster-project-list.jpg
  static/images/docs/project-admin/project-list.jpg
  static/images/docs/project-administration/project-and-multicluster-project/multi-cluster-basic-information.png
  static/images/docs/project-administration/project-and-multicluster-project/multi-cluster-list.png
  static/images/docs/project-administration/project-and-multicluster-project/project-basic-information.png
  static/images/docs/project-administration/project-and-multicluster-project/project-list.png
  static/images/docs/zh-cn/project-admin/basic-info-multicluster.jpg
  static/images/docs/zh-cn/project-admin/basic-info-page.jpg
  static/images/docs/zh-cn/project-admin/create-multicluster-project-page.jpg
  static/images/docs/zh-cn/project-admin/create-multicluster-project.jpg
  static/images/docs/zh-cn/project-admin/create-project-page.jpg
  static/images/docs/zh-cn/project-admin/create-project.jpg
  static/images/docs/zh-cn/project-admin/multicluster-project-list.jpg
  static/images/docs/zh-cn/project-admin/project-list.jpg
  static/images/docs/zh-cn/project-administration/project-and-multicluster-project/multi-cluster-basic-information.png
  static/images/docs/zh-cn/project-administration/project-and-multicluster-project/multi-cluster-list.png
  static/images/docs/zh-cn/project-administration/project-and-multicluster-project/project-basic-information.png
  static/images/docs/zh-cn/project-administration/project-and-multicluster-project/project-list.png
Labels: approved, size/L

#1650 Update multicluster quota note
  content/en/docs/workspace-administration/project-quotas.md
  content/zh/docs/workspace-administration/project-quotas.md
Labels: approved, size/S

#1634 Add interlinks and minor content changes
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/docs/access-control-and-account-management/multi-tenancy-in-kubesphere.md
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/en/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/faq/observability/byop.md
  content/en/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/M

#1656 Update telemetry guide
  content/en/docs/faq/installation/telemetry.md
  content/zh/docs/faq/installation/telemetry.md
  static/images/docs/faq/installation/telemetry-in-kubesphere/three-dots.png
  static/images/docs/faq/telemetry-in-kubesphere/edit-crd.jpg
  static/images/docs/faq/telemetry-in-kubesphere/edit-ks-installer.jpg
  static/images/docs/faq/telemetry-in-kubesphere/enable-telemetry.jpg
  static/images/docs/zh-cn/faq/installation/telemetry-in-kubesphere/three-dots.png
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/edit-crd.jpg
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/edit-ks-installer.jpg
  static/images/docs/zh-cn/faq/telemetry-in-kubesphere/enable-telemetry.jpg
Labels: approved, size/M

#1657 Minor word change of booster config guide
  content/en/docs/faq/installation/configure-booster.md
  content/zh/docs/faq/installation/configure-booster.md
Labels: approved, size/M

#1658 Update Doc style guide
  KubeSphere Documentation Style Guide.md
Labels: approved, size/M

#1655 update the page of live
  content/zh/live/3.1-live.md
  content/zh/live/_index.md
  content/zh/live/botkube-live.md
  content/zh/live/meetup-chengdu.md
  content/zh/live/meetup-hangzhou.md
  content/zh/live/meetup-shanghai.md
  content/zh/live/nm-live.md
  content/zh/live/poterlb-live.md
  content/zh/live/qingjiao-live.md
  i18n/zh.yaml
  layouts/live/list.html
Labels: approved, lgtm, size/L

#1665 update live page
  layouts/live/list.html
Labels: size/S

#1667 update the page of live
  content/zh/live/_index.md
  content/zh/live/devops-shanghai.md
  content/zh/live/faas-hangzhou.md
  content/zh/live/kubeedge-hangzhou.md
  content/zh/live/medialive-shanghai.md
  content/zh/live/milvus-hangzhou.md
  content/zh/live/multicluster-shanghai.md
  content/zh/live/mysql-hangzhou.md
  content/zh/live/mysql-shanghai.md
  content/zh/live/nebulagraph-hangzhou.md
  content/zh/live/neonio-shanghai.md
  content/zh/live/qke-ack.md
  content/zh/live/ray-shanghai.md
  content/zh/live/roundtable-hangzhou.md
  content/zh/live/segmentfault.md
  content/zh/live/webassembly.md
  content/zh/live/zhongtong-shanghai.md
Labels: approved, lgtm, size/XL

#1668 Update project role and member management
  content/en/docs/project-administration/role-and-member-management.md
  static/images/docs/project-admin/project_invite_member_step1.png
  static/images/docs/project-admin/project_invite_member_step2.png
  static/images/docs/project-admin/project_role_create_step1.png
  static/images/docs/project-admin/project_role_create_step2.png
  static/images/docs/project-admin/project_role_detail.png
  static/images/docs/project-admin/project_role_list.png
  static/images/docs/project-admin/project_user_edit.png
  static/images/docs/project-administration/role-and-member-management/add.png
  static/images/docs/project-administration/role-and-member-management/edit-project-account.png
  static/images/docs/project-administration/role-and-member-management/project-role-details.png
  static/images/docs/project-administration/role-and-member-management/project-role-list.png
  static/images/docs/project-administration/role-and-member-management/three-dots.png
Labels: approved, size/L

#1669 Update cn role and member guide
  content/zh/docs/project-administration/role-and-member-management.md
  content/zh/docs/workspace-administration/role-and-member-management.md
  static/images/docs/zh-cn/project-admin/project_invite_member_step2.png
  static/images/docs/zh-cn/project-admin/project_role_create_step1.png
  static/images/docs/zh-cn/project-admin/project_role_create_step2.png
  static/images/docs/zh-cn/project-admin/project_role_detail.png
  static/images/docs/zh-cn/project-admin/project_role_list.png
  static/images/docs/zh-cn/project-admin/project_user_edit.png
  static/images/docs/zh-cn/project-administration/role-and-member-management/add.png
  static/images/docs/zh-cn/project-administration/role-and-member-management/project-member-list.png
  static/images/docs/zh-cn/project-administration/role-and-member-management/project-role-detail.png
  static/images/docs/zh-cn/project-administration/role-and-member-management/project-role-list.png
  static/images/docs/zh-cn/project-administration/role-and-member-management/three-dots.png
Labels: approved, size/L

#1671 update api json
  content/en/api/crd.md
  content/en/api/kubesphere.md
  static/json/crd-3.1.json
  static/json/kubesphere-3.1.json
Labels: size/XXL

#1672 Add en ks cloud website link
  content/en/docs/cluster-administration/platform-settings/customize-basic-information.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/_index.md
Labels: approved

#1676 external-apps/deploy-clickhouse: Fix the command bug
  content/zh/docs/application-store/external-apps/deploy-clickhouse.md
Labels: approved, lgtm, size/XS

#1675 Sync TiDB Doc Updates in v3.1 to v3.0
  content/en/docs/application-store/external-apps/deploy-tidb.md
  content/zh/docs/application-store/external-apps/deploy-tidb.md
Labels: size/XS

#1602 Update Doc: Jenkins System Settings
  content/en/docs/devops-user-guide/how-to-use/jenkins-setting.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-setting.md
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/app-config.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/apply-config.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/cluster-management.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/configuration-as-code.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/configuration-as-code.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-configmap.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-configmap.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-jenkins.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/edit-jenkins.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/manage-jenkins.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/manage-jenkins.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/more-list.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/more-list.png
  static/images/docs/devops-user-guide/using-devops/jenkins-system-settings/plugin-version.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/app-config.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/apply-config.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/cluster-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/configuration-as-code.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/edit-configmap.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/edit-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/manage-jenkins.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/more-list.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-system-settings/plugin-version.png
Labels: lgtm, size/M

#1682 Update Doc: Workspace Overview
  content/en/docs/workspace-administration/what-is-workspace.md
  content/zh/docs/workspace-administration/what-is-workspace.md
  static/images/docs/workspace-administration/workspace-overview/created-workspace.jpg
  static/images/docs/workspace-administration/workspace-overview/provide-workspace-info.jpg
  static/images/docs/workspace-administration/workspace-overview/set-workspace-info.png
  static/images/docs/workspace-administration/workspace-overview/workspace-created.png
  static/images/docs/workspace-administration/workspace-overview/workspace-list.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-overview.jpg
  static/images/docs/workspace-administration/workspace-overview/workspace-overview.png
  static/images/docs/workspace-administration/workspace-overview/workspaces-list.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/created-workspace.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/delete-workspace.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/provide-workspace-info.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/set-workspace-info.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-basic-info.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-created.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-list-1.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-list.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-overview-4.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/workspace-overview.PNG
Labels: lgtm, size/M

#1683 Update Doc: Upload Helm-based Applications
  content/en/docs/workspace-administration/upload-helm-based-application.md
  content/zh/docs/workspace-administration/upload-helm-based-application.md
  static/images/docs/workspace-administration/upload-helm-based-application/confirm-upload.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/confirm-upload.png
  static/images/docs/workspace-administration/upload-helm-based-application/draft-app.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/draft-app.png
  static/images/docs/workspace-administration/upload-helm-based-application/upload-app-template.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-app-template.png
  static/images/docs/workspace-administration/upload-helm-based-application/upload-helm.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-helm.png
  static/images/docs/workspace-administration/upload-helm-based-application/upload-icon.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/upload-icon.png
  static/images/docs/workspace-administration/upload-helm-based-application/version-page.jpg
  static/images/docs/workspace-administration/upload-helm-based-application/version-page.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/confirm-upload-3.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/confirm-upload.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/draft-app-5.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/draft-app.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-app-template-1.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-app-template.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-helm-2.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-helm.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-icon-4.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/upload-icon.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/version-page-6.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/upload-helm-based-applications/version-page.PNG
Labels: approved, lgtm, size/M

#1686 Update MySQL dashboard guide
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql.md
  static/images/docs/project-user-guide/custom-application-monitoring/check-if-mysql-is-running.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/click-deploy.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/click-next.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/create-mysql-dashboard.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-app-configurations.png
  static/images/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-dashboards.png
  static/images/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-exporter-ready.png
  static/images/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-ready.png
  static/images/docs/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-root-password.png
  static/images/docs/project-user-guide/custom-application-monitoring/exporter-click-deploy-2.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/exporter-click-deploy.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/exporter-click-next.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/exporter-is-running.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/find-mysql-exporter.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/find-mysql.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/go-to-app-store.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/monitor-mysql-done.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/mysql-conn-params.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/navigate-to-custom-monitoring.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/save-mysql-template.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/set-servicemonitor-to-true.jpg
  static/images/docs/project-user-guide/custom-application-monitoring/uncomment-mysqlRootPassword.jpg
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/check-if-mysql-running.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/click-deploy.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/click-next.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/create-mysql-dashboard.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-deploy-2.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-deploy.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-click-next.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/exporter-is-running.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/find-mysql-exporter.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/find-mysql.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/go-to-app-store.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/monitor-mysql-done.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-conn-params.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-exporter-configurations.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-exporter-ready.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-monitoring-dashboard.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-ready.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/mysql-root-password.png
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/navigate-to-custom-monitoring.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/save-mysql-template.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/set-servicemonitor-to-true.PNG
  static/images/docs/zh-cn/project-user-guide/custom-application-monitoring/examples/monitor-mysql/uncommet-mysqlrootpassword.PNG
Labels: approved, do-not-merge/work-in-progress, size/L

#1687 Update Doc: Import a Helm Repository
  content/en/docs/workspace-administration/app-repository/import-helm-repository.md
  content/zh/docs/workspace-administration/app-repository/import-helm-repository.md
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-info-dialogue.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-info-dialogue.png
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo-list.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo-list.png
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/app-repo.png
  static/images/docs/workspace-administration/app-repository/import-helm-repository/validate-link.jpg
  static/images/docs/workspace-administration/app-repository/import-helm-repository/validate-link.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-info-dialogue-2.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-info-dialogue.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo-1.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo-list-4.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo-list.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/app-repo.PNG
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/validate-link-3.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/app-repository/import-helm-repository/validate-link.PNG
Labels: approved, lgtm, size/M

#1688 Update Doc: App Templates
  content/en/docs/project-user-guide/application/app-template.md
  content/zh/docs/project-user-guide/application/app-template.md
  static/images/docs/project-user-guide/applications/app-templates/app-store.jpg
  static/images/docs/project-user-guide/applications/app-templates/app-store.png
  static/images/docs/project-user-guide/applications/app-templates/private-app-repository.jpg
  static/images/docs/project-user-guide/applications/app-templates/private-app-repository.png
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/app-store-1.png
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/app-store.PNG
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/private-app-repository-2.png
  static/images/docs/zh-cn/project-user-guide/applications/app-templates/private-app-repository.PNG
Labels: approved, lgtm, size/XS

#1692 update the header of .com.cn
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1691 Update wording
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/reference/storage-system-installation/glusterfs-server.md
Labels: size/S

#1690 Update Doc: Deploy Apps from the App Store
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/zh/docs/project-user-guide/application/deploy-app-from-appstore.md
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/app-store.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.png
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nodeport.jpg
  static/images/docs/project-user-guide/applications/deploy-apps-from-app-store/nodeport.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/access-nginx.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/app-store.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/confirm-deployment.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/deploy-nginx.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-config-nginx.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/edit-internet-access.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/exposed-port.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/manifest-file.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-in-app-store.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-running.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nginx-service.png
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nodeport.jpg
  static/images/docs/zh-cn/project-user-guide/applications/deploy-apps-from-app-store/nodeport.png
Labels: approved, lgtm, size/M

#1696 Update Image in ZH Doc
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/select-repo.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/create-a-pipeline-using-a-jenkinsfile/select_repo.png
Labels: approved, lgtm, size/XS

#1698 Update Doc: Chaos Engineering with Litmus and KubeSphere
  content/zh/blogs/litmus-kubesphere.md
Labels: approved, lgtm, size/L

#1694 Update Doc: DevOps Project Management
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list.jpg
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops-2.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/create-devops.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page-4.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-detail-page.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list-3.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-list.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create-1.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/devops-project-create.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info-5.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/devops-project-management/project-basic-info.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list-1.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/overview/pipeline-list.PNG
Labels: approved, lgtm, size/S

#1695 Update Doc: Role and Member Management
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  content/zh/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_invite_member.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_list.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_step1.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_role_step2.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops_user_edit.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/plus-button.png
  static/images/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/three-dots.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-invite-member.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-invite-member_4.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-list.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-list_3.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step1.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step2.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step_1.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-role-step_2.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-user-edit.PNG
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/devops-user-edit_5.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/plus-button.png
  static/images/docs/zh-cn/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management/three-dots.png
Labels: size/M

#1701 Fix header grammar issues
  layouts/partials/header.html
Labels: approved, size/XS

#1702 Update nfs desc
  content/en/common/csi-plugins.md
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/reference/storage-system-installation/nfs-server.md
  content/zh/common/csi-plugins.md
  content/zh/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/understand-persistent-storage.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/reference/storage-system-installation/nfs-server.md
Labels: approved, lgtm, size/M

#1629 Add ZH Doc: Configure DingTalk Notification
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/access-token.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/activate-chat-access.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/app-info.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/app-page.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/application-form.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/apply-for-access.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/chat-id.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/chat-notification.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/click-add.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/click-custom.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/click-robot.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/create-app.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/create-robot.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/dev-mgt.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/dingtalk-configurations.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/dingtalk-configured.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/enter-public-ip.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/robot-configs.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/robot_notification.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/three-dots.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/user-id.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/userid-phone.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-dingtalk/view-robot.png
Labels: lgtm, size/L

#1704 Update Doc: Credential Management
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/zh/docs/devops-user-guide/how-to-use/credential-management.md
  static/images/docs/devops-user-guide/using-devops/credential-management/create-credential-page.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/create-credential-page.png
  static/images/docs/devops-user-guide/using-devops/credential-management/create-credential-step1.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/create-credential-step1.png
  static/images/docs/devops-user-guide/using-devops/credential-management/credential-detail-page.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/credential-detail-page.png
  static/images/docs/devops-user-guide/using-devops/credential-management/credentials-list.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/credentials-list.png
  static/images/docs/devops-user-guide/using-devops/credential-management/dockerhub-credentials.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/dockerhub-credentials.png
  static/images/docs/devops-user-guide/using-devops/credential-management/edit-credentials.jpg
  static/images/docs/devops-user-guide/using-devops/credential-management/edit-credentials.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/create-credential-page.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/create-credential_page.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential-detail-page.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential-detail_page.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential-list.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/credential_list.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/dockerhub-credentials.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/dockerhub_credentials.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/edit-credentials.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/credential-management/edit_credentials.png
Labels: approved, lgtm, size/S

#1705 Update Doc: Set the Email Server for KubeSphere Pipelines
  content/en/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-email.md
  static/images/docs/devops-user-guide/using-devops/jenkins-email/clusters-management.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-email/three-dots.png
  static/images/docs/devops-user-guide/using-devops/jenkins-email/workloads-list.jpg
  static/images/docs/devops-user-guide/using-devops/jenkins-email/workloads-list.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/clusters-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/three-dots.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/workloads-list.PNG
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-email-server-for-kubesphere-pipelines/workloads_list.png
Labels: approved, lgtm, size/S

#1706 Update Doc: Set a CI Node for Dependency Caching
  content/en/docs/devops-user-guide/how-to-use/set-ci-node.md
  content/zh/docs/devops-user-guide/how-to-use/set-ci-node.md
  static/images/docs/devops-user-guide/using-devops/set-ci-node-for-dependency-cache/clusters-management.jpg
  static/images/docs/devops-user-guide/using-devops/set-ci-node-for-dependency-cache/set-node-1.png
  static/images/docs/devops-user-guide/using-devops/set-ci-node-for-dependency-cache/set-node-2.png
  static/images/docs/devops-user-guide/using-devops/set-ci-node-for-dependency-cache/set-node-3.png
  static/images/docs/devops-user-guide/using-devops/set-ci-node-for-dependency-cache/set-node-4.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/add-ci-label.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/add-taint.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/clusters-management.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/select-ci-node.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/set-ci-node-for-dependency-caching/select-taint-management.png
Labels: approved, lgtm, size/S

#1621 Add ZH Doc: Configure WeCom Notification
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-wecom.md
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/add-dept.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/add-member-to-tag.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/add-member.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/add-tag.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/app-created.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/app-detail.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/click-create-app.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/company-id.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/create-app.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/create-tag.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/dept-id.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/enter-dept-name.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/member-account.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/notification_message.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/platform.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/set-access.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/tag-id.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/three-dots.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-wecom/view-secret.png
Labels: approved, lgtm, size/L

#1710 Update authentication configuration docs
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/zh/docs/access-control-and-account-management/configuring-authentication.md
Labels: approved, lgtm, size/S

#1709 Update Doc: Build and Deploy a Go Project
  content/en/docs/devops-user-guide/examples/go-project-pipeline.md
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-dockerhub-id.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-dockerhub-id.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline-2.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/create-pipeline.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/edit-jenkinsfile.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/pipeline-running.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/pipeline-running.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/run-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/run-pipeline.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/set-pipeline-name.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/set-pipeline-name.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/view-deployments.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-project/view-deployments.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-dockerhub-id.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/create-dockerhub_id.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/credential-docker-create.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/credential-docker_create.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/edit_jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/pipeline-running.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/pipeline_running.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/run-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/run_pipeline.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/view-deployment.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-a-go-project/view_deployment.png
Labels: approved, lgtm, size/M

#1693 Update app store notes
  content/en/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/app-store.md
Labels: approved, lgtm, size/XS

#1712 Update Doc: Build and Deploy a Maven Project
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/run-maven-pipeline.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-credential-list.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-namespace.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-pipeline.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-workload-svc.png
  static/images/docs/devops-user-guide/examples/build-and-deploy-a-maven-project/view-result-maven-workload.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/edit_jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/run-maven-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/run-maven_pipeline.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-credential-lists.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-credential_lists.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-edit_jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-namespace.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-workload-svc.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-workload.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven-workload_svc.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven_pipeline.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view-result-maven_workload.png
  static/images/docs/zh-cn/devops-user-guide/examples/build-and-deploy-maven-project/view_namespace.png
Labels: size/M

#1708 Update login failed faq docs
  content/en/docs/faq/access-control/cannot-login.md
  content/en/docs/faq/access-control/session-timeout.md
  content/zh/docs/faq/access-control/cannot-login.md
  content/zh/docs/faq/access-control/session-timeout.md
  static/images/docs/faq/access-control-and-account-management/cannot-login/forbidden.jpg
Labels: approved, lgtm, size/M

#1715 Update account login failure faq
  content/en/docs/faq/access-control/cannot-login.md
  content/en/docs/faq/access-control/session-timeout.md
  content/zh/docs/faq/access-control/cannot-login.md
Labels: approved, size/M

#1716 Update Doc: Install Plugins to Jenkins in KubeSphere
  content/en/docs/faq/devops/install-jenkins-plugins.md
  content/zh/docs/faq/devops/install-jenkins-plugins.md
  static/images/docs/faq/devops/install-plugins-to-jenkins/available-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-advanced-tab.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-manage-jenkins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/click-manage-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/installed-plugins.png
  static/images/docs/faq/devops/install-plugins-to-jenkins/update-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/available-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-advanced-tab.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-jenkins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/installed-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/update-plugins.png
Labels: approved, lgtm, size/XS

#1717 Update Images in Doc: Create a DevOps Kubeconfig on AWS
  static/images/docs/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
  static/images/docs/zh-cn/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
Labels: approved, lgtm, size/XS

#1719 Update Doc: Remove Built-in Apps in KubeSphere
  content/en/docs/faq/applications/remove-built-in-apps.md
  content/zh/docs/faq/applications/remove-built-in-apps.md
  static/images/docs/faq/applications/remove-built-in-apps/activate-tomcat.PNG
  static/images/docs/faq/applications/remove-built-in-apps/activate_tomcat.png
  static/images/docs/faq/applications/remove-built-in-apps/click-platform.PNG
  static/images/docs/faq/applications/remove-built-in-apps/click-tomcat.PNG
  static/images/docs/faq/applications/remove-built-in-apps/click_tomcat.png
  static/images/docs/faq/applications/remove-built-in-apps/confirm-suspend.PNG
  static/images/docs/faq/applications/remove-built-in-apps/confirm_suspend.png
  static/images/docs/faq/applications/remove-built-in-apps/select-app-store-management.PNG
  static/images/docs/faq/applications/remove-built-in-apps/suspend-tomcat.PNG
  static/images/docs/faq/applications/remove-built-in-apps/suspend_tomcat.png
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/activate-tomcat.png
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/click-tomcat.png
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/confirm-suspend.png
  static/images/docs/zh-cn/faq/applications/remove-built-in-apps/suspend-tomcat.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/activate-tomcat.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/click-platform.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/click-tomcat.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/confirm-suspend.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/select-app-store-management.png
  static/images/docs/zh-cn/faq/remove-built-in-apps/suspend-tomcat.png
Labels: lgtm, size/M

#1727 Add PatrickLuoYu to the owners.
  OWNERS
Labels: lgtm, size/XS

#1713 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-beijing.md
  content/zh/live/meetup-chengdu.md
  layouts/live/list.html
  static/images/live/meetup-chengdu-kv.png
Labels: approved, lgtm, size/L

#1729 Some content changes for SEO
  content/en/_index.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
Labels: approved, lgtm, size/S

#1728 Some content changes for SEO
  content/en/_index.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
Labels: approved, lgtm, size/S

#1724 Update Image in S2I Doc
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build_settings.png
Labels: approved, lgtm, size/XS

#1725 Update Image in S2I Doc-v3.0
  content/zh/docs/project-user-guide/image-builder/source-to-image.md
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build-settings.PNG
  static/images/docs/zh-cn/project-user-guide/image-builder/source-to-image/build_settings.png
Labels: approved, lgtm, size/XS

#1735 Fix image
  content/zh/docs/workspace-administration/what-is-workspace.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/workspace-overview/delete_workspace.png
Labels: dco-signoff: yes, size/XS

#1736 update the page of live
  content/zh/live/_index.md
  content/zh/live/apisix-chengdu.md
  content/zh/live/baas-chengdu.md
  content/zh/live/hpa-chengdu.md
  content/zh/live/meetup-chengdu.md
  content/zh/live/multicluster-chengdu.md
  content/zh/live/tideng-chengdu.md
  layouts/live/list.html
Labels: approved, lgtm, size/L

#1741 update iframe width in live page
  assets/scss/live-detail.scss
Labels: size/XS

#1742 update the header of zh website
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1740 Update docs web-kubectl
  content/en/docs/toolbox/web-kubectl.md
  content/zh/docs/toolbox/web-kubectl.md
  static/images/docs/web-kubectl/web-kubectl-cluster-select.png
  static/images/docs/web-kubectl/web-kubectl-enter.png
  static/images/docs/web-kubectl/web-kubectl-example.png
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-cluster-select.PNG
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-enter.PNG
  static/images/docs/zh-cn/toolbox/web-kubectl/web-kubectl-example.PNG
Labels: size/XS

#1739 Updated docs change-console-language
  content/en/docs/faq/console/change-console-language.md
  content/zh/docs/faq/console/change-console-language.md
  static/images/docs/faq/kubesphere-web-console/change-console-language/basic-info-page.jpg
  static/images/docs/faq/kubesphere-web-console/change-console-language/basic-information-page.png
  static/images/docs/faq/kubesphere-web-console/change-console-language/user-settings.jpg
  static/images/docs/faq/kubesphere-web-console/change-console-language/user-settings.png
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/basic-info-page.jpg
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/basic-information-page.png
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/user-settings.jpg
  static/images/docs/zh-cn/faq/kubesphere-web-console/change-console-language/user-settings.png
Labels: size/S

#1746 更新文字错误
  content/zh/docs/introduction/advantages.md
Labels: approved, lgtm, size/XS

#1744 Minor cn fix
  content/zh/docs/introduction/features.md
  content/zh/docs/introduction/what-is-kubesphere.md
Labels: approved, lgtm, size/XS

#1752 update email, footer, and header, add Azure as a new provider
  content/en/_index.md
  content/en/case/_index.md
  content/en/docs/_index.md
  content/en/privacy/_index.md
  content/zh/_index.md
  content/zh/case/_index.md
  content/zh/docs/_index.md
  content/zh/privacy/_index.md
  data/en/footer.yaml
  data/zh/footer.yaml
  i18n/en.yaml
  i18n/tr.yaml
  i18n/zh.yaml
  layouts/docs/second.html
  layouts/docs/single.html
  layouts/partials/footer.html
  layouts/partials/header.html
  static/images/docs/microsoft-azure.jpg
  static/json/crd-3.1.json
  static/json/crd.json
  static/json/kubesphere-3.1.json
  static/json/kubesphere.json
Labels: approved, lgtm, size/M

#1754 update footer
  data/zh/footer.yaml
Labels: approved, lgtm, size/XS

#1721 Update Doc: Deploy Apps in a Multi-cluster Project Using a Jenkinsfile
  content/en/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-dockerhub-id.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-dockerhub-id.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline-2.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline-2.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/create-pipeline.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/edit-jenkinsfile.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/multi-cluster-ok.png
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/set-pipeline-name.jpg
  static/images/docs/devops-user-guide/examples/compile-and-deploy-a-go-multi-cluster-project/set-pipeline-name.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-dockerhub-id-1.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-dockerhub-id.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-pipeline-2.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-pipeline.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create-pipeline_2.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/create_pipeline.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/credential-docker-create.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/credential-docker.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/edit-jenkinsfile.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/edit_jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/multi-cluster-ok.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/multi-cluster_ok.png
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/set-pipeline-name.PNG
  static/images/docs/zh-cn/devops-user-guide/examples/deploy-apps-in-multicluster-project-using-jenkinsfile/set-pipeline_name.png
Labels: lgtm, size/L

#1731 Add Doc: Use Jenkins Shared Libraries in a Pipeline
  content/en/docs/devops-user-guide/how-to-use/jenkins-shared-library.md
  content/zh/docs/devops-user-guide/how-to-use/jenkins-shared-library.md
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/click-add.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/click-configure.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/click-create.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/click-run.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/configure-shared-library.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/edit-jenkinsfile.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/log-details.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/run-successfully.png
  static/images/docs/devops-user-guide/using-devops/jenkins-shared-library/set-name.png
Labels: size/L

#1743 Add EN Doc: Use Nexus in Pipelines
  content/en/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/click-edit-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/click-edit-yaml.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/click-edit.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/click-pom.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/click-run.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/enter-jenkinsfile.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/enter-mirror-code.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/enter-server-code.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/gear.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/github-edit-icon.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/ks-devops-agent.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/maven-public-url.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/maven-public.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/maven-snapshots.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/modify-pom.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/pipeline-logs.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/pipeline-success.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/repo-type.png
  static/images/docs/devops-user-guide/examples/use-nexus-in-pipeline/set-pipeline-name.png
Labels: size/L

#1759 add keywords and description for 'content/zh/blogs/arm64-kubernetes-k…
  content/zh/blogs/arm64-kubernetes-kubesphere.md
Labels: approved, lgtm, size/XS

#1726 deploy-clickhouse: Add the repository link
  content/en/docs/application-store/external-apps/deploy-clickhouse.md
  content/zh/docs/application-store/external-apps/deploy-clickhouse.md
Labels: dco-signoff: no, do-not-merge/hold, lgtm, size/XS

#1764 add a new blog of KubeEye-automatic-cluster-diagnostic-tool
  content/zh/blogs/KubeEye-automatic-cluster-diagnostic-tool.md
Labels: approved, lgtm, size/L

#1760 change link in contribution page
  content/en/contribution/_index.md
  content/zh/contribution/_index.md
Labels: approved, lgtm, size/XS

#1768 update 'content/zh/blogs/arm64-kubernetes-kubesphere.md'
  content/zh/blogs/arm64-kubernetes-kubesphere.md
Labels: approved, lgtm, size/XS

#1765 add a new blog of use-KubeKey-to-install-and-deploy-Kubernetes-and-ku…
  content/zh/blogs/use-KubeKey-to-install-and-deploy-Kubernetes-and-kubeovn.md
Labels: approved, lgtm, size/L
