Repository kubesphere/website, pull requests merged in 2021-09, with the labels that each got.

#1914 new blog of gitops-argocd
  content/zh/blogs/gitops-argocd.md
Labels: approved, lgtm, size/L

#1917 new blog of kubesphere-edgenode-ip
  content/zh/blogs/kubesphere-edgenode-ip.md
Labels: approved, lgtm, size/M

#1916 new blog of edge-node-monitoring
  content/zh/blogs/edge-node-monitoring.md
Labels: approved, lgtm, size/L

#1915 new blog of kubesphere-core-architecture
  content/zh/blogs/kubesphere-core-architecture.md
Labels: approved, lgtm, size/L

#1921 add kubernetes-ai.md
  content/zh/blogs/kubernetes-ai.md
Labels: approved, lgtm, size/L

#1922 update the page of live
  content/zh/live/_index.md
  content/zh/live/nebula0902-live.md
  content/zh/live/wasm0909-live.md
  static/images/live/native-live-cover.png
Labels: approved, lgtm, size/M

#1912 Content amends for seo
  content/en/blogs/multi-cluster-deployment.md
  content/en/blogs/understand-requests-and-limits-in-kubernetes.md
  content/en/docs/application-store/app-lifecycle-management.md
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-linux/cluster-operation/remove-nodes.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
Labels: approved, lgtm, size/M

#1920 Add Serverless-way-for-Kubernetes-Log-Alerting.md
  content/zh/blogs/Serverless-way-for-Kubernetes-Log-Alerting.md
Labels: approved, lgtm, size/L

#1925 Minor Fix in EN Harbor Doc
  content/en/docs/application-store/built-in-apps/harbor-app.md
Labels: approved, lgtm, size/XS

#1926 new blog of Kasten-K10-KubeSphere
  content/zh/blogs/Kasten-K10-KubeSphere.md
Labels: approved, lgtm, size/L

#1927 add kubesphere-route.md
  content/zh/blogs/kubesphere-route.md
Labels: approved, lgtm, size/L

#1923 Update harbor-app.md
  content/zh/docs/application-store/built-in-apps/harbor-app.md
Labels: approved, lgtm, size/XS

#1933 fix: Replace h3 with h2 tag
  assets/scss/scenario.scss
  layouts/_default/scenario.html
Labels: approved, lgtm, size/XS

#1929 fix: some url no content pages
  content/en/docs/faq/access-control/_index.md
  content/en/docs/faq/applications/_index.md
  content/en/docs/faq/console/_index.md
  content/en/docs/faq/devops/_index.md
  content/en/docs/faq/installation/_index.md
  content/en/docs/faq/multi-cluster-management/_index.md
  content/en/docs/faq/observability/_index.md
  content/en/docs/faq/upgrade/_index.md
  content/zh/docs/faq/access-control/_index.md
  content/zh/docs/faq/applications/_index.md
  content/zh/docs/faq/console/_index.md
  content/zh/docs/faq/devops/_index.md
  content/zh/docs/faq/installation/_index.md
  content/zh/docs/faq/multi-cluster-management/_index.md
  content/zh/docs/faq/observability/_index.md
  content/zh/docs/faq/upgrade/_index.md
Labels: approved, lgtm, size/S

#1930 Update _index.md
  content/en/service-mesh/_index.md
Labels: approved, lgtm, size/S

#1936 fix: Support custom title tag in case page, eg: zto
  assets/scss/case-detail.scss
  content/zh/case/zto.md
  layouts/case/single.html
  layouts/partials/case_specialContent.html
Labels: approved, lgtm, size/M

#1937 update the page of live
  content/zh/live/_index.md
  content/zh/live/uisee0916-live.md
  content/zh/live/wasm0909-live.md
  static/images/live/0909-native-live-cover.png
  static/images/live/native-live-cover.png
Labels: approved, lgtm, size/M

#1938 fix: Custome case page title
  layouts/case/single.html
  layouts/partials/case_specialContent.html
Labels: approved, lgtm, size/XS

#1942 Fix Relative Path Bug in Uninstall Components Docs
  content/en/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
Labels: approved, lgtm, size/XS

#1939 new case of hongyaa
  content/zh/case/_index.md
  content/zh/case/hongyaa.md
Labels: approved, lgtm, size/L

#1940 new blog of logging-alert-notifaction
  content/zh/blogs/logging-alert-notifaction.md
Labels: approved, lgtm, size/L

#1954 update youtube channel link with an alternative nicer link
  config/upstream/config.toml
Labels: approved, lgtm, size/XS

#1952 Refine Words in Features ZH Doc
  content/zh/docs/introduction/features.md
Labels: approved, lgtm, size/XS

#1951 Add Tutorial Video in Canary Release ZH Doc
  content/zh/docs/project-user-guide/grayscale-release/canary-release.md
Labels: approved, lgtm, size/XS

#1950 Add Tutorial Video in WordPress ZH Doc
  content/zh/docs/quick-start/wordpress-deployment.md
Labels: approved, lgtm, size/XS

#1755 Add a doc: Deploy Litmus on KubeSphere
  content/en/docs/application-store/external-apps/deploy-litmus.md
  static/images/docs/appstore/external-apps/deploy-litmus/checkmark.png
  static/images/docs/appstore/external-apps/deploy-litmus/imported-successfully.png
  static/images/docs/appstore/external-apps/deploy-litmus/litmus-login-1.png
  static/images/docs/appstore/external-apps/deploy-litmus/litmus-login-page.png
  static/images/docs/appstore/external-apps/deploy-litmus/litmus-nodeport.png
  static/images/docs/appstore/external-apps/deploy-litmus/litmus-running.png
  static/images/docs/appstore/external-apps/deploy-litmus/litmus-successful.png
  static/images/docs/appstore/external-apps/deploy-litmus/nginx-replica.png
  static/images/docs/appstore/external-apps/deploy-litmus/one-pod-left.png
  static/images/docs/appstore/external-apps/deploy-litmus/packet-loss-rate.png
  static/images/docs/appstore/external-apps/deploy-litmus/pod-cpu-hog.png
  static/images/docs/appstore/external-apps/deploy-litmus/terminate-and-recreate.png
Labels: approved, lgtm, size/L

#1949 Add Tutorial Video in Bookinfo ZH Doc
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
Labels: approved, lgtm, size/XS

#1955 new case of chinamobile-iot
  content/zh/case/_index.md
  content/zh/case/chinamobile-iot.md
  static/images/case/chinamobile-iot.png
Labels: approved, lgtm, size/L

#1928 Update _index.md
  content/en/observability/_index.md
Labels: approved, lgtm, size/S

#1842 Add EN Doc: Trigger a Pipeline via a WebHook
  content/en/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/add-webhook.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/click-add-webhook.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/click-file.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/click-sonar.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/delivery-detail.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/edit-btn.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/edit-config.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/edit-file.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/pipeline-triggered.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/pods.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/webhook-push.png
  static/images/docs/devops-user-guide/using-devops/pipeline-webhook/webhook-ready.png
Labels: approved, area/devops, lgtm, size/L

#1965 add view count
  i18n/en.yaml
  i18n/zh.yaml
  layouts/partials/content.html
Labels: approved, lgtm, size/S

#1963 Minor Update in Nexus EN Doc
  content/en/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
Labels: approved, lgtm, size/XS

#1967 update the page of live
  content/zh/live/_index.md
  content/zh/live/uisee0923-live.md
  content/zh/live/yunda0930-live.md
  static/images/live/cloudnative-live-cover.png
Labels: approved, lgtm, size/M

#1947 new blog of kubesphere-container-2020
  content/zh/blogs/kubesphere-container-2020.md
Labels: approved, lgtm, size/M

#1975 Minor change in homepage title
  content/en/_index.md
Labels: approved, lgtm, size/XS

#1941 fourth task
  content/zh/docs/devops-user-guide/how-to-use/jenkins-shared-library.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/click-add.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/click-configure.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/click-create.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/click-run.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/configure-shared-library.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/edit-jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/log-details.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/run-successfully.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/jenkins-shared-library/set-name.png
Labels: approved, lgtm, size/L

#1961 sixth task
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
Labels: approved, lgtm, size/L

#1970 seventh task
  content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/click-edit-jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/click-edit-yaml.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/click-edit.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/click-pom.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/click-run.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/enter-jenkinsfile.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/enter-mirror-code.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/enter-server-code.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/gear.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/github-edit-icon.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/ks-devops-agent.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/maven-public-url.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/maven-public.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/maven-snapshots.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/modify-pom.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/pipeline-logs.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/pipeline-success.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/repo-type.png
  static/images/docs/zh-cn/devops-user-guide/examples/use-nexus-in-pipeline/set-pipeline-name.png
Labels: approved, lgtm, size/L

#1972 eighthtask
  content/zh/docs/devops-user-guide/how-to-use/pipeline-webhook.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/add-webhook.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/click-add-webhook.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/click-file.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/click-sonar.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/delivery-detail.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/edit-btn.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/edit-config.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/edit-file.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/pipeline-triggered.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/pods.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/webhook-push.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-webhook/webhook-ready.png
Labels: approved, lgtm, size/M

#1980 tenth task
  content/zh/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks.md
Labels: approved, lgtm, size/M

#1977 add a blog: Install Kubernetes 1.22 and containerd the Easy Way
  content/en/blogs/install-kubernetes-containerd.md
  static/images/blogs/en/kubekey-containerd/k8s-containerd.png
Labels: approved, lgtm, size/L

#1981 add a blog about Kasten K10
  content/en/blogs/Kubernetes-Backup-and-Restore-with-Kasten-K10 on-KubeSphere.md
  static/images/blogs/en/kastenk10image/KastenK10-architecture.png
  static/images/blogs/en/kastenk10image/kastenk10-step10.png
  static/images/blogs/en/kastenk10image/kastenk10-step11.png
  static/images/blogs/en/kastenk10image/kastenk10-step12.png
  static/images/blogs/en/kastenk10image/kastenk10-step13.png
  static/images/blogs/en/kastenk10image/kastenk10-step14.png
  static/images/blogs/en/kastenk10image/kastenk10-step15.png
  static/images/blogs/en/kastenk10image/kastenk10-step16.png
  static/images/blogs/en/kastenk10image/kastenk10-step17.png
  static/images/blogs/en/kastenk10image/kastenk10-step18.png
  static/images/blogs/en/kastenk10image/kastenk10-step19.png
  static/images/blogs/en/kastenk10image/kastenk10-step20.png
  static/images/blogs/en/kastenk10image/kastenk10-step21.png
  static/images/blogs/en/kastenk10image/kastenk10-step22.png
  static/images/blogs/en/kastenk10image/kastenk10-step23.png
  static/images/blogs/en/kastenk10image/kastenk10-step24.png
  static/images/blogs/en/kastenk10image/kastenk10-step25.png
  static/images/blogs/en/kastenk10image/kastenk10-step26.png
  static/images/blogs/en/kastenk10image/kastenk10-step27.png
  static/images/blogs/en/kastenk10image/kastenk10-step28.png
  static/images/blogs/en/kastenk10image/kastenk10-step3.png
  static/images/blogs/en/kastenk10image/kastenk10-step4.png
  static/images/blogs/en/kastenk10image/kastenk10-step5.png
  static/images/blogs/en/kastenk10image/kastenk10-step6.png
  static/images/blogs/en/kastenk10image/kastenk10-step7.png
  static/images/blogs/en/kastenk10image/kastenk10-step8.png
  static/images/blogs/en/kastenk10image/kastenk10-step9.png
  static/images/blogs/en/kastenk10image/kubesphere-architecture.png
Labels: approved, lgtm, size/L

#1971 update the page of live
  content/zh/live/_index.md
  content/zh/live/yunda1014-live.md
Labels: approved, lgtm, size/S
