Repository kubesphere/website, pull requests merged in 2021-04, with the labels that each got.

#1233 Add a blog: Embracing Microservices: What You Need to Know
  content/en/blogs/embracing-microservices-what-you-need-to-know.md
  static/images/blogs/en/embracing-microservices-what-you-need-to-know/ecommerce-platform.png
  static/images/blogs/en/embracing-microservices-what-you-need-to-know/microservices-banner.png
Labels: size/L

#1260 maxnerva case translated
  content/zh/case/maxnerva.md
Labels: lgtm, size/L

#1129 generate index page for each chapter automatically
  content/en/docs/access-control-and-account-management/_index.md
  content/en/docs/application-store/_index.md
  content/en/docs/cluster-administration/_index.md
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/faq/_index.md
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/introduction/_index.md
  content/en/docs/multicluster-management/_index.md
  content/en/docs/pluggable-components/_index.md
  content/en/docs/project-administration/_index.md
  content/en/docs/project-user-guide/_index.md
  content/en/docs/quick-start/_index.md
  content/en/docs/reference/_index.md
  content/en/docs/release/_index.md
  content/en/docs/toolbox/_index.md
  content/en/docs/upgrade/_index.md
  content/en/docs/workspace-administration/_index.md
  content/zh/docs/access-control-and-account-management/_index.md
  content/zh/docs/api-reference/_index.md
  content/zh/docs/application-store/_index.md
  content/zh/docs/cluster-administration/_index.md
  content/zh/docs/devops-user-guide/_index.md
  content/zh/docs/faq/_index.md
  content/zh/docs/installing-on-kubernetes/_index.md
  content/zh/docs/installing-on-linux/_index.md
  content/zh/docs/introduction/_index.md
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/project-administration/_index.md
  content/zh/docs/project-user-guide/_index.md
  content/zh/docs/quick-start/_index.md
  content/zh/docs/release/_index.md
  content/zh/docs/toolbox/_index.md
  content/zh/docs/upgrade/_index.md
  content/zh/docs/workspace-administration/_index.md
  layouts/docs/second.html
Labels: approved, lgtm, size/XXL

#1302 generate index page for each chapter automatically
  content/en/docs/access-control-and-account-management/_index.md
  content/en/docs/api-reference/_index.md
  content/en/docs/application-store/_index.md
  content/en/docs/cluster-administration/_index.md
  content/en/docs/devops-user-guide/_index.md
  content/en/docs/faq/_index.md
  content/en/docs/installing-on-kubernetes/_index.md
  content/en/docs/installing-on-linux/_index.md
  content/en/docs/introduction/_index.md
  content/en/docs/multicluster-management/_index.md
  content/en/docs/pluggable-components/_index.md
  content/en/docs/project-administration/_index.md
  content/en/docs/project-user-guide/_index.md
  content/en/docs/quick-start/_index.md
  content/en/docs/release/_index.md
  content/en/docs/toolbox/_index.md
  content/en/docs/upgrade/_index.md
  content/en/docs/workspace-administration/_index.md
  content/zh/docs/access-control-and-account-management/_index.md
  content/zh/docs/api-reference/_index.md
  content/zh/docs/application-store/_index.md
  content/zh/docs/cluster-administration/_index.md
  content/zh/docs/devops-user-guide/_index.md
  content/zh/docs/faq/_index.md
  content/zh/docs/installing-on-kubernetes/_index.md
  content/zh/docs/installing-on-linux/_index.md
  content/zh/docs/introduction/_index.md
  content/zh/docs/multicluster-management/_index.md
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/project-administration/_index.md
  content/zh/docs/project-user-guide/_index.md
  content/zh/docs/quick-start/_index.md
  content/zh/docs/release/_index.md
  content/zh/docs/toolbox/_index.md
  content/zh/docs/upgrade/_index.md
  content/zh/docs/workspace-administration/_index.md
  layouts/docs/second.html
Labels: lgtm, size/XXL

#1305 SEO Titles Fixes
  content/en/_index.md
  content/en/blogs/_index.md
  content/en/devops/_index.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/role-and-member-management.md
  content/en/docs/faq/access-control/_index.md
  content/en/docs/faq/observability/_index.md
  content/en/docs/faq/observability/logging.md
  content/en/docs/faq/observability/monitoring.md
  content/en/docs/faq/upgrade/_index.md
  content/en/docs/installing-on-kubernetes/introduction/overview.md
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/introduction/_index.md
  content/en/docs/multicluster-management/introduction/overview.md
  content/en/docs/pluggable-components/overview.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/project-user-guide/custom-application-monitoring/introduction.md
  content/en/docs/project-user-guide/custom-application-monitoring/visualization/overview.md
  content/en/docs/project-user-guide/grayscale-release/overview.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/upgrade/overview.md
  content/en/docs/workspace-administration/role-and-member-management.md
  content/en/observability/_index.md
  content/en/projects/_index.md
  content/en/videos/_index.md
Labels: lgtm, size/M

#1306 Update readme
  README.md
Labels: approved, lgtm, size/M

#1308 add modal
  assets/scss/footer.scss
  assets/scss/index.scss
  config/_default/config.toml
  config/upstream-zh/config.toml
  config/upstream/config.toml
  i18n/en.yaml
  i18n/zh.yaml
  layouts/index.html
  layouts/partials/footer.html
  static/images/footer/bilibili-hover.svg
  static/images/footer/bilibili.svg
  static/images/home/close.svg
  static/images/home/modal-bg.svg
  static/images/home/modal-content.svg
  static/images/home/slack.svg
  static/images/home/wechat.svg
Labels: approved, lgtm, size/XL

#1309 add modal
  assets/scss/footer.scss
  assets/scss/index.scss
  config/_default/config.toml
  config/upstream-zh/config.toml
  config/upstream/config.toml
  i18n/en.yaml
  i18n/zh.yaml
  layouts/index.html
  layouts/partials/footer.html
  static/images/footer/bilibili-hover.svg
  static/images/footer/bilibili.svg
  static/images/home/close.svg
  static/images/home/modal-bg.svg
  static/images/home/modal-content.svg
  static/images/home/slack.svg
  static/images/home/wechat.svg
Labels: approved, lgtm, size/XL

#1311 update wechat image
  layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#1310 update wechat image
  layouts/partials/footer.html
Labels: lgtm, size/XS

#1303 Edit create-workspaces-projects-accounts-and-roles-en.
  content/en/docs/quick-start/create-workspace-and-project.md
  static/images/docs/quickstart/create-workspaces-projects-accounts/operation-icon.png
Labels: lgtm, size/M

#1258 Translated the Observability page.
  content/zh/observability/_index.md
Labels: lgtm, size/M

#1314 Add email configuration guide in doc 3.1
  content/en/docs/cluster-administration/cluster-settings/mail-server.md
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  static/images/docs/alerting/mail_server_config.png
  static/images/docs/alerting/mail_server_guide.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-email/email-server.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-email/example-email-notification.png
Labels: lgtm, size/M

#1299 Add slack notification config guide in doc 3.1
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-slack/add-app.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-slack/example-notification.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-slack/oauth-token.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-slack/slack-notification.png
  static/images/docs/cluster-administration/platform-settings/notification-management/configure-slack/slack-scope.png
Labels: lgtm, size/M

#1325 Updated create-workspace-and-project-zh
  content/zh/docs/quick-start/create-workspace-and-project.md
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/operation-icon.png
Labels: size/M

#1270 Add enable Pod IP Pool and Topology guide
  content/en/docs/pluggable-components/pod-ip-pools.md
  content/en/docs/pluggable-components/service-topology.md
  static/images/docs/enable-pluggable-components/pod-ip-pools/pod-ip-pool.png
  static/images/docs/enable-pluggable-components/service-topology/topology.png
Labels: size/L

#1328 fix format in metrics server guide
  content/zh/docs/pluggable-components/metrics-server.md
Labels: size/XS

#1284 Add enable metering guide
  content/en/docs/pluggable-components/metering.md
  static/images/docs/enable-pluggable-components/kubesphere-metering/metering.png
Labels: size/M

#1330 Add set-up-external-authentication-en and change directory structure.
  content/en/docs/access-control-and-account-management/configuring-authentication.md
  content/en/docs/access-control-and-account-management/external-authentication/_index.md
  content/en/docs/access-control-and-account-management/external-authentication/oauth2.md
  content/en/docs/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  static/images/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/toolbox.png
Labels: size/L

#1332 Add Pipeline Settings
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/basic-info-tab.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/behavioral-strategy.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/branch-settings.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-settings.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-trigger-2.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-trigger.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-bitbucket.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-git.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-github.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-gitlab.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-svn.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/git-clone-options.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/parametric-build.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/scan-repo-trigger.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/script-path.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/webhook-push.png
Labels: lgtm, size/L

#1335 Add Pipeline Settings in v3.0
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/basic-info-tab.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/behavioral-strategy.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/branch-settings.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-settings.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-triger-2.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/build-trigger.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-git.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-bitbucket.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-github.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/code-source-svn.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/git-clone-options.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/parametric-build.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/scan-repo-trigger.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/script-path.png
  static/images/docs/devops-user-guide/using-devops/pipeline-settings/webhook.png
Labels: lgtm, size/L

#1321 Add New Doc in 3.0-DevOps Data Migration during Update
  content/en/docs/upgrade/devops-data-migration-upgrade.md
  content/zh/docs/upgrade/devops-data-migration-upgrade.md
  static/images/docs/upgrade/devops-data-migration-upgrade/configurations-not-supported.png
  static/images/docs/upgrade/devops-data-migration-upgrade/devops-2-1-architecture.png
  static/images/docs/upgrade/devops-data-migration-upgrade/devops-3-0-architecture.png
Labels: lgtm, size/L

#1338 Modified pipeline-settings-en
  content/en/docs/devops-user-guide/how-to-use/pipeline-settings.md
Labels: lgtm, size/XS

#1336 Translated pipeline-settings
  content/zh/docs/devops-user-guide/how-to-use/pipeline-settings.md
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/basic-info-tab.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/behavioral-strategy.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/branch-settings.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-settings.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-trigger-2.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/build-trigger.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-git.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-bitbucket.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-github.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/code-source-svn.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/git-clone-options.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/parametric-build.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/scan-repo-trigger.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/script-path.png
  static/images/docs/zh-cn/devops-user-guide/use-devops/pipeline-settings/webhook.png
Labels: lgtm, size/L

#1340 Dockershim-blog typo fixed
  content/zh/blogs/dockershim-out-of-kubernetes.md
Labels: lgtm, size/XS

#1322 Add doc department-management-en.
  content/en/docs/workspace-administration/department-management.md
  static/images/docs/workspace-administration/department-management/assign.png
  static/images/docs/workspace-administration/department-management/edit.png
  static/images/docs/workspace-administration/department-management/remove.png
Labels: lgtm, size/M

#1341 Translated data-migration-during-upgrade
  content/zh/docs/upgrade/devops-data-migration-upgrade.md
  static/images/docs/zh-cn/upgrade/devops-data-migration-upgrade/configurations-not-supported.png
  static/images/docs/zh-cn/upgrade/devops-data-migration-upgrade/devops-2-1-architecture.png
  static/images/docs/zh-cn/upgrade/devops-data-migration-upgrade/devops-3-0-architecture.png
Labels: lgtm, size/M

#1344 Translated create-devops-kubeconfig-on-aws
  content/zh/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  static/images/docs/zh-cn/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
  static/images/docs/zh-cn/faq/devops/create-devops-kubeconfig-on-aws/get-token.jpg
Labels: lgtm, size/M

#1343 Translated install-Jenkins-plugins
  content/zh/docs/faq/devops/install-jenkins-plugins.md
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/available-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-advanced-tab.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-jenkins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/installed-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/update-plugins.png
Labels: size/M

#1347 Translated create-devops-kubeconfig-on-aws
  content/zh/docs/faq/devops/create-devops-kubeconfig-on-aws.md
  static/images/docs/zh-cn/faq/devops/create-devops-kubeconfig-on-aws/create-kubeconfig.png
  static/images/docs/zh-cn/faq/devops/create-devops-kubeconfig-on-aws/get-token.jpg
Labels: lgtm, size/M

#1348 Translated install-Jenkins-plugins
  content/zh/docs/faq/devops/install-jenkins-plugins.md
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/available-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-advanced-tab.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-jenkins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/click-manage-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/installed-plugins.png
  static/images/docs/zh-cn/faq/devops/install-plugins-to-jenkins/update-plugins.png
Labels: lgtm, size/M

#1339 Add EN Version of KubeSphere DevOps Automated Testing Blog
  content/en/blogs/devops-automatic-testing.md
  static/images/blogs/en/devops-automatic-testing/api-test.png
  static/images/blogs/en/devops-automatic-testing/golang-test.png
  static/images/blogs/en/devops-automatic-testing/ui-test.png
Labels: lgtm, size/L

#1349 Add EN Version of KubeSphere DevOps Automated Testing Blog
  content/en/blogs/devops-automatic-testing.md
  static/images/blogs/en/devops-automatic-testing/api-test.png
  static/images/blogs/en/devops-automatic-testing/golang-test.png
  static/images/blogs/en/devops-automatic-testing/ui-test.png
Labels: lgtm, size/L

#1350 Fixed typo
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/zh/docs/project-user-guide/application/deploy-app-from-template.md
Labels: lgtm, size/XS

#1351 Fixed typo
  content/en/docs/project-user-guide/application/deploy-app-from-template.md
  content/zh/docs/project-user-guide/application/deploy-app-from-template.md
Labels: size/XS

#1353 Fixed typo
  content/en/docs/project-user-guide/application/deploy-app-from-appstore.md
  content/zh/docs/project-user-guide/application/deploy-app-from-appstore.md
Labels: size/XS

#1354 Remove extra spaces
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
Labels: lgtm, size/XS

#1346 Update node-management-zh-pics
  content/zh/docs/cluster-administration/nodes.md
  static/images/docs/zh-cn/cluster-administration/node-management/Node-Detail.png
  static/images/docs/zh-cn/cluster-administration/node-management/Node-Status.png
  static/images/docs/zh-cn/cluster-administration/node-management/add-taint.png
  static/images/docs/zh-cn/cluster-administration/node-management/add-taints.png
  static/images/docs/zh-cn/cluster-administration/node-management/assign_pods_to_node.png
  static/images/docs/zh-cn/cluster-administration/node-management/assign_pods_to_node1.png
  static/images/docs/zh-cn/cluster-administration/node-management/cluster-management1.png
  static/images/docs/zh-cn/cluster-administration/node-management/clusters-management-select.png
  static/images/docs/zh-cn/cluster-administration/node-management/clusters-select.png
  static/images/docs/zh-cn/cluster-administration/node-management/drop-down-list-node.png
  static/images/docs/zh-cn/cluster-administration/node-management/label-node.png
  static/images/docs/zh-cn/cluster-administration/node-management/label_node.png
  static/images/docs/zh-cn/cluster-administration/node-management/manage-taint.png
  static/images/docs/zh-cn/cluster-administration/node-management/node-drop-down-list.png
  static/images/docs/zh-cn/cluster-administration/node-management/node_detail.png
  static/images/docs/zh-cn/cluster-administration/node-management/node_status.png
  static/images/docs/zh-cn/cluster-administration/node-management/select-a-cluster.png
  static/images/docs/zh-cn/cluster-administration/node-management/taint-management.png
Labels: lgtm, size/S

#1331 Add enable kubeedge guide
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/pluggable-components/kubeedge.md
  static/images/docs/enable-pluggable-components/kubeedge/edge-nodes.png
  static/images/docs/enable-pluggable-components/kubeedge/kubeedge_arch.png
  static/images/docs/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-node-added.png
  static/images/docs/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-node-dialog.png
  static/images/docs/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-watcher.png
  static/images/docs/installing-on-linux/add-and-delete-nodes/add-edge-nodes/kubeedge_arch.png
Labels: lgtm, size/L

#1358 Fix small typos
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/docs/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/project-user-guide/image-builder/binary-to-image.md
Labels: lgtm, size/XS

#1364 Updated sonarqube-pic-zh
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/code-analysis.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-view-result.png
Labels: lgtm, size/XS

#1365 Refine the document of Metering & Billing in Chinese
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
Labels: lgtm, size/M

#1357 SEO (internal links and minor headings improvements)
  content/en/_index.md
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/en/case/vng.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/en/docs/multicluster-management/introduction/overview.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/M

#1369 Typo fixed
  content/en/docs/reference/glossary.md
  content/zh/docs/api-reference/glossary.md
Labels: lgtm, size/XS

#1355 SEO (internal links and minor headings improvements)
  content/en/_index.md
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/en/case/vng.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/en/docs/multicluster-management/introduction/overview.md
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/M

#1367 Translated configure-email
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-email.md
  content/zh/docs/pluggable-components/alerting.md
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-email/email-server.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-email/example-email-notification.png
Labels: lgtm, size/M

#1366 Translated configure-Slack
  content/en/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/zh/docs/cluster-administration/platform-settings/notification-management/configure-slack.md
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-slack/add-app.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-slack/example-notification1.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-slack/oauth-token.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-slack/slack-notification.png
  static/images/docs/zh-cn/cluster-administration/platform-settings/notification-management/configure-slack/slack-scope.png
Labels: lgtm, size/M

#1362 update markdown font
  assets/scss/markdown.scss
Labels: lgtm, size/XS

#1361 update markdown font
  assets/scss/markdown.scss
Labels: lgtm, size/XS

#1345 Add k8s requests and limits blog
  content/en/blogs/understand-requests-and-limits-in-kubernetes.md
  static/images/blogs/en/understand-requests-and-limits-in-kubesphere/cover.png
  static/images/blogs/en/understand-requests-and-limits-in-kubesphere/default-requests-and-limits.png
  static/images/blogs/en/understand-requests-and-limits-in-kubesphere/edit-quota.png
  static/images/blogs/en/understand-requests-and-limits-in-kubesphere/project-quota-page.png
  static/images/blogs/en/understand-requests-and-limits-in-kubesphere/workload-values.jpg
Labels: lgtm, size/L

#1374 Updated sonarqube-pic-zh
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/code-analysis.png
  static/images/docs/zh-cn/devops-user-guide/tool-integration/integrate-sonarqube-into-pipelines/sonarqube-view-result.png
Labels: lgtm, size/XS

#1376 Blog typo fixed
  content/en/conferences/porter.md
Labels: size/XS

#1377 Fixed broken links
  content/en/docs/project-administration/project-gateway.md
  content/zh/docs/project-administration/project-gateway.md
Labels: lgtm, size/XS

#1283 arm64-kubernetes-kubesphere.md
  content/zh/blogs/arm64-kubernetes-kubesphere.md
Labels: approved, lgtm, size/L

#1261 arm64-kubernetes-kubesphere.md
  content/zh/blogs/arm64-kubernetes-kubesphere.md
Labels: approved, lgtm, size/L

#1387 fix home page style
  assets/scss/index.scss
Labels: size/XS

#1386 fix home page style
  assets/scss/index.scss
Labels: size/XS

#1391 Update/add robots 3.0
  config/_default/config.toml
  content/en/api/crd.md
  content/en/api/kubesphere.md
  content/en/contribution/request.md
  content/en/partner/request.md
  content/zh/contribution/request.md
  content/zh/partner/request.md
  layouts/partials/head.html
  layouts/robots.txt
Labels: approved, lgtm, size/S

#1388 update header for operations requirement
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1395 zh-typos fixed
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
Labels: size/S

#1375 Update platform customization doc
  content/en/docs/cluster-administration/platform-settings/customize-basic-information.md
  content/zh/docs/cluster-administration/platform-settings/customize-basic-information.md
Labels: approved, lgtm, size/XS

#1399 Update 3.0 customzation desc
  content/en/docs/cluster-administration/platform-settings.md
  content/zh/docs/cluster-administration/platform-settings.md
Labels: size/XS

#1396 Update pic-zh
  content/zh/docs/cluster-administration/application-resources-monitoring.md
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/application-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/application-resources-monitoring1.png
Labels: lgtm, size/S

#1398 Update metering doc.
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
Labels: lgtm, size/M

#1401 Update pic-zh
  content/zh/docs/cluster-administration/application-resources-monitoring.md
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/application-resources-monitoring.png
  static/images/docs/zh-cn/cluster-administration/application-resources-monitoring/application-resources-monitoring1.png
Labels: size/S

#1403 Clean metering doc.
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
Labels: lgtm, size/XS

#1405 Fix release-3.0 links
  content/en/docs/cluster-administration/platform-settings.md
  content/en/docs/project-user-guide/grayscale-release/overview.md
  layouts/robots.txt
Labels: lgtm, size/XS

#1406 fix canonical tag url error
  layouts/partials/head.html
Labels: size/XS

#1408 fix canonical tag url error
  layouts/partials/head.html
Labels: size/XS

#1407 Fixed typo error.
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
Labels: lgtm, size/XS

#1409 Fixed broken links-3.0
  content/en/docs/cluster-administration/persistent-volume-and-storage-class.md
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/en/docs/devops-user-guide/understand-and-manage-devops-projects/overview.md
  content/en/docs/project-administration/role-and-member-management.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/project-user-guide/application-workloads/routes.md
  content/en/docs/project-user-guide/application/app-template.md
  content/en/docs/project-user-guide/application/compose-app.md
  content/en/docs/project-user-guide/storage/volumes.md
  content/en/docs/workspace-administration/project-quotas.md
  layouts/robots.txt
Labels: lgtm, size/M

#1404 Add enable en billing doc
  content/en/docs/toolbox/metering-and-billing/enable-billing.md
  static/images/docs/toolbox/metering-and-billing/enable-billing/billing-dashboard.png
Labels: lgtm, size/M

#1413 Add some links
  content/en/docs/introduction/features.md
  content/zh/docs/introduction/features.md
Labels: lgtm, size/S

#1414 Update Doc for v3.1: Application Lifecycle Management
  content/en/docs/application-store/app-lifecycle-management.md
  content/zh/docs/application-store/app-lifecycle-management.md
  static/images/docs/appstore/application-lifecycle-management/app-to-be-upgraded.jpg
  static/images/docs/appstore/application-lifecycle-management/app-to-be-upgraded.png
  static/images/docs/appstore/application-lifecycle-management/edit-template.png
  static/images/docs/appstore/application-lifecycle-management/upgrade-app.png
  static/images/docs/appstore/application-lifecycle-management/upgrade-finish.jpg
  static/images/docs/appstore/application-lifecycle-management/upgrade-finish.png
  static/images/docs/appstore/application-lifecycle-management/version-upgraded.jpg
  static/images/docs/appstore/application-lifecycle-management/version-upgraded.png
  static/images/docs/zh-cn/appstore/application-lifecycle-management/app-to-be-upgraded.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/edit-template.png
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upgrade-an-app.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/upgrade-finish.PNG
  static/images/docs/zh-cn/appstore/application-lifecycle-management/version-upgraded.PNG
Labels: lgtm, size/M

#1411 Add alerting policy guide
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  static/images/docs/project-user-guide/alerting/alerting-policies/alert-policy-created.png
  static/images/docs/project-user-guide/alerting/alerting-policies/alerting-policy-detail.png
  static/images/docs/project-user-guide/alerting/alerting-policies/edit-alerting-policy.png
  static/images/docs/project-user-guide/alerting/alerting-policies/rule-template.png
Labels: approved, lgtm, size/M

#1416 Fixed some links
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/introduction/intro.md
  content/en/docs/introduction/advantages.md
  content/en/docs/quick-start/enable-pluggable-components.md
Labels: size/S

#1419 Metering-and billing-en modified
  content/en/docs/toolbox/metering-and-billing/enable-billing.md
Labels: approved, lgtm, size/XS

#1415 Translated Enable-billing-en
  content/zh/docs/toolbox/metering-and-billing/enable-billing.md
  static/images/docs/zh-cn/toolbox/metering-and-billing/enable-billing/metering-and-billing.png
Labels: lgtm, size/M

#1417 Pages interlinking
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
  content/en/blogs/devops-automatic-testing.md
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/blogs/install-nfs-server-client-for-kubesphere-cluster.md
  content/en/blogs/value-of-kubesphere.md
  content/en/case/anchnet.md
  content/en/case/benlai.md
  content/en/case/maxnerva.md
  content/en/docs/introduction/features.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/en/docs/pluggable-components/_index.md
  content/en/news/kubesphere-3.0.0-ga-announcement.md
  content/en/news/kubesphere-available-on-aws-quickstart.md
Labels: approved, lgtm, size/M

#1418 Pages interlinking
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
  content/en/blogs/devops-automatic-testing.md
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/blogs/install-nfs-server-client-for-kubesphere-cluster.md
  content/en/blogs/value-of-kubesphere.md
  content/en/case/anchnet.md
  content/en/case/benlai.md
  content/en/case/maxnerva.md
  content/en/docs/introduction/features.md
  content/en/docs/introduction/what-is-kubesphere.md
  content/en/docs/pluggable-components/_index.md
  content/en/news/kubesphere-3.0.0-ga-announcement.md
  content/en/news/kubesphere-available-on-aws-quickstart.md
Labels: approved, lgtm, size/M

#1421 add storage bugfix
  content/zh/docs/release/release-v310.md
Labels: lgtm, size/XS

#1420 Translated alerting-policy-en
  content/zh/docs/project-user-guide/alerting/alerting-policy.md
  static/images/docs/zh-cn/project-user-guide/alerting/alerting-policies/alert-policy-created.png
  static/images/docs/zh-cn/project-user-guide/alerting/alerting-policies/alerting-policy-detail.png
  static/images/docs/zh-cn/project-user-guide/alerting/alerting-policies/edit-alerting-policy.png
  static/images/docs/zh-cn/project-user-guide/alerting/alerting-policies/rule-template1.png
Labels: lgtm, size/M

#1427 Alerting-policy-en modified
  content/en/docs/project-user-guide/alerting/alerting-policy.md
Labels: lgtm, size/XS

#1425 Update release note
  content/zh/docs/release/release-v310.md
Labels: size/M

#1428 Typo fixed
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/pluggable-components/overview.md
Labels: size/XS

#1423 api changes of notification
  content/en/docs/reference/api-changes/notification.md
Labels: lgtm, size/S

#1424 Adjust Edge, o11y parts & adjust Markdow format
  content/zh/docs/release/release-v310.md
Labels: size/L

#1394 cherry-pick the commit to master branch
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2021.md
  content/en/news/kubesphere-meetup-2020.md
  static/images/news/kubecon-eu/kubecon-news-banner.png
Labels: approved, size/M

#1393 add news: KubeCon and CloudNativeCon Europe 2021 is coming!
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2021.md
  content/en/news/kubesphere-meetup-2020.md
  static/images/news/kubecon-eu/kubecon-news-banner.png
Labels: approved, size/M

#1431 Update news
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2021.md
Labels: approved, size/S

#1432 Update news
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2021.md
Labels: size/S

#1372 Add Blog-Argo CD
  content/en/blogs/argo-cd-a-tool-for-devops.md
  static/images/blogs/en/argo-cd-a-tool-for-devops/argo-icon.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argo-schematics.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-2.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-log-in.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-page.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-service.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-topology.png
Labels: area/devops, lgtm, size/L

#1434 Sync argo
  content/en/blogs/argo-cd-a-tool-for-devops.md
  static/images/blogs/en/argo-cd-a-tool-for-devops/argo-icon.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argo-schematics.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-2.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-log-in.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-page.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-service.png
  static/images/blogs/en/argo-cd-a-tool-for-devops/argocd-topology.png
Labels: size/L

#1429 Change observability ZH-CN loc
  config/_default/config.toml
  content/zh/_index.md
  content/zh/blogs/GPU-Operator.md
  content/zh/blogs/kubesphere-3.0.0-ga-announcement.md
  content/zh/blogs/kubesphere-values.md
  content/zh/blogs/release-210.md
  content/zh/blogs/skywalking-kubesphere.md
  content/zh/case/vng.md
  content/zh/conferences/_index.md
  content/zh/conferences/logging.md
  content/zh/docs/faq/observability/_index.md
  content/zh/docs/introduction/advantages.md
  content/zh/docs/introduction/features.md
  content/zh/docs/introduction/scenarios.md
  content/zh/docs/introduction/what's-new-in-v3.0.md
  content/zh/docs/introduction/what-is-kubesphere.md
  content/zh/docs/multicluster-management/introduction/overview.md
  content/zh/docs/pluggable-components/alerting.md
  content/zh/docs/pluggable-components/service-mesh.md
  content/zh/docs/project-user-guide/custom-application-monitoring/visualization/overview.md
  content/zh/learn/_index.md
  content/zh/observability/_index.md
  content/zh/service-mesh/_index.md
  data/zh/footer.yaml
  data/zh/video.json
Labels: approved, lgtm, size/L

#1433 Update release note
  content/zh/docs/release/release-v310.md
Labels: lgtm, size/S

#1435 Update KS and K8s version
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
Labels: approved, lgtm, size/M

#1440 Update release note about optimization
  content/zh/docs/release/release-v310.md
Labels: lgtm, size/S

#1441 Add En 3.1 release notes
  content/en/docs/release/release-v200.md
  content/en/docs/release/release-v201.md
  content/en/docs/release/release-v202.md
  content/en/docs/release/release-v210.md
  content/en/docs/release/release-v211.md
  content/en/docs/release/release-v300.md
  content/en/docs/release/release-v310.md
  content/zh/docs/release/release-v310.md
Labels: approved, do-not-merge/work-in-progress, size/L

#1444 Update file-Kubekey-zh
  content/zh/docs/installing-on-linux/introduction/kubekey.md
Labels: lgtm, size/S

#1436 Translated department-management-en
  content/zh/docs/workspace-administration/department-management.md
  static/images/docs/zh-cn/workspace-administration-and-user-guide/department-management/assign.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/department-management/edit.png
  static/images/docs/zh-cn/workspace-administration-and-user-guide/department-management/remove.png
Labels: approved, lgtm, size/M

#1439 Update pics-create workspace and project
  content/en/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/quick-start/create-workspace-and-project.md
  static/images/docs/quickstart/create-workspaces-projects-accounts/chang-password.jpg
  static/images/docs/quickstart/create-workspaces-projects-accounts/chang-password1.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/invite-project-member.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/invite-project-member1.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/nodeport-setting.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/nodeport-setting1.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/quota.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/quota1.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/set-gateway.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/set-gateway1.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/specify-project-quota.png
  static/images/docs/quickstart/create-workspaces-projects-accounts/specify-project-quota1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/devops-工程.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/devops-工程1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/nodeport.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/nodeport1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建-devops-工程.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建-devops-工程1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建企业空间.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建企业空间1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建帐户.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/创建帐户1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/完成网关设置.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/完成网关设置1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/工程列表.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/工程列表1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/帐户列表.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/帐户列表1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置密码.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置密码1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置网关.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置网关1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置配额.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/设置配额1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请-devops-成员.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请-devops-成员1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请成员至项目.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/邀请成员至项目1.png
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/项目概览.jpg
  static/images/docs/zh-cn/quickstart/create-workspaces-projects-accounts/项目概览1.png
Labels: lgtm, size/M

#1442 Updated file-deploy bookinfo
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-bookinfo1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/click-to-visit1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/detail-page1.png
  static/images/docs/quickstart/deploy-bookinfo-to-k8s/running1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-bookinfo.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-bookinfo1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-to-visit.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/click-to-visit1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/detail-page.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/detail-page1.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/running.png
  static/images/docs/zh-cn/quickstart/deploy-bookinfo-to-k8s/running1.png
Labels: lgtm, size/M

#1443 Update pics-wordpress
  content/en/docs/quick-start/wordpress-deployment.md
  content/zh/docs/quick-start/wordpress-deployment.md
  static/images/docs/quickstart/wordpress-deployment/add-container1.png
  static/images/docs/quickstart/wordpress-deployment/add-service1.png
  static/images/docs/quickstart/wordpress-deployment/add-volume-page1.png
  static/images/docs/quickstart/wordpress-deployment/advanced-settings1.png
  static/images/docs/quickstart/wordpress-deployment/advanced1.png
  static/images/docs/quickstart/wordpress-deployment/application-created1.png
  static/images/docs/quickstart/wordpress-deployment/basic-info1.png
  static/images/docs/quickstart/wordpress-deployment/choose-existing-volume1.png
  static/images/docs/quickstart/wordpress-deployment/components-finished1.png
  static/images/docs/quickstart/wordpress-deployment/composing-app1.png
  static/images/docs/quickstart/wordpress-deployment/container-image-page1.png
  static/images/docs/quickstart/wordpress-deployment/container-image1.png
  static/images/docs/quickstart/wordpress-deployment/create-secrets1.png
  static/images/docs/quickstart/wordpress-deployment/edit-internet-access1.png
  static/images/docs/quickstart/wordpress-deployment/environment-var1.png
  static/images/docs/quickstart/wordpress-deployment/environment-varss1.png
  static/images/docs/quickstart/wordpress-deployment/ingress-create1.png
  static/images/docs/quickstart/wordpress-deployment/key-value1.png
  static/images/docs/quickstart/wordpress-deployment/mount-volume-page1.png
  static/images/docs/quickstart/wordpress-deployment/mysql-finished1.png
  static/images/docs/quickstart/wordpress-deployment/mysql-running1.png
  static/images/docs/quickstart/wordpress-deployment/mysqlname1.png
  static/images/docs/quickstart/wordpress-deployment/name-wordpress-1.png
  static/images/docs/quickstart/wordpress-deployment/nodeport-number1.png
  static/images/docs/quickstart/wordpress-deployment/volume-settings1.png
  static/images/docs/quickstart/wordpress-deployment/volume-template1.png
  static/images/docs/quickstart/wordpress-deployment/volumes1.png
  static/images/docs/quickstart/wordpress-deployment/wordpress-deployment1.png
  static/images/docs/quickstart/wordpress-deployment/wordpress-secrets1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/advanced-setting1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/advanced1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/application-created1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/composing-app1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/create-secret1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/edit-internet-access1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/mysql-running1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/nodeport-number1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volume-settings1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volume-template1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/volumes1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/wordpress-deployment1.png
  static/images/docs/zh-cn/quickstart/wordpress-deployment/wordpress-secrets1.png
Labels: lgtm, size/M

#1447 Update KS and K8s version in zh-files
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/zh/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/zh/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: lgtm, size/M

#1450 Add item for kube-auditing upgrade
  content/zh/docs/release/release-v310.md
Labels: size/XS

#1257 case localization
  content/zh/case/huaxia-bank.md
Labels: approved, lgtm, size/M

#1445 Update Alerting Policies (Node Level)
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-detail.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-rule.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/click-create.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/click-edit.png
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/edit-policy.png
Labels: lgtm, size/M

#1449 Modified support-matrix links
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: size/M

#1456 Fix fail-loaded image
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
Labels: size/XS

#1452 add a new partner
  content/en/partner/_index.md
  static/images/partner/cloudnative-community.jpg
Labels: approved, lgtm, size/XS

#1455 Translate alerting-policy-en
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alert-detail.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/alert-rule.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/click-create.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/click-edit.png
  static/images/docs/zh-cn/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy-node-level/edit-policy.png
Labels: size/M

#1461 netlify test
  content/en/docs/pluggable-components/metrics-server.md
Labels: approved, size/XS

#1463 Add installing on linux part for components
  content/en/docs/pluggable-components/kubeedge.md
  content/en/docs/pluggable-components/pod-ip-pools.md
  content/en/docs/pluggable-components/service-topology.md
Labels: approved, size/M

#1460 Add App store desc
  content/en/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/app-store.md
Labels: approved, size/S

#1454 Update KS 3.1 upgrade guide
  content/en/docs/upgrade/overview.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, size/L

#1465 update 3.1 docs link
  config/_default/config.toml
Labels: lgtm, size/S

#1458 Add Alerting messages guide
  content/en/docs/project-user-guide/alerting/alerting-message.md
  content/en/docs/project-user-guide/alerting/alerting-policy.md
  static/images/docs/project-user-guide/alerting/alerting-messages/alerting-messages.png
Labels: approved, lgtm, size/M

#1468 Update Alerting Messages (Node Level)
  content/en/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-message.md
  static/images/docs/cluster-administration/cluster-wide-alerting-and-notification/alerting-messages-node-level/alert-message-page.png
Labels: lgtm, size/M

#1462 add a new partner
  content/en/partner/_index.md
  static/images/partner/cloudnative-community.jpg
Labels: approved, lgtm, size/XS

#1453 Update/add cookie tip
  assets/scss/footer.scss
  assets/scss/private.scss
  content/en/privacy/_index.md
  content/zh/privacy/_index.md
  i18n/en.yaml
  i18n/zh.yaml
  layouts/partials/footer.html
  layouts/privacy/list.html
Labels: approved, lgtm, size/XXL

#1467 Translate service-topology-en
  content/zh/docs/pluggable-components/service-topology.md
  static/images/docs/zh-cn/enable-pluggable-components/service-topology/topology1.png
Labels: lgtm, size/L

#1466 Add upgrade guide cn
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/upgrade/overview.md
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#1470 Update KS 3.1 offline installation and upgrade guides
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-KubeKey.md
  content/en/docs/upgrade/Air-Gapped-Upgrade-with-ks-installer.md
  content/en/docs/upgrade/overview.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: approved, lgtm, size/XXL

#1356 Add Use Pipeline Templates
  content/en/docs/devops-user-guide/how-to-use/use-pipeline-templates.md
  content/zh/docs/devops-user-guide/how-to-use/use-pipeline-templates.md
  static/images/docs/devops-user-guide/using-devops/use-pipeline-templates/ci-stages.png
  static/images/docs/devops-user-guide/using-devops/use-pipeline-templates/ci-template.png
  static/images/docs/devops-user-guide/using-devops/use-pipeline-templates/cicd-stages.png
  static/images/docs/devops-user-guide/using-devops/use-pipeline-templates/cicd-template.png
Labels: area/devops, lgtm, size/M

#1469 Translate pod-ip-pools-en
  content/zh/docs/pluggable-components/pod-ip-pools.md
  static/images/docs/zh-cn/enable-pluggable-components/pod-ip-pools/pod-ip-pool.png
Labels: lgtm, size/L

#1472 Translate kubeedge-en
  content/zh/docs/pluggable-components/kubeedge.md
  static/images/docs/zh-cn/enable-pluggable-components/kubeedge/edge-nodes.png
  static/images/docs/zh-cn/enable-pluggable-components/kubeedge/kubeedge_arch.png
Labels: lgtm, size/L

#1474 hotfix kubeedge installation after upgrade
  content/en/docs/pluggable-components/kubeedge.md
  content/zh/docs/pluggable-components/kubeedge.md
Labels: approved, lgtm, size/M

#1475 update header to KubeSphere 3.1.0
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1480 fix the mistaken version in header
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#1459 Add Doc: Create a Multi-branch Pipeline with GitLab
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/check-log.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/click-import-project.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/click-jenkinsfile.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/click-run.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/commit-changes.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/create-pipeline.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/credential-created.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/deployment.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/docker-image.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/gitlab-result.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/jenkinsfile-online.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/new-branch.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/pipeline-logs.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/select-branch.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/select-gitlab.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/service.png
  static/images/docs/devops-user-guide/using-devops/gitlab-multibranch-pipeline/use-git-url.png
Labels: lgtm, size/L
