Repository kubesphere/website, pull requests merged in 2022-08, with the labels that each got.

#2608 update the page of user-group-hangzhou
  content/zh/user-group/hangzhou.md
Labels: approved, lgtm, size/S

#2607 add new blog of kubesphere-gitops
  content/zh/blogs/kubesphere-gitops.md
Labels: approved, lgtm, size/L

#2606 add new blog
  content/zh/blogs/coredns-k8s-dns.md
Labels: approved, lgtm, size/L

#2609 add svg favicon
  layouts/partials/favicons.html
  static/images/favicons/favicon.png
  static/images/favicons/favicon.svg
Labels: approved, lgtm, size/XS

#2605 fix: Algolia doesn't work in `https://v3-2.docs.kubesphere.io/docs`
  layouts/partials/css.html
  layouts/partials/head.html
Labels: approved, lgtm, size/M

#2610 Fix air-gapped installation
  content/en/docs/v3.3/faq/console/edit-resources-in-system-workspace.md
  content/en/docs/v3.3/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.3/installing-on-linux/introduction/vars.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.3/faq/console/edit-resources-in-system-workspace.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/vars.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
Labels: approved, lgtm, size/M

#2614 add news
  content/en/news/kubesphere-ambassador-certificates-en.md
Labels: approved, lgtm, size/M

#2613 add new case
  content/zh/case/_index.md
  content/zh/case/extreme-vision.md
Labels: approved, lgtm, size/L

#2615 remove unnecessary file
  .hugo_build.lock
Labels: approved, lgtm, size/XS

#2611 update byop
  content/zh/docs/v3.3/faq/observability/byop.md
Labels: approved, lgtm, size/S

#2617 add new page of user-group
  content/zh/user-group/_index.md
  content/zh/user-group/guangzhou.md
  static/images/user-group/guangzhou/fujiayang.jpeg
  static/images/user-group/guangzhou/heshaohui.jpg
  static/images/user-group/guangzhou/huangshihao.jpeg
  static/images/user-group/guangzhou/hutao.jpeg
  static/images/user-group/guangzhou/huzhuochao.jpeg
  static/images/user-group/guangzhou/liuxing.png
  static/images/user-group/guangzhou/louju.jpg
  static/images/user-group/guangzhou/peizhenfei.png
  static/images/user-group/guangzhou/peizhenfeivx.jpg
  static/images/user-group/guangzhou/wangjing.jpeg
  static/images/user-group/guangzhou/wxCode.png
  static/images/user-group/guangzhou/zhouzhengjun.jpg
  static/images/user-group/guangzhou/zhouzhengjunvx.jpeg
Labels: approved, lgtm, size/M

#2616 fix: Update demo tooltip text
  config/upstream-zh/config.toml
  config/upstream/config.toml
  i18n/en.yaml
  i18n/zh.yaml
  layouts/partials/header.html
Labels: lgtm, size/S

#2619 add netlity rules
  netlify.toml
Labels: approved, lgtm, size/S

#2621 update the page of live
  content/zh/live/_index.md
  content/zh/live/guangzhou0806-dragonfly.md
  content/zh/live/guangzhou0806-gitops.md
  content/zh/live/guangzhou0806-holmes.md
  content/zh/live/guangzhou0806-kubesphere.md
  content/zh/live/guangzhou0806-kusionstack.md
  content/zh/live/guangzhou0806-veeam.md
  content/zh/live/harbor0811-live.md
  content/zh/live/meetup-guangzhou-20220806.md
  content/zh/live/radondb0804-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2623 fix typo
  content/zh/live/guangzhou0806-holmes.md
  content/zh/live/meetup-guangzhou-20220806.md
Labels: approved, lgtm, size/XS

#2604 update description in ADD EDGE NODES
  content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
Labels: lgtm, size/L

#2620 update logging
  content/en/docs/v3.3/faq/observability/logging.md
  content/zh/docs/v3.3/faq/observability/logging.md
Labels: approved, lgtm, size/M

#2628 update jQuery
  layouts/partials/head.html
  static/js/jquery-3.5.0.min.js
  static/js/jquery-3.6.0.min.js
Labels: approved, lgtm, size/XS

#2627 update byop
  content/zh/docs/v3.3/faq/observability/byop.md
Labels: approved, lgtm, size/L

#2624 add news
  content/en/news/kubesphere-ambassador-certificates-en.md
  content/en/news/kubesphere-contributor-certificates-en.md
Labels: approved, lgtm, size/L

#2630 byop-en
  content/en/docs/v3.3/faq/observability/byop.md
  content/zh/docs/v3.3/faq/observability/byop.md
Labels: approved, lgtm, size/L

#2625 fix: The prompt text of the demo is not translated
  config/_default/config.toml
  config/upstream-zh/config.toml
  config/upstream/config.toml
  i18n/zh.yaml
  layouts/partials/header.html
Labels: approved, lgtm, size/S

#2633 update the page of live
  content/zh/live/_index.md
  content/zh/live/containerlab0818-live.md
  content/zh/live/harbor0811-live.md
  content/zh/live/meetup-hangzhou-20220827.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2632 update favicons
  static/images/favicons/android-chrome-192x192.png
  static/images/favicons/android-chrome-512x512.png
  static/images/favicons/apple-touch-icon.png
  static/images/favicons/browserconfig.xml
  static/images/favicons/favicon-16x16.png
  static/images/favicons/favicon-32x32.png
  static/images/favicons/favicon.ico
  static/images/favicons/mstile-144x144.png
  static/images/favicons/mstile-150x150.png
  static/images/favicons/mstile-310x150.png
  static/images/favicons/mstile-310x310.png
  static/images/favicons/mstile-70x70.png
  static/images/favicons/safari-pinned-tab.svg
  static/images/favicons/site.webmanifest
Labels: approved, lgtm, size/S

#2634 fix 3.3 cc file
  content/en/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/v3.3/faq/observability/logging.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/pluggable-components/auditing-logs.md
  content/en/docs/v3.3/pluggable-components/events.md
  content/en/docs/v3.3/pluggable-components/kubeedge.md
  content/en/docs/v3.3/pluggable-components/logging.md
  content/en/docs/v3.3/project-administration/project-network-isolation.md
  content/en/docs/v3.3/project-user-guide/application-workloads/routes.md
  content/zh/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/v3.3/faq/observability/logging.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.3/pluggable-components/auditing-logs.md
  content/zh/docs/v3.3/pluggable-components/events.md
  content/zh/docs/v3.3/pluggable-components/kubeedge.md
  content/zh/docs/v3.3/pluggable-components/logging.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/routes.md
Labels: approved, lgtm, size/XL

#2631 update the case of xindongfang
  content/zh/case/xdf.md
Labels: approved, lgtm, size/L

#2636 update social links
  layouts/docs/second.html
  layouts/docs/single.html
Labels: approved, lgtm, size/S

#2639 minor update links
  LICENSE
  layouts/partials/head.html
  layouts/partials/share.html
  static/js/jquery.modal.min.js
  static/js/pagination.min.js
  static/json/crd-3.1.json
  static/json/crd.json
  static/json/kubesphere.json
Labels: approved, lgtm, size/M

#2642 update the page of live
  content/zh/live/_index.md
  content/zh/live/containerlab0818-live.md
  content/zh/live/meetup-hangzhou-20220827.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2643 add new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/logo-deepflow.png
Labels: approved, lgtm, size/S

#2641 add images for edge nodes
  content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  static/images/docs/v3.3/installing-on-linux/add-and-delete-nodes/add-edge-nodes/add-edge-node.png
  static/images/docs/v3.3/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-command.png
  static/images/docs/v3.3/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/add-edge-node.png
  static/images/docs/v3.3/zh-cn/installing-on-linux/add-and-delete-nodes/add-edge-nodes/edge-command.png
Labels: lgtm, size/XS

#2646 fix display issues
  config/_default/config.toml
Labels: approved, lgtm, size/M

#2647 fix typo
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
Labels: approved, lgtm, size/XS

#2645 update jQuery
  layouts/partials/head.html
  static/js/jquery-3.6.0.min.js
  static/js/jquery-3.6.1.min.js
Labels: approved, lgtm

#2650 update the page of live
  content/zh/live/_index.md
  content/zh/live/hangzhou0827-devsecops.md
  content/zh/live/hangzhou0827-karmada.md
  content/zh/live/hangzhou0827-kubeedge.md
  content/zh/live/hangzhou0827-mlops.md
  content/zh/live/hangzhou0827-nebulagragh.md
  content/zh/live/hangzhou0827-velero.md
  content/zh/live/kubeedge0901-live.md
  content/zh/live/meetup-hangzhou-20220827.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L
