Repository kubesphere/website, pull requests merged in 2022-07, with the labels that each got.

#2543 add news
  content/zh/news/ospp-2022-selected-students.md
  content/zh/news/ospp-2022.md
Labels: approved, lgtm, size/M

#2544 Update air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
Labels: approved, lgtm, size/XS

#2546 add new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/Cloudview-logo.png
Labels: approved, lgtm, size/XS

#2545 fix: table text width
  assets/scss/markdown.scss
Labels: approved, lgtm, size/XS

#2550 update the page of live
  content/zh/live/_index.md
  content/zh/live/kubesphere-v3.3.0-live.md
  content/zh/live/pg0707-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2553 fix: Update algolia key
  layouts/partials/searchInput.html
Labels: lgtm, size/XS

#2548 Accessibility add iframe titles
  layouts/docs/second.html
  layouts/docs/single.html
Labels: approved, lgtm, size/XS

#2504 update hugo to 0.101.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2551 Add description of data retention periods of logs and audit, events, …
  content/en/docs/v3.3/application-store/built-in-apps/radondb-mysql-app.md
  content/en/docs/v3.3/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/en/docs/v3.3/devops-user-guide/examples/a-maven-project.md
  content/en/docs/v3.3/devops-user-guide/examples/go-project-pipeline.md
  content/en/docs/v3.3/devops-user-guide/examples/multi-cluster-project-example.md
  content/en/docs/v3.3/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/en/docs/v3.3/devops-user-guide/how-to-integrate/sonarqube.md
  content/en/docs/v3.3/faq/observability/logging.md
  content/en/docs/v3.3/project-administration/project-and-multicluster-project.md
  content/en/docs/v3.3/project-administration/project-gateway.md
  content/en/docs/v3.3/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/v3.3/project-user-guide/image-builder/source-to-image.md
  content/en/docs/v3.3/project-user-guide/storage/volumes.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/blogs/deploying-kubesphere-clusters-offline-with-kubekey.md
  content/zh/docs/v3.3/application-store/app-lifecycle-management.md
  content/zh/docs/v3.3/application-store/built-in-apps/radondb-mysql-app.md
  content/zh/docs/v3.3/application-store/external-apps/deploy-radondb-mysql.md
  content/zh/docs/v3.3/cluster-administration/cluster-wide-alerting-and-notification/alertmanager.md
  content/zh/docs/v3.3/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/v3.3/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/zh/docs/v3.3/faq/observability/logging.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/remove-nodes.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/project-administration/project-gateway.md
  content/zh/docs/v3.3/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/v3.3/project-user-guide/image-builder/source-to-image.md
  content/zh/docs/v3.3/project-user-guide/storage/volumes.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2555 Accessibility add alt to docs img
  content/en/docs/v3.3/application-store/external-apps/deploy-gitlab.md
  content/en/docs/v3.3/cluster-administration/cluster-settings/cluster-gateway.md
  content/en/docs/v3.3/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/en/docs/v3.3/project-administration/disk-log-collection.md
  content/en/docs/v3.3/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/v3.3/project-user-guide/application-workloads/cronjobs.md
  content/en/docs/v3.3/project-user-guide/application-workloads/deployments.md
  content/en/docs/v3.3/project-user-guide/application-workloads/jobs.md
  content/en/docs/v3.3/project-user-guide/application-workloads/statefulsets.md
  content/en/docs/v3.3/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/en/docs/v3.3/quick-start/create-workspace-and-project.md
  content/en/docs/v3.3/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/v3.3/application-store/external-apps/deploy-gitlab.md
  content/zh/docs/v3.3/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/v3.3/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/zh/docs/v3.3/project-administration/disk-log-collection.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/deployments.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/jobs.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/v3.3/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/zh/docs/v3.3/quick-start/deploy-bookinfo-to-k8s.md
Labels: approved, lgtm, size/M

#2556 fix: Hide Turkey language docs link
  config/_default/config.toml
  config/allMenu/config.toml
Labels: approved, lgtm, size/L

#2561 add news
  content/zh/news/kubesphere-user-group.md
Labels: approved, lgtm, size/L

#2559 add new blog
  content/zh/blogs/kubesphere-devops-java-microservice.md
Labels: approved, lgtm, size/L

#2560 add new blog
  content/zh/blogs/kubesphere-ssl.md
Labels: approved, lgtm, size/XL

#2563 Installation guide for kubesphere 3.2.1 on minikube in on-prem-kuber…
  content/en/docs/installing-on-kubernetes/installing-minikube-on-kubesphere.md
Labels: approved, lgtm, size/L

#2564 update the page of live
  content/zh/live/_index.md
  content/zh/live/crane0714-live.md
  content/zh/live/pg0707-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2565 Accessibility add alt to docs img (zh)
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/oidc-identity-provider.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/use-an-ldap-service.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/configure-dingtalk.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/configure-email.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/configure-slack.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/configure-webhook.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/configure-wecom.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/notification-management/customize-cluster-name.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/code-repositories/import-code-repositories.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/devops-settings/role-and-member-management.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/jenkins-email.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/pipeline-webhook.md
  content/zh/docs/v3.3/project-user-guide/custom-application-monitoring/visualization/overview.md
Labels: approved, lgtm, size/M

#2568 add news
  content/zh/news/kubesphere-speaker-certificates-20220715.md
Labels: approved, lgtm, size/L

#2569 update the news
  content/zh/news/kubesphere-speaker-certificates-20220715.md
Labels: approved, lgtm, size/XS

#2567 Accessibility add alt to docs img
  content/en/blogs/cilium-as-cni.md
  content/en/docs/v3.3/project-administration/disk-log-collection.md
  content/en/docs/v3.3/toolbox/events-query.md
  content/en/docs/v3.3/toolbox/log-query.md
  content/zh/docs/v3.3/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/v3.3/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/daemonsets.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/deployments.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/jobs.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/services.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/v3.3/project-user-guide/grayscale-release/canary-release.md
  content/zh/docs/v3.3/project-user-guide/image-builder/source-to-image.md
  content/zh/docs/v3.3/toolbox/events-query.md
  content/zh/docs/v3.3/toolbox/log-query.md
  content/zh/docs/v3.3/toolbox/metering-and-billing/view-resource-consumption.md
Labels: approved, lgtm, size/M

#2570 update the news
  content/zh/news/kubesphere-speaker-certificates-20220715.md
Labels: approved, lgtm, size/XS

#2574 update links
  content/en/blogs/multi-cluster-deployment.md
  content/en/blogs/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.3/devops-user-guide/examples/a-maven-project.md
  content/en/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/v3.3/project-user-guide/image-builder/binary-to-image.md
  content/en/docs/v3.3/project-user-guide/image-builder/source-to-image.md
  content/en/privacy/_index.md
  content/zh/blogs/Kasten-K10-KubeSphere.md
  content/zh/blogs/cilium-kubesphere-kubernetes.md
  content/zh/blogs/ebpf-guide.md
  content/zh/blogs/ebpf-software-stack.md
  content/zh/blogs/ebpf-tracing-user-processes.md
  content/zh/blogs/kubesphere-terminating-namespace.md
  content/zh/blogs/netapp.md
  content/zh/blogs/use-apache-apisix-ingress-in-kubesphere.md
  content/zh/case/zto.md
  content/zh/live/apisix826-live.md
  content/zh/live/argocd0217-live.md
  content/zh/live/ceph1216-live.md
  content/zh/live/ckacks1021-live.md
  content/zh/live/clickhouse0512-live.md
  content/zh/live/crane0714-live.md
  content/zh/live/faas1223-live.md
  content/zh/live/gitlab0224-live.md
  content/zh/live/go1104-live.md
  content/zh/live/gpu0623-live.md
  content/zh/live/headingdata0616-live.md
  content/zh/live/iot0414-live.md
  content/zh/live/jinaai0602-live.md
  content/zh/live/k8s-apisix-openelb0406-live.md
  content/zh/live/k8s0303-live.md
  content/zh/live/kasten0317-live.md
  content/zh/live/ksv0526-live.md
  content/zh/live/kubekey0331-live.md
  content/zh/live/kubekey1209-live.md
  content/zh/live/kubeovn1028-live.md
  content/zh/live/kubesphere-v3.3.0-live.md
  content/zh/live/milvus0324-live.md
  content/zh/live/mqtt1230-live.md
  content/zh/live/nebula0902-live.md
  content/zh/live/notification-manager-0428-live.md
  content/zh/live/openfunction0113-live.md
  content/zh/live/pulsar0609-live.md
  content/zh/live/rook1111-live.md
  content/zh/live/skywalking0310-live.md
  content/zh/live/uisee0916-live.md
  content/zh/live/uisee0923-live.md
  content/zh/live/wasm0909-live.md
  content/zh/live/webhook1202-live.md
  content/zh/live/yatai0421-live.md
  content/zh/live/yunda1014-live.md
  content/zh/news/ospp-2022.md
  content/zh/privacy/_index.md
Labels: approved, lgtm, size/L

#2575 remove the broken link
  content/en/news/kubesphere-geko-partnership.md
Labels: approved, lgtm, size/XS

#2578 update the page of live
  content/zh/live/_index.md
  content/zh/live/crane0714-live.md
  content/zh/live/zadig0721-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2576 update the news
  content/zh/news/kubesphere-speaker-certificates-20220715.md
Labels: approved, lgtm, size/XS

#2582 fix spaces in offline installation manifest
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/XL

#2583 Create kubesphere-contributor-certificates-20220721.md
  content/zh/news/kubesphere-contributor-certificates-20220721.md
Labels: approved, lgtm, size/L

#2580 [#2579] fix air-gapped installation ip inconsistency
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/S

#2577 add new blog
  content/zh/blogs/kubesphere-v3.3.0-offline-installation.md
Labels: approved, lgtm, size/XL

#2586 Update operation details
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/XS

#2584 Accessibility add iframe title
  layouts/videos/list.html
Labels: approved, lgtm, size/XS

#2588 Accessibility add alt to image
  layouts/index.html
Labels: approved, lgtm, size/XS

#2594 update the page of live
  content/zh/live/_index.md
  content/zh/live/devops0728-live.md
  content/zh/live/meetup-guangzhou-20220806.md
  content/zh/live/zadig0721-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2595 add news
  content/zh/news/kubesphere-ambassador-certificates-20220727.md
  content/zh/news/kubesphere-speaker-certificates-20220715.md
Labels: approved, lgtm, size/M

#2589 add Chinese version of Install Ceph
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd.md
Labels: approved, lgtm, size/M

#2598 Accessibility add iframe title
  layouts/index.html
Labels: approved, lgtm, size/XS

#2602 update the page of live
  content/zh/live/_index.md
  content/zh/live/devops0728-live.md
  content/zh/live/radondb0804-live.md
  content/zh/live/zhijianglab-kubesphere.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2599 fix: Update demo website address
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2600 fix backslash
  content/zh/docs/v3.3/reference/api-docs.md
Labels: approved, lgtm, size/XS
