Repository kubesphere/website, pull requests merged in 2022-12, with the labels that each got.

#2753 feat: Let page can be gray
  assets/scss/index.scss
Labels: approved, lgtm, size/XS

#2755 update the page of video
  content/zh/conferences/openfunction.md
  content/zh/conferences/qunar.md
  data/zh/video.json
Labels: approved, lgtm, size/M

#2756 add new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/crane.svg
Labels: approved, lgtm, size/M

#2757 fix: Update news and partner page
  assets/scss/news.scss
  assets/scss/partner.scss
  content/en/partner/_index.md
  layouts/news/list.html
  layouts/partner/list.html
Labels: approved, lgtm, size/L

#2758 devops changes
  content/en/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
Labels: approved, lgtm, size/XS

#2760 add new logo of case
  content/en/case/_index.md
  content/zh/case/_index.md
  static/images/case/logo-crrc.png
Labels: approved, lgtm, size/XS

#2759 update the page of conference and video
  content/zh/conferences/_index.md
  content/zh/conferences/fluent-operator-2.md
  content/zh/conferences/fluent-operator.md
  content/zh/conferences/fluentbit.md
  content/zh/conferences/serverless.md
  data/zh/video.json
Labels: approved, lgtm, size/L

#2761 add new blog
  content/zh/blogs/openelb-arp.md
Labels: approved, lgtm, size/L

#2762 fix: Open a new page for bilibili video in videos page
  layouts/videos/list.html
Labels: approved, lgtm, size/XS

#2764 Add turkey forum proxy
  netlify.toml
Labels: size/S

#2765 Add edge function for go-get
  .gitignore
  netlify.toml
  netlify/edge-functions/go-get/go-get.js
Labels: size/S

#2766 Modify chinese forum domain
  netlify.toml
Labels: size/XS

#2754 fix typo
  content/en/blogs/faas-openfunction.md
Labels: approved, lgtm, size/XS

#2769 update the page of video
  content/zh/live/_index.md
  data/zh/video.json
Labels: approved, lgtm, size/L

#2768 fix: Revert home page color
  assets/scss/index.scss
Labels: approved, lgtm

#2771 add new zh blog
  content/zh/blogs/kubesphere-3.3.1-access-control-and-account-management.md
Labels: approved, lgtm, size/M

#2772 add new blog
  content/zh/blogs/kubesphere-elasticsearch.md
Labels: approved, lgtm, size/L

#2774 add news of partner
  content/zh/news/kubesphere-partner.md
Labels: approved, lgtm, size/M

#2775 fix: Partner link not work
  content/zh/partner/_index.md
  layouts/partner/list.html
  layouts/user-group/list.html
Labels: approved, lgtm, size/S

#2778 add three logos of partners
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/Curve-logo.svg
  static/images/partner/logo-chaosmesh.svg
  static/images/partner/nocalhost-horizontal-color.svg
Labels: approved, lgtm, size/M

#2777 fix: Switching page language automatically
  layouts/_default/baseof.html
Labels: approved, lgtm, size/S

#2781 Add zh blog
  content/zh/blogs/kubesphere-practice.md
Labels: approved, lgtm, size/L

#2782 fix: Update the page language logic
  layouts/_default/baseof.html
  layouts/partials/header.html
Labels: approved, lgtm, size/M

#2780 update jquery
  layouts/partials/head.html
  static/js/jquery-3.6.1.min.js
  static/js/jquery-3.6.2.min.js
Labels: approved, lgtm, size/XS

#2767 update hugo to 0.108.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2783 add news of podcast
  content/zh/news/kubesphere-talk-podcast.md
Labels: approved, lgtm, size/M

#2784 update the page of user-group
  content/zh/user-group/_index.md
  content/zh/user-group/guangzhou.md
  content/zh/user-group/shanghai.md
Labels: approved, lgtm, size/S

#2788 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#2786 update jquery
  layouts/partials/head.html
  static/js/jquery-3.6.2.min.js
  static/js/jquery-3.6.3.min.js
Labels: approved, lgtm, size/XS

#2770 update agent connection
  content/en/docs/v3.3/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/v3.3/multicluster-management/enable-multicluster/agent-connection.md
Labels: approved, lgtm, size/S

#2787 update docs
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/installing-kubesphere-on-minikube.md
  content/en/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/v3.3/cluster-administration/storageclass.md
  content/en/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/en/docs/v3.3/faq/observability/byop.md
  content/en/docs/v3.3/faq/observability/logging.md
  content/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/pluggable-components/auditing-logs.md
  content/en/docs/v3.3/pluggable-components/events.md
  content/en/docs/v3.3/pluggable-components/logging.md
  content/en/docs/v3.3/project-user-guide/application-workloads/routes.md
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.3/reference/storage-system-installation/nfs-server.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/cas-identity-provider.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/set-up-external-authentication.md
  content/zh/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/v3.3/cluster-administration/storageclass.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/v3.3/faq/observability/byop.md
  content/zh/docs/v3.3/faq/observability/logging.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.3/pluggable-components/auditing-logs.md
  content/zh/docs/v3.3/pluggable-components/events.md
  content/zh/docs/v3.3/pluggable-components/logging.md
  content/zh/docs/v3.3/project-user-guide/application-workloads/routes.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/reference/api-docs.md
  content/zh/docs/v3.3/reference/storage-system-installation/nfs-server.md
Labels: approved, lgtm, size/XL

#2791 update hugo to 0.109.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2792 update the page of live
  content/zh/live/_index.md
  content/zh/live/k8s1229-live.md
Labels: approved, lgtm, size/M

#2793 fix the link
  content/zh/live/_index.md
Labels: approved, lgtm, size/S
