Repository kubesphere/website, pull requests merged in 2022-06, with the labels that each got.

#2472 add new blog of kubesphere-jh-gitlab
  content/zh/blogs/kubesphere-jh-gitlab.md
Labels: approved, lgtm, size/L

#2473 add new blog of kubesphere-10k-stars.md
  content/zh/blogs/kubesphere-10k-stars.md
Labels: approved, lgtm, size/M

#2475 update new blog of notifacation-mangaer
  content/zh/blogs/notification-manager-system.md
Labels: approved, lgtm, size/L

#2476 Fix-Credential and Toolbox Auditing
  content/en/docs/devops-user-guide/how-to-use/credential-management.md
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/zh/docs/devops-user-guide/how-to-use/credential-management.md
  content/zh/docs/toolbox/auditing/auditing-receive-customize.md
Labels: approved, lgtm, size/S

#2481 update the page of news
  content/zh/news/_index.md
  content/zh/news/console-opensource.md
  content/zh/news/kubekey-v2.0.0-release.md
  content/zh/news/kubekey-v2.1.0-release.md
  content/zh/news/kubesphere-10k-stars.md
  content/zh/news/kubesphere-2021-year-in-review.md
  content/zh/news/kubesphere-3.0.0-ga-announcement.md
  content/zh/news/kubesphere-3.1.0-ga-announcement.md
  content/zh/news/kubesphere-3.2.0-ga-announcement.md
  content/zh/news/kubesphere-3.3.0-rc.md
  content/zh/news/kubesphere-ambassador-certificates.md
  content/zh/news/kubesphere-certificates.md
  content/zh/news/kubesphere-contributor-certificates.md
  content/zh/news/kubesphere-member-certificates.md
  content/zh/news/kubesphere-release-note-post.md
  content/zh/news/kubesphere-speaker-certificates.md
  content/zh/news/notification-manager-v2.0.0-release.md
  content/zh/news/ospp-2022.md
  content/zh/news/release-210.md
Labels: approved, lgtm, size/L

#2483 add new case
  content/zh/case/_index.md
  content/zh/case/sinodata.md
Labels: approved, lgtm, size/L

#2484 Update3.3
  assets/scss/news.scss
  content/.history/en/docs/devops-user-guide/how-to-use/devops-settings/credential-management_20220518140604.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/toolbox/auditing/auditing-receive-customize.md
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2021.md
  content/en/news/join-us-at-kubecon-eu-2022.md
  content/en/news/kubecon-china-2021.md
  content/en/news/kubernetes-community-days-china.md
  content/en/news/kubesphere-10k-stars.md
  content/en/news/kubesphere-2021-year-in-review.md
  content/en/news/kubesphere-3.0.0-ga-announcement.md
  content/en/news/kubesphere-310-on-aws-quick-start.md
  content/en/news/kubesphere-available-on-aws-quickstart.md
  content/en/news/kubesphere-cigo-partnership.md
  content/en/news/kubesphere-geko-partnership.md
  content/en/news/kubesphere-meetup-2020.md
  content/en/news/kubesphere-radore-partnership.md
  content/en/news/spanish-traditional-chinese-available.md
  content/zh/blogs/kubesphere-jh-gitlab.md
  content/zh/blogs/notification-manager-system.md
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/add-cd-allowlist.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/credential-management.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/toolbox/auditing/auditing-receive-customize.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/news/_index.md
  content/zh/news/console-opensource.md
  content/zh/news/kubekey-v2.0.0-release.md
  content/zh/news/kubekey-v2.1.0-release.md
  content/zh/news/kubesphere-10k-stars.md
  content/zh/news/kubesphere-2021-year-in-review.md
  content/zh/news/kubesphere-3.0.0-ga-announcement.md
  content/zh/news/kubesphere-3.1.0-ga-announcement.md
  content/zh/news/kubesphere-3.2.0-ga-announcement.md
  content/zh/news/kubesphere-3.3.0-rc.md
  content/zh/news/kubesphere-ambassador-certificates.md
  content/zh/news/kubesphere-certificates.md
  content/zh/news/kubesphere-contributor-certificates.md
  content/zh/news/kubesphere-member-certificates.md
  content/zh/news/kubesphere-release-note-post.md
  content/zh/news/kubesphere-speaker-certificates.md
  content/zh/news/notification-manager-v2.0.0-release.md
  content/zh/news/ospp-2022.md
  content/zh/news/release-210.md
  layouts/news/list.html
  static/images/news/kubesphere-10k-stars/202206061450328.png
  static/images/news/kubesphere-10k-stars/kubesphere-10k-stars.png
Labels: approved, lgtm, size/XXL

#2485 update the page of live
  content/zh/live/_index.md
  content/zh/live/jinaai0602-live.md
  content/zh/live/pulsar0609-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2487 Update3.3
  content/.history/en/docs/cluster-administration/nodes_20220517155338.md
  content/.history/en/docs/cluster-administration/nodes_20220517162530.md
  content/.history/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully_20220517153821.md
  content/.history/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully_20220517162640.md
  content/.history/en/docs/devops-user-guide/how-to-use/devops-settings/credential-management_20220518140604.md
  content/.history/en/docs/faq/installation/ssh-connection-failure_20211012092152.md
  content/.history/en/docs/faq/installation/ssh-connection-failure_20220517164401.md
  content/.history/en/docs/faq/installation/ssh-connection-failure_20220517164412.md
  content/.history/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do_20220517155338.md
  content/.history/en/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do_20220517164516.md
  content/.history/en/docs/installing-on-linux/cluster-operation/add-edge-nodes_20220517155338.md
  content/.history/en/docs/installing-on-linux/cluster-operation/add-edge-nodes_20220517164611.md
  content/.history/en/docs/installing-on-linux/cluster-operation/add-edge-nodes_20220517164640.md
  content/.history/en/docs/installing-on-linux/cluster-operation/add-edge-nodes_20220517164647.md
  content/.history/en/docs/installing-on-linux/high-availability-configurations/ha-configuration_20220517155338.md
  content/.history/en/docs/installing-on-linux/high-availability-configurations/ha-configuration_20220517164841.md
  content/.history/en/docs/installing-on-linux/high-availability-configurations/ha-configuration_20220517164916.md
  content/.history/en/docs/installing-on-linux/high-availability-configurations/ha-configuration_20220517165014.md
  content/.history/en/docs/installing-on-linux/high-availability-configurations/ha-configuration_20220517171515.md
  content/.history/en/docs/installing-on-linux/introduction/air-gapped-installation_20220520161730.md
  content/.history/en/docs/installing-on-linux/introduction/air-gapped-installation_20220520161837.md
  content/.history/en/docs/installing-on-linux/introduction/intro_20211012092152.md
  content/.history/en/docs/installing-on-linux/introduction/intro_20220517171603.md
  content/.history/en/docs/installing-on-linux/introduction/intro_20220517171608.md
  content/.history/en/docs/installing-on-linux/introduction/multioverview_20220517155338.md
  content/.history/en/docs/installing-on-linux/introduction/multioverview_20220517171626.md
  content/.history/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere_20220517155338.md
  content/.history/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere_20220517171743.md
  content/.history/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere_20220517171757.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms_20220517155338.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms_20220517171833.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517155338.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517172059.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517172109.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517172132.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517172146.md
  content/.history/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms_20220517172149.md
  content/.history/en/docs/introduction/features_20211104141738.md
  content/.history/en/docs/introduction/features_20220517172205.md
  content/.history/zh/blogs/arm64-kubernetes-kubesphere_20220427170730.md
  content/.history/zh/blogs/arm64-kubernetes-kubesphere_20220517172331.md
  content/.history/zh/blogs/deploying-kubesphere-clusters-offline-with-kubekey_20220427165150.md
  content/.history/zh/blogs/deploying-kubesphere-clusters-offline-with-kubekey_20220517171231.md
  content/en/blogs/add-master-for-ha-using-kubekey.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/quick-start/wordpress-deployment.md
  content/zh/blogs/k8s-kubeeye-security.md
  content/zh/case/_index.md
  content/zh/case/sinodata.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/live/ksv0526-live.md
  content/zh/live/pulsar0609-live.md
  layouts/partials/downloadButton.html
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/XXL

#2491 Fix3.3
  content/en/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/en/docs/cluster-administration/cluster-settings/log-collections/add-es-as-receiver.md
  content/en/docs/cluster-administration/storageclass.md
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/introduction/scenarios.md
  content/en/docs/multicluster-management/unbind-cluster.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/upgrade/overview.md
  content/en/docs/upgrade/upgrade-with-ks-installer.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/blogs/k8s-kubeeye-security.md
  content/zh/case/_index.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/add-es-as-receiver.md
  content/zh/docs/cluster-administration/snapshotclass.md
  content/zh/docs/cluster-administration/storageclass.md
  content/zh/docs/devops-user-guide/how-to-use/code-repositories/import-code-repositories.md
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/faq/installation/telemetry.md
  content/zh/docs/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/multicluster-management/enable-multicluster/direct-connection.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  content/zh/docs/multicluster-management/unbind-cluster.md
  content/zh/docs/pluggable-components/alerting.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/network-policy.md
  content/zh/docs/pluggable-components/pod-ip-pools.md
  content/zh/docs/pluggable-components/service-mesh.md
  content/zh/docs/pluggable-components/service-topology.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/project-user-guide/storage/volumes.md
  content/zh/docs/quick-start/enable-pluggable-components.md
  content/zh/docs/toolbox/auditing/auditing-receive-customize.md
  content/zh/docs/toolbox/auditing/auditing-rule.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/overview.md
  content/zh/docs/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
  content/zh/live/_index.md
  content/zh/live/clickhouse0512-live.md
  content/zh/live/ksv0526-live.md
  layouts/partials/header.html
Labels: approved, lgtm, size/XXL

#2480 Accessibility add iframe title
  layouts/partner/request.html
Labels: size/XS

#2465 update links content
  content/en/blogs/kubesphere-3.1.0-ga-announcement.md
  content/en/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/release/release-v321.md
Labels: size/XS

#2449 update header on mobile
  assets/scss/header.scss
Labels: size/XS

#2423 Improve the title of the DevOps page
  content/zh/devops/_index.md
Labels: area/devops, lgtm, size/XS

#2088 Update release-v320.md
  content/zh/docs/release/release-v320.md
Labels: size/XS

#2492 fix devops issues
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
Labels: approved, area/devops, lgtm, size/XS

#2456 Improve the type of Credential
  content/en/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/en/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/en/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
  content/tr/conferences/cicd-jenkinsfile.md
  content/zh/blogs/spring-cloud-on-kubeshpere.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/gitlab-multibranch-pipeline.md
Labels: approved, area/devops, lgtm, size/M

#2478 add Copied text
  assets/js/markdown-tab.js
  assets/scss/common.scss
Labels: approved, lgtm, size/S

#2001 [feat] add Multi-cluster page
  assets/scss/scenario.scss
  content/en/multicluster/_index.md
  static/images/multicluster/CICD-Pipeline.png
  static/images/multicluster/deploy-application.png
  static/images/multicluster/mul-ops.png
  static/images/multicluster/strong-isolation.png
Labels: approved, lgtm, size/M

#2247 harbor robot update
  content/zh/docs/devops-user-guide/how-to-integrate/harbor.md
Labels: approved, lgtm, size/XS

#2494 Update cloud native videos
  content/zh/learn/level_9/lesson_55/video.md
Labels: approved, lgtm, size/XS

#2495 update cloud native img
  content/en/_index.md
  content/tr/_index.md
  content/zh/_index.md
  static/images/home/certification.png
Labels: approved, lgtm, size/XS

#2496 fix devops-CD
  content/en/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  content/zh/docs/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
Labels: approved, lgtm, size/L

#2497 update the page of live
  content/zh/live/_index.md
  content/zh/live/headingdata0616-live.md
  content/zh/live/pulsar0609-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2470 update hugo
  netlify.toml
Labels: approved, lgtm, size/XS

#2500 add new blog
  content/zh/blogs/kubesphere-multihosts.md
Labels: approved, lgtm, size/L

#2498 add new blog
  content/zh/blogs/mysql-on-k8s-statefulset-1.md
Labels: approved, lgtm, size/XL

#2506 Accessibility add link name
  layouts/docs/list.html
Labels: approved, lgtm, size/XS

#2507 update the page of live
  content/zh/live/_index.md
  content/zh/live/gpu0623-live.md
  content/zh/live/headingdata0616-live.md
  content/zh/live/pulsar-kubesphere-meetup0625.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2509 add zh blog
  content/zh/blogs/manual-kubesphere-persistentvolumes-migration.md
Labels: approved, lgtm, size/L

#2508 add new blog
  content/zh/blogs/kubesphere-ingress-fault-diagnosis.md
  content/zh/news/kubesphere-10k-stars.md
  content/zh/news/openelb-joins-cncf-sandbox-project.md
Labels: approved, lgtm, size/XL

#2510 add new blog
  content/zh/blogs/pulsar-on-kubesphere.md
Labels: approved, lgtm, size/L

#2516 fix 3.3
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/introduction/vars.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/introduction/what's-new-in-3.3.0.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/common/system-requirements.md
  content/zh/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/introduction/what's-new-in-3.3.0.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2515 fix: support docs switch to the path as '/docs/v3.3'
  layouts/partials/css.html
Labels: approved, lgtm, size/S

#2520 Update v3.2.x doc URL
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#2522 Accessibility add alt to docs img
  content/en/docs/application-store/external-apps/deploy-gitlab.md
  content/en/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/en/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/en/docs/project-administration/disk-log-collection.md
  content/en/docs/project-user-guide/application-workloads/container-image-settings.md
  content/en/docs/project-user-guide/application-workloads/cronjobs.md
  content/en/docs/project-user-guide/application-workloads/deployments.md
  content/en/docs/project-user-guide/application-workloads/jobs.md
  content/en/docs/project-user-guide/application-workloads/statefulsets.md
  content/en/docs/project-user-guide/configuration/secrets.md
  content/en/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/en/docs/quick-start/deploy-bookinfo-to-k8s.md
  content/zh/docs/application-store/external-apps/deploy-gitlab.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/devops-user-guide/examples/use-nexus-in-pipelines.md
  content/zh/docs/project-administration/disk-log-collection.md
  content/zh/docs/project-user-guide/application-workloads/container-image-settings.md
  content/zh/docs/project-user-guide/application-workloads/cronjobs.md
  content/zh/docs/project-user-guide/application-workloads/deployments.md
  content/zh/docs/project-user-guide/application-workloads/jobs.md
  content/zh/docs/project-user-guide/application-workloads/statefulsets.md
  content/zh/docs/project-user-guide/configuration/secrets.md
  content/zh/docs/project-user-guide/custom-application-monitoring/examples/monitor-sample-web.md
  content/zh/docs/quick-start/deploy-bookinfo-to-k8s.md
Labels: approved, lgtm, size/M

#2514 add new case
  content/zh/case/_index.md
  content/zh/case/xdf.md
  static/images/case/logo-xdf.png
Labels: approved, lgtm, size/L

#2525 Update v3.3.0 tip
  content/en/docs/release/release-v330.md
  content/zh/docs/release/release-v330.md
  layouts/partials/header.html
Labels: approved, lgtm, size/L

#2526 Update zh doc URL.
  config/_default/config.toml
Labels: approved, lgtm, size/M

#2527 add news: KubeSphere 3.3.0 GA
  content/zh/news/kubesphere-3.3.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2532 Add news: KubeSphere v3.3.0 Released
  content/en/news/kubesphere-3.1.0-ga-announcement.md
  content/en/news/kubesphere-3.2.0-ga-announcement.md
  content/en/news/kubesphere-3.3.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2538 change kubekey release version
  content/en/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.3/installing-on-linux/introduction/vars.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.3/quick-start/enable-pluggable-components.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.3/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.3/installing-on-linux/introduction/vars.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.3/quick-start/enable-pluggable-components.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/M

#2535 add new blog of kubesphere-loadbalance
  content/zh/blogs/kubesphere-loadbalance.md
Labels: approved, lgtm, size/L

#2534 add new blog of kubesphere-level
  content/zh/blogs/kubesphere-level.md
Labels: approved, lgtm, size/L

#2539 update the page of live
  content/zh/live/0625-dns.md
  content/zh/live/0625-headingdata.md
  content/zh/live/0625-pulsar-kubesphere.md
  content/zh/live/0625-pulsar.md
  content/zh/live/_index.md
  content/zh/live/gpu0623-live.md
  content/zh/live/kubesphere-v3.3.0-live.md
  content/zh/live/pulsar-kubesphere-meetup0625.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2536 add new blog of kubesphere-wiki
  content/zh/blogs/kubesphere-wiki.md
Labels: approved, lgtm, size/XL

#2537 Accessibility add link name
  layouts/docs/second.html
Labels: approved, lgtm, size/S

#2541 Accessibility add link name
  layouts/docs/single.html
Labels: approved, lgtm, size/S
