Repository kubesphere/website, pull requests merged in 2022-04, with the labels that each got.

#2372 Fix Minor Issues
  content/en/docs/introduction/what's-new-in-3.2.x.md
  content/en/projects/_index.md
Labels: approved, lgtm, size/S

#2371 Accessibility add link name to logo
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2378 update the page of live
  content/zh/live/_index.md
  content/zh/live/k8s-apisix-openelb0406-live.md
  content/zh/live/kubekey0331-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2379 Update Baidu Analytics
  layouts/partials/head.html
Labels: approved, lgtm, size/XS

#2380 fix join-us on mobile
  assets/scss/index.scss
Labels: approved, lgtm, size/XS

#2383 update the page of live
  content/zh/live/_index.md
  content/zh/live/iot0414-live.md
  content/zh/live/k8s-apisix-openelb0406-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2386 add new blog
  config/_default/config.toml
  content/zh/blogs/ospp-2022.md
Labels: approved, lgtm, size/L

#2388 add new case of turing
  content/zh/case/_index.md
  content/zh/case/turing.md
  static/images/case/logo-turing.png
Labels: approved, lgtm, size/L

#2384 fix footer form on mobile
  assets/scss/footer.scss
Labels: approved, lgtm, size/XS

#2336 Update use-an-oauth2-identity-provider.md
  content/zh/docs/access-control-and-account-management/external-authentication/use-an-oauth2-identity-provider.md
Labels: approved, lgtm, size/XS

#2389 Accessibility add link name to wechat
  layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#2394 update the page of live
  content/zh/live/_index.md
  content/zh/live/iot0414-live.md
  content/zh/live/yatai0421-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2395 add new blog
  content/zh/blogs/fluent-operator-logging.md
Labels: approved, lgtm, size/XL

#2391 add new case logo
  content/en/case/_index.md
  content/zh/case/_index.md
  static/images/case/section6-sinodata.png
Labels: approved, lgtm, size/S

#2382 Update links
  content/en/docs/quick-start/enable-pluggable-components.md
  content/en/docs/reference/api-docs.md
  content/zh/docs/reference/api-docs.md
Labels: approved, lgtm, size/S

#2396 add new blog
  content/zh/blogs/k8s-security.md
Labels: approved, lgtm, size/L

#2398 update the page of user-group-hangzhou
  content/zh/user-group/hangzhou.md
  static/images/user-group/hangzhou/gaopengcheng.png
  static/images/user-group/hangzhou/wangyijia.png
Labels: approved, lgtm, size/S

#2400 Accessibility add link name to social icons
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2403 add new user of user-group-hangzhou
  content/zh/user-group/hangzhou.md
  static/images/user-group/hangzhou/zhanghui.png
Labels: approved, lgtm, size/XS

#2406 add new blog of etcd
  content/zh/blogs/kubesphere-etcd.md
Labels: approved, lgtm, size/XL

#2385 Update air-gapped installation
  content/en/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/blogs/arm64-kubernetes-kubesphere.md
  content/zh/blogs/aws-kubernetes.md
  content/zh/blogs/cilium-kubesphere-kubernetes.md
  content/zh/blogs/kubesphere-k8s-cluster.md
  content/zh/blogs/use-KubeKey-to-install-and-deploy-Kubernetes-and-kubeovn.md
  content/zh/docs/installing-on-linux/cluster-operation/add-new-nodes.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
Labels: lgtm, size/XXL

#2410 update the page of live
  content/zh/live/_index.md
  content/zh/live/notification-manager-0428-live.md
  content/zh/live/yatai0421-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2411 fix missing kubesphere project in the script
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
Labels: lgtm, size/XS

#2416 update the url of ospp-2022
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#2404 add new blog of kubeeye
  content/zh/blogs/k8s-kubeeye-security.md
Labels: approved, lgtm, size/L

#2417 Accessibility add link arrow title
  layouts/blogs/list.html
Labels: approved, lgtm, size/XS

#2408 Accessibility add ifame title
  layouts/_default/scenario.html
Labels: approved, lgtm, size/XS
