Repository kubesphere/website, pull requests merged in 2022-03, with the labels that each got.

#2328 update the page of live
  content/zh/live/_index.md
  content/zh/live/gitlab0224-live.md
  content/zh/live/k8s0303-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2329 update the page of user-group
  content/zh/user-group/_index.md
Labels: approved, lgtm, size/XS

#2332 update the page of live
  content/zh/live/_index.md
  content/zh/live/k8s0303-live.md
  content/zh/live/skywalking0310-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2331 Add EN Blog: Canary Release in Kubernetes with Nginx Ingress
  content/en/blogs/canary-release-with-nginx-ingress.md
  static/images/blogs/en/canary-release-with-nginx-ingress/add-annotation.png
  static/images/blogs/en/canary-release-with-nginx-ingress/canary-details.png
  static/images/blogs/en/canary-release-with-nginx-ingress/canary-on-console.png
  static/images/blogs/en/canary-release-with-nginx-ingress/canary-release.png
  static/images/blogs/en/canary-release-with-nginx-ingress/cluster-gateway.png
  static/images/blogs/en/canary-release-with-nginx-ingress/user-based-canary.png
  static/images/blogs/en/canary-release-with-nginx-ingress/weight-based-canary.png
Labels: approved, lgtm, size/L

#2337 Remove remarks about containerd being experimentally supported.
  content/en/common/container-runtime-requirements.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/zh/common/container-runtime-requirements.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/S

#2285 Update YAML configuration in Documentation/FAQ/Observability FAQ/Logging.
  content/en/docs/faq/observability/logging.md
Labels: approved, lgtm, size/XS

#2327 Add EN Blog: Serverless vs FaaS
  content/en/blogs/serverless-vs-faas.md
  static/images/blogs/en/serverless-vs-faas/serverless-faas.png
Labels: approved, lgtm, size/M, tide/merge-method-squash

#2338 update the page of live
  content/zh/live/_index.md
  content/zh/live/argocd0217-live.md
  content/zh/live/ceph1216-live.md
  content/zh/live/ckacks1021-live.md
  content/zh/live/faas1223-live.md
  content/zh/live/gitlab0224-live.md
  content/zh/live/go1104-live.md
  content/zh/live/k8s0303-live.md
  content/zh/live/kubekey1209-live.md
  content/zh/live/kubeovn1028-live.md
  content/zh/live/mqtt1230-live.md
  content/zh/live/nebula0902-live.md
  content/zh/live/openfunction0113-live.md
  content/zh/live/rook1111-live.md
  content/zh/live/uisee0916-live.md
  content/zh/live/uisee0923-live.md
  content/zh/live/wasm0909-live.md
  content/zh/live/webhook1202-live.md
Labels: approved, lgtm, size/L

#2339 update the page of live
  content/zh/live/argocd0217-live.md
  content/zh/live/ceph1216-live.md
  content/zh/live/ckacks1021-live.md
  content/zh/live/faas1223-live.md
  content/zh/live/gitlab0224-live.md
  content/zh/live/go1104-live.md
  content/zh/live/k8s0303-live.md
  content/zh/live/kubekey1209-live.md
  content/zh/live/kubeovn1028-live.md
  content/zh/live/mqtt1230-live.md
  content/zh/live/nebula0902-live.md
  content/zh/live/openfunction0113-live.md
  content/zh/live/rook1111-live.md
  content/zh/live/uisee0916-live.md
  content/zh/live/uisee0923-live.md
  content/zh/live/wasm0909-live.md
  content/zh/live/webhook1202-live.md
Labels: approved, lgtm, size/L

#2342 fix: Meetup slide problem
  layouts/live/list.html
Labels: approved, lgtm, size/S

#2341 update the page of live
  content/zh/live/_index.md
  content/zh/live/changsha0312-cluster.md
  content/zh/live/changsha0312-microservice.md
  content/zh/live/changsha0312-rust.md
  content/zh/live/changsha0312-serverless.md
  content/zh/live/changsha0312-webassembly.md
  content/zh/live/kasten0317-live.md
  content/zh/live/meetup-changsha-20220312.md
  content/zh/live/skywalking0310-live.md
  content/zh/live/test.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2343 add a piece of news for KubeCon EU 2022
  content/en/news/_index.md
  content/en/news/join-us-at-kubecon-eu-2022.md
  static/images/news/kubecon-eu/kubecon-eu-2022-banner.png
Labels: approved, lgtm, size/M

#2344 fix: Meetup card scroll problem.
  assets/scss/live.scss
Labels: approved, lgtm, size/XS

#2348 update the page of live
  content/zh/live/_index.md
  content/zh/live/kasten0317-live.md
  content/zh/live/milvus0324-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2350 fix form color
  assets/scss/footer.scss
Labels: approved, lgtm, size/XS

#2347 update the docs to fix issues
  content/en/blogs/add-master-for-ha-using-kubekey.md
  content/en/blogs/aws-kubernetes.md
  content/en/blogs/cilium-as-cni.md
  content/en/blogs/dockershim-out-of-kubernetes.md
  content/en/blogs/install-kubernetes-using-kubekey.md
  content/en/blogs/install-nfs-server-client-for-kubesphere-cluster.md
  content/en/blogs/k8s-ha-practices.md
  content/en/blogs/scale-kubernetes-cluster-using-kubekey.md
  content/en/blogs/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/introduction/kubekey.md
  content/en/docs/installing-on-linux/introduction/multioverview.md
  content/en/docs/installing-on-linux/introduction/vars.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/quick-start/all-in-one-on-linux.md
  content/en/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/upgrade/upgrade-with-kubekey.md
  content/zh/blogs/aws-kubernetes.md
  content/zh/blogs/cilium-kubesphere-kubernetes.md
  content/zh/blogs/dockershim-out-of-kubernetes.md
  content/zh/blogs/kubesphere-k8s-cluster.md
  content/zh/blogs/use-KubeKey-to-install-and-deploy-Kubernetes-and-kubeovn.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/installing-on-kubernetes/introduction/prerequisites.md
  content/zh/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/introduction/kubekey.md
  content/zh/docs/installing-on-linux/introduction/multioverview.md
  content/zh/docs/installing-on-linux/introduction/vars.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/quick-start/all-in-one-on-linux.md
  content/zh/docs/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2357 add a new blog
  content/zh/blogs/qunar-kubesphere-best-practice.md
  content/zh/conferences/qunar.md
Labels: approved, lgtm, size/L

#2356 add a new partner of jihu gitlab
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/jihu.svg
Labels: approved, lgtm, size/M

#2359 add new blog
  content/zh/blogs/deploying-kubesphere-clusters-offline-with-kubekey.md
Labels: approved, lgtm, size/XL

#2352 Upload EN Blog: Guide to Kubernetes Ingress Controllers
  content/en/blogs/guide-to-kubernetes-ingress-controllers.md
Labels: approved, lgtm, size/L

#2354 Accessibility add alt to image
  layouts/index.html
Labels: approved, lgtm, size/XS

#2345 Add EN Blog: Restart a Kubernetes Cluster
  content/en/blogs/restart-k8s-cluster.md
  static/images/blogs/en/restart-k8s-cluster/restart-k8s.png
Labels: approved, lgtm, size/L, tide/merge-method-squash

#2360 add new blog of kubekey-v2.0.0-release
  content/zh/blogs/kubekey-v2.0.0-release.md
Labels: approved, lgtm, size/L

#2355 Add EN Blog: Delete Kubernetes Pods
  content/en/blogs/delete-k8s-pods.md
  static/images/blogs/en/delete-k8s-pod/delete-pod.png
  static/images/blogs/en/delete-k8s-pod/pod-ui.png
Labels: approved, lgtm, size/M

#2351 Upload EN Blog: Deep Dive into Kubernetes Logging
  content/en/blogs/deep-dive-into-kubernetes-logging.md
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_1.png
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_2.png
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_3.png
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_4.png
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_5.png
  static/images/blogs/en/deep-dive-into-kubernetes-logging/logging_6.png
Labels: approved, lgtm, size/L, tide/merge-method-squash

#2365 add new blog
  content/zh/blogs/kubekey-v2.0.0-release.md
  content/zh/blogs/kubesphere-terminating-namespace.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2369 update the page of live
  content/zh/live/_index.md
  content/zh/live/kubekey0331-live.md
  content/zh/live/milvus0324-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2364 add favicons
  layouts/partials/favicons.html
  layouts/partials/head.html
  static/favicon.ico
  static/images/favicons/android-chrome-192x192.png
  static/images/favicons/android-chrome-256x256.png
  static/images/favicons/apple-touch-icon.png
  static/images/favicons/browserconfig.xml
  static/images/favicons/favicon-16x16.png
  static/images/favicons/favicon-32x32.png
  static/images/favicons/favicon.ico
  static/images/favicons/mstile-150x150.png
  static/images/favicons/safari-pinned-tab.svg
  static/images/favicons/site.webmanifest
Labels: approved, lgtm, size/M
