Repository kubesphere/website, pull requests merged in 2022-09, with the labels that each got.

#2649 update hugo
  netlify.toml
Labels: approved, lgtm, size/XS

#2652 add new ambassador
  content/en/news/kubesphere-ambassador-certificates-en.md
Labels: approved, lgtm, size/S

#2654 update hugo
  netlify.toml
Labels: approved, lgtm, size/XS

#2655 add blog
  content/zh/blogs/kubesphere-data-migration-using-juicefs.md
Labels: approved, lgtm, size/L

#2656 add new blog
  content/zh/blogs/kubesphere-deepflow.md
Labels: approved, lgtm, size/M

#2657 update the page of live
  content/zh/live/_index.md
  content/zh/live/databend0908-live.md
  content/zh/live/kubeedge0901-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2658 add blog
  content/zh/blogs/kubesphere-gateway.md
Labels: approved, lgtm, size/L

#2659 fix
  content/zh/news/kubesphere-user-group.md
Labels: approved, lgtm, size/XS

#2651 update kubeedge docs
  content/en/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/pluggable-components/kubeedge.md
  content/zh/docs/v3.3/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/pluggable-components/kubeedge.md
Labels: approved, lgtm, size/S

#2660 fix the image
  content/zh/blogs/kubesphere-k8s-cluster.md
Labels: approved, lgtm, size/XS

#2665 Update OWNERS
  OWNERS
Labels: lgtm, size/XS

#2664 update favicon on safari
  layouts/partials/favicons.html
Labels: approved, lgtm, size/XS

#2662 update kubekey version
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.3/installing-on-linux/introduction/vars.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.3/installing-on-linux/introduction/vars.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2663 update demo
  i18n/en.yaml
  i18n/zh.yaml
Labels: approved, lgtm, size/XS

#2667 update the page of live
  content/zh/live/_index.md
  content/zh/live/container0915-live.md
  content/zh/live/databend0908-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2669 update hugo to 0.103.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2670 add new blog
  content/zh/blogs/cloudnative-paas.md
Labels: approved, lgtm, size/XL

#2674 update the page of live
  content/zh/live/_index.md
  content/zh/live/container0915-live.md
  content/zh/live/k8s0922-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2675 add new blog of nebulagraph-cloud-service
  content/zh/blogs/nebulagraph-cloud-service.md
Labels: approved, lgtm, size/L

#2672 update hugo to 0.103.1
  netlify.toml
Labels: approved, lgtm, size/XS

#2673 Update multioverview.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
Labels: approved, lgtm, size/XS

#2680 update the page of user-group-hangzhou
  content/zh/live/_index.md
  content/zh/user-group/hangzhou.md
Labels: approved, lgtm, size/M

#2677 add new blog of cks-guide
  content/zh/blogs/cks-guide.md
Labels: approved, lgtm, size/XL

#2678 add new blog of prometheus-storage
  content/zh/blogs/coredns-k8s-dns.md
  content/zh/blogs/prometheus-storage.md
Labels: approved, lgtm, size/L

#2676 add new blog of rabbitmq-k8s
  content/zh/blogs/rabbitmq-k8s.md
Labels: approved, lgtm, size/XL

#2681 fix the url
  content/zh/learn/level_8/lesson_1/content.md
  content/zh/learn/level_8/lesson_2/content.md
Labels: approved, lgtm, size/XS

#2684 update hugo to 0.104.2
  netlify.toml
Labels: approved, lgtm, size/XS
