Repository kubesphere/website, pull requests merged in 2022-02, with the labels that each got.

#2278 Add docs ：Deploy RadonDB MySQL Operator and Cluster
  content/en/docs/application-store/built-in-apps/radondb-mysql-app.md
  content/en/docs/application-store/external-apps/deploy-clickhouse.md
  content/en/docs/application-store/external-apps/deploy-radondb-mysql.md
  content/zh/docs/application-store/built-in-apps/radondb-mysql-app.md
  content/zh/docs/application-store/external-apps/deploy-clickhouse.md
  content/zh/docs/application-store/external-apps/deploy-radondb-mysql.md
  static/images/docs/appstore/external-apps/deploy-radondb-mysql/certify_url.png
  static/images/docs/appstore/external-apps/deploy-radondb-mysql/kubectl_terminal.png
  static/images/docs/appstore/external-apps/deploy-radondb-mysql/operator_yaml.png
  static/images/docs/appstore/external-apps/deploy-radondb-mysql/pod_terminal.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-radondb-mysql/certify_url.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-radondb-mysql/kubectl_terminal.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-radondb-mysql/operator_yaml.png
  static/images/docs/zh-cn/appstore/external-apps/deploy-radondb-mysql/pod_terminal.png
Labels: approved, lgtm, size/L

#2260 service account bilingual
  content/en/docs/pluggable-components/app-store.md
  content/en/docs/pluggable-components/devops.md
  content/en/docs/pluggable-components/overview.md
  content/en/docs/pluggable-components/service-mesh.md
  content/en/docs/project-user-guide/configuration/serviceaccounts.md
  content/zh/docs/pluggable-components/_index.md
  content/zh/docs/pluggable-components/alerting.md
  content/zh/docs/pluggable-components/app-store.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/devops.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/kubeedge.md
  content/zh/docs/pluggable-components/logging.md
  content/zh/docs/pluggable-components/metrics-server.md
  content/zh/docs/pluggable-components/network-policy.md
  content/zh/docs/pluggable-components/overview.md
  content/zh/docs/pluggable-components/pod-ip-pools.md
  content/zh/docs/pluggable-components/service-mesh.md
  content/zh/docs/pluggable-components/service-topology.md
  content/zh/docs/pluggable-components/uninstall-pluggable-components.md
  content/zh/docs/project-user-guide/configuration/serviceaccounts.md
Labels: approved, lgtm, size/L

#2288 add new blog of kubesphere-kubeedge
  content/zh/blogs/kubesphere-kubeedge.md
Labels: approved, lgtm, size/L

#2287 add new blog of kubesphere-backend-sourcecode
  content/zh/blogs/kubesphere-backend-sourcecode.md
Labels: approved, lgtm, size/XL

#2300 add new blog of kubesphere-gitlab-devops
  content/zh/blogs/kubesphere-gitlab-devops.md
Labels: approved, lgtm, size/L

#2284 add new blog of gitlab-kubesphere
  content/zh/blogs/gitlab-kubesphere.md
Labels: approved, lgtm, size/L

#2289 Change externalElasticsearchHost to externalElasticsearchUrl
  content/en/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/en/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/pluggable-components/auditing-logs.md
  content/en/docs/pluggable-components/events.md
  content/en/docs/pluggable-components/logging.md
  content/zh/docs/cluster-administration/cluster-settings/log-collections/introduction.md
  content/zh/docs/faq/observability/logging.md
  content/zh/docs/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/pluggable-components/auditing-logs.md
  content/zh/docs/pluggable-components/events.md
  content/zh/docs/pluggable-components/logging.md
Labels: approved, lgtm, size/M

#2301 update the footer
  data/zh/footer.yaml
Labels: approved, lgtm, size/XS

#2302 add new blog of k8s-backup-disater-recovery-service
  content/zh/blogs/k8s-backup-disater-recovery-service.md
Labels: approved, lgtm, size/L

#2283 add new blog
  content/zh/blogs/kubesphere-k8s-cluster.md
Labels: approved, lgtm, size/XL

#2303 update the page of live
  content/zh/live/_index.md
  content/zh/live/argocd0217-live.md
  content/zh/live/openfunction0113-live.md
Labels: approved, lgtm, size/M

#2306 fix-issues-2305-update-invalid-maven-cache
  content/en/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
Labels: approved, area/devops, lgtm, size/XS

#2309 fix: Let teacher card auto slide
  assets/scss/learn.scss
  layouts/learn/list.html
Labels: approved, lgtm, size/L

#2310 Add EN Blog: What is Helm in Kubernetes
  content/en/blogs/what-is-helm-in-kubernetes.md
  static/images/blogs/en/what-is-helm-in-kubernetes/k8s-and-helm.png
  static/images/blogs/en/what-is-helm-in-kubernetes/ks-app-store.png
Labels: approved, lgtm, size/L

#2299 Add EN Blog: Kubernetes High Availability Essential Practices Simply Explained
  content/en/blogs/k8s-ha-practices.md
  static/images/blogs/en/k8s-ha-practices/internalLoadBalancer.png
  static/images/blogs/en/k8s-ha-practices/k8s-ha-strategy.png
  static/images/blogs/en/k8s-ha-practices/k8s-structure.png
  static/images/blogs/en/k8s-ha-practices/kdm-ha.png
Labels: approved, lgtm, size/L

#2304 Update set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: approved, lgtm, size/XS

#2311 correct the chinese version of release-note for 3.2.0
  content/zh/docs/release/release-v320.md
Labels: approved, lgtm, size/M

#2314 minor updates to the footer and incorrect blog title
  content/en/blogs/Part-2:-How-to-migrate-to-containerd-and-CRI-O-after-Docker-Deprecation-in-Kubernetes.md
  i18n/en.yaml
  i18n/tr.yaml
  i18n/zh.yaml
  layouts/docs/second.html
  layouts/docs/single.html
  layouts/partials/footer.html
Labels: approved, lgtm, size/S

#2316 add new blog of neuvector-cloud-native-security
  content/zh/blogs/neuvector-cloud-native-security.md
Labels: approved, lgtm, size/L

#2318 update the page of user-group
  config/_default/config.toml
  content/zh/conferences/openfunction.md
  content/zh/user-group/_index.md
  content/zh/user-group/chengdu.md
  content/zh/user-group/hangzhou.md
  content/zh/user-group/shanghai.md
  data/zh/footer.yaml
  layouts/user-group/list.html
  static/images/user-group/chengdu/huangshihao.jpeg
  static/images/user-group/chengdu/hutao.jpeg
  static/images/user-group/chengdu/louju.jpg
  static/images/user-group/chengdu/person.png
  static/images/user-group/chengdu/zhouzhengjun.jpg
  static/images/user-group/chengdu/zhouzhengjunvx.jpeg
  static/images/user-group/hangzhou/majinjing.jpeg
  static/images/user-group/hangzhou/person.png
  static/images/user-group/hangzhou/xuexinglin.jpeg
  static/images/user-group/hangzhou/yinmin.jpeg
  static/images/user-group/hangzhou/yinminvx.png
  static/images/user-group/shanghai/gxd.png
  static/images/user-group/shanghai/liudehan.jpeg
  static/images/user-group/shanghai/zhanghaili.png
  static/images/user-group/shanghai/zhanghailivx.jpeg
  static/images/user-group/shanghai/zhanghaofei.jpeg
  static/images/user-group/shanghai/zhl.png
Labels: approved, lgtm, size/L

#2319 fix a typo of user-group hangzhou
  content/zh/user-group/hangzhou.md
Labels: approved, lgtm, size/XS

#2322 Fix blog path error.
  content/en/blogs/Part-2-How-to-migrate-to-containerd-and-CRI-O-after-Docker-Deprecation-in-Kubernetes.md
  static/images/blogs/Part-2-How-to-migrate-to-containerd-and-CRI-O-after-Docker-Deprecation-in-Kubernetes/2.png
Labels: approved, lgtm, size/XS

#2320 update the header of website
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2323 add k8s operator blog
  content/en/blogs/what-are-kubernetes-operators.md
  static/images/blogs/en/what-are-operators/k8s-operators.png
Labels: approved, lgtm, size/L

#2324 fix: Update styles for the user group page
  assets/scss/user-group-single.scss
  assets/scss/user-group.scss
  content/zh/user-group/_index.md
  layouts/user-group/list.html
Labels: approved, lgtm, size/M
