Repository kubesphere/website, pull requests merged in 2022-10, with the labels that each got.

#2688 add new blog
  content/zh/blogs/kubesphere-kubeedge-edgemesh.md
Labels: approved, lgtm, size/L

#2687 add new blog of kubesphere-redis
  content/zh/blogs/kubesphere-redis.md
Labels: approved, lgtm, size/L

#2679 Update release-v320.md
  content/zh/docs/v3.3/release/release-v320.md
Labels: approved, lgtm, size/XS

#2666 update NFS description
  content/en/docs/v3.3/cluster-administration/storageclass.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/reference/storage-system-installation/nfs-server.md
  content/zh/docs/v3.3/cluster-administration/storageclass.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/reference/storage-system-installation/nfs-server.md
Labels: approved, lgtm, size/S

#2686 update hugo to 0.104.3
  netlify.toml
Labels: approved, lgtm, size/XS

#2689 update cloud native courses
  content/zh/learn/level_6/lesson_12/_index.md
  content/zh/learn/level_6/lesson_12/content.md
  content/zh/learn/level_6/lesson_12/video.md
  content/zh/learn/level_6/lesson_13/_index.md
  content/zh/learn/level_6/lesson_13/content.md
  content/zh/learn/level_6/lesson_13/video.md
  content/zh/learn/level_6/lesson_14/_index.md
  content/zh/learn/level_6/lesson_14/content.md
  content/zh/learn/level_6/lesson_14/video.md
  content/zh/learn/level_6/lesson_15/_index.md
  content/zh/learn/level_6/lesson_15/content.md
  content/zh/learn/level_6/lesson_15/video.md
  content/zh/learn/level_6/lesson_16/_index.md
  content/zh/learn/level_6/lesson_16/content.md
  content/zh/learn/level_6/lesson_16/video.md
  content/zh/learn/level_6/lesson_17/_index.md
  content/zh/learn/level_6/lesson_17/content.md
  content/zh/learn/level_6/lesson_17/video.md
  content/zh/learn/level_6/lesson_18/_index.md
  content/zh/learn/level_6/lesson_18/content.md
  content/zh/learn/level_6/lesson_18/video.md
  content/zh/learn/level_6/lesson_19/_index.md
  content/zh/learn/level_6/lesson_19/content.md
  content/zh/learn/level_6/lesson_19/video.md
  content/zh/learn/level_6/lesson_20/_index.md
  content/zh/learn/level_6/lesson_20/content.md
  content/zh/learn/level_6/lesson_20/video.md
  content/zh/learn/level_6/lesson_21/_index.md
  content/zh/learn/level_6/lesson_21/content.md
  content/zh/learn/level_6/lesson_21/video.md
  content/zh/learn/level_6/lesson_22/_index.md
  content/zh/learn/level_6/lesson_22/content.md
  content/zh/learn/level_6/lesson_22/video.md
  content/zh/learn/level_6/lesson_23/_index.md
  content/zh/learn/level_6/lesson_23/content.md
  content/zh/learn/level_6/lesson_23/video.md
  content/zh/learn/level_6/lesson_24/_index.md
  content/zh/learn/level_6/lesson_24/content.md
  content/zh/learn/level_6/lesson_24/video.md
Labels: approved, lgtm, size/L

#2690 update the page of live
  content/zh/live/_index.md
  content/zh/live/k8s0922-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2692 update the page of live
  content/zh/live/_index.md
  content/zh/live/curve1013-live.md
Labels: approved, lgtm, size/M

#2695 update version
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/XS

#2694 update gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#2696 update the page of live
  content/zh/live/_index.md
  content/zh/live/apisix-kubesphere-meetup1022.md
Labels: approved, lgtm, size/M

#2698 add new blog
  content/zh/blogs/Kubernetes- microservice- monitoring.md
Labels: approved, lgtm, size/L

#2682 add cas identity provider
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/cas-identity-provider.md
  content/zh/docs/v3.3/access-control-and-account-management/external-authentication/set-up-external-authentication.md
Labels: approved, lgtm, size/M

#2697 add new blog
  content/zh/blogs/kubesphere- microservice-grayrelease.md
Labels: approved, lgtm, size/L

#2699 update the page of live
  content/zh/live/_index.md
  content/zh/live/apisix-kubesphere-meetup1022.md
  content/zh/live/curve1013-live.md
  content/zh/live/multicluster1020-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2700 add new case
  content/zh/case/_index.md
  content/zh/case/vesoft.md
  content/zh/case/xdf.md
  static/images/case/section6-vesoft-4.png
Labels: approved, lgtm, size/L

#2702 add new blog
  content/zh/blogs/kubesphere-nfs.md
Labels: approved, lgtm, size/L

#2703 add new blog
  content/zh/blogs/kubernetes-vmware-vsphere.md
Labels: approved, lgtm, size/L

#2704 Delete the description of the static ip supporting of the deploy.
  content/zh/docs/v3.3/release/release-v310.md
Labels: approved, lgtm, size/XS

#2705 update the page of live
  content/zh/live/_index.md
  content/zh/live/apisix-kubesphere-meetup1022-ks.md
  content/zh/live/apisix-kubesphere-meetup1022-openfunction.md
  content/zh/live/apisix-kubesphere-meetup1022-seevo.md
  content/zh/live/apisix-kubesphere-meetup1022-vivo.md
  content/zh/live/apisix-kubesphere-meetup1022.md
  content/zh/live/juicefs1027-live.md
  content/zh/live/multicluster1020-live.md
  static/images/live/cloudnative-live-20221020.png
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2706 fix: Update slack channel address
  config/_default/config.toml
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/contribution/_index.md
  content/zh/contribution/_index.md
Labels: lgtm, size/S

#2708 update the page of projects
  content/en/projects/_index.md
  content/zh/projects/_index.md
Labels: approved, lgtm, size/M

#2707 add news of partnership
  content/en/news/KubeSphere-Turkey-and-Huawei-Partnership.md
  content/zh/news/KubeSphere-Turkey-and-Huawei-Announce-Partnership.md
Labels: approved, lgtm, size/M

#2710 3.3.1 update release notes
  content/en/docs/v3.3/introduction/what's-new-in-3.3.md
  content/en/docs/v3.3/release/release-v330.md
  content/en/docs/v3.3/release/release-v331.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-ks-installer.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/what-changed.md
  content/zh/docs/v3.3/introduction/what's-new-in-3.3.md
  content/zh/docs/v3.3/release/release-v330.md
  content/zh/docs/v3.3/release/release-v331.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/what-changed.md
  layouts/partials/header.html
Labels: approved, lgtm, size/L

#2711 fix: Show github link directly
  assets/scss/projects.scss
Labels: approved, lgtm, size/XS

#2412 Added files for installing kubesphere on minikube issue #2134
  .github/workflows/build.yml
  content/en/docs/installing-on-kubernetes/on-prem-kubernetes/installing-kubesphere-on-minikube.md
Labels: approved, kind/documentation, lgtm, size/L

#2701 update nfs-client to nfs-subdir
  content/zh/docs/v3.3/cluster-administration/storageclass.md
Labels: approved, lgtm, size/S

#2712 add news of ks 3.3.1
  content/zh/news/kubesphere-3.3.1-ga-announcement.md
Labels: approved, lgtm, size/M
