Repository kubesphere/website, pull requests merged in 2022-05, with the labels that each got.

#2421 update the page of live
  content/zh/live/_index.md
  content/zh/live/notification-manager-0428-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/M

#2426 add new user of usergroup-hangzhou
  content/zh/blogs/kubesphere-etcd.md
  content/zh/live/_index.md
  content/zh/user-group/hangzhou.md
  static/images/user-group/hangzhou/cuiguangzhang.png
Labels: approved, lgtm, size/XS

#2419 Update shut-down-and-restart-cluster-gracefully.md
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
Labels: approved, lgtm, size/XS

#2431 update the page of live
  content/zh/live/_index.md
  content/zh/live/clickhouse0512-live.md
Labels: approved, lgtm, size/M

#2428 fix issues
  content/en/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/en/docs/quick-start/create-workspace-and-project.md
  content/zh/docs/multicluster-management/enable-multicluster/agent-connection.md
  content/zh/docs/quick-start/create-workspace-and-project.md
Labels: approved, lgtm, size/L

#2430 3.3 devops
  config/_default/config.toml
  content/en/docs/cluster-administration/shut-down-and-restart-cluster-gracefully.md
  content/en/docs/devops-user-guide/how-to-use/jenkins-email.md
  content/zh/blogs/k8s-kubeeye-security.md
  content/zh/blogs/kubesphere-etcd.md
  content/zh/docs/application-store/built-in-apps/jh-gitlab.md
  content/zh/docs/devops-user-guide/devops-overview/_index.md
  content/zh/docs/devops-user-guide/devops-overview/devops-project-management.md
  content/zh/docs/devops-user-guide/devops-overview/overview.md
  content/zh/docs/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/devops-user-guide/examples/go-project-pipeline.md
  content/zh/docs/devops-user-guide/examples/multi-cluster-project-example.md
  content/zh/docs/devops-user-guide/how-to-integrate/sonarqube.md
  content/zh/docs/devops-user-guide/how-to-use/code-repositories/_index.md
  content/zh/docs/devops-user-guide/how-to-use/code-repositories/import-code-repositories.md
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/_index.md
  content/zh/docs/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/_index.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/add-cd-allowlist.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/credential-management.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/role-and-member-management.md
  content/zh/docs/devops-user-guide/how-to-use/devops-settings/set-ci-node.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/_index.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/choose-jenkins-agent.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/customize-jenkins-agent.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/gitlab-multibranch-pipeline.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/jenkins-email.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/jenkins-setting.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/jenkins-shared-library.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/pipeline-settings.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/pipeline-webhook.md
  content/zh/docs/devops-user-guide/how-to-use/pipelines/use-pipeline-templates.md
  content/zh/live/_index.md
  content/zh/live/notification-manager-0428-live.md
  content/zh/user-group/hangzhou.md
  layouts/_default/scenario.html
  layouts/blogs/list.html
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/app-creation.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/from-app-store.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/jh-helm-charts.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/jh-install-basic-info.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/jh-instance.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/jihu-gitlab-app.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/kubectl-check.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/pod-status.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/project-creation.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/succ-installation.png
  static/images/docs/zh-cn/appstore/built-in-apps/jh-app/workspace-creation.png
  static/images/live/cloudnative-live-banner.png
  static/images/user-group/hangzhou/cuiguangzhang.png
Labels: approved, area/devops, lgtm, size/XL

#2437 add new user of user-group-chengdu
  content/zh/user-group/chengdu.md
  static/images/user-group/chengdu/heshaohui.jpg
Labels: approved, lgtm, size/XS

#2438 update the page of live
  content/zh/live/_index.md
  content/zh/live/chengdu0514-devops.md
  content/zh/live/chengdu0514-fluent-operator.md
  content/zh/live/chengdu0514-kusion.md
  content/zh/live/chengdu0514-level.md
  content/zh/live/chengdu0514-nydus.md
  content/zh/live/chengdu0514-openfunction.md
  content/zh/live/clickhouse0512-live.md
  content/zh/live/fudata-kubesphere.md
  content/zh/live/meetup-chengdu-20220514.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2439 fix: experience account password is incorrect
  i18n/en.yaml
  i18n/zh.yaml
Labels: approved, lgtm, size/XS

#2440 update the page of user-group
  content/zh/user-group/chengdu.md
  content/zh/user-group/hangzhou.md
  static/images/user-group/hangzhou/fudata-kubesphere-cover.png
Labels: approved, lgtm, size/XS

#2434 Scenarios grammer issues
  content/en/docs/introduction/scenarios.md
Labels: approved, lgtm, size/S

#2447 Multi cluster grammar
  content/en/docs/multicluster-management/introduction/kubefed-in-kubesphere.md
Labels: approved, lgtm

#2443 Update release-v321.md
  content/en/docs/release/release-v321.md
Labels: approved, lgtm, size/XS

#2432 minor manifest update
  static/images/favicons/site.webmanifest
Labels: approved, lgtm, size/XS

#2422 Accessibility add iframe title
  layouts/contribution/list.html
Labels: approved, lgtm, size/XS

#2427 fix scroll on modal video
  assets/scss/common.scss
Labels: approved, lgtm, size/XS

#2393 Accessibility add link name
  layouts/partials/downloadButton.html
Labels: approved, lgtm, size/XS

#2451 corrected spelling from meanly to mainly
  content/en/conferences/porter.md
Labels: approved, lgtm, size/XS

#2452 add zh blog
  content/zh/blogs/kubesphere-3.3.0-alpha.md
Labels: approved, lgtm, size/M

#2455 update header
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2457 update the page of live
  content/zh/live/_index.md
  content/zh/live/ksv0526-live.md
Labels: approved, lgtm, size/M

#2460 update zh blog
  content/zh/blogs/kubesphere-3.3.0-rc.md
Labels: approved, lgtm, size/S

#2461 update header
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#2454 fix: Use local file to replace the file in jsdelivr cdn
  content/zh/blogs/calico-wireguard-support-with-azure-cni.md
  layouts/api/single.html
  layouts/partials/css.html
  layouts/partials/head.html
  static/images/jsDelivr/1.1.png
  static/images/jsDelivr/2.1.png
  static/npm/docsearch.js@2/dist/cdn/docsearch.min.css
  static/npm/docsearch.js@2/dist/cdn/docsearch.min.js
  static/npm/redoc/bundles/redoc.standalone.js
Labels: approved, lgtm, size/XXL

#2466 update the page of live
  content/zh/live/_index.md
  content/zh/live/jinaai0602-live.md
  content/zh/live/ksv0526-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/L

#2467 update the page of live
  content/zh/live/_index.md
  content/zh/live/ksv0526-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/S

#2468 Update All-in-One Installation
  content/en/docs/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/XS
