Repository kubesphere/website, pull requests merged in 2022-11, with the labels that each got.

#2713 📝 add new blog
  content/zh/blogs/fluxcd-design.md
Labels: approved, lgtm, size/M

#2715 add new blog
  content/zh/blogs/kubesphere-devops-pipeline-guide.md
Labels: approved, lgtm, size/XL

#2718 update k8s versions
  README.md
  content/en/common/kubernetes-versions.md
  content/en/docs/v3.3/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.3/quick-start/create-workspace-and-project.md
  content/en/docs/v3.3/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-ks-installer.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/common/kubernetes-versions.md
  content/zh/docs/v3.3/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-ks-on-tencent-tke.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/zh/docs/v3.3/installing-on-kubernetes/introduction/prerequisites.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
  static/images/common/view-file.png
Labels: approved, lgtm, size/L

#2717 update the page of live
  content/zh/live/_index.md
  content/zh/live/authorization1103-live.md
  content/zh/live/juicefs1027-live.md
  static/images/live/cloudnative-live-20221020.png
  static/images/live/cloudnative-live-20221027.png
Labels: approved, lgtm, size/M

#2716 add new blog
  content/zh/blogs/kubesphere-pig-practice.md
Labels: approved, lgtm, size/XXL

#2719 update hugo to 0.105.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2720 add two logo of case
  content/en/case/_index.md
  content/zh/case/_index.md
  static/images/case/logo-csztv.png
  static/images/case/logo-nctv.png
Labels: approved, lgtm, size/S

#2721 ks 3.3.1 ga announcement added
  content/en/news/kubesphere-3.3.1-ga-announcement.md
Labels: approved, lgtm, size/M

#2723 update the page of case
  content/en/case/_index.md
  content/zh/case/_index.md
Labels: approved, lgtm, size/L

#2724 Add zh blog
  content/zh/blogs/kubernetes-cni.md
Labels: approved, lgtm, size/XL

#2725 update the page of live
  content/zh/live/_index.md
  content/zh/live/authorization1103-live.md
  static/images/live/cloudnative-live-20221027.png
  static/images/live/cloudnative-live-20221103.png
Labels: approved, lgtm, size/M

#2726 replace one logo of case
  static/images/case/logo-nctv.png
Labels: approved, lgtm, size/XS

#2727 update the page of partner
  content/zh/partner/_index.md
  static/images/partner/QingCloud-Logo-Color.png
Labels: approved, lgtm, size/L

#2728 Update release-v331.md
  content/zh/docs/v3.3/release/release-v331.md
Labels: approved, lgtm, size/XS

#2731 ✨ Add project Kubeeye
  content/en/projects/_index.md
  content/zh/projects/_index.md
Labels: approved, lgtm, size/S

#2732 fix: Update partner page
  assets/scss/partner.scss
  config/upstream-zh/config.toml
  config/upstream/config.toml
  content/en/partner/_index.md
  content/zh/partner/_index.md
  layouts/partner/list.html
Labels: approved, lgtm, size/M

#2733 fix the link of apply partner
  content/zh/partner/_index.md
Labels: approved, lgtm, size/XS

#2735 update the page of live
  content/zh/live/_index.md
  content/zh/live/stonedb1117-live.md
Labels: approved, lgtm, size/M

#2737 update hugo to 0.106.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2738 update the page of live
  content/zh/live/_index.md
  content/zh/live/fluxcd1124-live.md
  content/zh/live/stonedb1117-live.md
  static/images/live/cloudnative-live-20221103.png
  static/images/live/cloudnative-live-20221117.png
Labels: approved, lgtm, size/M

#2739 fix kk version
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.3/installing-on-linux/introduction/vars.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.3/installing-on-linux/introduction/vars.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2745 update hugo to 0.107.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2746 add zh blog
  content/zh/blogs/kubesphere-log-collection.md
Labels: approved, lgtm, size/L

#2748 add new blog
  content/zh/blogs/rocketmq-k8s.md
Labels: approved, lgtm, size/XXL

#2749 add command for removing clusters
  content/en/docs/v3.3/multicluster-management/unbind-cluster.md
  content/zh/docs/v3.3/multicluster-management/unbind-cluster.md
Labels: approved, lgtm, size/M

#2750 update the page of live
  content/zh/live/_index.md
  content/zh/live/fluxcd1124-live.md
  static/images/live/cloudnative-live-20221117.png
  static/images/live/cloudnative-live-20221124.png
Labels: approved, lgtm, size/M

#2751 add new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/JuiceFS_logo.png
  static/images/partner/sofastack-logo.png
Labels: approved, lgtm, size/S
