Repository kubesphere/website, pull requests merged in 2022-01, with the labels that each got.

#2251 fix: Update lesson menu styles on the lesson page
  assets/scss/learn-page.scss
  layouts/learn/single.html
  static/images/learn/actions-download.svg
  static/images/learn/actions-picture-active.svg
  static/images/learn/actions-picture-open.svg
  static/images/learn/actions-picture.svg
  static/images/learn/actions-ppt.svg
  static/images/learn/icon-setion-close.svg
  static/images/learn/icon-setion-open.svg
  static/images/learn/lesson-video-hover.svg
  static/images/learn/lesson-video-play.svg
  static/images/learn/lesson-video.svg
Labels: approved, lgtm, size/L

#2252 fix: Can't set background color for card title on conferences page
  assets/scss/conferences.scss
  assets/scss/content.scss
  content/zh/conferences/_index.md
  layouts/conferences/list.html
Labels: approved, lgtm, size/S

#2259 Update set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: approved, lgtm, size/XS

#2261 update the page of live
  content/zh/live/_index.md
  content/zh/live/openfunction0113-live.md
Labels: approved, lgtm, size/M

#2264 add new file of learn
  content/zh/learn/level_5/_index.md
  content/zh/learn/level_5/lesson_1/_index.md
  content/zh/learn/level_5/lesson_1/content.md
  content/zh/learn/level_5/lesson_1/video.md
  content/zh/learn/level_5/lesson_2/_index.md
  content/zh/learn/level_5/lesson_2/content.md
  content/zh/learn/level_5/lesson_2/video.md
  content/zh/learn/level_5/lesson_3/_index.md
  content/zh/learn/level_5/lesson_3/content.md
  content/zh/learn/level_5/lesson_3/video.md
  content/zh/learn/level_5/lesson_4/_index.md
  content/zh/learn/level_5/lesson_4/content.md
  content/zh/learn/level_5/lesson_4/video.md
  content/zh/learn/level_5/lesson_5/_index.md
  content/zh/learn/level_5/lesson_5/content.md
  content/zh/learn/level_5/lesson_5/video.md
  content/zh/learn/level_5/lesson_6/_index.md
  content/zh/learn/level_5/lesson_6/content.md
  content/zh/learn/level_5/lesson_6/video.md
  content/zh/learn/level_5/lesson_7/_index.md
  content/zh/learn/level_5/lesson_7/content.md
  content/zh/learn/level_5/lesson_7/video.md
  content/zh/learn/level_5/lesson_8/_index.md
  content/zh/learn/level_5/lesson_8/content.md
  content/zh/learn/level_5/lesson_8/video.md
Labels: approved, lgtm, size/L

#2223 Submit third level learning
  content/zh/learn/level_3/_index.md
  content/zh/learn/level_3/lesson_70/_index.md
  content/zh/learn/level_3/lesson_70/content.md
  content/zh/learn/level_3/lesson_70/video.md
  content/zh/learn/level_3/lesson_71/_index.md
  content/zh/learn/level_3/lesson_71/content.md
  content/zh/learn/level_3/lesson_71/video.md
  content/zh/learn/level_3/lesson_72/_index.md
  content/zh/learn/level_3/lesson_72/content.md
  content/zh/learn/level_3/lesson_72/video.md
  content/zh/learn/level_3/lesson_73/_index.md
  content/zh/learn/level_3/lesson_73/content.md
  content/zh/learn/level_3/lesson_73/video.md
  content/zh/learn/level_3/lesson_74/_index.md
  content/zh/learn/level_3/lesson_74/content.md
  content/zh/learn/level_3/lesson_74/video.md
  content/zh/learn/level_3/lesson_75/_index.md
  content/zh/learn/level_3/lesson_75/content.md
  content/zh/learn/level_3/lesson_75/video.md
  content/zh/learn/level_3/lesson_76/_index.md
  content/zh/learn/level_3/lesson_76/content.md
  content/zh/learn/level_3/lesson_76/video.md
Labels: approved, lgtm, size/L

#2221 docs-zh: add how to deploy chaos mesh on kubesphere
  content/zh/docs/application-store/built-in-apps/chaos-mesh-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-dashboard-networkchaos.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-experiment-scope.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-app.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-basic-info.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-config.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-deployed.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-deployments.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-nodeport.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/experiment-result.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/experiment-status.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/install-chaos-mesh.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/login-to-dashboard.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/web-show-app.png
Labels: approved, lgtm, size/M

#2268 add new learn file
  content/zh/learn/level_6/_index.md
  content/zh/learn/level_6/lesson_1/_index.md
  content/zh/learn/level_6/lesson_1/content.md
  content/zh/learn/level_6/lesson_1/video.md
  content/zh/learn/level_6/lesson_10/_index.md
  content/zh/learn/level_6/lesson_10/content.md
  content/zh/learn/level_6/lesson_10/video.md
  content/zh/learn/level_6/lesson_11/_index.md
  content/zh/learn/level_6/lesson_11/content.md
  content/zh/learn/level_6/lesson_11/video.md
  content/zh/learn/level_6/lesson_2/_index.md
  content/zh/learn/level_6/lesson_2/content.md
  content/zh/learn/level_6/lesson_2/video.md
  content/zh/learn/level_6/lesson_3/_index.md
  content/zh/learn/level_6/lesson_3/content.md
  content/zh/learn/level_6/lesson_3/video.md
  content/zh/learn/level_6/lesson_4/_index.md
  content/zh/learn/level_6/lesson_4/content.md
  content/zh/learn/level_6/lesson_4/video.md
  content/zh/learn/level_6/lesson_5/_index.md
  content/zh/learn/level_6/lesson_5/content.md
  content/zh/learn/level_6/lesson_5/video.md
  content/zh/learn/level_6/lesson_6/_index.md
  content/zh/learn/level_6/lesson_6/content.md
  content/zh/learn/level_6/lesson_6/video.md
  content/zh/learn/level_6/lesson_7/_index.md
  content/zh/learn/level_6/lesson_7/content.md
  content/zh/learn/level_6/lesson_7/video.md
  content/zh/learn/level_6/lesson_8/_index.md
  content/zh/learn/level_6/lesson_8/content.md
  content/zh/learn/level_6/lesson_8/video.md
  content/zh/learn/level_6/lesson_9/_index.md
  content/zh/learn/level_6/lesson_9/content.md
  content/zh/learn/level_6/lesson_9/video.md
Labels: approved, lgtm, size/L

#2253 update the page of conferences
  content/zh/conferences/_index.md
  content/zh/conferences/apps.md
  content/zh/conferences/openfunction.md
  content/zh/conferences/qunar.md
  content/zh/conferences/rbac.md
Labels: approved, lgtm, size/L

#2255 Cluster Gateway Document Translation
  content/en/docs/cluster-administration/cluster-settings/cluster-gateway.md
  content/zh/docs/cluster-administration/cluster-settings/cluster-gateway.md
Labels: approved, lgtm, size/M

#2272 add new learn file
  content/zh/learn/level_10/_index.md
  content/zh/learn/level_10/lesson_1/_index.md
  content/zh/learn/level_10/lesson_1/content.md
  content/zh/learn/level_10/lesson_1/video.md
  content/zh/learn/level_10/lesson_10/_index.md
  content/zh/learn/level_10/lesson_10/video.md
  content/zh/learn/level_10/lesson_2/_index.md
  content/zh/learn/level_10/lesson_2/content.md
  content/zh/learn/level_10/lesson_2/video.md
  content/zh/learn/level_10/lesson_3/_index.md
  content/zh/learn/level_10/lesson_3/content.md
  content/zh/learn/level_10/lesson_3/video.md
  content/zh/learn/level_10/lesson_4/_index.md
  content/zh/learn/level_10/lesson_4/content.md
  content/zh/learn/level_10/lesson_4/video.md
  content/zh/learn/level_10/lesson_5/_index.md
  content/zh/learn/level_10/lesson_5/content.md
  content/zh/learn/level_10/lesson_5/video.md
  content/zh/learn/level_10/lesson_6/_index.md
  content/zh/learn/level_10/lesson_6/content.md
  content/zh/learn/level_10/lesson_6/video.md
  content/zh/learn/level_10/lesson_7/_index.md
  content/zh/learn/level_10/lesson_7/content.md
  content/zh/learn/level_10/lesson_7/video.md
  content/zh/learn/level_10/lesson_8/_index.md
  content/zh/learn/level_10/lesson_8/content.md
  content/zh/learn/level_10/lesson_8/video.md
  content/zh/learn/level_10/lesson_9/_index.md
  content/zh/learn/level_10/lesson_9/video.md
Labels: approved, lgtm, size/L

#2271 feat: Support for expanding and collapsing course lists
  assets/scss/learn.scss
  layouts/learn/list.html
Labels: approved, lgtm, size/M

#2274 update the page of conferences
  content/zh/conferences/_index.md
  content/zh/conferences/event.md
  content/zh/conferences/metering.md
Labels: approved, lgtm, size/M

#2263 Add KubeKey Built-in HA Mode EN Doc
  content/en/docs/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
Labels: approved, lgtm, size/L

#2270 Update nodes.md
  content/zh/docs/cluster-administration/nodes.md
Labels: approved, lgtm, size/XS

#2275 update the page of live
  content/zh/live/_index.md
  content/zh/live/openfunction0113-live.md
  static/images/live/cloudnative-live-banner.png
Labels: approved, lgtm, size/S

#2277 add new file of learn
  content/zh/learn/level_7/_index.md
  content/zh/learn/level_7/lesson_1/_index.md
  content/zh/learn/level_7/lesson_1/content.md
  content/zh/learn/level_7/lesson_1/video.md
  content/zh/learn/level_7/lesson_10/_index.md
  content/zh/learn/level_7/lesson_10/content.md
  content/zh/learn/level_7/lesson_10/video.md
  content/zh/learn/level_7/lesson_11/_index.md
  content/zh/learn/level_7/lesson_11/content.md
  content/zh/learn/level_7/lesson_11/video.md
  content/zh/learn/level_7/lesson_12/_index.md
  content/zh/learn/level_7/lesson_12/content.md
  content/zh/learn/level_7/lesson_12/video.md
  content/zh/learn/level_7/lesson_13/_index.md
  content/zh/learn/level_7/lesson_13/content.md
  content/zh/learn/level_7/lesson_13/video.md
  content/zh/learn/level_7/lesson_14/_index.md
  content/zh/learn/level_7/lesson_14/content.md
  content/zh/learn/level_7/lesson_14/video.md
  content/zh/learn/level_7/lesson_15/_index.md
  content/zh/learn/level_7/lesson_15/content.md
  content/zh/learn/level_7/lesson_15/video.md
  content/zh/learn/level_7/lesson_2/_index.md
  content/zh/learn/level_7/lesson_2/content.md
  content/zh/learn/level_7/lesson_2/video.md
  content/zh/learn/level_7/lesson_3/_index.md
  content/zh/learn/level_7/lesson_3/content.md
  content/zh/learn/level_7/lesson_3/video.md
  content/zh/learn/level_7/lesson_4/_index.md
  content/zh/learn/level_7/lesson_4/content.md
  content/zh/learn/level_7/lesson_4/video.md
  content/zh/learn/level_7/lesson_5/_index.md
  content/zh/learn/level_7/lesson_5/content.md
  content/zh/learn/level_7/lesson_5/video.md
  content/zh/learn/level_7/lesson_6/_index.md
  content/zh/learn/level_7/lesson_6/content.md
  content/zh/learn/level_7/lesson_6/video.md
  content/zh/learn/level_7/lesson_7/_index.md
  content/zh/learn/level_7/lesson_7/content.md
  content/zh/learn/level_7/lesson_7/video.md
  content/zh/learn/level_7/lesson_8/_index.md
  content/zh/learn/level_7/lesson_8/content.md
  content/zh/learn/level_7/lesson_8/video.md
  content/zh/learn/level_7/lesson_9/_index.md
  content/zh/learn/level_7/lesson_9/content.md
  content/zh/learn/level_7/lesson_9/video.md
Labels: approved, lgtm, size/L

#2280 Added 2 artciles
  content/en/blogs/Part-1-Explaining-Container-Runtimes.md
  content/en/blogs/Part-2:-How-to-migrate-to-containerd-and-CRI-O-after-Docker-Deprecation-in-Kubernetes.md
  static/images/blogs/Part-1-Explaining-Container-Runtimes/1.png
  static/images/blogs/Part-1-Explaining-Container-Runtimes/5.png
  static/images/blogs/Part-1-Explaining-Container-Runtimes/6.png
  static/images/blogs/Part-1-Explaining-Container-Runtimes/7.png
  static/images/blogs/Part-1-Explaining-Container-Runtimes/8.png
  static/images/blogs/Part-2:-How-to-migrate-to-containerd-and-CRI-O-after-Docker-Deprecation-in-Kubernetes/2.png
Labels: approved, lgtm, size/L

#2279 chores: fix broken img links
  content/zh/docs/application-store/built-in-apps/chaos-mesh-app.md
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-architecture-v2.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-basic-info.png
  static/images/docs/zh-cn/appstore/built-in-apps/deploy-chaos-mesh/install-chaos-mesh.png
Labels: approved, lgtm, size/S

#2219 docs: add how to deploy chaos mesh on kubesphere
  content/en/docs/application-store/built-in-apps/deploy-chaos-mesh.md
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-dashboard-networkchaos.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-experiment-scope.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-app.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-architecture-v2.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-basic-info.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-config.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-deployed.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-kubesphere-banner.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/chaos-mesh-nodeport.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/experiment-result.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/install-chaos-mesh.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/login-to-dashboard.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/start-chaos-experiment.png
  static/images/docs/appstore/built-in-apps/deploy-chaos-mesh/web-show-app.png
Labels: approved, lgtm, size/M

#2282 update the page of learn
  content/zh/learn/_index.md
Labels: approved, lgtm, size/M

#2286 Update the page of learn
  config/_default/config.toml
  content/zh/learn/_index.md
  content/zh/learn/level_1/lesson_1/_index.md
  content/zh/learn/level_1/lesson_1/content.md
  content/zh/learn/level_1/lesson_1/video.md
Labels: approved, lgtm, size/M

#2249 Add EN OpenFunction Blog
  content/en/blogs/faas-openfunction.md
Labels: approved, lgtm, size/L, tide/merge-method-squash

#2290 Fix Some Issues in Documents
  content/en/docs/multicluster-management/unbind-cluster.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aliyun-ack.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
  content/zh/docs/multicluster-management/import-cloud-hosted-k8s/import-gke.md
  content/zh/docs/multicluster-management/unbind-cluster.md
Labels: approved, lgtm, size/S

#2294 modify the title
  content/en/blogs/transform-traditional-applications-into-microservices.md
Labels: approved, lgtm, size/XS

#2291 add kubesphere-2021-year-in-review.md
  content/en/news/_index.md
  content/en/news/kubesphere-2021-year-in-review.md
  static/images/news/community-report-2021/2021-community-recap-cover.png
  static/images/news/community-report-2021/2021-community-recap.png
  static/images/news/community-report-2021/contributing-enterprises-partners.png
  static/images/news/community-report-2021/integration-with-cloud.png
  static/images/news/community-report-2021/known-adopters.png
  static/images/news/community-report-2021/project-metrics.png
Labels: approved, lgtm, size/L

#2295 Fix Typo
  content/en/news/kubesphere-2021-year-in-review.md
Labels: approved, lgtm, size/XS

#2296 refine the annual report according the comments
  content/en/news/kubesphere-2021-year-in-review.md
Labels: approved, size/S
