Repository kubesphere/website, pull requests merged in 2023-04, with the labels that each got.

#2873 Fix: change kk version to 3.0.7
  KubeSphere Documentation Style Guide.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.3/installing-on-linux/introduction/vars.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.3/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.3/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.3/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.3/installing-on-linux/introduction/vars.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.3/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.3/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/release/release-v300.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/v3.3/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.3/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#2874 update the article
  content/zh/blogs/apache-log4j2-vulnerability-solution.md
Labels: approved, lgtm, size/XS

#2876 update the page of live
  content/zh/live/_index.md
  content/zh/live/cs4all-kubesphere.md
  content/zh/live/meetup-shenzhen-20230408.md
  content/zh/live/shenzhen0408-api.md
  content/zh/live/shenzhen0408-flomesh.md
  content/zh/live/shenzhen0408-gitops.md
  content/zh/live/shenzhen0408-jenkins.md
  content/zh/live/shenzhen0408-kubesphere.md
  static/images/live/cloud-native-20230408.png
  static/images/live/cloudnative-live-20230223.png
Labels: approved, lgtm, size/L

#2878 Fix: delete customize platform info
  content/en/docs/v3.3/cluster-administration/platform-settings/_index.md
  content/en/docs/v3.3/cluster-administration/platform-settings/customize-basic-information.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/_index.md
  content/zh/docs/v3.3/cluster-administration/platform-settings/customize-basic-information.md
Labels: approved, lgtm, size/M

#2879 update the page of live
  content/zh/live/_index.md
Labels: approved, lgtm, size/XS

#2880 fix: Update user group list page
  assets/scss/common.scss
  assets/scss/user-group.scss
  content/zh/user-group/_index.md
  content/zh/user-group/shenzhen.md
  layouts/user-group/list.html
  layouts/user-group/single.html
  static/images/user-group/list/cityCards/shenzhen.png
  static/images/user-group/shenzhen/logo.svg
Labels: approved, lgtm, size/XL

#2881 update the page of live
  content/zh/live/_index.md
  content/zh/live/chatgpt-k8s-0420-live.md
Labels: approved, lgtm, size/M

#2882 add new page of shenzhen usergroup
  content/zh/user-group/_index.md
  content/zh/user-group/shenzhen.md
  static/images/user-group/shenzhen/caiyaohui.png
  static/images/user-group/shenzhen/liuxifeng.jpeg
  static/images/user-group/shenzhen/wumiaoyong.jpg
  static/images/user-group/shenzhen/xupeng.jpeg
  static/images/user-group/shenzhen/xupengvx.jpeg
  static/images/user-group/shenzhen/zhengjianlin.jpeg
Labels: approved, lgtm, size/M

#2884 add new blog
  content/zh/blogs/best-practices-KubeSphere-assist-in-improving-the-efficiency-of-R&D.md
Labels: approved, lgtm, size/L

#2885 update the page of live
  content/zh/live/_index.md
  content/zh/live/chatgpt-k8s-0420-live.md
  static/images/live/cloud-native-20230408.png
  static/images/live/cloud-native-20230420.png
Labels: approved, lgtm, size/M

#2886 ospp-2023 replace ospp-2022
  config/_default/config.toml
Labels: approved, lgtm, size/XS
