Repository kubesphere/website, pull requests merged in 2023-05, with the labels that each got.

#2888 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/excelsecu.md
  static/images/case/logo-excelsecu.png
Labels: approved, lgtm, size/L

#2890 update jquery to 3.7.0
  layouts/partials/head.html
  static/js/jquery-3.6.4.min.js
  static/js/jquery-3.7.0.min.js
Labels: approved, lgtm, size/XS

#2891 Fix: fix desc in image list
  content/en/docs/v3.3/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/en/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.3/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/v3.3/installing-on-linux/introduction/air-gapped-installation.md
Labels: approved, lgtm, size/S

#2893 add one new blog
  content/zh/blogs/Building-Resilient-and-Scalable-Systems.md
Labels: approved, lgtm, size/L

#2894 add one new zh blog
  content/zh/blogs/nacos-on-kubesphere.md
Labels: approved, lgtm, size/XL

#2892 add one new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/logo-flomesh.png
Labels: approved, lgtm, size/S

#2897 Remove url patch in algolia
  layouts/partials/searchInput.html
Labels: approved, size/M

#2898 update the page of live
  content/zh/live/meetup-shenzhen-20230408.md
  content/zh/live/shenzhen0408-flomesh.md
Labels: approved, lgtm, size/XS

#2899 add one new zh blog
  content/zh/blogs/deploy-kubesphere-on-ubuntu22.04.md
Labels: approved, lgtm, size/XL

#2901 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-hangzhou-20230603.md
Labels: approved, lgtm, size/M

#2902 add one new zh blog
  content/zh/blogs/deploy-kubesphere-on-openEuler22.03.md
  content/zh/blogs/deploy-kubesphere-on-ubuntu22.04.md
Labels: approved, lgtm, size/XL
