Repository kubesphere/website, pull requests merged in 2023-03, with the labels that each got.

#2851 add a new case logo
  content/en/case/_index.md
  content/zh/case/_index.md
  static/images/case/logo-pigeon.png
Labels: approved, lgtm, size/XS

#2852 update hugo to 0.111.2
  netlify.toml
Labels: approved, lgtm, size/XS

#2857 update devops-user-guide
  content/en/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-jenkinsfile.md
Labels: approved, lgtm, size/XS

#2853 add one new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/databend-logo.svg
Labels: approved, lgtm, size/XS

#2859 add new blog
  content/zh/blogs/databend-on-kubesphere.md
Labels: approved, lgtm, size/L

#2849 docs: fix broken link
  content/en/docs/v3.3/project-user-guide/application/deploy-app-from-template.md
  content/tr/conferences/app-template.md
  content/zh/docs/v3.3/project-user-guide/application/deploy-app-from-template.md
Labels: approved, lgtm, size/S

#2816 Update all-in-one-on-linux.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/XS

#2860 fix: Make Chinese text in line
  assets/scss/common.scss
  layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#2863 add one new blog
  content/zh/blogs/t3-kubesphere-best-practice.md
Labels: approved, lgtm, size/M

#2862 update jquery
  layouts/partials/head.html
  static/js/jquery-3.6.3.min.js
  static/js/jquery-3.6.4.min.js
Labels: approved, lgtm, size/XS

#2865 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/wuxitv.md
  static/images/case/logo-wxtv.png
Labels: approved, lgtm, size/L

#2867 update hugo to 0.111.3
  netlify.toml
Labels: approved, lgtm, size/XS

#2864 Fix url typo
  content/en/blogs/serverless-way-for-kubernetes-log-alert.md
Labels: approved, lgtm, size/XS

#2872 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-shenzhen-20230408.md
Labels: approved, lgtm, size/M
