Repository kubesphere/website, pull requests merged in 2023-10, with the labels that each got.

#2988 update v3.4.0 offline images list
  content/en/docs/v3.4/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
  content/zh/docs/v3.4/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
Labels: approved, lgtm, size/L

#2992 add one en news
  content/en/news/kubesphere-ambassador-certificates-20230920.md
Labels: approved, lgtm, size/M

#2994 add one new case
  content/zh/_index.md
  content/zh/case/_index.md
  content/zh/case/alphaflow.md
Labels: approved, lgtm, size/L

#2995 add one zh news
  content/zh/news/kubesphere-ambassador-certificates-20230920.md
Labels: approved, lgtm, size/M

#2993 fix: Add redirects of learn and live page
  netlify.toml
Labels: approved, lgtm, size/S

#2999 fix the docs of v3.4
  content/en/docs/v3.4/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/en/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/en/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks.md
  content/en/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke.md
  content/en/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-huaweicloud-cce.md
  content/en/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-oke.md
  content/en/docs/v3.4/installing-on-kubernetes/introduction/prerequisites.md
  content/en/docs/v3.4/installing-on-linux/cluster-operation/add-edge-nodes.md
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.4/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.4/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.4/quick-start/minimal-kubesphere-on-k8s.md
  content/en/docs/v3.4/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/en/docs/v3.4/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.4/upgrade/overview.md
  content/en/docs/v3.4/upgrade/upgrade-with-ks-installer.md
  content/en/docs/v3.4/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.4/devops-user-guide/examples/create-multi-cluster-pipeline.md
  content/zh/docs/v3.4/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-do.md
  content/zh/docs/v3.4/installing-on-kubernetes/introduction/prerequisites.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.4/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.4/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.4/quick-start/minimal-kubesphere-on-k8s.md
  content/zh/docs/v3.4/upgrade/air-gapped-upgrade-with-ks-installer.md
  content/zh/docs/v3.4/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.4/upgrade/upgrade-with-ks-installer.md
  content/zh/docs/v3.4/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#3003 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-chengdu-20231104.md
Labels: approved, lgtm, size/M

#3005 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/hshc.md
  static/images/case/logo-hshc.png
Labels: approved, lgtm, size/L

#3006 Update overview.md
  content/zh/docs/v3.4/upgrade/overview.md
Labels: approved, lgtm, size/XS

#3002 fix: Add /en/learn and redirect to /zh/learn
  content/en/learn/_index.md
  layouts/learn/list.html
  netlify.toml
Labels: approved, lgtm, size/M

#2990 update hugo to 0.119.0
  netlify.toml
Labels: approved, lgtm, size/XS

#3007 add one new zh blog
  content/zh/blogs/deploy-kubesphere-v3.4.0-on-arm-openeuler.md
Labels: approved, lgtm, size/XL

#3008 fix the typo of docs
  content/zh/docs/v3.3/project-user-guide/storage/volumes.md
  content/zh/docs/v3.4/project-user-guide/storage/volumes.md
Labels: approved, lgtm, size/XS

#3010 add new conferences
  content/zh/conferences/_index.md
  content/zh/conferences/alerting-2023.md
  content/zh/conferences/openfunction-2023.md
Labels: approved, lgtm, size/M

#3009 fix: Update change the hegiht of the header background
  layouts/partials/header.html
Labels: approved, lgtm, size/XS
