Repository kubesphere/website, pull requests merged in 2023-08, with the labels that each got.

#2946 add one new zh blog
  content/zh/blogs/best-practice-kubesphere-a-manufacturing-company.md
Labels: approved, lgtm, size/M

#2947 add one new blog
  content/zh/blogs/expanding -kubernetes-v1.24 -worker-nodes-with-kubekey.md
Labels: approved, lgtm, size/XL

#2948 fix some blogs
  content/zh/blogs/kubesphere-etcd.md
  content/zh/blogs/kubesphere-k8s-cluster.md
  content/zh/blogs/mysql-on-k8s-statefulset-1.md
  content/zh/blogs/mysql-on-k8s-statefulset-2.md
  content/zh/blogs/rabbitmq-k8s.md
  content/zh/blogs/rocketmq-k8s.md
  content/zh/news/kubesphere-ambassador-certificates-20220727.md
Labels: approved, lgtm, size/S

#2949 update the page of live and user-group-shanghai
  content/zh/live/_index.md
  content/zh/live/meetup-shanghai-20230805.md
  content/zh/live/shanghai0805-aiops.md
  content/zh/live/shanghai0805-aws.md
  content/zh/live/shanghai0805-emqx.md
  content/zh/live/shanghai0805-milvus.md
  content/zh/live/shanghai0805-monitor.md
  content/zh/live/shanghai0805-openfunction.md
  content/zh/user-group/shanghai.md
  static/images/live/cloudnative-live-20230727.png
  static/images/live/cloudnative-live-20230805.png
Labels: approved, lgtm, size/L

#2938 update hugo to 0.117.0
  netlify.toml
Labels: approved, size/XS

#2950 update the page of user-group-shanghai
  content/zh/user-group/shanghai.md
  static/images/user-group/shanghai/mayongxing.jpg
Labels: approved, lgtm, size/XS

#2951 add one new zh blog
  content/zh/blogs/zookeeper-on-kubesphere.md
Labels: approved, lgtm, size/XXL

#2953 add one new zh blog
  content/zh/blogs/kubesphere-best-practices-in-smart-connected-vehicles.md
Labels: approved, lgtm, size/L

#2954 add one news and update the header
  content/zh/blogs/kubesphere-v3.3.0-offline-installation.md
  content/zh/news/kubecon-china-2023.md
  layouts/partials/header.html
Labels: approved, lgtm, size/M

#2956 update the page of user-group-hangzhou
  content/zh/news/kubesphere-user-group.md
  content/zh/user-group/hangzhou.md
  static/images/user-group/hangzhou/zhuyaguang.jpg
Labels: approved, lgtm, size/M

#2955 add one new blog
  content/zh/blogs/kubesphere-based-architecture-design-and-cost-analysis.md
Labels: approved, lgtm, size/L

#2957 add one new case logo
  content/en/case/_index.md
  content/zh/case/_index.md
  static/images/case/logo-alphaflow.png
Labels: approved, lgtm, size/XS

#2959 update the home page
  content/zh/_index.md
Labels: approved, lgtm, size/XS

#2960 update one doc
  content/zh/docs/v3.3/multicluster-management/enable-multicluster/direct-connection.md
Labels: approved, lgtm, size/XS

#2964 Update import-aws-eks.md
  content/zh/docs/v3.3/multicluster-management/import-cloud-hosted-k8s/import-aws-eks.md
Labels: approved, lgtm, size/S

#2966 fix the link and update the header of website
  content/zh/docs/v3.4/_index.md
  layouts/partials/header.html
  static/images/docs/v3.x/qingcloud.svg
Labels: approved, lgtm, size/S
