Repository kubesphere/website, pull requests merged in 2023-07, with the labels that each got.

#2927 update hugo to 0.115.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2930 add one en news
  content/en/news/Explore-CNCF-KCD-Turkey-with-KubeSphere-Turkey.md
Labels: approved, lgtm, size/M

#2929 update hugo to 0.115.2
  netlify.toml
Labels: approved, lgtm, size/XS

#2935 update the link of ospp-2023
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#2934 update hugo to 0.115.3
  netlify.toml
Labels: approved, lgtm, size/XS

#2936 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/eastcom.md
  static/images/case/logo-eastcom.png
Labels: approved, lgtm, size/L

#2940 update the page of live
  content/zh/live/_index.md
  content/zh/live/cloudnative0727-live.md
  content/zh/live/meetup-shanghai-20230805.md
Labels: approved, lgtm, size/M

#2941 replace the jinshuju from with huiju
  data/zh/footer.yaml
Labels: approved, lgtm, size/XS

#2944 add one news of release note
  content/zh/news/kubesphere-3.4.0-ga-announcement.md
Labels: approved, lgtm, size/L

#2945 update the page of live
  content/zh/live/_index.md
  content/zh/live/cloudnative0727-live.md
  static/images/live/cloudnative-live-20230603.png
  static/images/live/cloudnative-live-20230727.png
Labels: approved, lgtm, size/M
