Repository kubesphere/website, pull requests merged in 2023-12, with the labels that each got.

#3030 update the page of conferences
  content/zh/conferences/alerting-2023.md
  content/zh/conferences/fluentbit.md
  content/zh/conferences/openfunction-2023.md
Labels: approved, lgtm, size/L

#3031 add one new zh blog
  content/zh/blogs/kubekey-upgrades-kubesphere-and-k8s-patch-versions.md
Labels: approved, lgtm, size/XL

#3032 update the page of live
  content/zh/live/_index.md
  content/zh/live/databend1207-live.md
Labels: approved, lgtm, size/M

#3033 add one new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/Cardtr-Logo.png
  static/images/partner/partner10.jpg
Labels: approved, lgtm, size/S

#3034 update the page of live
  content/zh/live/_index.md
  content/zh/live/databend1207-live.md
  content/zh/live/meetup-suzhou-20231223.md
  layouts/partials/header.html
Labels: approved, lgtm, size/S

#3035 add two partners
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/DigitalOcean-logo.svg
  static/images/partner/Hostinger-logo-primary.png
Labels: approved, lgtm, size/L

#3037 add a new zh blog
  content/zh/blogs/deploying-kubesphere-and-k8s-offline-with-kubekey.md
Labels: approved, lgtm, size/XXL

#3038 update the page of live
  content/zh/live/meetup-suzhou-20231223.md
Labels: approved, lgtm, size/L

#3036 add one new zh blog
  content/zh/blogs/upgrading-k8s-minor-versions-with-kubekey.md
Labels: approved, lgtm, size/XL

#3039 add new docs of install-and-use-kubesphere-on-hostinger-vps.md
  content/en/docs/v3.4/installing-on-linux/public-cloud/install-and-use-kubesphere-on-hostinger-vps.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-and-use-kubesphere-on-hostinger-vps.md
Labels: approved, lgtm, size/M

#3043 update hugo to 0.121.1
  netlify.toml
Labels: approved, lgtm, size/XS

#3046 Update horizontal-pod-autoscaling.md
  content/zh/docs/v3.4/project-user-guide/application-workloads/horizontal-pod-autoscaling.md
Labels: approved, lgtm, size/XS

#3047 add new zh blog
  content/zh/blogs/best-practices-of-kubesphere-in-zhidian.md
Labels: approved, lgtm, size/L

#3048 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-suzhou-20231223.md
  content/zh/live/suzhou1223-ai.md
  content/zh/live/suzhou1223-devops.md
  content/zh/live/suzhou1223-kubesphere.md
  content/zh/live/suzhou1223-minjie.md
  content/zh/live/suzhou1223-os.md
  content/zh/live/suzhou1223-skywalking.md
  static/images/live/cloudnative-live-20231125.png
  static/images/live/cloudnative-live-20231223.png
Labels: approved, lgtm, size/L
