Repository kubesphere/website, pull requests merged in 2023-01, with the labels that each got.

#2798 📝 Add new blog
  content/zh/blogs/kubesphere-curve.md
Labels: approved, lgtm, size/L

#2797 add new blog
  content/zh/blogs/kubesphere-openldap.md
Labels: approved, lgtm, size/L

#2799 update the page of lives
  content/zh/live/_index.md
  content/zh/live/gitops0111-live.md
Labels: approved, lgtm, size/M

#2800 add a news item
  content/en/news/kubesphere-ambassador-certificates-20220727.md
  content/en/news/kubesphere-contributor-certificates-20220721.md
  content/zh/news/KubeSphere-Turkey-and-Huawei-Partnership.md
  content/zh/news/kubesphere-2022-year-in-review.md
Labels: approved, lgtm, size/L

#2801 add new blog
  content/zh/blogs/kubesphere-integrate-kubeedge.md
Labels: approved, lgtm, size/XL

#2803 update the article of kubesphere-2022-year-in-review
  content/zh/news/kubesphere-2022-year-in-review.md
Labels: approved, lgtm, size/XS

#2805 update kubesphere-year-in-year
  content/en/news/kubesphere-2022-year-in-review.md
Labels: approved, lgtm, size/L

#2806 update the page of live
  content/zh/live/_index.md
  content/zh/live/gitops0111-live.md
  content/zh/live/go1104-live.md
  static/images/live/cloudnative-live-20221229.png
  static/images/live/cloudnative-live-20230111.png
Labels: approved, lgtm, size/M

#2807 fix 404
  content/en/docs/v3.3/installing-on-linux/on-premises/installing-kubesphere-on-minikube.md
  content/en/docs/v3.3/introduction/features.md
  content/zh/docs/v3.3/application-store/external-apps/deploy-tidb.md
  content/zh/docs/v3.3/introduction/features.md
Labels: approved, lgtm, size/XS

#2808 fix broken link in kubesphere-310-on-aws-quick-start
  content/en/news/kubesphere-310-on-aws-quick-start.md
Labels: approved, lgtm, size/XS

#2809 fix the broken links
  content/en/news/kubesphere-10k-stars.md
  content/en/news/kubesphere-ambassador-certificates-20220727.md
  content/en/news/kubesphere-contributor-certificates-20220721.md
  content/zh/conferences/qunar.md
  content/zh/news/kubekey-v2.0.0-release.md
  content/zh/news/kubekey-v2.1.0-release.md
  content/zh/news/kubesphere-10k-stars.md
  content/zh/news/kubesphere-2021-year-in-review.md
  content/zh/news/kubesphere-3.0.0-ga-announcement.md
  content/zh/news/kubesphere-3.2.0-ga-announcement.md
  content/zh/news/kubesphere-3.3.0-ga-announcement.md
  content/zh/news/kubesphere-3.3.0-rc.md
  content/zh/news/kubesphere-ambassador-certificates-20220727.md
  content/zh/news/kubesphere-ambassador-certificates.md
  content/zh/news/kubesphere-contributor-certificates-20220721.md
  content/zh/news/kubesphere-contributor-certificates.md
  content/zh/news/kubesphere-member-certificates.md
  content/zh/news/kubesphere-partner.md
  content/zh/news/kubesphere-speaker-certificates-20220715.md
  content/zh/news/kubesphere-speaker-certificates.md
  content/zh/news/kubesphere-user-group.md
  content/zh/news/ospp-2022-selected-students.md
Labels: approved, lgtm, size/L

#2812 update use-gitops-for-continuous-deployment zh and en
  content/en/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
Labels: approved, lgtm, size/XL

#2813 add note in use-gitops-for-continous-deployment
  content/en/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/continuous-deployments/use-gitops-for-continous-deployment.md
Labels: approved, lgtm, size/S

#2815 fix: The '/zh/' url problem
  layouts/_default/baseof.html
Labels: approved, lgtm, size/XS

#2814 update hugo to 0.110.0
  netlify.toml
Labels: approved, lgtm, size/XS

#2819 add description of image-pull-secrets
  content/en/docs/v3.3/project-user-guide/configuration/image-registry.md
  content/zh/docs/v3.3/project-user-guide/configuration/image-registry.md
  static/images/docs/v3.3/project-user-guide/configurations/image-pull-secrets.png
Labels: approved, lgtm, size/XS

#2818 delete one logo
  content/en/_index.md
  content/en/case/_index.md
  content/zh/_index.md
  content/zh/case/_index.md
  static/images/case/section6-supaur.png
Labels: approved, lgtm, size/XS
