Repository kubesphere/website, pull requests merged in 2023-11, with the labels that each got.

#3011 add one new zh blog
  content/en/blogs/openelb-joins-cncf-sandbox-project.md
  content/en/news/KubeSphere-Turkey-and-Huawei-Partnership.md
  content/zh/blogs/deploy-kubesphere-v3.4.0-on-arm-openeuler-2.md
  content/zh/news/KubeSphere-Turkey-and-Huawei-Partnership.md
  content/zh/news/kubesphere-partner.md
  content/zh/news/openelb-joins-cncf-sandbox-project.md
Labels: approved, lgtm, size/XXL

#3013 feat: Add certification zh menu
  assets/scss/header.scss
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#3015 update the news of kubesphere-ambassador-certificates-20230920
  content/en/news/kubesphere-ambassador-certificates-20230920.md
  content/zh/news/kubesphere-ambassador-certificates-20230920.md
Labels: approved, lgtm, size/S

#3016 update the page of live
  content/zh/live/_index.md
  content/zh/live/chengdu1104-dlrover.md
  content/zh/live/chengdu1104-gateway.md
  content/zh/live/chengdu1104-kubeblocks-rsm.md
  content/zh/live/chengdu1104-kubeblocks.md
  content/zh/live/chengdu1104-kubesphere-v4.0.md
  content/zh/live/chengdu1104-sofaboot.md
  content/zh/live/meetup-chengdu-20231104.md
  content/zh/live/meetup-guangzhou-20231125.md
  content/zh/user-group/chengdu.md
  static/images/live/cloudnative-live-20230805.png
  static/images/live/cloudnative-live-20231104.png
Labels: approved, lgtm, size/XL

#3017 fix some typo
  content/zh/live/_index.md
  content/zh/live/meetup-guangzhou-20231125.md
Labels: approved, lgtm, size/S

#3014 update hugo to 0.120.3
  netlify.toml
Labels: approved, lgtm, size/XS

#3018 release: update kk v3.0.13 in ks v.3.4
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/en/docs/v3.4/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/en/docs/v3.4/installing-on-linux/introduction/air-gapped-installation.md
  content/en/docs/v3.4/installing-on-linux/introduction/kubekey.md
  content/en/docs/v3.4/installing-on-linux/introduction/multioverview.md
  content/en/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/en/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/en/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/en/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/en/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/en/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/en/docs/v3.4/quick-start/all-in-one-on-linux.md
  content/en/docs/v3.4/upgrade/air-gapped-upgrade-with-kubekey.md
  content/en/docs/v3.4/upgrade/upgrade-with-kubekey.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/ha-configuration.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/internal-ha-configuration.md
  content/zh/docs/v3.4/installing-on-linux/high-availability-configurations/set-up-ha-cluster-using-keepalived-haproxy.md
  content/zh/docs/v3.4/installing-on-linux/introduction/air-gapped-installation.md
  content/zh/docs/v3.4/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.4/installing-on-linux/introduction/multioverview.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-and-k3s.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-vmware-vsphere.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-glusterfs.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-nfs-client.md
  content/zh/docs/v3.4/installing-on-linux/persistent-storage-configurations/install-qingcloud-csi.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-ali-ecs.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-huaweicloud-ecs.md
  content/zh/docs/v3.4/installing-on-linux/public-cloud/install-kubesphere-on-qingcloud-vms.md
  content/zh/docs/v3.4/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.4/upgrade/air-gapped-upgrade-with-kubekey.md
  content/zh/docs/v3.4/upgrade/upgrade-with-kubekey.md
Labels: approved, lgtm, size/L

#3019 add the content of alerting-2023.md
  content/zh/conferences/alerting-2023.md
Labels: approved, lgtm, size/L

#3021 add one news of v3.4.1 ga
  content/zh/news/kubesphere-3.4.1-ga-announcement.md
Labels: approved, lgtm, size/M

#3023 update the page of live
  content/zh/live/meetup-guangzhou-20231125.md
Labels: approved, lgtm, size/S

#2996 use-step-template
  content/zh/docs/v3.4/devops-user-guide/how-to-use/pipelines/use-pipeline-step-template.md
  static/images/docs/v3.x/zh-cn/devops-user-guide/use-devops/use-step-templates/create-pipeline-1.png
  static/images/docs/v3.x/zh-cn/devops-user-guide/use-devops/use-step-templates/create-pipeline-2.png
  static/images/docs/v3.x/zh-cn/devops-user-guide/use-devops/use-step-templates/create-step-1.png
  static/images/docs/v3.x/zh-cn/devops-user-guide/use-devops/use-step-templates/use-step-1.png
Labels: approved, lgtm, size/L

#2975 docs: add OpenSearch as receiver
  content/zh/docs/v3.4/cluster-administration/cluster-settings/log-collections/add-opensearch-as-receiver.md
  static/images/docs/v3.x/zh-cn/cluster-administration/cluster-settings/log-collections/cc-ks-installer.png
  static/images/docs/v3.x/zh-cn/cluster-administration/cluster-settings/log-collections/cc-search.png
  static/images/docs/v3.x/zh-cn/cluster-administration/cluster-settings/log-collections/logging-dashboard.png
  static/images/docs/v3.x/zh-cn/cluster-administration/cluster-settings/log-collections/logging-filter.png
  static/images/docs/v3.x/zh-cn/cluster-administration/cluster-settings/log-collections/logging-icon.png
Labels: approved, lgtm, size/L

#3024 add one new zh blog
  content/zh/blogs/deploy-kubesphere-on-Debian12.md
  content/zh/blogs/deploy-kubesphere-on-arm-kylin-v10.md
  content/zh/blogs/deploy-kubesphere-on-openEuler22.03.md
  content/zh/blogs/deploy-kubesphere-on-ubuntu22.04.md
Labels: approved, lgtm, size/XXL

#2981 Create logs-dashboard.md
  content/zh/docs/v3.4/cluster-administration/logs-dashboard.md
  static/images/docs/v3.x/logs-ds1.png
  static/images/docs/v3.x/logs-ds2.png
  static/images/docs/v3.x/logs-ds3.png
Labels: approved, lgtm, size/L

#3025 add one zh news
  content/zh/news/ospp-2023-summary.md
Labels: approved, lgtm, size/M

#3026 add 3.4.1 release notes
  content/en/docs/v3.4/release/release-v340.md
  content/en/docs/v3.4/release/release-v341.md
  content/zh/docs/v3.4/release/release-v340.md
  content/zh/docs/v3.4/release/release-v341.md
Labels: approved, lgtm, size/L

#3027 add one en news
  content/en/news/kubesphere-3.0.0-ga-announcement.md
  content/en/news/kubesphere-3.1.0-ga-announcement.md
  content/en/news/kubesphere-3.2.0-ga-announcement.md
  content/en/news/kubesphere-3.3.0-ga-announcement.md
  content/en/news/kubesphere-3.4.1-ga-announcement.md
  static/images/blogs/en/release-announcement3.2.0/kubesphere-v3.2.0-GA-cover.png
Labels: approved, lgtm, size/M

#2976 docs: update alerting message
  content/zh/docs/v3.4/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/add-alert-policy-group-info.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/add-policy-rule.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-policy-group-list.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-policy-info.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/alert-policy-list.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/policy-group-operator.png
  static/images/docs/v3.x/cluster-administration/cluster-wide-alerting-and-notification/alerting-policies-node-level/policy-template.png
Labels: approved, lgtm, size/L
