Repository kubesphere/website, pull requests merged in 2023-02, with the labels that each got.

#2820 update byop
  content/en/docs/v3.3/faq/observability/byop.md
Labels: lgtm, size/M

#2821 update byop cn
  content/zh/docs/v3.3/faq/observability/byop.md
Labels: size/M

#2822 update Google Analytics ID
  layouts/partials/head.html
Labels: approved, lgtm, size/XS

#2826 3.3.2 release notes
  content/en/docs/v3.3/release/release-v332.md
  content/zh/docs/v3.3/release/release-v332.md
Labels: approved, lgtm, size/L

#2827 fix the link of video
  data/en/video.json
Labels: approved, lgtm, size/XS

#2828 update the page of user-group
  content/zh/user-group/chengdu.md
  content/zh/user-group/guangzhou.md
  content/zh/user-group/hangzhou.md
  content/zh/user-group/shanghai.md
Labels: approved, lgtm, size/M

#2829 add news and update the header
  content/zh/news/kubesphere-3.3.2-ga-announcement.md
  layouts/partials/header.html
Labels: approved, lgtm, size/M

#2831 Combined Chinese and English sites
  config/_default/config.toml
  config/upstream-zh/config.toml
  config/upstream/config.toml
  layouts/partials/head.html
  nginx.conf
Labels: approved, lgtm, size/M

#2832 Update baidu analytics id
  config/_default/config.toml
Labels: approved, size/XS

#2830 add one blog
  content/zh/blogs/kubesphere-jenkins-log4j2.md
Labels: approved, lgtm, size/XL

#2833 update the page of live
  content/zh/live/_index.md
  content/zh/live/csi0216-live.md
Labels: approved, lgtm, size/M

#2835 add new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/keyenlinx.md
  content/zh/case/xdf.md
  static/images/case/logo-keyenlinx.png
Labels: approved, lgtm, size/L

#2837 fix display issues
  content/en/docs/v3.3/quick-start/all-in-one-on-linux.md
  content/zh/docs/v3.3/quick-start/all-in-one-on-linux.md
Labels: approved, lgtm, size/XS

#2836 update current year
  layouts/docs/second.html
  layouts/docs/single.html
  layouts/partials/footer.html
Labels: approved, lgtm, size/XS

#2839 update the page of live
  content/zh/live/_index.md
  content/zh/live/csi0216-live.md
  content/zh/live/ebpf0223-live.md
  static/images/live/cloudnative-live-20230111.png
  static/images/live/cloudnative-live-20230216.png
Labels: approved, lgtm, size/M

#2845 fix: Support markdown formate content
  assets/scss/case-detail.scss
  layouts/case/single.html
Labels: approved, lgtm, size/S

#2844 add a news
  content/zh/news/fluent-operator-v2.0-announcement.md
Labels: approved, lgtm, size/M

#2841 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/yiheda.md
  static/images/case/logo-yiheda.png
Labels: approved, lgtm, size/L

#2843 add one new blog
  content/zh/blogs/kubesphere-ssl-tls.md
Labels: approved, lgtm, size/XL

#2846 update the page of live
  content/zh/live/_index.md
  content/zh/live/ebpf0223-live.md
  static/images/live/cloudnative-live-20230216.png
  static/images/live/cloudnative-live-20230223.png
Labels: approved, lgtm, size/M

#2847 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/bobinfo.md
  static/images/case/logo-hsh.png
Labels: approved, lgtm, size/L

#2825 Update install-kubesphere-on-ack.md
  content/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-ack.md
Labels: approved, lgtm, size/S

#2848 add one new blog
  content/zh/blogs/kubesphere-jenkins-log4j2.md
  content/zh/blogs/kubesphere-jenkins.md
Labels: approved, lgtm, size/L
