Repository kubesphere/website, pull requests merged in 2023-06, with the labels that each got.

#2904 update hugo to 0.112.5
  netlify.toml
Labels: approved, lgtm, size/XS

#2907 update hugo to 0.112.7
  netlify.toml
Labels: approved, lgtm, size/XS

#2909 Update: update the links
  static/json/kubesphere-3.1.json
  static/json/kubesphere.json
Labels: approved, lgtm, size/M

#2910 update the page of live
  content/zh/live/_index.md
  content/zh/live/hangzhou0603-curve.md
  content/zh/live/hangzhou0603-flomesh.md
  content/zh/live/hangzhou0603-gitlab.md
  content/zh/live/hangzhou0603-kubesphere.md
  content/zh/live/meetup-hangzhou-20230603.md
  static/images/live/cloud-native-20230420.png
  static/images/live/cloudnative-live-20230603.png
Labels: approved, lgtm, size/L

#2913 update the page of live and user-group-hangzhou
  content/zh/live/_index.md
  content/zh/user-group/hangzhou.md
Labels: approved, lgtm, size/XS

#2914 fix some typo
  content/zh/blogs/deploy-kubesphere-on-openEuler22.03.md
  content/zh/blogs/deploy-kubesphere-on-ubuntu22.04.md
  content/zh/blogs/kubesphere-jenkins-log4j2.md
  content/zh/blogs/kubesphere-ssl-tls.md
  content/zh/blogs/kubesphere-v3.3.0-offline-installation.md
  content/zh/blogs/nacos-on-kubesphere.md
  content/zh/live/changsha0312-microservice.md
  content/zh/live/meetup-changsha-20220312.md
Labels: approved, lgtm, size/S

#2915 fix: Remove 'Proxima Nova' font file
  assets/scss/common.scss
  assets/scss/doc.scss
  assets/scss/variables.scss
  static/fonts/ProximaNova/ProximaNova-Bold.ttf
  static/fonts/ProximaNova/ProximaNova-Bold.woff
  static/fonts/ProximaNova/ProximaNova-Bold.woff2
  static/fonts/ProximaNova/ProximaNova-Light.ttf
  static/fonts/ProximaNova/ProximaNova-Light.woff
  static/fonts/ProximaNova/ProximaNova-Light.woff2
  static/fonts/ProximaNova/ProximaNova-Regular.ttf
  static/fonts/ProximaNova/ProximaNova-Regular.woff
  static/fonts/ProximaNova/ProximaNova-Regular.woff2
  static/fonts/ProximaNova/ProximaNova-Regular_1.ttf
  static/fonts/ProximaNova/ProximaNova-Regular_1.woff
  static/fonts/ProximaNova/ProximaNova-Regular_1.woff2
  static/fonts/ProximaNova/ProximaNova-Semibold.ttf
  static/fonts/ProximaNova/ProximaNova-Semibold.woff
  static/fonts/ProximaNova/ProximaNova-Semibold.woff2
  static/fonts/ProximaNova/ProximaNova-SemiboldIt.ttf
  static/fonts/ProximaNova/ProximaNova-SemiboldIt.woff
  static/fonts/ProximaNova/ProximaNova-SemiboldIt.woff2
  static/fonts/ProximaNova/stylesheet.css
Labels: approved, lgtm, size/M

#2916 update go-get.js
  .netlify/edge-functions/go-get.js
Labels: size/XS

#2917 update go-get.js
  .netlify/edge-functions/go-get.js
Labels: size/XS

#2919 Update: update ks pass
  i18n/en.yaml
  i18n/zh.yaml
Labels: approved, lgtm, size/XS

#2918 add new zh blog
  content/zh/blogs/deploy-kubesphere-on-Debian12.md
Labels: approved, lgtm, size/XL

#2921 update hugo to 0.114.1
  netlify.toml
Labels: approved, lgtm, size/XS

#2923 add one news
  content/zh/news/ospp-2023-selected-students.md
Labels: approved, lgtm, size/M

#2924 fix: fix s2i
  content/en/docs/v3.3/project-user-guide/image-builder/s2i-templates.md
  content/zh/docs/v3.3/project-user-guide/image-builder/s2i-templates.md
Labels: approved, lgtm, size/XS

#2925 add one new zh blog
  content/zh/blogs/kubesphere-gitlab-secure.md
Labels: approved, lgtm, size/L
