Repository kubesphere/website, pull requests merged in 2024-09, with the labels that each got.

#3165 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#3166 add one news
  content/en/news/hiring-kubesphere-dev-advocate.md
Labels: approved, lgtm, size/M

#3168 update the header of website
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#3169 Update appendix.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/05-appendix.adoc
Labels: size/XS

#3170 【doc】add improvement plan
  content/zh/docs/v4.1/24-faq/01-info-collection.adoc
  content/zh/docs/v4.1/24-faq/_index.adoc
  content/zh/docs/v4.1/25-reference/_index.adoc
Labels: lgtm, size/M

#3173 Update appendix.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/05-appendix.adoc
Labels: size/S

#3174 Update appendix.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/05-appendix.adoc
Labels: size/XS

#3176 fix doc links in homepage
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  layouts/partials/downloadButton.html
Labels: approved, lgtm, size/S

#3178 update the conferences
  config/_default/config.toml
  content/zh/conferences/thanos-2024.md
Labels: approved, lgtm, size/L

#3179 update the link of downloadbutton
  layouts/partials/downloadButton.html
Labels: approved, lgtm, size/XS

#3177 Update 01-install-kubesphere.adoc
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
Labels: size/S

#3183 Update 02-install-kubernetes-and-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
Labels: approved, lgtm

#3184 【doc】 add imageRegistry settings and helm install
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
Labels: approved, lgtm, size/M

#3185 Update release-v412.md
  content/zh/docs/v4.1/20-release-notes/release-v412.md
Labels: approved, lgtm, size/XS
