Repository kubesphere/website, pull requests merged in 2024-11, with the labels that each got.

#3204 fix: try to fix KubeSphere 4.1 docs display bugs
  assets/scss/common.scss
  assets/scss/markdown.scss
  content/en/docs/v4.1/_index.adoc
  content/zh/docs/v4.1/_index.adoc
  layouts/docs/list.html
  layouts/docs/second.html
  layouts/docs/single.html
  layouts/partials/findFirstInNextSection.html
  layouts/partials/findLastInPreSection.html
  layouts/partials/page_navigation.html
  layouts/partials/pagination.html
  layouts/partials/section.html
  layouts/partials/section_item.html
Labels: approved, lgtm, size/L

#3206 fix the link of docs
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/04-offline-installation.adoc
Labels: approved, lgtm, size/XS

#3210 add one new blog
  content/zh/blogs/kubesphere-v4-appstore-configuration-guide.md
Labels: approved, lgtm, size/L

#3212 add one new zh blog
  content/zh/blogs/kubesphere-v4-extension-guide.md
  content/zh/blogs/kubesphere-v4-install-guide.md
Labels: approved, lgtm, size/L

#3213 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-chengdu-20241123.md
Labels: approved, lgtm, size/M

#3211 update install guide
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
Labels: approved, lgtm, size/M

#3216 add one new zh blog
  content/zh/blogs/gitops-argocd.md
  content/zh/blogs/kubesphere-4.1.2-deployment-and-extension-installation.md
Labels: approved, lgtm, size/XL

#3219 update some meetup information
  content/zh/live/_index.md
  content/zh/live/chengdu1123-higress.md
  content/zh/live/chengdu1123-iomesh.md
  content/zh/live/chengdu1123-kubesphere1.md
  content/zh/live/chengdu1123-kubesphere2.md
  content/zh/live/chengdu1123-spring.md
  content/zh/live/meetup-chengdu-20241123.md
  content/zh/live/meetup-guangzhou-20241228.md
  data/zh/video.json
  static/images/live/cloudnative-live-20240720.png
  static/images/live/cloudnative-live-20241123.png
Labels: approved, lgtm, size/L
