Repository kubesphere/website, pull requests merged in 2024-12, with the labels that each got.

#3220 ospp2024 update
  content/zh/news/ospp-2024-summary.md
Labels: approved, lgtm, size/M

#3221 Add topiam config oidc link
  content/zh/docs/v4.1/04-platform-management/03-platform-settings/03-external-authentication/01-set-up-external-authentication.adoc
Labels: approved, lgtm, size/XS

#3218 【documentation】 更新存储系统相关文档
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/07-configure-opensource-storage.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/_index.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/07-configure-opensource-storage.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/04-configure-external-persistent-storage/_index.adoc
Labels: approved, lgtm, size/M

#3223 【documentation】Update docs
  content/en/docs/_custom-en/clusterManagement/persistentVolumeClaims/persistentVolumeClaims-oper-expandAPersistentVolume.adoc
  content/en/docs/_custom-en/platformManagement/multiclusterManagement/clusters/clusters-oper-addClusterBasicInfo.adoc
  content/en/docs/_custom-en/workspaceManagement/toolBox/toolBox-oper-viewKubeconfig.adoc
  content/en/docs/v4.1/01-intro/02-architecture.adoc
  content/en/docs/v4.1/02-quickstart/03-control-user-permissions.adoc
  content/en/docs/v4.1/02-quickstart/05-deploy-wordpress.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/04-offline-installation.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/05-appendix.adoc
  content/en/docs/v4.1/04-platform-management/03-platform-settings/03-external-authentication/01-set-up-external-authentication.adoc
  content/en/docs/v4.1/06-extension-user-guide/01-install-components.adoc
  content/en/docs/v4.1/06-extension-user-guide/03-manage-components/01-set-configurations.adoc
  content/en/docs/v4.1/07-cluster-management/04-projects/01-create-a-project.adoc
  content/en/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/01-add-a-member-cluster/_index.adoc
  content/en/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/05-edit-cluster-configuration.adoc
  content/en/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/07-update-kubeconfig.adoc
  content/en/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/09-remove-a-member-cluster.adoc
  content/en/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/11-add-a-removed-member-cluster.adoc
  content/en/docs/v4.1/08-workspace-management/02-workspaces/02-view-a-workspace-list.adoc
  content/en/docs/v4.1/08-workspace-management/04-projects/08-unbind-a-project-from-a-workspace.adoc
  content/en/docs/v4.1/10-toolbox/01-use-kubectl-tool.adoc
  content/en/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/01-create-a-pipeline-using-graphical-editing-panel.adoc
  content/en/docs/v4.1/11-use-extensions/02-app-store/03-app-store-management/01-apps/06-publish-an-app-template.adoc
  content/en/docs/v4.1/11-use-extensions/03-service-mesh/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/01-vector/01-intro.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/01-vector/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/02-logging/06-log-receivers/03-manage-log-receivers/04-edit-log-receiver-settings.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/06-alerting/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/16-grafana/01-built-in-dashboards.adoc
  content/en/docs/v4.1/11-use-extensions/11-network/02-pod-ip-pools/07-edit-yaml-for-a-pod-ip-pool.adoc
  content/en/docs/v4.1/11-use-extensions/12-gateway/03-cluster-gateway/01-enable-a-cluster-gateway.adoc
  content/zh/docs/_custom/clusterManagement/persistentVolumeClaims/persistentVolumeClaims-oper-expandAPersistentVolume.adoc
  content/zh/docs/v4.1/01-intro/02-architecture.adoc
  content/zh/docs/v4.1/02-quickstart/05-deploy-wordpress.adoc
  content/zh/docs/v4.1/04-platform-management/03-platform-settings/03-external-authentication/01-set-up-external-authentication.adoc
  content/zh/docs/v4.1/06-extension-user-guide/03-manage-components/01-set-configurations.adoc
  content/zh/docs/v4.1/06-extension-user-guide/_index.adoc
  content/zh/docs/v4.1/07-cluster-management/04-projects/01-create-a-project.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/01-add-a-member-cluster/_index.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/05-edit-cluster-configuration.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/07-update-kubeconfig.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/09-remove-a-member-cluster.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/11-add-a-removed-member-cluster.adoc
  content/zh/docs/v4.1/08-workspace-management/02-workspaces/02-view-a-workspace-list.adoc
  content/zh/docs/v4.1/08-workspace-management/04-projects/08-unbind-a-project-from-a-workspace.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/01-vector/01-intro.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/01-vector/_index.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/16-grafana/01-built-in-dashboards.adoc
  static/images/ks-qkcp/zh/v4.1.2/grafana/node-dashboard.png
Labels: approved, lgtm, size/XL

#3224 add kubedesign and extension links
  config/_default/config.toml
Labels: approved, lgtm, size/S

#3225 add metrics-server guide
  content/en/docs/_custom-en/clusterManagement/workloads/workloads-desc-workloads.adoc
  content/en/docs/v4.1/07-cluster-management/05-application-workloads/01-workloads/09-edit-auto-scaling-settings.adoc
  content/en/docs/v4.1/11-use-extensions/04-kubefed/03-application-workloads/03-workloads/_index.adoc
  content/en/docs/v4.1/11-use-extensions/24-metrics-server/01-edit-auto-scaling-settings.adoc
  content/en/docs/v4.1/11-use-extensions/24-metrics-server/_index.adoc
  content/zh/docs/_custom/clusterManagement/workloads/workloads-desc-workloads.adoc
  content/zh/docs/v4.1/07-cluster-management/05-application-workloads/01-workloads/09-edit-auto-scaling-settings.adoc
  content/zh/docs/v4.1/11-use-extensions/04-kubefed/03-application-workloads/03-workloads/_index.adoc
  content/zh/docs/v4.1/11-use-extensions/24-metrics-server/01-edit-auto-scaling-settings.adoc
  content/zh/docs/v4.1/11-use-extensions/24-metrics-server/_index.adoc
  static/images/ks-qkcp/zh/icons/clock-2.svg
Labels: approved, lgtm, size/L
