Repository kubesphere/website, pull requests merged in 2024-07, with the labels that each got.

#3135 update the page of live
  content/zh/live/_index.md
Labels: approved, lgtm, size/XS

#3139 add one new zh blog
  content/zh/blogs/deploy-ollama-on-kubesphere.md
Labels: approved, lgtm, size/XL

#3138 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-shanghai-20240720.md
Labels: approved, lgtm, size/M

#3142 Optimize docs search results
  content/en/docs/v3.3/_index.md
  content/en/docs/v3.4/_index.md
  content/zh/docs/v3.3/_index.md
  content/zh/docs/v3.4/_index.md
  layouts/partials/head.html
  layouts/partials/searchInput.html
Labels: approved, lgtm, size/M

#3140 add one new zh blog
  content/zh/blogs/deploy-kubesphere- offline-on-arm-kylin.md
Labels: approved, lgtm, size/XL

#3143 add one new zh blog
  content/zh/blogs/containerd-cni.md
  content/zh/user-group/hangzhou.md
Labels: approved, lgtm, size/L

#3144 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-shanghai-20240720.md
  content/zh/live/shanghai0720-csghub.md
  content/zh/live/shanghai0720-kdp.md
  content/zh/live/shanghai0720-langchain.md
  content/zh/live/shanghai0720-starship.md
  content/zh/live/shanghai0720-ys1000.md
  static/images/live/cloudnative-live-20240525.png
  static/images/live/cloudnative-live-20240720.png
Labels: approved, lgtm, size/L

#3147 update the page of shanghai-user-group
  content/zh/user-group/shanghai.md
Labels: approved, lgtm, size/XS

#3146 add one new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/opencsg-logo.svg
Labels: approved, lgtm, size/M

#3148 add one new zh blog
  content/zh/blogs/kubernetes-longhorn.md
Labels: approved, lgtm, size/XL

#3149 add one new zh blog
  content/zh/blogs/breaching-docker-image-limits-to-deploy-kubesphere-3.4.1.md
Labels: approved, lgtm, size/L

#3151 add one new zh blog
  content/zh/blogs/deploy-milvus-on-kubesphere.md
Labels: approved, lgtm, size/XL
