Repository kubesphere/website, pull requests merged in 2024-04, with the labels that each got.

#3088 update the page of live
  content/zh/live/_index.md
Labels: approved, lgtm, size/XS

#3089 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-shenzhen-20240420.md
Labels: approved, lgtm, size/M

#3091 add one new zh blog
  content/zh/blogs/jenkins+argo-for-multi-cluster-cd.md
  content/zh/blogs/jenkins+argo-for-single-cluster-cd.md
  content/zh/blogs/upgrading-k8s-with-kubekey.md
Labels: approved, lgtm, size/L

#3096 update hugo to 0.125.0
  netlify.toml
Labels: approved, lgtm, size/XS

#3092 add one new zh blog
  content/zh/blogs/using-prometheus-monitor-jetson-edge.md
  content/zh/docs/v3.3/introduction/scenarios.md
  content/zh/docs/v3.4/introduction/scenarios.md
Labels: approved, lgtm, size/XL

#3093 fix some blogs' url of images
  content/en/blogs/faas-openfunction.md
  content/zh/blogs/calico-wireguard-support-with-azure-cni.md
  content/zh/blogs/deploy-kubesphere-v3.4.0-on-arm-openeuler.md
  content/zh/blogs/kubesphere-devops-pipeline-guide.md
  content/zh/blogs/kubesphere-log-collection.md
  content/zh/blogs/kubesphere-v3.3.0-offline-installation.md
  content/zh/blogs/openelb-arp.md
Labels: approved, lgtm, size/S

#3099 update hugo to 0.125.2
  netlify.toml
Labels: approved, lgtm, size/XS

#3100 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-shenzhen-20240420.md
  content/zh/live/shenzhen0420-k8s.md
  content/zh/live/shenzhen0420-kdp.md
  content/zh/live/shenzhen0420-kubesphere.md
  content/zh/live/shenzhen0420-kubevirt.md
  content/zh/live/shenzhen0420-pe.md
  content/zh/live/shenzhen0420-velero.md
  content/zh/user-group/shenzhen.md
  static/images/live/cloudnative-live-20240323.png
  static/images/live/cloudnative-live-20240420.png
Labels: approved, lgtm, size/L

#3103 add new zh blog
  content/zh/blogs/minimum-configuration-for-network-isolation.md
Labels: approved, lgtm, size/M

#3102 update hugo to 0.125.4
  netlify.toml
Labels: approved, lgtm, size/XS

#3104 add one new partner
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/logo-jibukeji.jpg
Labels: approved, lgtm, size/XS

#3105 add the link of ospp-2024
  config/_default/config.toml
Labels: approved, lgtm, size/XS

#3106 fix devops docs
  content/zh/docs/v3.4/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
Labels: approved, lgtm, size/XS
