Repository kubesphere/website, pull requests merged in 2024-10, with the labels that each got.

#3186 update the header of official website
  layouts/partials/header.html
Labels: approved, lgtm, size/XS

#3187 update dockerhub link
  content/zh/docs/v3.3/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/v3.3/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/v3.3/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/v3.3/project-user-guide/image-builder/source-to-image.md
  content/zh/docs/v3.4/devops-user-guide/examples/a-maven-project.md
  content/zh/docs/v3.4/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
  content/zh/docs/v3.4/project-user-guide/image-builder/binary-to-image.md
  content/zh/docs/v3.4/project-user-guide/image-builder/source-to-image.md
Labels: approved, lgtm, size/S

#3190 add the news of v4 ga
  content/zh/news/kubesphere-v4-ga-announcement.md
Labels: approved, lgtm, size/L

#3193 correct the article format
  content/en/news/kubesphere-v4-ga-announcement.md
Labels: approved, lgtm, size/XS

#3195 【Documentation】Update 01-intro.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/01-platform-services/01-intro.adoc
Labels: approved, lgtm, size/XS

#3197 add one new zh blog
  content/zh/blogs/kubesphere-v4-install-giude.md
Labels: approved, lgtm, size/L

#3199 add one news
  content/en/news/kubesphere-cve-2024-46528.md
  content/zh/news/kubesphere-cve-2024-46528.md
Labels: approved, lgtm, size/M

#3198 【documentation】update devops docs
  content/en/docs/v4.1/20-release-notes/release-v412.md
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/02-devops-projects/04-delete-devops-projects.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/01-devops-project-management.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/01-create-a-pipeline-using-graphical-editing-panel.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/02-create-a-pipeline-using-jenkinsfile.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/03-use-pipeline-templates.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/04-gitlab-multibranch-pipeline.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/06-pipeline-webhook.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/07-access-jenkins-console.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/02-pipelines/08-jenkins-shared-library.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/03-use-gitops-for-continous-deployment.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/04-import-code-repositories.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/05-devops-settings/01-credential-management.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/05-devops-settings/02-role-and-member-management.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/05-devops-settings/03-add-cd-allowlist.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/04-how-to-integrate/01-sonarqube.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/04-how-to-integrate/02-harbor.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/01-platform-services/01-intro.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/07-whizard/01-enable-whizard.adoc
  content/zh/docs/v4.1/20-release-notes/release-v412.md
  content/zh/docs/v4.1/_index.adoc
  static/images/ks-qkcp/zh/devops-user-guide/use-devops/create-a-pipeline-using-graphical-editing-panel/waitforqualitygate_set.png
Labels: approved, lgtm, size/L

#3200 optimize the release of v4.1.1
  content/en/docs/v4.1/20-release-notes/release-v411.md
  content/zh/docs/v4.1/20-release-notes/release-v411.md
Labels: approved, size/S

#3201 Update ks-core helm chart version to 1.1.2
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
Labels: size/XS

#3203 [Documentation] Update 01-sonarqube.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/04-how-to-integrate/01-sonarqube.adoc
Labels: approved, lgtm, size/XS
