Repository kubesphere/website, pull requests merged in 2024-01, with the labels that each got.

#3051 update hugo to 0.121.2
  netlify.toml
Labels: approved, lgtm, size/XS

#3049 Remove unsupported v1.20.x from v3.4
  content/en/docs/v3.4/installing-on-linux/introduction/kubekey.md
  content/zh/docs/v3.4/installing-on-linux/introduction/kubekey.md
Labels: approved, lgtm, size/XS

#3041 Update version install-ks-on-linux-airgapped.md
  content/zh/docs/v3.4/installing-on-kubernetes/on-prem-kubernetes/install-ks-on-linux-airgapped.md
Labels: approved, lgtm, size/XS

#3053 add four partner's logos
  content/en/partner/_index.md
  content/zh/partner/_index.md
  static/images/partner/logo-emq.svg
  static/images/partner/logo-kubeblocks.svg
  static/images/partner/logo-skywalking.png
  static/images/partner/logo-zmops.svg
Labels: approved, lgtm, size/L

#3055 add one new case
  content/en/case/_index.md
  content/zh/case/_index.md
  content/zh/case/turing.md
  content/zh/case/vesoft.md
  content/zh/case/vsleem.md
  static/images/case/logo-vsleem.png
Labels: approved, lgtm, size/L

#3056 update the page of live
  content/zh/live/_index.md
  content/zh/live/okg0118-live.md
Labels: approved, lgtm, size/M

#3057 fix commands in creating devops
  content/zh/docs/v3.4/devops-user-guide/how-to-use/pipelines/create-a-pipeline-using-graphical-editing-panel.md
Labels: approved, lgtm, size/XS

#3054 fix: Update pluggable-components url
  content/zh/docs/v3.4/cluster-administration/cluster-settings/log-collections/add-opensearch-as-receiver.md
Labels: approved, lgtm, size/XS

#3058 update the link of slack
  config/_default/config.toml
  content/en/blogs/TiDB-on-KubeSphere-upload-helm-chart.md
  content/en/blogs/TiDB-on-KubeSphere-using-qke.md
  content/en/contribution/_index.md
  content/zh/blogs/logging-alert-notifaction.md
  content/zh/live/okg0118-live.md
Labels: approved, lgtm, size/S

#3059 add one zh news
  content/zh/news/kubesphere-2023-year-in-review.md
Labels: approved, lgtm, size/L

#3060 update the page of live
  content/zh/live/_index.md
  content/zh/live/okg0118-live.md
  content/zh/news/kubesphere-2023-year-in-review.md
  static/images/live/cloudnative-live-20231223.png
  static/images/live/cloudnative-live-20240118.png
Labels: approved, lgtm, size/M

#3062 add en news of kubesphere-2023-year-in-review
  content/en/news/kubesphere-2023-year-in-review.md
Labels: approved, lgtm, size/L

#3064 update hugo to 0.122.0
  netlify.toml
Labels: approved, lgtm, size/XS
