Repository kubesphere/website, pull requests merged in 2024-02, with the labels that each got.

#3066 optimize the docs
  content/zh/docs/v3.4/cluster-administration/cluster-settings/log-collections/add-opensearch-as-receiver.md
  content/zh/docs/v3.4/cluster-administration/cluster-wide-alerting-and-notification/alerting-policy.md
  content/zh/docs/v3.4/cluster-administration/logs-dashboard.md
  content/zh/docs/v3.4/devops-user-guide/how-to-use/pipelines/use-pipeline-step-template.md
Labels: approved, lgtm, size/M

#3067 add the en docs of v3.4.x
  content/en/docs/v3.4/cluster-administration/cluster-settings/log-collections/add-opensearch-as-receiver.md
  content/en/docs/v3.4/cluster-administration/logs-dashboard.md
  content/en/docs/v3.4/devops-user-guide/how-to-use/pipelines/use-pipeline-step-template.md
  static/images/docs/v3.x/cluster-administration/cluster-settings/log-collections/cc-ks-installer.png
  static/images/docs/v3.x/cluster-administration/cluster-settings/log-collections/cc-search.png
  static/images/docs/v3.x/cluster-administration/cluster-settings/log-collections/logging-dashboard.png
  static/images/docs/v3.x/cluster-administration/cluster-settings/log-collections/logging-filter.png
  static/images/docs/v3.x/cluster-administration/cluster-settings/log-collections/logging-icon.png
  static/images/docs/v3.x/cluster-administration/logs-dashboard/logs-dashboard-1.png
  static/images/docs/v3.x/cluster-administration/logs-dashboard/logs-dashboard-2.png
  static/images/docs/v3.x/cluster-administration/logs-dashboard/logs-dashboard-3.png
  static/images/docs/v3.x/devops-user-guide/using-devops/use-step-templates/create-pipeline-1.png
  static/images/docs/v3.x/devops-user-guide/using-devops/use-step-templates/create-pipeline-2.png
  static/images/docs/v3.x/devops-user-guide/using-devops/use-step-templates/create-step-1.png
  static/images/docs/v3.x/devops-user-guide/using-devops/use-step-templates/use-step-1.png
Labels: approved, lgtm, size/XL

#3065 Update remove-nodes.md
  content/zh/docs/v3.4/installing-on-linux/cluster-operation/remove-nodes.md
Labels: approved, lgtm, size/XS

#3070 update hugo to 0.123.1
  netlify.toml
Labels: approved, lgtm, size/XS

#3072 add one new zh blog
  content/zh/blogs/kubesphere-etcd-guide.md
Labels: approved, lgtm, size/L

#3074 update hugo to 0.123.4
  netlify.toml
Labels: approved, lgtm, size/XS
