Repository kubesphere/website, pull requests merged in 2024-06, with the labels that each got.

#3122 update hugo to 0.126.2
  netlify.toml
Labels: approved, lgtm, size/XS

#3127 add one new zh blog
  content/zh/blogs/containerd-kubernetes.md
Labels: approved, lgtm, size/L

#3130 add one new zh blog
  content/zh/blogs/kdp-on-kubesphere.md
Labels: approved, lgtm, size/L

#3129 update robots, temporarily disallow v4.1
  layouts/robots.txt
Labels: approved, lgtm, size/XS

#3132 add one new zh blog
  content/zh/blogs/kubesphere-best-practices-in-the-internet-ecommerce-industry.md
Labels: approved, lgtm, size/L

#3133 add one news
  content/zh/news/ospp-2024-selected-students.md
Labels: approved, lgtm, size/M

#3134 update the page of videos
  data/zh/video.json
Labels: approved, lgtm, size/L
