Repository kubesphere/website, pull requests merged in 2024-05, with the labels that each got.

#3108 update hugo to 0.125.7
  netlify.toml
Labels: approved, lgtm, size/XS

#3109 add one new zh blog
  content/zh/blogs/using-kubekey-deploy-k8s-v1.28.8.md
Labels: approved, lgtm, size/XL

#3110 update the page of live
  content/zh/live/_index.md
  content/zh/live/meetup-beijing-20240525.md
Labels: approved, lgtm, size/M

#2871 Update monitoring.md
  content/zh/docs/v3.3/faq/observability/monitoring.md
Labels: approved, lgtm, size/S

#3113 update hugo to 0.126.1
  netlify.toml
Labels: approved, lgtm, size/XS

#3115 add one zh news of kubekey
  content/zh/news/kubekey-v3.1-release.md
Labels: approved, lgtm, size/L

#3116 update the docs
  content/zh/docs/v3.3/faq/observability/monitoring.md
  content/zh/docs/v3.4/faq/observability/monitoring.md
Labels: approved, lgtm, size/S

#3118 add one new zh blog
  content/zh/blogs/deploy-kubesphere-3.4.1-and-k8s-v1.28-with-kubekey-3.1.1.md
Labels: approved, lgtm, size/XL

#3120 update the page of live
  content/zh/live/_index.md
  content/zh/live/beijing0525-ai.md
  content/zh/live/beijing0525-databend.md
  content/zh/live/beijing0525-kubesphere-1.md
  content/zh/live/beijing0525-kubesphere-2.md
  content/zh/live/beijing0525-skywalking-1.md
  content/zh/live/beijing0525-skywalking-2.md
  content/zh/live/meetup-beijing-20240525.md
  static/images/live/cloudnative-live-20240420.png
  static/images/live/cloudnative-live-20240525.png
Labels: approved, size/L
