Repository kubesphere/website, pull requests merged in 2025-03, with the labels that each got.

#3236 【documentation】add https doc & remove whizard and notification-history docs
  content/en/docs/v4.1/02-quickstart/02-access-kubesphere-via-https.adoc
  content/en/docs/v4.1/02-quickstart/03-install-an-extension.adoc
  content/en/docs/v4.1/02-quickstart/04-control-user-permissions.adoc
  content/en/docs/v4.1/02-quickstart/05-deploy-wordpress.adoc
  content/en/docs/v4.1/02-quickstart/06-deploy-bookinfo.adoc
  content/en/docs/v4.1/02-quickstart/07-canary-release-example.adoc
  content/en/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/01-devops-project-management.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/01-platform-services/01-intro.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/05-monitoring/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/06-alerting/03-rule-groups/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/07-whizard/_index.adoc
  content/en/docs/v4.1/11-use-extensions/05-observability-platform/11-notifications/04-notification-history/_index.adoc
  content/en/docs/v4.1/_index.adoc
  content/zh/docs/v4.1/02-quickstart/02-access-kubesphere-via-https.adoc
  content/zh/docs/v4.1/02-quickstart/03-install-an-extension.adoc
  content/zh/docs/v4.1/02-quickstart/04-control-user-permissions.adoc
  content/zh/docs/v4.1/02-quickstart/05-deploy-wordpress.adoc
  content/zh/docs/v4.1/02-quickstart/06-deploy-bookinfo.adoc
  content/zh/docs/v4.1/02-quickstart/07-canary-release-example.adoc
  content/zh/docs/v4.1/07-cluster-management/10-multi-cluster-management/01-clusters/09-remove-a-member-cluster.adoc
  content/zh/docs/v4.1/11-use-extensions/01-devops/03-how-to-use/01-devops-project-management.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/01-platform-services/01-intro.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/05-monitoring/_index.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/06-alerting/03-rule-groups/_index.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/07-whizard/_index.adoc
  content/zh/docs/v4.1/11-use-extensions/05-observability-platform/11-notifications/04-notification-history/_index.adoc
  content/zh/docs/v4.1/_index.adoc
Labels: approved, lgtm, size/XXL

#3239 add v4.1.3 release note
  content/en/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/en/docs/v4.1/20-release-notes/release-v412.md
  content/en/docs/v4.1/20-release-notes/release-v413.md
  content/zh/blogs/kubesphere-v4-install-guide.md
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/zh/docs/v4.1/20-release-notes/release-v412.md
  content/zh/docs/v4.1/20-release-notes/release-v413.md
Labels: size/M

#3240 【documentation】Add security policy and some fixes
  content/en/docs/_custom-en/glossary.adoc
  content/en/docs/v4.1/02-quickstart/02-access-kubesphere-via-https.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/en/docs/v4.1/21-security/01-security-policy.adoc
  content/en/docs/v4.1/21-security/_index.adoc
  content/en/docs/v4.1/25-reference/_index.adoc
  content/en/docs/v4.1/25-reference/glossary-final.adoc
  content/zh/docs/_custom/glossary.adoc
  content/zh/docs/v4.1/02-quickstart/02-access-kubesphere-via-https.adoc
  content/zh/docs/v4.1/20-release-notes/release-v413.md
  content/zh/docs/v4.1/21-security/01-security-policy.adoc
  content/zh/docs/v4.1/21-security/_index.adoc
Labels: size/XL

#3241 update header.html
  layouts/partials/header.html
Labels: size/XS

#3242 add 02-upgrade-kubesphere-from-v4.1.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/02-upgrade-kubesphere-from-v4.1.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/_index.adoc
Labels: size/L

#3243 Update the 4.1.3 article.
  content/en/news/kubesphere-4.1.3-ga-announcement.md
  content/zh/news/kubesphere-4.1.3-ga-announcement.md
Labels: approved, lgtm, size/L
