Repository kubesphere/website, pull requests merged in 2025-04, with the labels that each got.

#3246 fix: fix formatting and remove unnecessary links in documentation
  content/en/blogs/value-of-kubesphere.md
  content/en/docs/v3.3/release/release-v210.md
  content/zh/blogs/kubesphere-values.md
  content/zh/docs/v3.3/release/release-v210.md
  content/zh/news/release-210.md
  data/zh/footer.yaml
Labels: size/S

#3248 【documentation】 translate Security Vulnerability Advisory
  content/en/docs/v4.1/21-security/02-vulnerability-advisory.adoc
Labels: size/L

#3249 Update extension upgrade docs
  content/en/docs/v4.1/06-extension-user-guide/01-install-extensions.adoc
  content/en/docs/v4.1/06-extension-user-guide/02-manage-extensions/01-set-configurations.adoc
  content/en/docs/v4.1/06-extension-user-guide/02-manage-extensions/02-set-cluster-agents.adoc
  content/en/docs/v4.1/06-extension-user-guide/02-manage-extensions/03-disable-extensions.adoc
  content/en/docs/v4.1/06-extension-user-guide/02-manage-extensions/_index.adoc
  content/en/docs/v4.1/06-extension-user-guide/03-upgrade-extensions.adoc
  content/en/docs/v4.1/06-extension-user-guide/04-uninstall-extensions.adoc
  content/zh/docs/v4.1/06-extension-user-guide/01-install-extensions.adoc
  content/zh/docs/v4.1/06-extension-user-guide/02-manage-extensions/01-set-configurations.adoc
  content/zh/docs/v4.1/06-extension-user-guide/02-manage-extensions/02-set-cluster-agents.adoc
  content/zh/docs/v4.1/06-extension-user-guide/02-manage-extensions/03-disable-extensions.adoc
  content/zh/docs/v4.1/06-extension-user-guide/02-manage-extensions/_index.adoc
  content/zh/docs/v4.1/06-extension-user-guide/03-upgrade-extensions.adoc
  content/zh/docs/v4.1/06-extension-user-guide/04-uninstall-extensions.adoc
Labels: size/S

#3250 update KubeSphere Gateway component (ingress-nginx)
  content/en/news/KubeSphere Gateway Component (ingress-nginx) Security-en.md
  content/zh/news/KubeSphere Gateway Component (ingress-nginx) Security-zh.md
Labels: approved, lgtm, size/L

#3253 Update 03-upgrade-kubesphere-from-v3.4.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
Labels: size/L

#3254 Update 03-upgrade-kubesphere-from-v3.4.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
Labels: size/XS

#3255 【Documentation】update upgrade docs
  content/en/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/02-upgrade-kubesphere-from-v4.1.x.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/_index.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/02-upgrade-kubesphere-from-v4.1.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/_index.adoc
Labels: lgtm, size/L

#3257 Update 03-upgrade-kubesphere-from-v3.4.x.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/03-upgrade-kubesphere/03-upgrade-kubesphere-from-v3.4.x.adoc
Labels: size/S

#3256 【documentation】add oidc doc
  content/en/docs/v4.1/04-platform-management/03-platform-settings/04-ks-as-oidc-identity-provider.adoc
  content/zh/docs/v4.1/04-platform-management/03-platform-settings/03-external-authentication/01-set-up-external-authentication.adoc
  content/zh/docs/v4.1/04-platform-management/03-platform-settings/04-ks-as-oidc-identity-provider.adoc
  static/images/ks-qkcp/zh/v4.1.3/configure-harbor.png
  static/images/ks-qkcp/zh/v4.1.3/first-login.png
  static/images/ks-qkcp/zh/v4.1.3/harbor-login.png
  static/images/ks-qkcp/zh/v4.1.3/ks-login.png
  static/images/ks-qkcp/zh/v4.1.3/oidc-flow.png
Labels: size/L

#3258 Update 01-supported-k8s.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/_index.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/01-supported-k8s.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/_index.adoc
Labels: size/M
