Repository kubesphere/website, pull requests merged in 2025-05, with the labels that each got.

#3261 ks mcp news update
  content/en/news/ks-mcp-server-2025.md
  content/zh/news/ks-mcp-serverzh.md
Labels: approved, lgtm, size/L

#3262 Upgrade KubeSphere from v3.4.x to v4.1.3 news
  content/en/news/How to Upgrade KubeSphere from v3.4.x to v4.1.3.md
  content/zh/news/The Complete Guide to Smoothly Upgrading from KubeSphere v3.4.x to v4.x.md
Labels: approved, lgtm, size/L

#3263 Change the time of the article
  content/en/news/How to Upgrade KubeSphere from v3.4.x to v4.1.3.md
  content/en/news/ks-mcp-server-2025.md
  content/en/news/kubesphere-4.1.3-ga-announcement.md
  content/zh/news/Docker Components in KubeSphere-zh.md
  content/zh/news/KubeSphere Gateway Component (ingress-nginx) Security-zh.md
  content/zh/news/Kubesphere-product lifecycle policy.md
  content/zh/news/The Complete Guide to Smoothly Upgrading from KubeSphere v3.4.x to v4.x.md
  content/zh/news/ks-mcp-serverzh.md
  content/zh/news/kubesphere-4.1.3-ga-announcement.md
Labels: size/S

#3265 update time
  content/en/news/KubeSphere Gateway Component (ingress-nginx) Security-en.md
Labels: size/XS

#3266 【Documentation】Add ks-high-availability
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/02-configure-high-availability/02-configure-k8s-high-availability.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/01-preparations/02-configure-high-availability/_index.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/03-offline-installation.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/04-configure-ks-high-availability.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/05-add-and-delete-cluster-nodes/01-add-cluster-nodes.adoc
  content/en/docs/v4.1/_index.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/02-configure-high-availability/02-configure-k8s-high-availability.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/01-preparations/02-configure-high-availability/_index.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/03-offline-installation.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/04-configure-ks-high-availability.adoc
  content/zh/docs/v4.1/03-installation-and-upgrade/05-add-and-delete-cluster-nodes/01-add-cluster-nodes.adoc
  content/zh/docs/v4.1/_index.adoc
Labels: size/XL

#3264 fix: Remove openlb link on footer
  data/en/footer.yaml
  data/zh/footer.yaml
Labels: size/XS
