Repository kubesphere/website, pull requests merged in 2025-01, with the labels that each got.

#3226 meetup update
  content/zh/live/_index.md
  content/zh/live/guangzhou1228-ai.md
  content/zh/live/guangzhou1228-jiqun.md
  content/zh/live/guangzhou1228-luban.md
  content/zh/live/guangzhou1228-spring.md
  content/zh/live/guangzhou1228-wangguan.md
  content/zh/live/meetup-chengd-20241228.md
  content/zh/live/meetup-guangzhou-20241228.md
  content/zh/live/meetup-hangzhou-20250419.md
Labels: approved, lgtm, size/XL

#3222 use ks-core-1.1.3
  content/zh/docs/v3.3/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v3.4/installing-on-linux/on-premises/install-kubesphere-on-bare-metal.md
  content/zh/docs/v4.1/20-release-notes/release-v412.md
Labels: size/XS

#3228 add charts repo mirror
  content/en/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/en/docs/v4.1/03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc
  content/en/docs/v4.1/20-release-notes/release-v412.md
  content/zh/blogs/kubesphere-4.1.2-deployment-and-extension-installation.md
  content/zh/blogs/kubesphere-v4-install-guide.md
  content/zh/docs/v4.1/02-quickstart/01-install-kubesphere.adoc
  content/zh/docs/v4.1/20-release-notes/release-v412.md
Labels: approved, lgtm, size/S

#3231 year review
  content/zh/news/kubesphere-2024-year-in-review.md
Labels: approved, lgtm, size/L

#3232 Update the English website review content
  content/en/news/kubesphere-2024-year-in-review.md
Labels: approved, lgtm, size/L
