Repository kubesphere/website, pull requests merged in 2025-07, with the labels that each got.

#3271 Update policy time
  content/en/news/KubeSphere Product Lifecycle Policy.md
  content/zh/news/Kubesphere-product lifecycle policy.md
Labels: lgtm, size/XS

#3276 change twitter to x
  config/_default/config.toml
  content/en/contribution/_index.md
  content/en/news/kubesphere-available-on-aws-quickstart.md
  content/zh/contribution/_index.md
  content/zh/news/ospp-2022-selected-students.md
Labels: lgtm, size/S

#3281 fix: Disable doc url
  layouts/docs/single.html
  netlify.toml
Labels: size/M
